### ISSUE TITLE
Lib file check update makes modpack load up slower. 

### ISSUE THREAD

**Issue by YourturnGaming** [xJon/The-1.7.10-Pack#1063]
There's a delay when getting 

06.03 20:35:15 [Server] main/INFO [STDOUT]: [info.inpureprojects.core.API.Utils.Downloader:download:19]: Downloading: http://files.inpureprojects.info/libs/commons-codec-1.9.jar
06.03 20:35:15 [Server] main/INFO [INpurePreloader]: Starting library configuration...

It would be nice to have it either updated or see if you can remove this step just to speed up the loading process.  The url http://files.inpureprojects.info/libs/commons-codec-1.9.jar doesn't redirect to anywhere. 

This occurs both server and client side.

**Comment by StrayanDropbear** [comment]
+1

**Comment by xJon** [comment]
The timeout is literally between 10 to 15 seconds, are you serious?

**Comment by YourturnGaming** [comment]
It's slower server side. Usually takes 2-3 minutes. Could be the host also.

**Comment by xJon** [comment]
On my server-side it's 10 seconds. How is it possible?

**Comment by YourturnGaming** [comment]
If it helps we are using a panel called multicraft, I'll run a few tests to see if I can't speed up the process.

**Comment by xJon** [comment]
Can you try just running it in a different environment?

**Comment by Noles** [comment]
This is related to inpureprojects directly.
There is already a discussion about.

INpureProjects/INpureCore#21

**Comment by rastamanfb** [comment]
yep can also say that it takes about 2 minutes per file and its checking for 2 files. this adds about 4 minutes to the total time to restart a server.

its been some time now, is inpure closing its doors?

**Comment by YourturnGaming** [comment]
Looking into it, seems like it only occurs in the panel called multicraft. Running locally seems quicker. 

¯\_(ツ)_/¯

**Comment by f-koehler** [comment]
But it still tries to download
http://files.inpureprojects.info/libs/commons-codec-1.9.jar
and
http://files.inpureprojects.info/libs/commons-compress-1.8.1.jar

For each file one has to wait for the connection to timeout.

**Comment by rastamanfb** [comment]
I run a server that is hosted and they only provide multicraft.
If we manually obtain those files where do we place them?

**Comment by xJon** [comment]
If you guys put [these](https://github.com/INpureProjects/INpureCore/tree/master/libs) two files into the `/mods/1.7.10` folder, does it work smoothly?

**Comment by rastamanfb** [comment]
yep no longer pauses on startup.

**Comment by xJon** [comment]
Thanks for reporting, @rastamanfb, and all the others.
We will shortly add the libs to the client and server v0.8.4 versions.
For the server, redownload the .zip file, and for clients, reinstall (but only if needed!)

**Comment by rastamanfb** [comment]
This problem seems to be back with 0.8.5

**Comment by xJon** [comment]
@rastamanfb Any additional logs or information?

**Comment by rastamanfb** [comment]
I didnt open a new one as its exactly the same delay and time out due to the files missing.
as i usually update by deleting the mod folder and library folder and replacing them, it clears these files.
you have not included them in your server pack so it results in the same delays we were seeing before as the webhost that hosts this files is no longer available

**Comment by xJon** [comment]
Should be fixed now, would happy with your confirm @rastamanfb.
Thanks anyway for pointing this issue out!

**Comment by rastamanfb** [comment]
indeed, i run a server.
you mentioned before that you were going to include the files

**Comment by xJon** [comment]
@rastamanfb Yes they are now included with the download of v0.8.5.
