### ISSUE TITLE
Crashing after checking inverntory

### ISSUE THREAD

**Issue by Dory787** [xJon/The-1.7.10-Pack#1065]
Let me start by saying I love this pack. It's lots of fun and never gets old. However I'm having technical issues. I can play the pack I can walk around and place things and cut tress but the minute I check my inventory my game freezes and crashes. Now I saw someone else post about the same thing and he was told to delete his pack and reinstall which I did even though I lost my previous world. I started playing again and for about 3 hours it worked beautifully but then it crashed out of no where and the problem arose. I will do not want lose y world again as i have done a lot in it. Is there a way anyone can help me solve my issue without having to lose my world?

**Comment by xJon** [comment]
I need your crash report. Post it using a [paste-tool](http://pastebin.com).

**Comment by Dory787** [comment]
How do I check my crash report?

**Comment by xJon** [comment]
Read [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/blob/master/README.md).

**Comment by Dory787** [comment]
http://paste.ubuntu.com/15345028/

**Comment by Dory787** [comment]
I Don't know if this is what you're looking for but this is what comes up when I go to my logs

**Comment by xJon** [comment]
No this is not it. I need the *crash-report*.

**Comment by Dory787** [comment]
http://paste.ubuntu.com/15351684/ 
Hopefully this is it. It's the latest log.

**Comment by xJon** [comment]
No. The crash log is in `/the-1710-pack/crash-reports/`.

**Comment by Dory787** [comment]
http://pastebin.com/0HsP7Tqk

Okay when I go to reports this is the only thing that shows up. If this isn't it then idk I already feel like such a scrub for not knowing how to find the crash report.

**Comment by Dory787** [comment]
http://pastebin.com/6QvxT7xJ Okay this was underthe crash report files

**Comment by xJon** [comment]
Thank you. As it seems, some of your HQM data is corrupt.
To reset it, go to `/saves/*save-name*/hqm` and delete that folder (`hqm`).
