### ISSUE TITLE
I Can't play Singleplayer.

### ISSUE THREAD

**Issue by HelmCaT** [xJon/The-1.7.10-Pack#1069]
My problem is i cant play singleplayer i dont know if the multiplayer is working cuz its mojang maintenance :D

In the minecraft client i have this text after trying to join to the world... A fatal error has occured, this connection is terminated.

I know there is no log but i cant drag it there lol

**Comment by xJon** [comment]
http://paste.ubuntu.com/

**Comment by xJon** [comment]
Closed due to missing information.
