### ISSUE TITLE
No furnace recipes in NEI

### ISSUE THREAD

**Issue by jnyl42** [xJon/The-1.7.10-Pack#1070]
NEI is not showing the recipes for any furnace products.  The only smelting recipes are Philosopher Stone recipes.  I have a bunch of new players on my server and it's super confusing for them.  Thanks for looking.

**Comment by xJon** [comment]
Philosopher Stone? this might be caused by the addition of mods.
What modpack version are you playing?

**Comment by jnyl42** [comment]
I just mean that there are no recipes for the furnace.  Iron Ore to Iron Ingot, Rubber to Rubber Bar, that kind of stuff.  You can do the same thing with PhiloStone so it shows that recipe, but it doesn't show basic furnace smelting recipes.
Running 0.8.4 server

**Comment by xJon** [comment]
![image](https://cloud.githubusercontent.com/assets/8945347/13752907/89ab0620-ea19-11e5-9420-02d0b8480005.png)
