### ISSUE TITLE
Suggestion - Add Thaumic Enegistics

### ISSUE THREAD

**Issue by maxchiavel** [xJon/The-1.7.10-Pack#1071]
It would great to add the add-on Thaumic Energistics to help manage all that essentia. It seems it is the only thing in this modpack that can't be automated.

**Comment by Amaxter** [comment]
Yeah I really want it badly.

**Comment by ciak2009** [comment]
Traitor @Amaxter

**Comment by Smalfinn** [comment]
I too would love to see this mod added please :dash:

**Comment by missexo** [comment]
we would also love this if it could be added :)

**Comment by xJon** [comment]
Added! :+1:
