### ISSUE TITLE
Optifine version help! 

### ISSUE THREAD

**Issue by ScytherDMC** [xJon/The-1.7.10-Pack#1072]
I'm using the recommended version 0.8.4 of the 1.7.10 Pack but can't seam to find a version of Optifine that will load the game without crashing. Previously I was using Optifine 1.7.10 B7 on a earlier version of the 1.7.10 Pack, but now it crashes before the start screen loads. 

Any help would be greatly appreciated.

**Comment by xJon** [comment]
Can you provide the crash report using a [paste-tool](http://pastebin.com)?

**Comment by xJon** [comment]
Close due to missing information.
