### ISSUE TITLE
Suggestion: Adding Immersive Engineering 

### ISSUE THREAD

**Issue by MillaJunya** [xJon/The-1.7.10-Pack#1074]
I've seen some of immersive engineering and from what I've seen it looks like not only a very visually impressive mod but also adds some new forms of transferring power and generating it.

**Comment by xJon** [comment]
We don't want to add a mod just because it's visually impressive.
Most of the features that Immersive Engineering adds are already in the pack, therefor adding the mod  isn't necessary.
