### ISSUE TITLE
Singleplayer Crashes on Generating Terrain?

### ISSUE THREAD

**Issue by Scottvrakis** [xJon/The-1.7.10-Pack#1076]
For some reason, my game crashes whenever I try to play SP, it starts to generate terrain, and then the entire game dies and brings me back to the Technic launcher. I don't even get a crash report as it crashes, I've found one within some of the modpack folders.

[crash-2016-03-19_13.18.46-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/180927/crash-2016-03-19_13.18.46-server.txt)

Can anyone give me some help?

**Comment by xJon** [comment]
Simply reset MachineMuse's configuration files in the modpack's folder to fix the issue. Your world is fine.

**Comment by Scottvrakis** [comment]
Ah! Thanks friend!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2115-c>
Checked
by Avast Antivirus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2115-c>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
