### ISSUE TITLE
Optifine Issues?

### ISSUE THREAD

**Issue by mandm635** [xJon/The-1.7.10-Pack#1077]
I have tried to install the latest version of Optifine with the recommended version of the 1.7.10 pack, and while it appears to have launched correctly, and even displays Optifine above Forge on the Start menu, but does not appear to be functioning. I do not have any Optifine options, however I do have an option for shaders in the video settings menu. I am not sure if this is intentional, I think it might be, but if there is something I can do, that would be great. While I do not need Optifine, it would be nice to get a little FPS boost. I usually run at 200+ FPS, and with the 1.7.10 pack, assuming that Optifine is not functioning, I get a steady 30 FPS on servers (haven't tried single player yet), which is definitely playable for a modpack of this size. Well any help/info is much appreciated! Thanks for your time and the great work put into this pack!

**Comment by xJon** [comment]
![image](https://cloud.githubusercontent.com/assets/8945347/13917242/28bbdd4a-ef68-11e5-94a0-aba269331077.png)

**Comment by mandm635** [comment]
Yes it loads the Optifine message, but it does not seem to be working, check the options and at least for me I can see no Optifine features.

**Comment by xJon** [comment]
![image](https://cloud.githubusercontent.com/assets/8945347/13948604/a59fc184-f029-11e5-9abb-0d951e1939f0.png)
...
