### ISSUE TITLE
Can't place block

### ISSUE THREAD

**Issue by TheFamousPG** [xJon/The-1.7.10-Pack#1078]
Hi,

I don't know why, but I can't place any block here :
https://i.gyazo.com/a7361aa4e7dfd6337b0f6a254f7bfc1f.png

When I break one block, I can't replace it, It appear only here... I don't know why..
https://i.gyazo.com/7695d78f3eb36d11c0f669e18a3a5b43.png

**Comment by TheFamousPG** [comment]
Ok, I found the problem, because there are invisible garage door.....
https://gyazo.com/06b5fb4aad8c99677fecb551ddfadc3a

DOn't break it with laser drill ;)

**Comment by xJon** [comment]
:+1:
