### ISSUE TITLE
An Error was Raised While Attempting To Read Pack Info?

### ISSUE THREAD

**Issue by thestrauch** [xJon/The-1.7.10-Pack#1079]
So I used t be able to use this pack without problems, but all of a sudden when I try to use it today I get this error: "An error was raised while attempting to read pack info for modpack the-1.7.10-pack, build 0.8.4: Server returned HTTP response code: 500 for URL:" and then the URL for the pack solder. I tried deleting and reinstalling, but it appears to be am issue with the hosting server. I was wondering if anyone else has had this issue and if so, have the fixed it. Thanks!

**Comment by thestrauch** [comment]
It is now saying Error unzipping a file for the following pack: The 1.7.10 Pack attempting to extract file the-1.7.10-pack-0.8.4.zip, but it does not exist."

**Comment by thestrauch** [comment]
NVM fixed itself

**Comment by xJon** [comment]
:+1:
