### ISSUE TITLE
Offline lag, but it isn't FPS lag...

### ISSUE THREAD

**Issue by fui312** [xJon/The-1.7.10-Pack#1081]
I've been playing this mod pack awhile and never really ran into any issues, that was, until my world started getting bigger, and bigger, and bigger, and more technical with more things running at once. Now, I would have thought that the lag I would soon get be FPS lag, however, this isn't the case...

Basically, whenever I go onto my world, it's like joining a terrible latency server (minus actually connecting/loading), I get terrible 'server' lag, but my FPS is fine (~60+). I've tried disabling all useless chunk loaders and even jumping dimensions. These 'symptoms' of this lag is:
- Slow block breaking and harvesting
- Unresponsive machines and block structures.

I've tried disabling mods I thought might be causing it, but nothing so far as worked. Also usually the lag doesn't start until loading more chunks, particularly those with machines or special function blocks (which sucks because I'm all over the place in my world anyway)

Computer Specs (in-case):
- AMD R7-6000 Series
- Intel i7
- 16GB Ram
- Running 64bit JavaSE

**Comment by xJon** [comment]
You probably mean you have TPS (tick per second) problems, which are common in servers.
To understand your issue better I'll have to ask you to submit here your latest client log. To know where to find it and how to post it read [this](https://github.com/xJon/The-1.7.10-Pack/blob/master/README.md).

Another thing you can do to understand which chunk causes you these problems in to install [Opis](http://minecraft.curseforge.com/projects/opis) (and its core mod).

**Comment by fui312** [comment]
[2016-03-23-2.txt](https://github.com/xJon/The-1.7.10-Pack/files/186824/2016-03-23-2.txt)

I've attached my latest log from 23rd March (yesterday for me). Still getting these issues.
I will have a look using Opis to see any consistencies with these issues. Thanks!

**Comment by xJon** [comment]
In the log I can see just overloads, no errors.
You'll have to use Opis and understand which chunks in what dimension make your server work so hard. Nothing else I can help you with, unfortunately. That's modded Minecraft.
