### ISSUE TITLE
LZH condensator repair issue

### ISSUE THREAD

**Issue by cptBP** [xJon/The-1.7.10-Pack#1082]
Hey I love the modpack but I ran into an issue, I cannot find a way to repair the lzh condensator component with neither redstone or lapis lazuli. I don't know if  i just got the recipe wrong, I could not find it on google.

Thanks!

**Comment by xJon** [comment]
So you can't craft it?

**Comment by cptBP** [comment]
yeah I tried to a damaged lzh condensator on a crafting table with lapis  there is no crafting recipe possible to repair it. I also tried with a lapis block and its not working either.

**Comment by xJon** [comment]
Where did you hear you can do it that way?

**Comment by cptBP** [comment]
http://wiki.industrial-craft.net/index.php?title=LZH-Condensator

http://ftbwiki.org/LZH-Condensator#Recharging

I just found the IC2 bug tracking website and I think the problem might be with the mod after all. The bug is listed in a couple of different issues:

http://bt.industrial-craft.net/view.php?id=1580

http://bt.industrial-craft.net/view.php?id=1744

I kinda gave up anyway on the reactor anyway lol.

Thanks for taking the time to respond tough!

**Comment by xJon** [comment]
Welp
