### ISSUE TITLE
Practicalities

### ISSUE THREAD

**Issue by mandm635** [xJon/The-1.7.10-Pack#1084]
Practicalities is a fairly small mod that adds a lot of cool, higher tiered items. You can create things such as Wither Farms and op swords. I feel that it would be a nice addition to add some projects for late game players. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2181911-practicalities-0-6-2

**Comment by xJon** [comment]
Thank you for suggesting but the mod doesn't really fit the modpack.
It won't be added.
