### ISSUE TITLE
i need help every time i try to install the 1.7.10 pack it says i need 3 GB RAM and i dont know how to change it pls help

### ISSUE THREAD

**Issue by cookie1234567** [xJon/The-1.7.10-Pack#1087]

**Comment by kijjuy** [comment]
In the Technic Launcher, click on launcher options in the top right corner of the window, right under the close and minimize buttons.

![2016_03_25_20_13_23_photos](https://cloud.githubusercontent.com/assets/8691010/14056741/74efa078-f2c6-11e5-9b34-ad74d673ba3e.png)

 Then click on the Java settings tab,
![2016_03_25_20_14_53_photos](https://cloud.githubusercontent.com/assets/8691010/14056802/40334794-f2c7-11e5-86ba-c0420dcc220c.png)

 then click on the "memory" drop down menu,

![2016_03_25_20_15_47_photos](https://cloud.githubusercontent.com/assets/8691010/14056750/b57b95de-f2c6-11e5-8bbb-c1ffd1780e58.png)
and click on the amount that you want to allocate. 
If you cant't go past 2GB of memory, try updating to 64 bit Java.

**Comment by xJon** [comment]
Happy to see other people give support; thanks @kijjuy
