### ISSUE TITLE
Horrible Performance

### ISSUE THREAD

**Issue by kijjuy** [xJon/The-1.7.10-Pack#1088]
I don't know whether Minecraft is poorly optimized, or maybe all the mods are hitting my video card pretty hard (and it can definitely take the hits), but i get about 20-30 fps, and usually cap out at about 40 fps while doing something like staring at the ground. Is anybody having the same problems? Does anybody have a fix for some of this very low fps?

**Comment by xJon** [comment]
Try adding [Optifine](http://optifine.net/downloads). I can't recommend you anything else except a system upgrade.

**Comment by kijjuy** [comment]
I think part of the problem was having V-Sync enabled. Btw I just bought an MSI r9 390 2 days ago so it should be able to run it. Disabling V-Sync gets me to about 60-80 fps😀

**Comment by xJon** [comment]
Welp

**Comment by xJon** [comment]
:+1:
