### ISSUE TITLE
Bug/Problem: Vampirism Issue

### ISSUE THREAD

**Issue by Chemical1** [xJon/The-1.7.10-Pack#1093]
So the problem is we are Vampires and we have tried leveling up as much as we can Legit. But when we come to level 8 the problem is we need to mesmerize Villagers. But no matter how much we try we can't its impossible. Does anyone Know what to do?

**Comment by Chemical1** [comment]
Also If your a vampire you cant get into a bed and wake up by leaving it using the button.

**Comment by xJon** [comment]
It may be an issue with the Witchery mod but there's really not much *we* can do about it.
It better should be reported directly to the mod author.
