### ISSUE TITLE
No seaweed seed recipe

### ISSUE THREAD

**Issue by Twingrey** [xJon/The-1.7.10-Pack#1094]
Pam's Harvestcraft issue, the recipe for seaweed seeds is gone, the seeds themselves exist alright. Had to use admin rights on my server to give these seeds manually to players.

**Comment by xJon** [comment]
Recipe for the seeds? Aren't you supposed to find them physically (in-game)?

**Comment by xJon** [comment]
This issue should be directly reported to the mod author; unfortunately there's nothing we can do.
