### ISSUE TITLE
Maybe add some mods

### ISSUE THREAD

**Issue by MekanismCrafter** [xJon/The-1.7.10-Pack#1095]
In my sp world I added some cool stuff. Right now I've got 168 mods in the list;here is it:
Clothingcraft
Agricraft
CustomNPCs
ExtraTiC
Geochests
Immersive Engeneering
Runic Dungeons
Ships Mod
Statue (I'm not sure if i added this mod)
I hope some of these will be in a new version.

**Comment by mandm635** [comment]
First off, just realize how much work it takes to add one md, so much as 9 of them. There is a ton of testing and general maintance that goes into mods to keep the pack working smoothly, and a lot of these mods are pretty large to just add. Second of all, some of the mods, such as CustomNPC are too much of a headache for servers and in most cases too op, with little ways of restricting them. Also, the Statues mod is already in the pack. The Ships Mod, while fun, is too buggy/eary to add to a professional pack such as this. For ExtraTIC, Metallurgy is not even in the pack, which is most of what ExtraTIC is used for. All in all, I'll admit that I don't have much expierence with most of the listed mods, but from briefly viewing them, I do believe that they are either; too buggy, already implemented with other mods, don't fit the theme of the pack, or are not really necessary. If these mods are truly important to you, you can always add them yourself, although you wont have them on servers, not to mention that even if these were accepted, it could be months before you see them added in any way.

**Comment by xJon** [comment]
:arrow_up:
