### ISSUE TITLE
Client crash after a few seconds on joining server

### ISSUE THREAD

**Issue by DoctaLlama** [xJon/The-1.7.10-Pack#1097]
So anyone who tries to join my server gets the same error. Server is running fine but this shows up on the console and their client CTDs. I created a new world and after a while same thing happens to me and one other guy at the same time but another dude who was on wasnt affected. (wasn't near us?)

Here is the console message for those who CTD while joining the server:
http://pastebin.com/cXXKGrNp

**Comment by xJon** [comment]
That's not a crash report.

**Comment by DoctaLlama** [comment]
http://pastebin.com/D05SEMih

**Comment by xJon** [comment]
Update your server to v0.8.4.
