### ISSUE TITLE
Salt Ore can't be processed

### ISSUE THREAD

**Issue by Boehrsi** [xJon/The-1.7.10-Pack#1099]
Pams HarvestCraft salt ore can't be processed to salt by using any machine. Only the nether salt ore is usable that way. It seems that some recipes are missing.

Server Version: 0.8.4
Client Version: 0.8.4
No additional changes

**Comment by xJon** [comment]
You just mine it with a pick. Did it use to have processing recipes in other versions of the modpack?

**Comment by Boehrsi** [comment]
To be honest I don't know. Just thought a pulverizer receipt would be useful (to process salt ore mined with silk touch). Mekanism salt ore has one as far as I remember. So it looked like a bug, but I think you are right, after some googling it seems like the ore isn't meant to be processed. So this is more of a feature request or even invalid.

**Comment by xJon** [comment]
Alright then
