### ISSUE TITLE
Decocraft

### ISSUE THREAD

**Issue by mandm635** [xJon/The-1.7.10-Pack#1102]
I feel that this mod could add a lot of ways to really spruce up your home and make it yours. It adds a ton of awesome models that really enhance a home. It also adds good use for red, green, and blue dye. I have not run nito any serious problems while using this mod(crashing or breaking) but some small rendering issues with the inventory that will be fixed soon. Anyways I feel that this mod should at least be considered. [Decocraft](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292016-decocraft-2-2-decorations-for-minecraft-halloween)

**Comment by xJon** [comment]
Currently won't be added. Thanks anyway for suggesting!
