### ISSUE TITLE
Ender io conduits

### ISSUE THREAD

**Issue by missexo** [xJon/The-1.7.10-Pack#1105]
hi im running a sever though stripe and have been having problems with my sever the admin of stripe have got back to me and said that there are problems with the ender io cables it keeps ticking the sever or something like that im wondering if someone could maybe look into it to see if there is a problem with the mod or it might just be our faults

**Comment by missexo** [comment]
ive noticed also i can set up the conduits correctly and come back and they have just stopped working all of a sudden :(

**Comment by mandm635** [comment]
After doing some Googling, I do not see anything related to your problem. If you could give me some more details or maybe a server log from pastebin or something. I could be wrong, but I believe that it is either on your side, another mod causing problems, or something else entirely is going on.

**Comment by xJon** [comment]
**^**

**Comment by missexo** [comment]
we did find the problem someone on the sever was using them and they had it set up wrong or something anyway we destoryed it and it was working fine then i noticed that they sometimes stopped working when i used a warp book um not sure how i could get the sever log as i dont run it (sorry kinda noob here) i rent a sever from a site called stripe

**Comment by mandm635** [comment]
I am not sure I can help you with this then, I am unfamiliar with Stripe, but I guess it could be some compatability problem with EnderIO and Warp Books, or it could be unrelated. Be sure the conduits are set up properly, and maybe put a post on the two mod authors sites and they might look into it.

**Comment by xJon** [comment]
Closing the issue for now.
