### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by rodfernandes7** [xJon/The-1.7.10-Pack#1106]
How do I play this mod online? Can I just download a vanilla server and run it in the launcher?

**Comment by mandm635** [comment]
This is not a mod, it is a mod pack. You cannot run it in the launcher, you will have to configure it yourself and host it from your pc. It will severely decrease your pc/mc performance. If you do not have at least 16 Gigabytes of RAM on your machine, this is not for you, and you can join a 1.7.10 pack server. Search around and you should find some. An official server is in the making but I do not know when it will be up. Just know that you will have to deal with other players(not just your friends), and server rules.

There should be a download for the server on the technic page [here](http://the-1710-pack.com/repo). Before you try to run a heavely moded server on your computer, be sure that a, be sure you know what your doing, and b, that your computer is powerful enough to run both a server and your client. You should also have a pretty good/stable internet connection that not only supports(and allows as most carriers dissaprove of it...) servers and can handle third-party connections.

If you have not run a server before, don't start with this. You should also know that it can be risky to run a server. If you really wan't a server, you can try a minecraft server hosting site. This one, [Akliz](http://akliz.the-1710-pack.com/), gets you a 20% discount for the 1.7.10 pack. Think of a server like this, the server is what handles the world, chunk loading, and all of the blocks and machines. Really everything in the world, and transmitting this to the clients(you and/or people connected). All the clients really do when connected to a server is render the data that it recieves from the server.

If you are ignoring my advice, here is a good [tutorial](http://minecraft.gamepedia.com/Tutorials/Setting_up_a_server) but it is a little different(similar), with the mods, but the server will do almost everything for you. The only thing you should have to do is [Port Forward](http://portforward.com/). This tutorial should walk you through it for your device. The next thing you should do is to configure your server so it fits your needs; configuring/disabling mods, adding your ip to server.properties, and other tweaks. I assume if you are running this on your pc that it will be a personal server for you and your friends, if you have other plans, stop now.

Just be careful and use good judgement. I highly recommend that you do not run this from your computer.

**Comment by xJon** [comment]
Wow, thank you @mandm635 for the detailed answer.
