### ISSUE TITLE
Pack crashing after logging into server for a few seconds

### ISSUE THREAD

**Issue by MazerFazer23** [xJon/The-1.7.10-Pack#1107]
As the title shows I keep crashing every time I go to log into my friends server. I was heading back from the Twilight forest and when I returned it crash...Thank you for helping me with this.
[crash-2016-04-12_20.15.02-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/216249/crash-2016-04-12_20.15.02-client.txt)

Addition to this note It continues to crash each time I go to log in, thanks!

**Comment by mandm635** [comment]
Are other players able to connect to the server? Also, is the server crashing or your client. If other players can connect, maybe have your friend do a rollback to when you could play using Aroma Backup. If that is not an option, it is possible that your player has become corrupt. A fix for the server owner to delete your player's player file, and while you will loose your inventory/achievements/anything specific to your player, you should be able to play(make a copy in case it doesnt work). I am not sure what is causing the crash, a server log might be helpful though.

**Comment by MazerFazer23** [comment]
Alright I am going to request a player deletion, I will most certainly get back to you if this solution does not work. Thanks for the reply! ^-^

**Comment by MazerFazer23** [comment]
Alright so I am not real sure what caused the crashes either, but we tried doing a rollback to the day before and that didn't seemed to work. Although when I went to go to reinstall the pack for a 2nd time it  seemed to have fixed whatever the heck was going on with it...Packs man...I don't them. Anyways I do thank you for assisting me on all this and I hope you have a good day!

**Comment by mandm635** [comment]
Well, sometimes mods decide that don't like you one bit ;),  And no problem!

**Comment by xJon** [comment]
Thanks for helping @mandm635!
