### ISSUE TITLE
Growthcraft crash with v0.8.5

### ISSUE THREAD

**Issue by Tirades** [xJon/The-1.7.10-Pack#1109]
Crashes after "Initialising" during loading screen. I'm using the latest patch. No other mods.

[crash-2016-04-18_19.13.49-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/225151/crash-2016-04-18_19.13.49-client.txt)

**Comment by xJon** [comment]
https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/FAQ---Troubleshooting#illegalstateexception
