### ISSUE TITLE
crash at load

### ISSUE THREAD

**Issue by Forbid2** [xJon/The-1.7.10-Pack#1110]
[crash-2016-04-19_08.16.24-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/225959/crash-2016-04-19_08.16.24-client.txt)

Should i just go back to the previous version?

**Comment by mandm635** [comment]
Try this: [Growthcraft Help](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/FAQ---Troubleshooting#illegalstateexception). Basically, delete all of the Growthcraft .json files from the directory it gives you(the very top one).

**Comment by xJon** [comment]
#1109
