### ISSUE TITLE
Energy conversion

### ISSUE THREAD

**Issue by rodfernandes7** [xJon/The-1.7.10-Pack#1111]
Is there a way to convert RF to EU (IndustrialCraft)?

**Comment by xJon** [comment]
Even if there is, I'd recommend you to also make an EU power plant.
It's simply a better, more legitimate way of playing the modded game :)

**Comment by Tirades** [comment]
RedNet Energy Cables will convert RF but I agree with xJon's advice.

**Comment by xJon** [comment]
Closing for now :)
