### ISSUE TITLE
Pistronics 2

### ISSUE THREAD

**Issue by raleith** [xJon/The-1.7.10-Pack#1112]
id like to see this added because it makes alot more posibilitys for fuctioning builds like massive swing open doors and the like it also adds lots of new possibilitys for piston fuctionality in general that i think would make this all the better

**Comment by mandm635** [comment]
My personal opinion is no. As I agree it is a really cool mod, but [Pistronics 2](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294844-pistronics-2-modular-pistons-rotators-and-statues) is currently in beta. I couldn't find the original Pistronics, but if it exists, it will not be 1.7.10. When Pistronics 2 updates to a stable release, I think it would be a good mod to add.

**Comment by thecakeisalie25** [comment]
I'm really positive about this, I looked at the mod and i think it could be used in a lot of contraptions, and automating stuff would be easier.

**Comment by Curunir** [comment]
If you are convinced about a certain mod and want it included in the pack, the best way is to add it manually to your local pack installation and try it out for a while. If you encounter no problems with recipes, stability and interaction with other mods, come back and report your findings. This will raise your chances of being heard considerably.

**Comment by Curunir** [comment]
Jon still takes suggestions, but has no intention to consider any of them, because he is a dick.
