### ISSUE TITLE
Crafting Bug

### ISSUE THREAD

**Issue by nlhammonds** [xJon/The-1.7.10-Pack#1113]
Hello everyone,

I really hope someone knows how to fix this, but it seems whenever I try to craft anything in the two by two squares in the inventory it doesn't work, it just glitches out. I also tried certain things like stone sticks to make the saw for forge microblocks but even in the crafting bench it just glitches out. The item will show up in the box you take it out of after you craft it, but I can't take it out, i'll click it and it just glitches back into the crafting bench as if I never clicked it. So I've realized because of this I can't make the chisel, saw, and it wouldn't let me make carpenter's blocks either.

Pleassee hellpp

**Comment by xJon** [comment]
Do you have any additional mods?
And what's the modpack version?

**Comment by xJon** [comment]
Closed due to missing information.
