### ISSUE TITLE
Archimedes' Ships Plus

### ISSUE THREAD

**Issue by mandm635** [xJon/The-1.7.10-Pack#1114]
I know people have suggested the Archimedes' Ship mod in the past, but a new developer took it over, and form what I can tell, is MUCH more stable than the early versions. I feel that it should at least be reconsidered. Here is a [link](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2364835-archimedes-ships-plus-move-your-world-submarines-1) to the new forum page. I reccomend that you at least test the mod a little on it's own to see the changes.

**Comment by xJon** [comment]
Not going to happen currently.
Even if it's more stable than the last version, it's not stable enough to be in the modpack.
Thanks anyway for suggesting!
