### ISSUE TITLE
Mod addition: Better Records

### ISSUE THREAD

**Issue by Freddo3000** [xJon/The-1.7.10-Pack#1115]
Hello, I've been playing around with the pack for a bit, and I find that a few mods that I've been using previously I miss quite a bit, this being one of them aswell as Immersive Engineering(Although that has been posted already, quite sad that it was denied!).

Either way, I've used it for a fair amount of time and the only issue I've found are the decorational lasers occasionally causing crashes, and would probably need to be disabled.

Either way, here is the link to it,[boop](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2155190-better-records-download-songs-from-the-internet).

What this mod adds is customizable records that can play MP3 files aswell as other formats, and radios that can tune in to internet radios. How it works is when anyone gets close to a radio, they connect to a internet radio, defined in a tuned "frequency crystal" sitting in a radio block, and for records, whenever they get close to a record player, they download the MP3 file from a defined website, such as dropbox, that is etched into the record.

I hope this gets added, have a good day.

**Comment by mandm635** [comment]
I was skeptical of the Better Records mod at first but after looking into it, I believe that it is a really cool mod that would enhance the pack.

**Comment by xJon** [comment]
It might be nice but the mod doesn't fit the modpack's theme and we already have a lot of mods. Thanks anyway for suggesting.
