### ISSUE TITLE
Client Lag While Loading

### ISSUE THREAD

**Issue by Dylxn** [xJon/The-1.7.10-Pack#1116]
Client Log: http://paste.ubuntu.com/16087650/

Issue: When the modpack is first being loaded up it takes 10-15 minutes to load. Additionally when switching dimensions(twilight forest/nether) my client lags(freezes)  for about three minutes. I'm running the game on 400 FPS in resizable full screen so I highly doubt it's a computer issue.

Error only occurs when loading outside of the normal in game client. The pack runs very smoothly while in game with no issues.

Running the latest client version with no additional mods added to the pack : 0.8.5
Not using Optifine mod.
Latest Java update.

**Comment by xJon** [comment]
Would you want to try to provide another log and maybe there will be an error there?

**Comment by xJon** [comment]
Closing for now.
