### ISSUE TITLE
Issue starting the pack..

### ISSUE THREAD

**Issue by kingstinger1** [xJon/The-1.7.10-Pack#1119]
I left our server to load into my alias profile and clicked play it it hangs up on loading the pack. In the Launcher console i get this:
[B#347] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[B#347] SLF4J: Defaulting to no-operation (NOP) logger implementation
[B#347] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

So, not knowing what that is I just deleted the modpack and began reinstalling it. But it wont complete either It seems to be hung up on installation..

![pack loading](https://cloud.githubusercontent.com/assets/13582557/14940096/49b47acc-0f23-11e6-8228-97f1e5880e55.PNG)

The screenshot indicates where it is hung up for over 20 minutes now..
Any idea what the issue may be?

**Comment by xJon** [comment]
Are you able to launch other big 1.7.10 modpacks through the Technic Launcher?

**Comment by kingstinger1** [comment]
Yes I was able to the next day. For 4 straight hours I was unable to launch
the pack. There were several others as well. But like I said the next
morning there was no issue.

**Comment by xJon** [comment]
Okay, so I'm closing this one.
