### ISSUE TITLE
Shutting down internal server...A fatal error has occurred, this connection is terminated

### ISSUE THREAD

**Issue by KerrosEx** [xJon/The-1.7.10-Pack#1120]
When i try to play in singleplayer it starts for 0.5 seconds then it kicks me out with the "Shutting down..." message..
[fml-client-latest.TXT](https://github.com/xJon/The-1.7.10-Pack/files/244257/fml-client-latest.TXT)

**Comment by xJon** [comment]
Try to remove the Morph mod manually, launch your save again and then re-add it. That might reset the issue.
