### ISSUE TITLE
Crash after trying to join a world

### ISSUE THREAD

**Issue by KuboS0S** [xJon/The-1.7.10-Pack#1121]
I can't load up my world, as it always crashes Minecraft (it was randomly crashing or exiting the world before, I have no performance issues and 8GB / 16GB ram allocated).
Here's the crash log: http://www.mediafire.com/download/d743w0l9fyd5qqn/crash-2016-04-30_09.18.10-server.txt
Thanks!

**Comment by KuboS0S** [comment]
Sorry for not sending the files using paste.ubuntu.com as I couldn't manage to upload the files (Bad gateway errors).

**Comment by xJon** [comment]
Did you start to play with Steve's Carts 2 in your world?

**Comment by KuboS0S** [comment]
I did, but I didn't have problems with it and it was running for a very long time. Is that the problem?  (Probably is, when you're asking this way.)

**Comment by xJon** [comment]
You can try to remove Steve's Carts 2, load your world, and then re-add it.
It'd reset all the items/blocks from Steve's Carts 2, and should fix your issue.

**Comment by KuboS0S** [comment]
Thanks, I'll give it a try, if it works, then I'll close this problem.

**Comment by KuboS0S** [comment]
It worked, I can join the world, but after a while it crashes again. (I tried removing, then re-adding Steve's Carts 2, as well as playing without it entirely.) Here's the report I got (it seems to come from Botania). Thanks!
[crash-2016-05-12_23.46.46-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/262300/crash-2016-05-12_23.46.46-client.txt)
.

**Comment by KuboS0S** [comment]
It works now, I used Optifine before to improve performance, but it works after I removed it. Issue solved.
