### ISSUE TITLE
Suggestion: Ztones

### ISSUE THREAD

**Issue by TheChiller12** [xJon/The-1.7.10-Pack#1122]
As the title explains it, I really think Ztones would be a great mod to add to the modpack.

Pros:
Does not affect chunk generation majorly (apart from dungeon chest spawning).
Does not add any game-breaking features (i.e Orespawn).
Adds in mostly aesthetic blocks (i.e like blocks from Chisel 2).

Cons:
Some items only retrievable from dungeon chests may have to be given for already up and running servers.

Thank you for your time! #

**Comment by mandm635** [comment]
[Ztones mod](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2221070-ztones-v-2-2-1-decorative-blocks-16x)

The mod looks ok, and the textures seem very nice, but I am not sure about the tools included. Overall, I don't believe we need another athestetic mod, with mods such as Chisel 2 already in the pack. I could really go either way with the mod. If it is added, don't forget the galacticraft config addons hidden in a spoiler at the bottom.

**Comment by TheChiller12** [comment]
Well, mandm635, you are right that Chisel 2 seems like a good amount of aesthetic blocks, but I feel like Ztones adds an amount of blocks that were absent in Chisel 2. For example, the Izsm block adds vibrant colors as blocks into the game while adding regular depth into its textures unlike the unstable bright single-colored blocks from Extra Utilities.

**Comment by mandm635** [comment]
Don't get me wrong, I do like the mod, but thinking in the long run, with a pack this size, I just don't know if it's worth adding. The more mods there are(espicially ones with lots of blocks), the longer it takes to launch, the harder it is for computers to run it, the game runs slower, and there is more potential for bugs. However, I will give my support, but leave the final decision of "do we need it" to the devs.

**Comment by thecakeisalie25** [comment]
I really like this idea, it seems to add a lot of aesthetic blocks that I can't find elsewhere.

**Comment by xJon** [comment]
@mandm635 Said it better.
