### ISSUE TITLE
Incompatible FML Modded server

### ISSUE THREAD

**Issue by rastamanfb** [xJon/The-1.7.10-Pack#1123]
I have just updated my client to 0.8.5 and deleted the json files to run it
I updated my server doing the usual delete of mods, libs, and removed the growth craft json configs from there.
I cannot join the server due to the following message
![incompatible](https://cloud.githubusercontent.com/assets/12107215/14991256/6913ccf6-1158-11e6-917f-b17d22a172bf.jpg)

**Comment by xJon** [comment]
What mod is incompatible?

**Comment by rastamanfb** [comment]
I will try and get this info. i have reuploaded the files and now its getting a boot loop so i will need to fix that before testing again.

**Comment by rastamanfb** [comment]
please close.
after reuploading the files again from a fresh download and re deleting the json files it is now working correctly
