### ISSUE TITLE
Crashing While Loading

### ISSUE THREAD

**Issue by Remrox** [xJon/The-1.7.10-Pack#1124]
My minecraft crashes while saying Initializing. 
I am using 0.8.4 And trying to join a server, Should the owner update the server to latest version or is it a launcher/MC problem?

**Comment by xJon** [comment]
If you're crashing please post the crash report using http://pastebin.com
And if you want to enter a server, it has to have the same modpack version of your client.

**Comment by xJon** [comment]
Closing due missing information.
