### ISSUE TITLE
Client loading forever

### ISSUE THREAD

**Issue by j2ghz** [xJon/The-1.7.10-Pack#1125]
Installed JDK 8 64bit, installed technic pack launcher, launched The-1.7.10-Pack. On one PC it worked, on the other it's stuck as seen in screenshots.

---
http://i.imgur.com/ZZJPR3a.png
http://i.imgur.com/NnXMM5L.png
https://gist.github.com/anonymous/8506e87287da7e196d0964e51c81accc
https://gist.github.com/anonymous/ed77ca6104d31fff8ead0cd8b1ff1019
https://gist.github.com/anonymous/47551f23bc3a9027cd84d05076ce3866
https://gist.github.com/anonymous/50b51c8674d582810d1e4deb783765b6

**Comment by j2ghz** [comment]
* restarted PC
* reinstalled graphics drivers
* installed vanilla minecraft, works
* deleted and redownloaded pack
Didn't help

---
https://gist.github.com/anonymous/2bf599e65be4354119623bec83fb61ce

**Comment by j2ghz** [comment]
https://gist.github.com/anonymous/f22470da1a1468c02a2b3abc94af7a1f

After 1.5  hours it finally loaded, but it's incredibly slow

**Comment by j2ghz** [comment]
I deleted whole Technic Pack and installed as portable to C:/TP/ instead of normal install into %appdata%/.technic

Loads normally and performs normally.

**Comment by xJon** [comment]
:+1:
