### ISSUE TITLE
Recipe Conflict Industrialcraft 2, Mekanism Tools and Thermal Foundation

### ISSUE THREAD

**Issue by revfisk** [xJon/The-1.7.10-Pack#1126]
The bronze items have a conflict which currently makes crafting the mekanism bronze paxel impossible in survival. The crafting table defaults to the thermal foundation bronze tools, and these do not fit the recipe for the mekanism bronze paxel. 

I am playing on a server, so disabling them tools in the mod options does not seem to work. 

Love the pack!

**Comment by xJon** [comment]
You can set in the controls menu a key to switch between conflicted recipes.

**Comment by revfisk** [comment]
Thank you! Excellent!

**Comment by xJon** [comment]
:)
