### ISSUE TITLE
Crashing for various reasons

### ISSUE THREAD

**Issue by djandy** [xJon/The-1.7.10-Pack#1130]
hi my game keeps crashing after trying to load the world i was playing it was very early on i have 1 small big reactor a couple of pulverisors a couple of furnaces and a quarry that i just built now ive been reading through the crash logs 1 says steves addons 1 says buildcraft 1 says RF all apparently running different versions than reported then another says AE2 API unknowen

**Comment by mandm635** [comment]
Could you post the crash log with pastebin or similar?

**Comment by djandy** [comment]
http://pastebin.com/uWp9vC9
http://pastebin.com/rquv7st
http://pastebin.com/awkcznfum5
http://pastebin.com/pkUs4Jv1

**Comment by djandy** [comment]
that was the 4 different types each blaming a different mod

**Comment by mandm635** [comment]
Only the last link is working but ill take a look

**Comment by mandm635** [comment]
To be clear, you can play other worlds correct? If so, it looks like this world mite be gone, there is something outside of the world bounds causing the error i believe. It may be possible using mcedit to locate the issue. Still learning crash logs so correct me if im wrong, and maybe there is another fix.

**Comment by djandy** [comment]
well i loaded a backup just before the quarry started working and swapped it for an ender quarry and havent had any problems so far update on that thought i mite go where i was going when it crashed just to fully test and its crashed again this time blaming forestry so yeh something in that aera is killing it could it be something trying to spawn in?

**Comment by djandy** [comment]
and is this likely to effect every world i play whenever whatever it is tryes to spawn in?

**Comment by mandm635** [comment]
Im not sure exactly what is happening, I would recommend waiting for @xJon to weigh in.

**Comment by djandy** [comment]
that world was gone and so far in last 2 days ive created 2 more worlds both crash and are un recoverable all im doing is running around there is 1 thing avast seems to block 2 parts of java when loading worlds is that going to be anything to do with it?

**Comment by mandm635** [comment]
It might be, you could try disabling Avast and seeing if it works. Are you using any other mods, and how much ram are you running the pack with?

**Comment by djandy** [comment]
no other mods no and 15gb ram

**Comment by djandy** [comment]
OMG its now just deleted every pack i had in technic or technic cant find them and im back wtf

**Comment by xJon** [comment]
Closed due to inactivity.
