### ISSUE TITLE
Add Mod Request

### ISSUE THREAD

**Issue by dez187** [xJon/The-1.7.10-Pack#1131]
Hi there,
I found your modpack awesome; I looked everywhere on internet for a modpack with this mix of tech and magic, I love it.

I would like if it's possible that you add Metter Overdrive, Minechem, Immersive Engineering and Draconic Evolution.

I also saw that Mekanism will be update to version 9 in few days.

At last its possible do a much large number of quest?

Thanks for your work.

**Comment by CatFace21** [comment]
it would be sick if there add the mods

**Comment by mandm635** [comment]
I took this pack and added all of the mods that I personally wanted(over 100 more :p) you could do the same on a smaller scale and add all the mods you want

**Comment by SpiCraftsman** [comment]
Please can you add Draconic Evolution

**Comment by xJon** [comment]
The mods are not going to be added as they don't fit the modpack's theme. We have lots of mods already.  Thanks anyway for suggesting.
