### ISSUE TITLE
Defense Tech Mod

### ISSUE THREAD

**Issue by mandm635** [xJon/The-1.7.10-Pack#1132]
The creator of Mekanism has come out with a new mod(requires mekanism) that is a remake of the old ICBM. It adds missiles, new tnt, and more. I don't believe we have another mod in this pack that allows for this scale of destruction :). Anyways, I think it would be a cool addition. [http://aidancbrady.com/defensetech/](http://aidancbrady.com/defensetech/)

**Comment by xJon** [comment]
Any idea about the mod's stability?

**Comment by mandm635** [comment]
I havent tested it too much but from what I have tested is really smooth, however it did just come out so is bound to have some issues. At the moment I am not sure how severe these issues are.

**Comment by xJon** [comment]
May be problematic to have missiles along with server protection.

**Comment by xJon** [comment]
Won't happen, unfortunately, due reasons noted above.

**Comment by xJon** [comment]
Will be added with few explosives disabled by default!
