### ISSUE TITLE
Crashing on startup 

### ISSUE THREAD

**Issue by Boone257** [xJon/The-1.7.10-Pack#1133]
Crash report:  http://paste.ubuntu.com/16469750/
every time i start up i loads for 15-40 seconds then crashes back to the launcher. 
i wasnt doing any thing crazy it just froze and i had to restart my PC. 
Im not using optifine.
im playing on a client not a sever.
im using 5gb of ram.
and am on a 64bit version of java.
no herobrine. (that im aware of)
using the recommended modpack version and latest launcher.
i can make new worlds and play on those, but im pretty far and really dont want to restart.

**Comment by mandm635** [comment]
It appears that something went wrong with the Hardcore Questing mod. First, make a backup of the world, then you can try launching the world without that mod installed. If it works, you can re-add the mod and continue playing. Note this might delete all of your progress on the quests, and any items you have from that mod. If this doesn't work, post the new crash log. As a last resort as well you can try to delete/reinstall the pack but be sure to backup your world.

**Comment by mandm635** [comment]
See if this works: [http://www.resonant-rise.com/topic/4773-server-crashes-on-startup/](http://www.resonant-rise.com/topic/4773-server-crashes-on-startup/)

**Comment by Boone257** [comment]
i deleted it out of my world folder and got this crash: http://paste.ubuntu.com/16481892/

**Comment by mandm635** [comment]
Hmmm, it seems that your world has corrupted. Try adding the Hard Core Questing mod back, and opening the world with MCEdit, then pressing Ctrl + l and clicking repair region.
