### ISSUE TITLE
Vajra+Drum Quest

### ISSUE THREAD

**Issue by ILikeYo** [xJon/The-1.7.10-Pack#1139]
Hello,

Recently i wantet to craft the Vajra but i cant't , it buggs back in the Crafting Menu and At the quest with the Drums and fluids the it says Drum 0/1 what drum. A normal Drum dosen't work.

I play in the 0.7.9f

**Comment by xJon** [comment]
Thank you for reporting the issue and including the modpack version you play with, but due to you being really outdated I can't do anything with your report.
Sorry! just try to be up to date.
