### ISSUE TITLE
the modpack is to eazy/short 

### ISSUE THREAD

**Issue by CatFace21** [xJon/The-1.7.10-Pack#1140]
i was play the mod play for like a day i have done like 80% of the stuff in the modpack.
this is Y its eazy Diamonds r to eazy to get magic crops all you need is 4 diamonds then you have done every thing. but that just me say something  if you thing so to. all i am asking is if you can add something like over powered end mob that you have to kill n swords you have to get from there.

ps Stilll best modpack i have every played

**Comment by xJon** [comment]
Do you have any specific suggestion?
Also, did you complete all the HQM quests?

**Comment by CatFace21** [comment]
i dont have any suggestion right now but i have complete HQM quests

**Comment by CatFace21** [comment]
but one thing i do know is that if you have magic crop n tinkers  then you can make a over powered sword n stuff in the 1st 1 - 2 hours you know skyfac you know that mod pack there have it soo you have to kill mobs to get the seeds that may make it harder

**Comment by xJon** [comment]
Thanks anyways for the suggestions.
Maybe if you have a specific mod/config suggestion we would be able to do something.
