### ISSUE TITLE
Potion ID confilct

### ISSUE THREAD

**Issue by MunkyMagick** [xJon/The-1.7.10-Pack#1142]
There is a potion ID conflict for a witchery effect and Taint Withdrawal from Thaumic Tinkerer. (id 32)

This can be easily fixed by changing the ID in the thaumic tinkerer config (line 35), but I thought you might like to change it in your next update.

**Comment by xJon** [comment]
How could one reproduce the issue?
Also, line 35 of the ThaumicTinkerer config is not changeable.

**Comment by xJon** [comment]
Did you mean Thaumic Exploration? Took me a while to understand.
Will be fixed in the next update - thanks for reporting.

**Comment by MunkyMagick** [comment]
Yes I think it was thaumic exploration. Sorry for the confusion...

Get Outlook for iOS




On Sun, Jun 19, 2016 at 4:11 AM +0100, "Jon" <notifications@github.com> wrote:





Did you mean Thaumic Exploration? Took me a while to understand.
Will be fixed in the next update - thanks for reporting.

---
