### ISSUE TITLE
Mod Suggestion 3 mods ExtraTic Draconic Evolution and Metallurgy   Links in Desc

### ISSUE THREAD

**Issue by david425** [xJon/The-1.7.10-Pack#1143]
http://mods.curse.com/mc-mods/minecraft/extratic

http://minecraft.curseforge.com/projects/metallurgy

http://minecraft.curseforge.com/projects/draconic-evolution 

All these mods i think would be great if added and further imrpove tinkering in this modpack thanks :D

**Comment by xJon** [comment]
Currently not going to add the mods. Thanks anyway for suggesting!
