### ISSUE TITLE
Add the dual hotbars mod

### ISSUE THREAD

**Issue by thecakeisalie25** [xJon/The-1.7.10-Pack#1145]
This mod does what you think, adds a hotbar.
It adds nothing to unbalance the game, and uses the inventory slots in your inventory, and is generally awesome. It would be really helpful if it was added.
Link: [link](http://mods.curse.com/mc-mods/minecraft/223272-dual-hotbar#t1:description
)Thanks.

**Comment by xJon** [comment]
Not going to happen, it doesn't fit the modpack's theme.
Thanks anyway for suggesting!
