### ISSUE TITLE
Missing 'server' JUM

### ISSUE THREAD

**Issue by Loedman** [xJon/The-1.7.10-Pack#1147]
I get an error saying it's missing server jum or something like that. Full erroris in pic. Doesn't do anything after that.
![schermafdruk 2016-05-28 17 17 36](https://cloud.githubusercontent.com/assets/19624849/15628082/1bd23802-24f8-11e6-9be6-5532372effc4.png)

**Comment by xJon** [comment]
Your Java installation is missing some components.
Anyway you can edit the launch `.bat` file to fix this: remove the `-server` argument.

**Comment by Loedman** [comment]
It still doesn't work for me.
