### ISSUE TITLE
Error while loading map.

### ISSUE THREAD

**Issue by KiesieK** [xJon/The-1.7.10-Pack#1148]
http://pastebin.com/PsSfr4vF
PC Specs if needed:
I5-6600K OC'ed to 4.5GHZ
2x8GB 2666MHZ Geil Dragon
Z170A Gaming Pro Carbon (MSI)
8800GT by Palit (gonna change soon)

Gave 8GB to modpack.
![fdafdsafsd](https://cloud.githubusercontent.com/assets/19631779/15631962/ee705b9c-2582-11e6-803d-01666bc3543a.PNG)

**Comment by xJon** [comment]
Is that the full log?
Also, when did the problem start to occur?

**Comment by KiesieK** [comment]
It was entire log from technic launcher (there was nothing above it). Well, i've never played it, wanted to start playing on those mods. So it started to occur after installing.

**Comment by xJon** [comment]
Please post the `fml-client-latest.log` file. Use [this](http://paste.ubuntu.com/).

**Comment by KiesieK** [comment]
http://paste.ubuntu.com/16815391/

**Comment by xJon** [comment]
Disable the Morph mod, enter your world, and then re-add it.
Should fix your issue.
