### ISSUE TITLE
Missing 'server' JUM

### ISSUE THREAD

**Issue by Loedman** [xJon/The-1.7.10-Pack#1149]
Yesterday I had problem with making a server, so I asked this website. Said that I needed to remove -server argument so I did that, and I got a new error.

[LaunchServer.txt](https://github.com/xJon/The-1.7.10-Pack/files/288475/LaunchServer.txt)
![schermafdruk 2016-05-28 17 17 36](https://cloud.githubusercontent.com/assets/19624849/15635247/f1c22c24-25d9-11e6-908d-ded2d23794a4.png)
![schermafdruk 2016-05-29 20 02 22](https://cloud.githubusercontent.com/assets/19624849/15635246/f1c19fac-25d9-11e6-86bb-78e9af3b7a6e.png)

**Comment by Loedman** [comment]
Can you maybe give a link to the things I need to download to not have missing things in Java or something like that?

**Comment by Loedman** [comment]
![schermafdruk 2016-05-29 20 18 13](https://cloud.githubusercontent.com/assets/19624849/15635268/7d33c678-25da-11e6-98c1-0de0002378cf.png)

**Comment by xJon** [comment]
On a second look, I'm pretty sure I understood your issue.
You have Java 32 bit installed. Install Java 64 bit.

**Comment by Loedman** [comment]
5 minutes before you answered I already installed java 64. Again, because I already had it. I installed it from the official oracle website.

**Comment by xJon** [comment]
Did you uninstall your 32 bit Java?

**Comment by mandm635** [comment]
Try navigating to your Java folder and be sure that only the 64bit version is listed there. If it is correct then it is possible that Java thinks you still have the other version installed, but I wont go into detail unless that is the case.

**Comment by xJon** [comment]
Closed due to inactivity.
