### ISSUE TITLE
Flans Mods Textures

### ISSUE THREAD

**Issue by Spiderweb121** [xJon/The-1.7.10-Pack#1150]
For some of the guns, They are still there. But on some others, They have basically just vanished when you hold them or drop them on the ground. It only leaves a shadow on the ground.

**Comment by xJon** [comment]
Are you using a Sphax patch or what?
If so, of what version?

**Comment by Spiderweb121** [comment]
If you mean texture pack Sphax, then no. I am using no texture pack.

**Comment by xJon** [comment]
What modpack version?
Any additional mods?

**Comment by xJon** [comment]
Can you name specific names of gun without textures so I'll try to reproduce?

**Comment by Spiderweb121** [comment]
Give me a minute then.

**Comment by Spiderweb121** [comment]
I can't load the world. When I create a new one, Same thing happens and it
gets deleted.

**Comment by xJon** [comment]
Can you provide a bit more information about your unfolding issue?
Can you include your latest client log?

**Comment by xJon** [comment]
Will keep investigating in https://github.com/xJon/The-1.7.10-Pack/issues/1163
