### ISSUE TITLE
Freezing issue

### ISSUE THREAD

**Issue by gman2010** [xJon/The-1.7.10-Pack#1151]
so, im having an issue with The 1710 pack freezing whenever i start a world OR join a server.. it does not crash so i never get a crash report i always have to force it to stop. any ideas what could be causing this. ive checked my ram to include the DIMMS which they are installed also have opened the console in technic to see where the last line is and where it stops working.. nothing shows to be out of the ordinary this has been happening ever since the .8.4 update..
Here is the bottom part of my log.
http://pastebin.com/zuAqnHhu

**Comment by gman2010** [comment]
http://pastebin.com/m3WDYaV1

This is from me trying to log in to a server.. just in case this helps any..

**Comment by xJon** [comment]
Literally no errors in the log you gave. Any chance for a full client latest log? use the paste tool from the readme file

**Comment by gman2010** [comment]
I'm not noticing any errors either.. So let me try to explain it and maybe someone might have an idea.. So it seems to be happening when i enter a world (letting it load completely before moving and not having an issue with it) then once i start moving i get like 5-6 steps and it freezes.. :/ I really enjoy this pack but unfortunately its unplayable for me now..

**Comment by xJon** [comment]
It doesn't happen with other modpacks?

**Comment by gman2010** [comment]
No sir. No other Technic or FTB modpacks freeze on me like this without crashing.. it sucks because i wish i could get a crash log.. im hoping with 9.0 being released soon it will just magically fix itself

**Comment by xJon** [comment]
You did note it happened just update the v0.8.5 update?
Any I'd really like your latest client log. See [there](https://github.com/xJon/The-1.7.10-Pack/blob/master/README.md) how to get it.
It's your log from your latest play session, so be sure your game freezes in that session.

**Comment by gman2010** [comment]
okay, ill obtain that straight away.. and actually this started occurring after the 0.8.4 update.. let me snag the latest log on this ill see if i cant file share it because pastebin wont allow me to paste the whole thing as it was too big.. i'll also try paste.ubuntu.com maybe that will work

**Comment by gman2010** [comment]
So here is another thing that i found very interesting when just looking at my log file.. The file name up until just recently had a proper date format. the last 3 i have had have been behind by several days the one for today (6/22) is named 2016-06-14-1.log and the one from the 14th (last time i tried) was named 2016-06-08-1.log.. i dont think this is the issue but just found it odd anyways here is the log from when i tried today.
http://paste.ubuntu.com/17702453/

**Comment by xJon** [comment]
That's not the log. You need to find the log named `fml-client-latest.log`.

**Comment by gman2010** [comment]
ah, okay here it is.. sorry.. the -.log- file confused me a little as far as which one you needed...
[fml-client-latest.zip](https://github.com/xJon/The-1.7.10-Pack/files/328922/fml-client-latest.zip)

hope you dont mind me just setting it as an attachment because i cant get any of the paste sites to process all the text in it..

**Comment by xJon** [comment]
http://paste.ubuntu.com/ accepts large files but okay.

**Comment by gman2010** [comment]
But see it did freeze thats just it and i have no clue why.. ill video capture it today and post it up too.. but in the meantime ill keep saving logs each time it freezes and build up a collection of files for comparison. Ill try to post at least every day that i have time to fiddle (uninstall/reinstall/tweak) and i do understand that you are a busy guy so unless you want to you dont have to make this a priority im not stressing about it and im sorry if it seems like ive been bugging in any way..

**Comment by xJon** [comment]
No, it's alright; I'm here to help you.
If we don't see anything in the log try to capture it and then provide again the latest log.
Also try with the new released version, v0.9.0.

On another note, does this issue occur to you in new generated worlds and/or in servers?

**Comment by gman2010** [comment]
It happens with both, but seemingly faster on public servers, i will have a capture of it by the end of the day posted up for you to view in the morning (im assuming you are UK) im also going to try a fresh install of windows 8 on my other hard drive to see if that helps solve anything. My reasoning for that is your mod pack works on my girlfriends computer and she is running 8. Also am wondering if it might be a coincidence that when i upgraded to 10 i did just that and not a fresh install and it just so happens that around that time this all started happening the 0.8.4 release had just happened and i fresh installed windows 10. Will let you know though

**Comment by gman2010** [comment]
so.. latest update..... just got done installing windows 8.1 again on one of my other hard drives allowing me to run it as a dual boot.. AAAAAND it works... so my conclusion is that it is an issue with whatever version of windows 10 i have missing something that one of the mods in this pack uses to allow it to work.. i am content with this for now but would be really curious to know which mod requires what that im missing :/

**Comment by xJon** [comment]
*Welp*

**Comment by gman2010** [comment]
If you would like Jon i can still recreate the happenings and capture/post them.. if you would like to get in contact with me other then on here let me know

**Comment by LukaPix** [comment]
Im having the exact same problem on win10

**Comment by xJon** [comment]
@LukaPix You can open your own issue with your details and we'll look at it.

**Comment by LukaPix** [comment]
no need to, this is easily fixed by using jre and not jdk for Minecraft x'D
