### ISSUE TITLE
Fatal Blocks Missing 

### ISSUE THREAD

**Issue by psychopathicklr** [xJon/The-1.7.10-Pack#1152]
i'm running the same forge on both the server and client
I have the mods and the config files all in the right places for the server 
i have the server running fine 
i have all the mods the server has and the configs on my client 
whenever i launch my client 5 mods are not compatible with forge so i cant join the server
i was wondering what an effective way of finding the mods where or someone telling me which mods in this pack i have to remove

**Comment by xJon** [comment]
It means your server and client don't have the same modpack version installed.
