### ISSUE TITLE
game crash 

### ISSUE THREAD

**Issue by saaaaad** [xJon/The-1.7.10-Pack#1154]
so i have an issue when i click play i see ablack screen and i need to wait then the game crash

**Comment by saaaaad** [comment]
so i have an issue when i click play i see ablack screen and i need to wait then the game crash

**Comment by xJon** [comment]
Crash log?

**Comment by saaaaad** [comment]
haw can iknow?

**Comment by xJon** [comment]
Read [this](https://github.com/xJon/The-1.7.10-Pack/blob/master/README.md) to see where you can find it.

**Comment by saaaaad** [comment]
ok thats it http://paste.ubuntu.com/17000909/

**Comment by xJon** [comment]
Do you have any additional mods?

**Comment by saaaaad** [comment]
no

**Comment by xJon** [comment]
We're using the latest release of OpenComputers for 1.7.10.
Please report the issue [there](https://github.com/MightyPirates/OpenComputers/issues), as there's nothing we can do.
