### ISSUE TITLE
Game Crashing on title screen

### ISSUE THREAD

**Issue by doctorwho122801** [xJon/The-1.7.10-Pack#1156]
After i Installed the pack off of technic launcher on to my Mac it opened up just fine and i started a single player creative-world. My computer went to sleep while on full screen a few time while i left it on for various reasons. One time i got back, woke it up, and it froze for a sec and sent me back to the technic Launcher without a popup or anything. I tried to open it again but when i got to the title screen it froze for a sec and brought me back once again to the Launcher without a pop up.
 saying why it closed on me. Pls explain its one of my favorite packs :(

**Comment by xJon** [comment]
Crash log?

**Comment by doctorwho122801** [comment]
how?(sorry)

**Comment by xJon** [comment]
Read [this](https://github.com/xJon/The-1.7.10-Pack/blob/master/README.md) to see where you can find it.

**Comment by doctorwho122801** [comment]
http://paste.ubuntu.com/17004443/ 
is this it?

**Comment by doctorwho122801** [comment]
is that the right one xJon

**Comment by xJon** [comment]
Nope.

**Comment by doctorwho122801** [comment]
http://paste.ubuntu.com/17027845/ this one @xJon

**Comment by doctorwho122801** [comment]
or this one? http://paste.ubuntu.com/17028181/

**Comment by xJon** [comment]
What modpack version do you have installed?
Also, do you have any additional mods?

**Comment by doctorwho122801** [comment]
modpack version is 0.8.5 and no i don't have any additional mods @xJon

**Comment by xJon** [comment]
In the modpack's folder, reset the `options.txt` file (by deleting it). It should fix your issue.

**Comment by doctorwho122801** [comment]
thank you soooooo much 👍
