### ISSUE TITLE
Miniature Green Heart needs a custom recipe

### ISSUE THREAD

**Issue by CatFace21** [xJon/The-1.7.10-Pack#1158]
# on the wiki its said:
The Miniature Green Heart is an item from Tinkers' Construct. It cannot currently be legitimately obtained in survival. It will likely be used to craft the Green Heart Canister, but there is no such recipe (yet) except in packs with custom recipes. It can be eaten to restore 30 life.

Soo i thick you need to add a custom mob or crafting recipes on the mod pack  plz fix @xJon @The-1-7-10-Pack

Ps i think you should add lucky blocks

**Comment by xJon** [comment]
We don't want currently to add a custom recipe for it.
