### ISSUE TITLE
A fatal error has occured, this connection is terminated

### ISSUE THREAD

**Issue by crausk** [xJon/The-1.7.10-Pack#1159]
Hi, After i created a world this shows.
This is the last log 
http://paste.ubuntu.com/17020868/
I errased the mod pack and install it againg but it does not solve anything, its the first time that i try to play this modpack.

**Comment by xJon** [comment]
Can you post the latest client log? the error is not showing in this log.

**Comment by xJon** [comment]
Closed due to missing information.
