### ISSUE TITLE
Game crashs if I join my friends hamachi server.

### ISSUE THREAD

**Issue by Gauhst** [xJon/The-1.7.10-Pack#1160]
So If I join the hamachi server of my friend it crashs in the loading screen.
I didnt edit anything I reinstalled it, my friend removed my ''saves'' so its like I'm joining the server for the first time. nothing works

here is the crash log : http://paste.ubuntu.com/17031789/

Please help me

**Comment by xJon** [comment]
Some TC item in the inventory of a player is acting bad. If you want, you can delete the player data and so reset it and fix the problem.
