### ISSUE TITLE
Empty Graves

### ISSUE THREAD

**Issue by HomeFunk** [xJon/The-1.7.10-Pack#1161]
10++ times now we have lost our hole inventory, with no apparent reason.

get killed by another player, go and knock down grave - only getting head in return. this does seem to be random, but only when players killed eachother (morph or not, in diffrent dimensions etc.)

last bit of my client log of said problem.

**EDITED: please use a paste-tool and post the full log.**

**Comment by xJon** [comment]
http://paste.ubuntu.com/

**Comment by xJon** [comment]
Closed due to missing information.
