### ISSUE TITLE
Malware report when map is loading up.

### ISSUE THREAD

**Issue by sonic1412** [xJon/The-1.7.10-Pack#1162]
When I run the pack Avast! tells me that it has blocked a malware attack from here: http://sso.anbtr.com/domain/modstats.org
This is probably due to a mod sending info to that address, which has been bought by some unscrupulous individual. I will update this if I find what mod is sending the information.

Edit, Log information: 
[fml-client-latest.zip](https://github.com/xJon/The-1.7.10-Pack/files/310029/fml-client-latest.zip)

**Comment by xJon** [comment]
I'm not sure how can we check which mod sends that. Maybe in your latest client log?

**Comment by sonic1412** [comment]
I believe this is the correct log file:
https://github.com/xJon/The-1.7.10-Pack/files/310029/fml-client-latest.zip

**Comment by xJon** [comment]
Can't find anything related in your log.

**Comment by sonic1412** [comment]
Strange, ill do some more looking on my end and update this ticket.

**Comment by xJon** [comment]
Got the same report from ESET while trying to connect to a particular server.
Is it the same to you?

**Comment by sonic1412** [comment]
It is the same for me. Whenever I load into a new map, or a saved one, some code somewhere runs and I get the message that Avast! has saved me from a malware attack.

**Comment by xJon** [comment]
It's not really a malware attack but a blacklisted address.

**Comment by sonic1412** [comment]
Do you think it would be safe to add the modpack to Avast!'s exclusion list?

**Comment by xJon** [comment]
Pretty sure it's safe but you can let your antivirus keep blocking it, it shouldn't affect your gameplay.

**Comment by xJon** [comment]
Currently closing.
