### ISSUE TITLE
Enchanting Plus (Advanced Enchantment Table)

### ISSUE THREAD

**Issue by Kane632** [xJon/The-1.7.10-Pack#1165]
The 1.7.10 pack version: 0.8.5
Enchanting Plus version: 1.7.10-4.0.0.74

I can only enchant the same item multiple times if I am in creative mode. If I am in survival and enchant it (It doesn't matter if it is the table from the mod, or the vanilla one), then It says that I do not own that item and can't use it again in the _Advanced Enchantment Table_.
If I enchant an item X times in creative, then I can modify it one last time in survival, blocking it again.

I have tried going through the config (eplus.cfg) and changing `B:secureItems=true` to false and the problem persists.

**Comment by xJon** [comment]
Does it happen to you in other game saves?

**Comment by Kane632** [comment]
It happens on both of my servers (local and hosted) but you made me think. They're with the `online-mode=false` so I created a new local server with `online-mode=true` and seems that I can enchant again correctly. Maybe the mod doesn't support well the offline UUIDs of minecraft usernames, but if I am in an offline server with `B:secureItems=false` it should work (I suppose).

**Comment by xJon** [comment]
Interesting. Glad you managed to figure it out yourself :+1:
