### ISSUE TITLE
Crash on searching for "tank" in NEI

### ISSUE THREAD

**Issue by rcslaney** [xJon/The-1.7.10-Pack#1166]
Searching for "tank" in NEI takes a very long time causing it to freeze temporarily then moving to page 2 of NEI list causes it to freeze up completely then crash due to running out of memory. It seems to be an issue with the portable tanks from thermal expansion as searching for "portable" too also crashes it. I'm guessing some invalid registered fluid or something?

**Comment by xJon** [comment]
What's the modpack version you're using?

**Comment by rcslaney** [comment]
Using v0.8.5

**Comment by xJon** [comment]
There's a slight lag when you first look it up but it depends on your system if your game decides to crash.
Nothing we can really do about it unfortunately.
