### ISSUE TITLE
Crash on v0.9.0

### ISSUE THREAD

**Issue by Forbid2** [xJon/The-1.7.10-Pack#1169]
**EDITED: Please use a paste-tool: http://pastebin.com/Ferj4keC**

**Comment by xJon** [comment]
https://github.com/xbony2/Nuclear-Control/issues/161

**Comment by xJon** [comment]
Maybe can you provide a bit more detail so I'll know how severe the bug is?

**Comment by Forbid2** [comment]
What do you need?

**Comment by Forbid2** [comment]
It crashes after it loads. So when it gets done loading goes to menu and crashed before it makes it there

**Comment by xJon** [comment]
Do you have any custom capes for modded Minecraft?
anyway, for now, you can manually revert the version of the Nuclear Control 2 mod - download [this](http://minecraft.curseforge.com/projects/nuclear-control-2/files/2275987/download) and switch it in the `mods` folder with the newer version. If this happens to you only in v0.9.0, reverting should fix your problem.

**Comment by trippnout** [comment]
What about a fix for people running servers. It runs on my computer fine but my friends it crashes and if he messes with that mod pack the server won't let him join.

**Comment by xJon** [comment]
If it's a private server you can manually change the mod's version.

**Comment by xJon** [comment]
Basically just stuck on this bug fix to work on v0.9.1.

**Comment by Forbid2** [comment]
Ya the fix you gave me works. I also had to update the server part as well

**Comment by xJon** [comment]
Yes, that's the problematic aspect of the *"fix"*

**Comment by trippnout** [comment]
Any word on the mod being updated to fix this bug. Instead of having people do it manually ? I don't mind doing it but I have a feeling I'll have to do it for all my friends who can't connect to my server

**Comment by xJon** [comment]
@trippnout I did report the bug to the mod author and so did others, no idea on progress of releasing a new version though.

**Comment by trippnout** [comment]
K thanks.

**Comment by clienthax** [comment]
@xJon @Forbid2 Please try this, http://haxyshideout.co.uk/projects/mcfixs/1.7.10pack/IC2NuclearControl-2.4.0b.jar

**Comment by xJon** [comment]
@trippnout please confirm this compiled version works for you (you manage to launch and play with the mod)

**Comment by trippnout** [comment]
Mine ran perfectly without having to change anything. It's my friends who's computer has this problem. I haven't yet fixed his, because doing so I'll have to change the server, and the server is managed 3rd party. So it would be down while they changed those files over for us.

**Comment by xJon** [comment]
@trippnout Can you ask your friend to test this build then? and can you @Forbid2 test it and confirm it launches, too?

**Comment by Forbid2** [comment]
I will test tomorrow morning

**Comment by xJon** [comment]
@Forbid2 Thanks, I appreciate it

**Comment by Forbid2** [comment]
Works for me

**Comment by xJon** [comment]
@Forbid2 Thanks!
