### ISSUE TITLE
growthcraft thistles v 9.0

### ISSUE THREAD

**Issue by djandy** [xJon/The-1.7.10-Pack#1172]
hi been playing for a few hours was just underground digging out a base come up and thistles have taken over the word littlerally as far as has been loaded there isnt a single piece of dirt without 1 on is there a way of turning down the spawn rate on these?

**Comment by djandy** [comment]
found it in the config but also in the config it says max of 10 allowed per chunk i have every chunk full to the brim with them for as far as the eye can see so theres problems with the mod at a guess

**Comment by xJon** [comment]
Can you give me some instructions to reproduce the issue?

**Comment by MacDeth** [comment]
xJon you can simply find a biome with thistles and wait. They'll take over the land pretty quickly. I'd recommend afking for a half hour to an hour.

**Comment by MacDeth** [comment]
![2016-07-03_20 41 10](https://cloud.githubusercontent.com/assets/3325276/16548532/af8d0252-415e-11e6-88d7-eaf8193b6e3b.png)
Here you can clearly see the line where the chunks weren't loaded, and the spreading stopped there.

**Comment by xJon** [comment]
In the newer versions this can be configured. Will make sure this be changed. Thanks for reporting.

**Comment by MacDeth** [comment]
Thanks, glad I could help you help me. I had to use water on those hills to remove them in a last ditch effort, haha.
