### ISSUE TITLE
Mekanism conversion 8v to 9v 

### ISSUE THREAD

**Issue by Dommain** [xJon/The-1.7.10-Pack#1173]
I have about 250k energy cells that I cannot use for crafting the induction cells after the update to the test version. It shows a ":100" after the cell which the NBT data is keeping it from being used in crafting. Do not know if the remediable.

**Comment by Dommain** [comment]
Basic tank doesn't have a recipe?

**Comment by Dommain** [comment]
upgraded infuser using installer card and they will not accept energy from ender IO.

**Comment by xJon** [comment]
Issues due to updates are common and you may have to use cheats to fix them.
About the recipe - I can double check for that.

**Comment by Dommain** [comment]
Destroying the energy cells fixes the NBT data issue. Tablets are still not fixed. >_>

**Comment by xJon** [comment]
The tanks recipes is an issue that we can fix manually with the INpureCore configs.
But what tablets are you talking about?
