### ISSUE TITLE
Crash while initializing

### ISSUE THREAD

**Issue by Amedinno** [xJon/The-1.7.10-Pack#1174]
I just don't know what is going on. No extra mods, clean installed modpack.

Latest 
http://paste.ubuntu.com/17936955/

**Comment by Amedinno** [comment]
I am using 0.8.5 btw

**Comment by Amedinno** [comment]
http://paste.ubuntu.com/17938042/

**Comment by xJon** [comment]
You should at least try to update to v0.9.0 just to see if the issue is gone.

**Comment by Amedinno** [comment]
Not gone

http://paste.ubuntu.com/17966017/

**Comment by xJon** [comment]
Do you play on a server or client?

**Comment by Amedinno** [comment]
Client

**Comment by xJon** [comment]
Did you try to reinstall already?

**Comment by Amedinno** [comment]
Yes, about 5 times. But I never re-installed the launcher

**Comment by xJon** [comment]
Reinstalling through the launcher or manually?

**Comment by Amedinno** [comment]
Both

**Comment by Amedinno** [comment]
I re-installed using the "Delete Pack" button and manually deleting the pack by myself

**Comment by xJon** [comment]
Try to launch the pack without MagicBees. Is it working?

**Comment by Amedinno** [comment]
Sorry forgot to reply, thanks! It is working.
