### ISSUE TITLE
Crash starting server

### ISSUE THREAD

**Issue by roddroch** [xJon/The-1.7.10-Pack#1175]
I had a error like this b4, but it was just some shit that i done
I started the vanilla server, then i deleted the server that i made, and created other, executing the right .jar 
Crash report http://paste.ubuntu.com/18132010/
Server http://paste.ubuntu.com/18132034/

Bad english, sorry

**Comment by xJon** [comment]
Reset your questing data inside of `/saves/hqm/`.
