### ISSUE TITLE
Superflat worlds woring incorrectly

### ISSUE THREAD

**Issue by Excepto** [xJon/The-1.7.10-Pack#1176]
When I try to open a superflat world and try to use a different preset than the classic flat when i get out of the superflat menu it changes the world type to biomes'o plenty.

**Comment by xJon** [comment]
Unfortunately there might be a bug which doesn't let you edit the superflat worlds. If you want to fix it, manually remove a mod named `DefaultWorldGenerator-1.7.10-0.1-b13-client.jar`.
