### ISSUE TITLE
How to setup the 1.7.10 pack with thermos+?

### ISSUE THREAD

**Issue by mrsaminus** [xJon/The-1.7.10-Pack#1177]
Hello.

Can anyone help me with setting up this amazing modpack for my server using Thermos?
Im not to good with all that thecnical stuff... quite a noob :package:

**Comment by xJon** [comment]
I'm actually not sure, new to Thermos. But it shouldn't be a different process than with other modpacks. Just lookup a tutorial online.

**Comment by xJon** [comment]
Closing for now.
