### ISSUE TITLE
Server Pause

### ISSUE THREAD

**Issue by TANGOjPANDA** [xJon/The-1.7.10-Pack#1179]
So i am running a server and the proiblem is every 8 hours it will freeze all up and downstream of data in essence kicking all players on at the time. this isnt registered on the console and nothing abnormal is logged. The strange part is that if i just click on the console and clcik enter it will catch up and continue as if nothing happened. It is a slight annoyance but other than that not much of a problem. 
P.S I will like to add it isn't running out of memory, and has happened 3 times in the last 24 hours only when people are on (might just be coincidence it happened when people are on).
P.S.S I dont see much of a reason to post a log due to it not recording anything in this time. If needed i will upload one.

**Comment by mandm635** [comment]
Are you sure that it is not running out of memory? Please say how you are checking. How does the server run normally for players connecting from another location? PC specs?

**Comment by TANGOjPANDA** [comment]
Specs are 12 GB ram 4 which is dedicated to the server it has had 5 players playing at one time fairly well. Each time the server pauses it is when only a single player is on. CPU is and fx8350 8 core running at 4 GHz.
I am starting to believe it is coming down to how windows/amd vary power output over

**Comment by TANGOjPANDA** [comment]
Sorry accidently clicked comment I was gonna say I think it comes down to how my computer is handling tasks it seems to deprioritise the task and it slows down to a point it stops thinking and then requires a user input to readjust its priority

**Comment by mandm635** [comment]
Well if that is the case than the only solution I can think of is to install a reatart plugin the restarts the server every 4 hours or so. This might not work but it may prioritize the server again. It is a pain to setup mods and plugins but you could use Thermos maybe. Can't remember if Sponge is 1.7 but if it is than thats another option. If that doesn't work, there could be a program or setting that would keep the server prioritized. 

Good luck, and sorry i'm not making a ton of sense but im on vacation so just checking in.

**Comment by TANGOjPANDA** [comment]
Its not much of a problem for me I literally have a server for 8 people and we try to go on at the same time so I am usually on when people want it on so it never pauses when the majority is on. I'll try the fix you have said just cause I have time and I'll keep this thread updated.

**Comment by Curunir** [comment]
You can manually assign a priority in Task Manager, although tread carefully when using this option. I found that the best and most reliable platform to host a Minecraft server (and running a client, too) is a standard Linux distribution like Mint or Ubuntu.

**Comment by TANGOjPANDA** [comment]
Firstly from previous experience im know the affinities wont help this problem. 
seconmdly i realised it isn't only this modpack it seems to be any new ones i have tried (vanilla and modpacks of 1.10 have had the same issue) but saying that i haven't hosted a 1.7.10 server on my pc before i restored it recently. so i am unable to compare it with any previous experiences. i am going to assume for now that it is specific to my pc and will leave it at that. and assume that it will not persisit through a reset which i will be doing later this year. Obviously if anybody has any suggestion i would be happy to try them out.
