### ISSUE TITLE
Freezes after while, no error in log

### ISSUE THREAD

**Issue by freemanovec** [xJon/The-1.7.10-Pack#1180]
I have the same problem as in [here](https://github.com/xJon/The-1.7.10-Pack/issues/828), client freezes after a few minutes of playing (server still runs (LAN multiplayer)).
**No error in any log.**
Reinstalling worked for around one hour, then the crashing started again.
Minecraft Version: 1.7.10
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_91, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

Any ideas?

**Comment by xJon** [comment]
Could you still post here using the Ubuntu paste-tool your `fml-client-latest.log` file?

**Comment by freemanovec** [comment]
There's really nothing about it in the log. No info, no error. Just usual info (minimap updates etc.)
I've tried removing a lot of mods, but it crashed with and without a few of them. List of them should be in the log. I also added a few mods (one that fixes the LAN multiplayer port and one from my repo), but it makes no difference. It freezes at seemingly random points at a ranging time from start (10m-2h). Tried with+without texture pack, still same. I blame some of the core mods' endpoint, but that's just my newbie opinion and it is propably something else. I am getting this bug just on this computer setup, on my ntb it works fine. It doesn't matter if the world is LAN open or not, I already had this bug on my previous world.
fml-client-latest.log: [Ubuntu Pastebin Entry](http://paste.ubuntu.com/18329492/)
That's it. No error. But it just freezes. Thanks for your patience.

**Comment by xJon** [comment]
Did you try to update to v0.9.0?

**Comment by freemanovec** [comment]
You have updated Mekanism to v9! *hug*
Ill keep you posted about the freeze

**Comment by freemanovec** [comment]
No freezing occured. But now the screen just turned black. Game still runs, but nothing is displayed. I'll open a new issue.

**Comment by freemanovec** [comment]
Unfortunetely the same problem is back.

**Comment by xJon** [comment]
What changed?

**Comment by freemanovec** [comment]
Same old, only on pack version 9.1

**Comment by xJon** [comment]
Did you try to update to v0.9.2?

**Comment by freemanovec** [comment]
Yup, still the same problem.

**Comment by freemanovec** [comment]
I removed Botanica and it seems to work

**Comment by xJon** [comment]
Botanica or Botania?

**Comment by freemanovec** [comment]
Botania, sorry

**Comment by freemanovec** [comment]
I will reopen if it will happen again

**Comment by freemanovec** [comment]
The bug appeared again, it seems to be tied with the save.

**Comment by xJon** [comment]
Did you check to see there's still no error?
Anyway, try to remove Fastcraft and see if there's any change.

**Comment by freemanovec** [comment]
I'm just running the backup with Moon being replaced by the version from the broken save, if it won't happen again in 30 minutes I'll try running the broken save without Fastcraft.

**Comment by freemanovec** [comment]
And yes, there's still no error/stacktrace/warning/leak in the log. Is there any possible way I can run this pack monitored completely? I mean like when running a dev enviro in Eclipse, when it gives you the breakpoints etc.?

**Comment by xJon** [comment]
Not really, except activating debug modes in few mods. Anyway, did you try to remove Fastcraft?

**Comment by freemanovec** [comment]
I didn't have to, it stopped blackscreening before I tried to do that. I still don't know what was causing this issue, but it was definitelly tied with the save. I'm going to close this issue for now.
