### ISSUE TITLE
twilight biome id conflict

### ISSUE THREAD

**Issue by mrsaminus** [xJon/The-1.7.10-Pack#1181]
easyer to paste the log from discord here to show the problem and what is tryed

MrSaminus - Today at 7:03 PM
i have a problem on my server with "Twilight biome ID" it says it has a conflict and the number needs to be changed in the config..
https://gyazo.com/6f7a9ee7f147386da7d1821f4a673a5b
i have tryed this.. but still same message.. any idea of what biome code i should use?
sunshinehunter - Today at 7:23 PM
You shouldn't edit by yourself
You shouldn't edit by yourself
Did you add mods with biomes?
MrSaminus - Today at 7:30 PM
i have not added anything.. but i have disabled "taint" and "redwood"
SlackerNet>XI<ADM - Today at 7:46 PM
try and rename the world and gen a new one. to see if the error returns
MrSaminus - Today at 7:46 PM
2 sec
SlackerNet>XI<ADM - Today at 7:47 PM
what version are you using ?
MrSaminus - Today at 7:48 PM
0.8.5 (of the modpack)(edited)
SlackerNet>XI<ADM - Today at 7:48 PM
ok cool on ours twilite is dim 7
MrSaminus - Today at 7:49 PM
i can try it again 
still same error.. dim is set at 7.. bop has no 7 as i can see
SlackerNet>XI<ADM - Today at 7:59 PM
what forge ver do you have we use 1614
SlackerNet>XI<ADM - Today at 8:00 PM
is  it crashing ? you can always check the log for any errors
MrSaminus - Today at 8:02 PM
no crash.. only message about ID conflict..
SlackerNet>XI<ADM - Today at 8:05 PM
i am searching the issue now...dont know what it is in conflict with could make it hard to do. One idea would be change server prop from BOP to large biomes and gen yet another world..that would pinpoint bop as the issue
MrSaminus - Today at 8:05 PM
i have tryed to google it also.. but the only thing i found was : change the number... i have done it sevral times.. now its "7" and no bop id's are "7"
SlackerNet>XI<ADM - Today at 8:09 PM
i would think we need to check the bop version #
BOP versions are 0.85 has 1826 and 0.90 has 2027 ... what ver do you have ?
MrSaminus - Today at 8:15 PM
2 sec
SlackerNet>XI<ADM - Today at 8:17 PM
twilite ver did not change from 085 to 090
MrSaminus - Today at 8:17 PM
i got 1826
SlackerNet>XI<ADM - Today at 8:17 PM
dam
MrSaminus - Today at 8:18 PM
so i dont realy know what to do 
SlackerNet>XI<ADM - Today at 8:19 PM
well lets try to isolate it. make a new world with serv prop set to large biomes...maybe bop is corrupt ? i have a copy of it if you want to try it..bop 1826
cant add files on here have to do it in dm
MrSaminus - Today at 8:21 PM
i tryed to make a new world. but the same conflict came.. but yes both twilight and bop can be corrupt..
SlackerNet>XI<ADM - Today at 8:52 PM
we couldnt figure out the biome id error Mr Saminus is having if anyone has another idea it would be appreciated....replaced bop and twilite mod files, also changed the biome id from 7 to 8 in the config ..no luck at all
MrSaminus - Today at 8:55 PM
did not get the error in SP so i also tryed to copy the config from there.. no luck... almost like a bug thinkin its a error but no logs... players going to twiligt gets the game closed

**Comment by xJon** [comment]
Do you have any additional mods?

**Comment by mrsaminus** [comment]
no... only changes from the original pack is that i disabled "taint" and "redwood"

**Comment by xJon** [comment]
Doesn't make any sense, as it doesn't appear in normal builds of the modpack.
What version of the modpack are you playing with?

**Comment by mrsaminus** [comment]
i use the 0.8.5 since i cant get the 0.9.0 to start on my launcher

**Comment by mrsaminus** [comment]
and it's a clean "out of the box" install. only that i have enabled volcanoes like i was told how, and disabled taint + redwood

**Comment by xJon** [comment]
When did this message appear in your chat?

**Comment by mrsaminus** [comment]
when i enter the server. and the game crashes when players try to go in to twilight

**Comment by xJon** [comment]
What server? maybe the server and your client modpack version are different.

**Comment by mrsaminus** [comment]
i use a install pack from my host omgserv.com

**Comment by xJon** [comment]
Do you know what version of The 1.7.10 Pack they are using and if it is the same as your client's?

**Comment by mrsaminus** [comment]
yes its the : 0.8.5 (MC 1.7.10)

**Comment by xJon** [comment]
Can you connect to other v0.8.5 public servers?

**Comment by mrsaminus** [comment]
i can try :)

**Comment by mrsaminus** [comment]
sorry for late reply.. yes i can accsess other servers with no errors

**Comment by xJon** [comment]
So the problem is with the server. Ask them to fix it or simply reinstall it without deleting your world.
