### ISSUE TITLE
Renderer turns dark

### ISSUE THREAD

**Issue by freemanovec** [xJon/The-1.7.10-Pack#1182]
After a while of playing the screen just turns black. The game still runs, audio works, but nothing is displayed. As if there was an overlay.
[fml-client-lates.log](http://paste.ubuntu.com/18631639/) - FYI, I shutted the game down at line 38063

**Comment by freemanovec** [comment]
Seems to be an error on my side, it just happened again in my dev MC.

**Comment by xJon** [comment]
:+1:
