### ISSUE TITLE
IOException: An existing connection was forcibly closed by the remote host 

### ISSUE THREAD

**Issue by petruciorex** [xJon/The-1.7.10-Pack#1183]
this issue is happening when i'm trying to play in one of my friends server
i don't know why is happening,but i have checked the java,hamachi,firewall and the google and nothing about some fix to this error.

**Comment by mandm635** [comment]
Make sure that you are using the same modpack version as the server.

**Comment by petruciorex** [comment]
yes,i'm using =P

**Comment by mandm635** [comment]
Can other players connect to the server? Also are you using a legit minecraft account?

**Comment by petruciorex** [comment]
yes,i'm using ''premium'' account and other people can enter in the server

**Comment by petruciorex** [comment]
I got into the server 2 times before this error hapen

**Comment by petruciorex** [comment]
here a list what i have tryed until now
-isin't the network provider(i have called then 3 times)
-i have checked hamachi and tryed others programs like tunngle and the same error happen
-i have checked firewall permisions/indoors outdoors rules for the hamachi and java and nothing
-i searched the entire google and haven't find nothing 
-i can't join my friend(who is hosting) and him can't join me if i'm hosting the server
-i have already tryed to open the modem doors and nothing happened again

i hope some of this clues help you,if you haven't understand something just tell me over here

**Comment by mandm635** [comment]
Try connecting without hamatchi running. You shouldnt need it unless ypu are hosting

**Comment by petruciorex** [comment]
i have tryed,but it fail

**Comment by mandm635** [comment]
Why are you using Hamatchi?

**Comment by xJon** [comment]
Please read [this](https://github.com/xJon/The-1.7.10-Pack/blob/master/README.md).

**Comment by petruciorex** [comment]
ok,i'm going to try one more time without the hammachi and post every information what i can

**Comment by petruciorex** [comment]
ok here is what the server:
[19:23:05] [Server thread/INFO]: petruciorex lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Foi forþado o cancelamento de uma conexÒo existente pelo host remoto], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[19:23:05] [Server thread/INFO]: petruciorex left the game
[19:23:18] [User Authenticator #7/INFO]: UUID of player petruciorex is 58754efd-dc4c-4679-800a-6b9a4e5d4576

and here is my internal server

Connecting to *********** [B#347]  [19:32:59] [Netty Client IO #2/INFO] [LiteLoader]: Baking listener list for PostLoginListener with 0 listeners
[B#347]  [19:32:59] [Netty Client IO #2/INFO] [FML]: Server protocol version 2
[B#347]  [19:33:01] [Netty Client IO #2/INFO] [FML]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S00PacketKeepAlive
[B#347]  [19:33:03] [Netty Client IO #2/INFO] [FML]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S00PacketKeepAlive
[B#347]  [19:33:05] [Netty Client IO #2/INFO] [FML]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S00PacketKeepAlive
[B#347]  [19:33:07] [Netty Client IO #2/INFO] [FML]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S00PacketKeepAlive
[B#347]  [19:33:09] [Netty Client IO #2/INFO] [FML]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S00PacketKeepAlive
[B#347]  [19:33:11] [Netty Client IO #2/INFO] [FML]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S00PacketKeepAlive
[B#347]  [19:33:13] [Netty Client IO #2/INFO] [FML]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S00PacketKeepAlive
[B#347]  [19:33:15] [Netty Client IO #2/INFO] [FML]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S00PacketKeepAlive
[B#347]  [19:33:17] [Netty Client IO #2/INFO] [FML]: Unexpected packet during modded negotiation - assuming vanilla or keepalives : net.minecraft.network.play.server.S00PacketKeepAlive
[B#347]  [19:33:18] [Netty Client IO #2/ERROR] [FML]: NetworkDispatcher exception
[B#347]  java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
[B#347]  	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_91]
[B#347]  	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_91]
[B#347]  	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_91]
[B#347]  	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_91]
[B#347]  	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_91]
[B#347]  	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
[B#347]  	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
[B#347]  	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
[B#347]  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
[B#347]  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
[B#347]  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
[B#347]  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
[B#347]  	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
[B#347]  	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[B#347]  [19:33:18] [Netty Client IO #2/INFO] [EnderCore]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[B#347]  [19:33:18] [Netty Client IO #2/INFO] [MineMenu]: CLIENT: Disconnected from server, enabling all click actions
[B#347]  [19:33:18] [Netty Client IO #2/INFO] [EnderCore]: Reset configs to client values for tterrag.wailaplugins.config.WPConfigHandler
[B#347]  [19:33:18] [Netty Client IO #2/INFO] [simplyjetpacks]: Loading config

thats all i can give(i think)

**Comment by petruciorex** [comment]
and here is my internal server
http://pastebin.com/iD8YdtFL

**Comment by xJon** [comment]
This is not the `fml-server-latest.log` file. Also use the Ubuntu paste-tool that supports large files because it is.

**Comment by petruciorex** [comment]
so how can i help you to help me?
what should i post here exatly?

**Comment by xJon** [comment]
I just said. This file is located in the `logs` folder.

**Comment by petruciorex** [comment]
lastest logs for some reason it crashes when i put in the Unbunt

**Comment by petruciorex** [comment]
file:///C:/Users/petrucio/Desktop/fml-server-latest.log

**Comment by Curunir** [comment]
There is still a chance that the server owner modified the pack and didn't share that modification with you, even a small config file change can cause errors.
Apart from that, you might ask an admin to reset your player data. If your location or some item on you was the problem, this should allow you to log in again. However, you will lose your inventory and start at the world spawn point.

**Comment by petruciorex** [comment]
i already have tryed this,and the same problem persists

**Comment by TANGOjPANDA** [comment]
I suggest you make sure a vanilla server works first, to rule out any other problems you might be having and whether it is this modpack which is causing the problem

**Comment by petruciorex** [comment]
TANGOjPANDA i allready tryed make an vanilla server,and it worked withou't problens

**Comment by TANGOjPANDA** [comment]
the next logical step would be to find the point at which it stops working, so is there a modpack which you are able to host a server and join (preferably in the 1.7.10 instance of minecraft)
have you been able to join one of your friends servers before it might be there side which isnt working. 
I doubt the problem is to do with the modpack

**Comment by petruciorex** [comment]
i had joined the server 2 times before the error start,and if i host the server nobody can join my server for some reason

**Comment by xJon** [comment]
Closed due to inactivity, will reopen if requested.
