### ISSUE TITLE
Black Crash Screen on launch - Please Help

### ISSUE THREAD

**Issue by AndrewOps** [xJon/The-1.7.10-Pack#1184]
I have version 0.9.0 but have tried 0.8.5
It loads fine until the actual minecraft screen comes up.
This happens with all modpacks I have installed.
This is the log: http://paste.ubuntu.com/18938094/

**Comment by AndrewOps** [comment]
Update: I have got my others packs to work but still not This one.

**Comment by xJon** [comment]
I see no issue at all in the log. Just normal loading. If you see a black screen, it doesn't mean the pack crashed.
