### ISSUE TITLE
crash while initializing

### ISSUE THREAD

**Issue by alonehunter** [xJon/The-1.7.10-Pack#1188]
http://paste.ubuntu.com/19163571/ here is my log. when i start game a few minutes later it returns me to technic launcher.

**Comment by xJon** [comment]
Did you try to do a clean install?

**Comment by alonehunter** [comment]
yes i did

**Comment by alonehunter** [comment]
i install java again and now its working thanks

**Comment by xJon** [comment]
:+1:
