### ISSUE TITLE
Doesn't start, goes back to launcher

### ISSUE THREAD

**Issue by BadassWalrus2** [xJon/The-1.7.10-Pack#1189]
When i launch the modpack it will hide the launcher then after about 10-20 seconds it will just go back to the launcher.
 Notes:
Happens with other modpacks
3.5 GBs of ram
Java 8 64bit

Thanks for anyhelp

**EDIT: It was a problem with java, i needed java 7 but only had java 8**

**Comment by xJon** [comment]
Okay?
