### ISSUE TITLE
Adding Immersive Engineering(If possible)

### ISSUE THREAD

**Issue by Gravewalker** [xJon/The-1.7.10-Pack#1190]
This mod is just really amazing and it has a ton of potential, it will work with other mods that are already on the 1.7.10 pack.  The level of technicality and dedication is outstanding on this mod and I think it would really benefit the pack if you were to add it.  If this is at all possible that would be amazing.  Thank you!

http://minecraft.curseforge.com/projects/immersive-engineering

**Comment by mandm635** [comment]
#1135
