### ISSUE TITLE
Fatal Exception in singleplayer mode

### ISSUE THREAD

**Issue by MrSpacey** [xJon/The-1.7.10-Pack#1191]
Every time i try to load a world in singleplayer i get this error:

Connection Lost: A fatal exception has ocurred, this connection is terminated, when i click "Back to title screen" it shows me the multiplayer tab, which is exactly what i do not want since i want to play singleplayer.

So is this a bug or does the mod only works in MP?

**Comment by mandm635** [comment]
Have you changed anything in the pack? Also, it is a mc bug that takes you to the multiplayer tab. The pack is 100% SP and MP compatable.

**Comment by MrSpacey** [comment]
Nope, i downloaded the modpack and then launched it, nothing more

**Comment by mandm635** [comment]
PC specs? Also you could try redownloading the pack

**Comment by MrSpacey** [comment]
Dell Inspiron I14-3442 A40

Intel I5-4210 @1.70GHz (4CPUs)
GeForce 820M
8GB RAM (4 used by the modpack)
Windows 10 Pro 64bit

**Comment by mandm635** [comment]
Have you tried other large packs and gotten good fps?

**Comment by Mates420** [comment]
Hi i had same problem. You have to turn off internet connection before entering your world. Worked for me.

**Comment by Curunir** [comment]
Nobody can diagnose your problem with just the information you gave. Please share crash logs if you can find any. Also make sure you have installed the pack in a location that has diskspace left, assigned at least 3GiB of RAM in the launcher and installed [the latest Java](https://www.java.com/en/download/manual.jsp).

**Comment by xJon** [comment]
Closed due to inactivity.
