### ISSUE TITLE
Server crashes when entering mystcraft dimensions

### ISSUE THREAD

**Issue by PeggleFrank** [xJon/The-1.7.10-Pack#1193]
At first, the server was fine, but now that we've made about a dozen mystcraft dimensions, the server crashes whenever we try to enter or create one. I run the server locally, and it's usually just me and two other friends.

This is what I saw last time.

[22:00:55] [Server thread/INFO] [FML]: Loading dimension 16 (world) (net.minecra
ft.server.dedicated.DedicatedServer@6c4b7cad)

This, however, pops up every time the server crashes. I don't know what it means.

[22:00:55] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]
: [Flan's Mod] Tried to add m4Carbine to player class gignAssault1 but the item
did not exist
[22:00:55] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]
: [Flan's Mod] Tried to add mp5k to player class gignDualWield1 but the item did
 not exist
[22:00:56] [Server thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:549]
: [Flan's Mod] Tried to add mp5k+flanMWSilencer to player class gignSniper2 but
the item did not exist

There's nothing else in the logs; it always ends with Flans. The server still shows as online in the server browser, but it's impossible to join, and the console is unresponsive to any commands I put in. 

This doesn't happen with any other dimensions. We've resorted to the deep dark for a quarry dimension, and the last millenium for a void dimension. I'd like to figure out why this keeps happening, because we'd love to mess around with Mystcraft ages more.

EDIT: I'm using version 0.9.1.

**Comment by xJon** [comment]
Can you post the full crash logs using pastebin.com?

**Comment by xJon** [comment]
Closed due to missing information.
