### ISSUE TITLE
[0.9.1] Error while opening

### ISSUE THREAD

**Issue by us0110** [xJon/The-1.7.10-Pack#1194]
This is my latest log I don't know if it's the correct one, but it is what I found.
http://paste.ubuntu.com/20575314/
This is the latest report I found.
    C:\Users\Davis\AppData\Roaming\.technic\modpacks\the-1710-pack\reports\2016-07-22_20.12.20.zip: The archive is corrupt

 I use 4gb of ram on the launcher and at the time I was using version 0.9.1 This problem only started when I tried to run the version the second time, the first time when I updated the version the game opened normaly, but now I can't launch it with any version of the mod.
I don't use optifine.
EDIT; I tried to reinstall the pack, but when I pressed install it started to install it and the all of a sudden just stopped.
EDITv2: Deleted the pack and tried installing, doesn't work either.

**Comment by xJon** [comment]
I need the `fml-client-latest.log` file.

**Comment by us0110** [comment]
That would be a problem, because when I deleted the pack it deleted the logs, and now I can't even install it again. Maybe the tehnic launcher log helps: http://paste.ubuntu.com/20646308/
