### ISSUE TITLE
TE Energy Cells / computer craft 

### ISSUE THREAD

**Issue by swiftkickku** [xJon/The-1.7.10-Pack#1196]
I seem to be having problems connecting my Thermal Expansion energy cells to computer craft pastebin processes. They physically connect when activating the wired modem but don't seem to register when i try to access via computer. I'm not sure if this is a problem other people have had at all. it seems though as if they don't recognize each other at all.

**Comment by xJon** [comment]
Does that still happen?

**Comment by xJon** [comment]
Closed due to inactivity.
