### ISSUE TITLE
Electrotine Ore does not spawn in the world.

### ISSUE THREAD

**Issue by tdp4** [xJon/The-1.7.10-Pack#1197]
Electrotine as far as I can tell should be as common as diamond.  It is part of ProjectRed and used for advanced machines.  Other ores with this ID do spawn.  It also doesn't seem to show up with the Laser Drill from MineFactory Reloaded.

ItemID 2932:6

**Comment by tdp4** [comment]
FML log fml-server-latest.log:

[19:57:05] [Server thread/DEBUG] [FML/]: Fixed block id mismatch ProjRed|Exploration:projectred.exploration.ore: 2984 (init) -> 2932 (map).

**Comment by xJon** [comment]
https://github.com/xJon/The-1.7.10-Pack/issues/956#issuecomment-166724560

**Comment by tdp4** [comment]
Thanks xJon.  Would it make sense to (or possible to) turn off/hide the items related to electrotine then?

**Comment by xJon** [comment]
Unfortunately that's not an option in the ProjectRed config.
