### ISSUE TITLE
MrCrayFish Wooden coffee table recipe produces fences.

### ISSUE THREAD

**Issue by tdp4** [xJon/The-1.7.10-Pack#1198]
Attempted to craft a wooden coffee table with oak planks but another mod has used that recipe to generate a variation on fences.  I'll try to get more information tonight.

I did check the stone coffee tables and they craft as expected.

**Comment by xJon** [comment]
Nothing we can currently do right now except recommending you to use the recipe switch key. You can find it in the controls menu and switch between conflicting recipes in the crafting table.
