### ISSUE TITLE
[0.9.1] Crashed when I tried to enter my world

### ISSUE THREAD

**Issue by us0110** [xJon/The-1.7.10-Pack#1200]
The crash report - http://paste.ubuntu.com/21738661/
I just started up the mod everything went smoothly and the when I started loading up my single-player world the game just crashed.

**Comment by Curunir** [comment]
I cannot help with the actual problem, but you are running a severely outdated Java version. This exposes your machine to attacks and may also cause game issues, so I recommend you get the [latest runtime](https://www.java.com/en/download/manual.jsp).

**Comment by xJon** [comment]
Do what Curunir suggested, and then report the crash [there](https://github.com/BuildCraft/BuildCraft/issues). As for your world, delete the ticking entity using [NBTExplorer](https://www.youtube.com/watch?v=fWUUsdp3pJ8).
