### ISSUE TITLE
Cruise launcher broken

### ISSUE THREAD

**Issue by Powerpin** [xJon/The-1.7.10-Pack#1203]
We can't craft the cruise launcher due of a missing items. In NEI, the up left corner show up a "error.name 1830.8" invisible item that cant be found or crafted.

1.7.10 v0.9.1

**Comment by xJon** [comment]
Can you report that [there](https://github.com/aidancbrady/DefenseTech/issues)?

**Comment by xJon** [comment]
Let's hope this issue won't occur again in v0.9.2.

**Comment by acujl** [comment]
I still can't.. Using the latest server

**Comment by xJon** [comment]
@acujl Unfortunately this is no longer supported.
