### ISSUE TITLE
UK server crashing

### ISSUE THREAD

**Issue by RogueRedMage** [xJon/The-1.7.10-Pack#1204]
My friend and I are unable to join the UK server. We don't know why because it was working 2 days ago but now we can't log on without crashing. We think it might be something to do with our base but we don't know what specifically causes it.

Usernames:
Kinas10
RogueRedMage

**Comment by RogueRedMage** [comment]
http://pastebin.com/phTWnG1k

**Comment by xJon** [comment]
That's not the crash log.

**Comment by RogueRedMage** [comment]
How do I find which one is the right one?

**Comment by RogueRedMage** [comment]
http://pastebin.com/zr03zejY I think this is it

**Comment by xJon** [comment]
The server owners are looking into that.

**Comment by RogueRedMage** [comment]
k thanks
