### ISSUE TITLE
Antimatter Explosive is Uncraftable

### ISSUE THREAD

**Issue by Altonite** [xJon/The-1.7.10-Pack#1208]
I have a private server running the 1710 Pack and I thought it would be a great idea to make an antimatter explosive. I looked up the recipe in NEI and I saw that it required fire. There is no way to create the item version of fire according to NEI so how can I fix this problem? Thanks for helping and let me know if anybody else has this problem.

**Comment by xJon** [comment]
It's disabled by default, as well as the Red Matter explosive.

**Comment by Altonite** [comment]
How do I turn them on?

**Comment by xJon** [comment]
In the config file.

**Comment by Altonite** [comment]
I turned antimatter and red matter explosives on in the file but it still requires fire to craft.
