### ISSUE TITLE
[Suggestion] 4 mods

### ISSUE THREAD

**Issue by Anhilyx** [xJon/The-1.7.10-Pack#1210]
Hello everybody
I think The 1.7.10 Pack is a very complete modpack, but i think some parts of the modpack can be increased, so i porpose to add 4 mods : 
- Better Dungeons for the exploration : https://mods.curse.com/mc-mods/minecraft/better-dungeons
- W. T. F. 's Expedition for the underground exploration : https://mods.curse.com/mc-mods/minecraft/227931-wtfs-expedition-cavebiomes-ores-trees-and-tweaks
- Draconic Evolution for high level technology and magic : https://mods.curse.com/mc-mods/minecraft/223565-draconic-evolution
- Soul Shards (with a more important amount of killed mods to level up (customisable in the .cfg file)) for automatic mob spawn (Draconic Evolution can replace this mod) : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445947-1-7-10-soul-shards-reborn-original-soul-shards
Previously, I also post an other suggestion on the forum, but not here : https://forums.enderplay.com/threads/a-mod-who-can-be-added.110/ . It's for the mod More Enchantements. Warning, if you add it, it's better to disable the enchantement heat in the config file, because i find a bug with this enchantement : it's possible to loot different things like iron when mining netherrhack or shiny metal when mining some nether ores (I don't remember it).
I hope you ad  these mods to the modpack.

**Comment by xJon** [comment]
Currently the mods won't be added, as the modpack doesn't really need even more content.
Better Dungeons is a lot of fun but it's not stable enough to be put into the modpack.
Thanks anyway!
