### ISSUE TITLE
Blood Magic Issues

### ISSUE THREAD

**Issue by itsleems** [xJon/The-1.7.10-Pack#1211]
So when i use the Blood Magic Mod, when i try and upgrade my blood altar, it will say that the altar is upgraded but the capacity of the altar doesnt go up at all. I've tried re-downloading both the pack and the technic launcher but nothing seems to work.

**Comment by xJon** [comment]
Does that still happen?

**Comment by itsleems** [comment]
Yeah, I have no clue why it happens

**Comment by AntonioToni** [comment]
do you use runes of capacity?
that upgrades the capacity

**Comment by xJon** [comment]
:arrow_up: ?

**Comment by itsleems** [comment]
No but I'd like to be able to use other runes since regardless of what their it is I only have 10000 blood cap

**Comment by xJon** [comment]
"It's not an issue; It's a feature"
