### ISSUE TITLE
Question/Suggestion

### ISSUE THREAD

**Issue by Kronix420** [xJon/The-1.7.10-Pack#1213]
Any reason why we aren't using [**_NoMoreRecipeConflict-0.3(1.7.10).jar_**](http://mods.curse.com/mc-mods/minecraft/238123-stimmedcow-nomorerecipeconflict) *(currently using 0.2)*? Is there a compatibility issue or something changed in the latest version that's problematic in some way?

Has [**_Multimine_**](http://atomicstryker.net/multimine.php) been considered recently? Very interesting mod IMO.

Im a big fan of [**_BetterFoliage_**](https://minecraft.curseforge.com/projects/better-foliage) and would love to see it added (which would also be very easy due tio the modpack section of the OP linked).

Is [**_ExtraTiC_**](https://mods.curse.com/mc-mods/minecraft/extratic) Not needed? Looks like it adds a ton of cross compatibility. and I always add it to my personal modpacks.

Are there any special configs, or other reasons why I would have a problem with switching [**_advanced machines AS_**](http://forum.industrial-craft.net/index.php?page=Thread&threadID=4907) -- for [**_advancedMachines-59.0.2_**](http://forum.industrial-craft.net/index.php?page=Thread&threadID=9335)?
Furthermore, I'd like to see this change become official if others agree.

This quote from the author's (Immibis) signature on the IC2 forums sums up my reasoning quite well (even though honestly; the IC2 forum thread hasn't been replied to in some time, but that just goes to show you that the code is final, and has no issues from my personal experience with it since the last iteration:
 >Disappointed with the bugs and nerfedness of AtomicStryker Corp's Advanced Machines, and the unupdatedness of Snyke's Enterprises?
>Need low-lag renewable power?
>Come to [advanced machines] for free UUM!
>
>*Note: UUM may stand for Unnerfed Unbuggy Updated Machines and may not be actual UUM. The extra U was lost due to a bit error. Battery snot included.*

In my personal experience it adds more functionality, and is just overall a better made mod, and I have tried both, separately of course; extensively.

**Comment by Kronix420** [comment]
Forgot to mention [**_Millenaire_**](http://millenaire.org/) -- one of my favorites.

**Comment by xJon** [comment]
* Wireless Redstone will update, thanks for noticing.
* We use version 0.2 because version 0.3 seemed to have a problem with the config option to disable GUI recipe switch button.
* The version of Advanced Machines that we used never had any reported bugs, and I didn't encounter any myself, so I see no reason to do a switch and delete old blocks from peoples' worlds.
* Industrial Engineering is a modpack, not a mod
* The other mod suggestions are rather interesting, but they won't be added. The modpack really doesn't need more content and it's sort-of complete as is. And instead of using NEK, I'd suggest using MineMenu (press `R`).

**Comment by Kronix420** [comment]
which config file has the issue?

Advanced machines as has less functionality IMO. not about bugs

facepalm on industrial engineering.

Im having a bit of trouble making the switch to minemenu.. just not used to it. Ill keep trying until it gets more natural.

---

All-in-all, I appreciate the response and respect all your decisions. Thanks for your consideration, and keep up the great work. Its the only modpack I use.
