### ISSUE TITLE
Cape and Donation

### ISSUE THREAD

**Issue by joelou1** [xJon/The-1.7.10-Pack#1214]
I would love to donate and recieve a Cape for doing so. My question is, is the cape custom and will it require an update of the modpack each time a new player donates? Or does it uses an API that locates a database and every donators gets the same Cape?

It won't affect my choice to donate, but I'm curious.\

EDIT: What does Jon's Exclusives exactly do?

**Comment by xJon** [comment]
* > it uses an API that locates a database and every donators gets the same Cape

* [Jon's Exclusives features](https://github.com/xJon/Jons-Exclusives#features)

It requires just relaunch of the modpack to refresh the API. Doing it in any other way would be stupid :)

**Comment by joelou1** [comment]
So let's say I have a brand new cape in a .json version and add it to the server, no user from my server would see it unless they have the said .json. If it's what I understood?

**Comment by xJon** [comment]
No, not at all!
* The capes are actually client sided totally, the mod is installed server-side too just for the login chat messages
* Client side, the mod has a .json file set in the config that is connected to the remote mod configs, that are connected to the cape API. You can see the links loading in the modpack's log, too. *Everything is automatic, you don't need to change anything, everybody that have the modpack with v0.9.3 will be able to see the cape*

**Comment by joelou1** [comment]
This makes sens. So in order to have players on my server to have custom Cape(And all players to see them), they'll have to download them manually. Ok. good. Thanks. I'll be suporting soon. I need to make supper first.

**Comment by xJon** [comment]
> they'll have to download them manually

What do you mean?

**Comment by joelou1** [comment]
Well, EG: I have a custom creeper cape. In order for my friends to see it, they'll have to download and put in the config or whatever the capes are in, in order for them to see it on me, right?

**Comment by xJon** [comment]
Indeed. I think you figured out how the mod works for the modpack (correct me if I'm wrong).
If you want to consult about your private use of the mod, please open a new issue in the mod's repository.

**Comment by joelou1** [comment]
Thank you. Case close.
