### ISSUE TITLE
Nuclear Reactors

### ISSUE THREAD

**Issue by MustardseedLol** [xJon/The-1.7.10-Pack#1217]
So I'm having an issue with nuclear reactors.  There's no problem at all in single player, but when I use them on a server there's an issue with EU output.  I have my reactor setup in a fashion that produces 360EU/t.  In single player, it does just that.  Using an EU-Reader shows that the MFSU is indeed receiving 360EU/t via Insulated HV cables.  However, using the exact same setup on a server I play on, I am only receiving 1/100 of the EU.  The nuclear reactor shows it's producing 360EU/t, but the MFSU is only gaining 3.6EU/t.  I tried messing around with the dual uranium fuel rods I was using by bringing down the EU output to 200EU/t, but resulted in the MFSU only gaining 2EU/t, a hundredth of what it should be gaining.  I'm not sure if I'm the only having this issue, but it'd be great if it could be fixed after I went through a lot of time to get to this point only to find disappointment.

**Comment by xJon** [comment]
Think it's a mod-bug? We're using the latest version of IndustrialCraft 2. If you're using v0.9.3 of the modpack, this should be reported directly to IC2's dev.

**Comment by xJon** [comment]
Closed due to inactivity.
