### ISSUE TITLE
World loads as empty without blocks and keep disconnect players

### ISSUE THREAD

**Issue by aradansk** [xJon/The-1.7.10-Pack#1219]
Hallo, I have problem with my world I had for few of my friends. Today I was last who disconnected from server about at 4:30pm and now I want to connect and my world looks like it was without blocks at all. I see my waypoints and my coordinate looks like where I was before exiting the game. All users see their inventory, but we looks like we are flying somewhere (nothing around us). Last thing I was doing in game was crafting enderIO dark steel armors and weapons. All users are also disconnected by server with "Timeout" after 30-60sec.

Unfortunatelly, we have this server maybe one month and we do not want to loose everything we build. I had backup only from AromaBackup so I have backup from 4:00pm and 4:30pm.

please, help

thanks a lot
AradanSK

**Comment by mandm635** [comment]
Sounds like the server is running out of memory, do you have access to the console/logs?

**Comment by aradansk** [comment]
Yes, I have, server is running computer in my house, its dedicated only for that, its 8gb ram intel i5 computer. Its possible to put some command in console to generate logs needed for diagnostic?

**Comment by mandm635** [comment]
If the pc is running Windows, the logs are available in the folder called logs, where you run the server from. I should only need the latest log. If it is not windows, some googling should help. I do not believe 8gb is enough to run the server. I have to launch my client of the modpack with 6gb, and not only is a server in general more taxing, but connecting multiple players can be an issue. 

How much ram are you launching the server with? And what framerate do your friends normally get?

**Comment by thefiz** [comment]
This was an issue with the Technic launcher being DDoSed.. It happened to all servers running the pack at the same time.  It should be resolved now

**Comment by xJon** [comment]
Is it fixed, @aradansk?

**Comment by aradansk** [comment]
Hallo, I am sorry not answereed, I was busy. Yes, its working now, so problem was really as someone stated about DDoSed servers. Thank you for help to all. Good luck

**Comment by xJon** [comment]
:+1:
