### ISSUE TITLE
Unable to craft Unstable Ingots

### ISSUE THREAD

**Issue by thefiz** [xJon/The-1.7.10-Pack#1220]
When using a vanilla crafting table, you are unable to craft an Unstable Ingot.  The recipe shows that it should work, you click the item to take it out of the table, and it pops right back in after a very short delay. 

No errors show on the log at all, it just doesn't craft.

On someone's suggestion, I also tried an assembly halo with the same result.

**Comment by xJon** [comment]
This isn't a problem in v0.9.4.
