### ISSUE TITLE
Java error when joining a server's Lobby.

### ISSUE THREAD

**Issue by joelou1** [xJon/The-1.7.10-Pack#1221]
You may or may not be able to fix this, but here goes nothing.
I've been trying to go to a network's lobby, which is Vanilla-like. It would work with ANY modpack as it only uses Vanilla blocks for 1.7.10. (Tested with Tekkit, Sky Factory, FTB Infinity)

Trying to log in in this specific server causes this Java.lang error:
- Internal Exception: java.lang.RuntimeException: No OpenGL context found in the current thread.

I've been joining the Recommended server to test if it wasn't a problem related to the modpack itself, but it worked just fine.
I've also hosted my own Vanilla server, works like a charm.

I only assume 2 things. Either the modpacks is faulty, either the FML on the server I try to join is incompatible.

What do you think? Related or not?

EDIT: Here's what I could salvage from FML...
http://pastebin.com/5UJbME60

I wonder...
http://prnt.sc/cg15ct
http://prnt.sc/cg159e

Then I supose it might just be FML being a sissy?...

**Comment by Curunir** [comment]
Many mods do strange things with Minecraft, and modpacks tend to pile up a lot of strangeness. You might try removing mods from the pack one by one until it works, to find out which particular mod is preventing your intended usage. Then you could try going just without that one, and maybe ask the mod author why this is happening.
Or you might just ask the guys who run that "lobby". As it stands, I don't see the point of connecting to something like that with wildly different modpacks and even different Forge versions. You won't be able to play together, and all the things the clients think they can do will be overridden by the more limited server (in case of vanilla, very limited).

**Comment by xJon** [comment]
> Or you might just ask the guys who run that "lobby". As it stands, I don't see the point of connecting to something like that with wildly different modpacks and even different Forge versions. You won't be able to play together, and all the things the clients think they can do will be overridden by the more limited server (in case of vanilla, very limited).
