### ISSUE TITLE
Add compacter mod

### ISSUE THREAD

**Issue by deframet** [xJon/The-1.7.10-Pack#1222]
I'd like you to add compacter to 1.7.10 pack.
This mod adds one block (the compacter) that crafts input items in a grid of 2x2 or 3x3 (even recursively!!) and crafts unlimited items per tick, yet is a lot less laggy than cyclic and other couterparts. 
It would be great for servers. You can view its source code [here](https://github.com/bdew/compacter).

**Comment by deframet** [comment]
Yay :)

**Comment by xJon** [comment]
:+1: 
We're planning to release v0.9.4 when [Jon's Exclusives](https://github.com/xJon/Jons-Exclusives) gets its patch from @clienthax.
