### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by thefiz** [xJon/The-1.7.10-Pack#1223]
I'm getting a crash report on a server, and this is the error report..  The section I am looking at is on the end...

`The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from Flans Mod-1.7.10-4.10.0.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may have caused the error. `

[crash-2016-09-13_04.00.05-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/473507/crash-2016-09-13_04.00.05-server.txt)

**Comment by mandm635** [comment]
When does the crash occur? And I don't believe that end part is causing it, although that might be a bug.

**Comment by thefiz** [comment]
That's what I'm trying to pin down, as my users are reporting instability, but I'm not seeing the root cause..

**Comment by mandm635** [comment]
Could you post the latest log?

**Comment by xJon** [comment]
`forgeessentials` is crashing you.
