### ISSUE TITLE
Sphax Textute Link 

### ISSUE THREAD

**Issue by Ruln** [xJon/The-1.7.10-Pack#1224]
Hi,

The links on the technic site that link you to the sphax texture packs. Then all the different options such as x128 x64 etc are all broken links.

Do you have any live links I can get the textures

**Comment by xJon** [comment]
Novamanga's patches, which are the updated ones, work for me.

**Comment by Ruln** [comment]
http://download936.mediafire.com/7ticpd5dqhsg/8o2r3fkcx14lthn/Sphax+The+1.7.10+Pack+64x.zip

This download link for it doesn't work though. When I download I'm told it's 0KB

**Comment by mandm635** [comment]
First go here: [bit.ly/The-1-7-10-Pack-Sphax](bit.ly/The-1-7-10-Pack-Sphax), then, scroll down and click the 1.7.10 Show Spoiler button. Under v8.4+ by Novamanga, click either the 64x or 32x, based on what your computer can take. After clicking one of those, the download should begin automatically.

**Comment by Ruln** [comment]
Although your link didn't work, I've been on that page and it takes me to the media fire page where it just doesn't load. I can download other mediafire zips just not this one

**Comment by mandm635** [comment]
Wierd, it should be working. Am I allowed to put it on a private dropbox link and pm it to you?

**Comment by xJon** [comment]
Here is a direct link to the download of the latest x64 patch: http://www.mediafire.com/download/8o2r3fkcx14lthn/Sphax_The_1.7.10_Pack_64x.zip
