### ISSUE TITLE
AromaBackup Crashes client

### ISSUE THREAD

**Issue by NastyCanasta** [xJon/The-1.7.10-Pack#1225]
AromaBackup has a 50/50 chance to crash my client every time the game is saved. This chance goes up the longer my session is. It's a "clean" crash, so nothing is lost, and the client simply shuts down, but it is an annoyance. I do want to keep my world backed up, but my game abruptly shutting down can be irritating.  Is there anything I can do?

**Comment by NastyCanasta** [comment]
P.S: If I'm hosting an LAN, it closes my client and shuts down the server. It doesn't crash the other computer, it just disconnects them.

**Comment by mandm635** [comment]
Please provide your client logs.

**Comment by NastyCanasta** [comment]
[crash-2016-09-18_08.28.50-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/479107/crash-2016-09-18_08.28.50-server.txt)

**Comment by xJon** [comment]
You may want to try to report this bug [here](https://github.com/micdoodle8/Galacticraft/issues).

**Comment by NastyCanasta** [comment]
I don't think the Bug is related to Galacticraft.

**Comment by NastyCanasta** [comment]
Or did you see something related to the mod that is past my coding skills? (which happen to be nil)

**Comment by xJon** [comment]
In the crash-report.

**Comment by xJon** [comment]
Does that still happen?

**Comment by NastyCanasta** [comment]
It does. Unfortunately, my post was never responded to on the forum you told me

**Comment by xJon** [comment]
That's unfortunate that currently there's no support for the Galacticraft mod, but there's nothing we can do. You can consider also trying to contact the author of AromaBackup.

**Comment by NastyCanasta** [comment]
Alright, thanks for your attention anyway!

**Comment by NastyCanasta** [comment]
IMPORTANT NOTE: I've done some messing around, and discovered that the crash chance goes up to almost certain if you are inactive for long periods of time. Say, 10 minutes. This also includes being at the in-game menu, in your inventory, and writing a book or sign. The problem persists even when the game is paused in single-player

**Comment by oryfoxer7410** [comment]
How are you hosting? If its just backups you need, I would disable Aroma then just use a scheduled task. 

If windows, you can run a quick backup .bat on a schedule and if Linux you can do it from Crontab. If you need help, let me know and I can assist with a backup solutions besides Aroma.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if needed.
