### ISSUE TITLE
Vajra Creation Issues

### ISSUE THREAD

**Issue by MagicBubbles** [xJon/The-1.7.10-Pack#1226]
In singleplayer the creation works fine, but when i try it on our server the items i want to create (Vajra Core and Magnetron) doesnt spawn, it just "rubberbands" back into the crafting table.
Seems the server tries to create Vajra Core 6642:5 while singleplayer tries to make 6641:5, no idea  if thats important tho. Server 0.9.3 version, saw the recipie was disabled and also wondering if that's intended.

Sinc.
/Bubbles

**Comment by xJon** [comment]
In version v0.9.3, the recipe was disabled for what? And in client or server?

**Comment by MagicBubbles** [comment]
Ehm i tried to make it in the server, the items show up and the core is in the result part of the crafting table, but whenever i click it to claim it it rubberbands back into the crafting table. We figured out the recipie was disabled by default and could just change it and see if that works but have to make sure it isnt intended to be disabled. =)

**Comment by xJon** [comment]
Thanks for reporting, this has been fixed for future downloads of the v0.9.3 server package!
