### ISSUE TITLE
Installation of the 1.7.10 Pack on Crystal-Serv.com

### ISSUE THREAD

**Issue by ImTheBadAss** [xJon/The-1.7.10-Pack#1227]
Hi guys, i'm traying to instal the 1.7.10 Pack on Crystal-Serv.com
But the server dosn't work !
I need lot of help lol i don't understand why it doesn't work, i try it again and again ><

I download the server of the-1.7.10-Pack
i decompresse it with winrar
i uplaud it on my server with filezila
i rename the .jar ==> tekkit.jar

and now, when i'm traying to put on my server and play
my server don't want start and we cannot join the server ...

If someone know how to do it with Crystal-Serv.com ... I have skype ou what you need to help me !
Thanks guys to try to help me

**Comment by xJon** [comment]
You need to activate the server using `LaunchServer.bat`.

**Comment by ImTheBadAss** [comment]
Hmm i tryed it look:
![picture issue](https://cloud.githubusercontent.com/assets/22333792/18707889/668ba0bc-7ff8-11e6-95a6-9d2ace5833ce.png)

**Comment by ImTheBadAss** [comment]
Here are the files (when i unzip the mod pack server)
![files](https://cloud.githubusercontent.com/assets/22333792/18707957/b00b0ef8-7ff8-11e6-9cee-5266531b9063.png)

**Comment by xJon** [comment]
What's `Tekkit.rar`?

**Comment by ImTheBadAss** [comment]
Oh, sorry !
Someone told me "change minecraft_server.1.7.10.jar to Tekkit.jar"

So Tekkit.jar it's "minecraft_server.1.7.10.jar"

**Comment by xJon** [comment]
So rename it back.

**Comment by ImTheBadAss** [comment]
it's done

**Comment by xJon** [comment]
You should be able to just upload the server package, but it'd be the best to consult with the server hosting company you're dealing with, because I don't know exactly how their setup works.
