### ISSUE TITLE
Iguana's Tinker's Tweaks

### ISSUE THREAD

**Issue by mario610** [xJon/The-1.7.10-Pack#1230]
I feel like it wold make tinker's contruct easier to make better tools

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2176855-iguanas-tinker-tweaks

**Comment by Excepto** [comment]
I like the suggestion but when i tried to run it with the pack my world didnt't want to load. Except of iguana tweaks i played with ex nihilo. So that might a compatability issue. But if thats get solved im all for it.

**Comment by xJon** [comment]
Not going to happen, thanks anyway for suggesting though!
