### ISSUE TITLE
Still no mods on my server.

### ISSUE THREAD

**Issue by camelCaseText** [xJon/The-1.7.10-Pack#1231]
I don't mean to be a pest, but I added an issue the other day asking about getting the mods to show/run on our server. I ran the LaunchServer.bat, I set the eula.txt to true and everything, but to no avail. We still have the same issues with item IDs and mod blocks not behaving properly. Hopefully we can get it figured out. Thanks!
Link to previous thread: https://github.com/xJon/The-1.7.10-Pack/issues/1229

**Comment by xJon** [comment]
*"How to set up a dedicated server"*, by @Curunir, 2016
> 1. Download the server package version you need here: http://the-1710-pack.com/repo
2. Extract the package to where you want your server to run. This will work side-by-side with a client installation, but unless your PC is a high-end monster, it is much recommended to use another PC for the server, if any is available.
3. Make sure your clients can see the server. If you are all on the same home network (LAN), this should just work. To have it work across the Internet, the server needs to have the port it will listen to (default: 25565) forwarded from the router. This will not (ever) work if your ISP puts you in the baby cage that is carrier-grade NAT, so let's hope yours doesn't.
4. Edit your server.properties file with all the settings you need. Guide is here: http://minecraft.gamepedia.com/Server.properties
5. If you want to import a singleplayer world, locate the worldsave and copy it over to the server directory. You need to set the world name in server.properties to the exact directory name of the worldsave for it to use the existing one. Even if you let it generate a world, the name that you set here will be used, default is just "world".
6. If you need it to work for more than just a couple of friends, give it more RAM. Edit the launch script and change the -Xms (minimum) and -Xmx (maximum) allocation values as needed. For a first try, defaults will be fine.
7. If you were wondering, launch.bat is your launch script on Windows, while launch.sh is the one for Linux/Unix/MacOS. ALWAYS use the script, never manually start the server.jar. If you do, you will start a vanilla (i.e. unmodded) server that will do weird shit.
8. Run the server, don't be intimidated by the millions of errors and give it time. Once it stops generating new lines while not falling back to the command line or closing, it should be up and running. Try connecting with a client, using the IP adress or a DNS-resolved name.

**Comment by camelCaseText** [comment]
So I should just wait out the launch.bat until the server actually launches? I've run the launch.bat to the point where it says "press any key to continue", which just closed it with nothing else happened. I'll try again and see what happens.

**Comment by xJon** [comment]
You'll need to set `eula.txt` to true.

**Comment by camelCaseText** [comment]
Yes yes. I ran the launch.bat, set the eula.txt to true, then I assume I run the launch.bat again? That's how I interpret #7 up there.

**Comment by xJon** [comment]
Yes

**Comment by camelCaseText** [comment]
Alright! It seems to be working correctly. Thank you very much!

**Comment by xJon** [comment]
:+1:
