### ISSUE TITLE
Mod suggestion - Traincraft

### ISSUE THREAD

**Issue by bark46dogdog** [xJon/The-1.7.10-Pack#1234]
Heyo, I really love this pack, been playing it for a while. I was really hoping tho, that traincraft could be added to the pack. [https://minecraft.curseforge.com/projects/traincraft](https://minecraft.curseforge.com/projects/traincraft) Please let me know what you think, thanks! ^^

**Comment by xJon** [comment]
https://github.com/xJon/The-1.7.10-Pack/issues/1232#issuecomment-249837867
