### ISSUE TITLE
Won't Load Game After Crash

### ISSUE THREAD

**Issue by RaspberryC** [xJon/The-1.7.10-Pack#1235]
A couple of days ago, my computer crashed while I was playing. I rebooted and attempted to reload my game. The game shut down and the Technic Launcher opened. I tried again with the same results. Then I tried restarting my computer -- no luck. I use MCBackup 3.7.8.0, so I restored my last backup. Once again, the game shut down when I attempted to load my game. Thinking that perhaps the problem lay with my computer, I transferred copies of the backups to my other computer. (I have done this many times with no problems.) MCBackup wouldn't even recognize them. How could all of my backups have been corrupted? Is there anything I can do? This actually happened to me a few months ago and I just abandoned my game to start a new one. I don't want to do that again!
I was told to post my logs here. I'm not 100% sure what that means, so forgive me if I posted the wrong thing. This sort of stuff makes me feel really computer illiterate.

[fml-client-latest.txt](https://github.com/xJon/The-1.7.10-Pack/files/504774/fml-client-latest.txt)
[latest.txt](https://github.com/xJon/The-1.7.10-Pack/files/504773/latest.txt)

**Comment by RaspberryC** [comment]
[techniclauncher_2016-09-26.zip](https://github.com/xJon/The-1.7.10-Pack/files/504781/techniclauncher_2016-09-26.zip)

**Comment by xJon** [comment]
I see no crash?

**Comment by RaspberryC** [comment]
Yes, every time I attempt to load the game, it crashes to the technic launcher. I had started a new game and I just experienced the same issue. Is there somewhere else in the files I should be looking?

**Comment by RaspberryC** [comment]
Sorry for the late responses. I don't go online as often as I should. 

Here's what happened today when I tried to launch my new game. Same crash to launcher. 

[techniclauncher_2016-10-08.zip](https://github.com/xJon/The-1.7.10-Pack/files/517999/techniclauncher_2016-10-08.zip)

**Comment by xJon** [comment]
The errors show a corrupt world. Please try to load one of your automatic backups :)
