### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by sharpmainb** [xJon/The-1.7.10-Pack#1236]
I installed your pack from technic and when i try to start up it crashes
[crash-2016-10-07_20.48.55-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/516901/crash-2016-10-07_20.48.55-client.txt)

**Comment by xJon** [comment]
Did you try to reinstall?
Also, do you have any anti-virus program installed on your computer that may stop mods' access to directories?

**Comment by sharpmainb** [comment]
even with avast turned off and admin rights it wont work

**Comment by xJon** [comment]
Did you try to reinstall though?

**Comment by xJon** [comment]
Closed due to inactivity.
