### ISSUE TITLE
Banned for being in the wrong place at the Wrong time?

### ISSUE THREAD

**Issue by Nightmare1447** [xJon/The-1.7.10-Pack#1237]
So I joined 3-4 days ago, and I was looking for experienced players to team with. So I asked Jessica who I was teaming with when I was banned. And COUINCIDENTLY she was duping, I guess that's how she got so much stuff. Anyways, I don't know why I was banned since I wasn't the one duping. A better solution to that problem would have been banning the duper then questioning the new guy who joined yesterday. If you do unban me, if you feel the need just take my quantum etc stuff in my enderchest or just clear my inv and enderchest :P if it seems fit to you.

**Comment by Lord-Ptolemy** [comment]
Welcome to the 1.7.10 issue tracker. Not the 1.7.10 random community server issue tracker. If you're not here to report a bug with the modpack then you're in the wrong place.
