### ISSUE TITLE
Big Reactors

### ISSUE THREAD

**Issue by mikkelkp112** [xJon/The-1.7.10-Pack#1239]
I dont know if im the only one that has experienced this problem, but seemingly no matter what i do i cannot get a reactor, made with Big Reactors to produce any power. Not in Single Player nor in Multiplayer.

**Comment by samforbis** [comment]
I was playing on my server yesterday testing things and I was able to make a Big Reactors reactor just fine.  You might be making it incorrectly.

**Comment by xJon** [comment]
Do you know how to make them usually in other modpacks?
