### ISSUE TITLE
Can anyone tell me how to creat a server pls *_* 

### ISSUE THREAD

**Issue by Sxphire** [xJon/The-1.7.10-Pack#1241]

**Comment by xJon** [comment]
*"How to set up a dedicated server"*, by @Curunir, 2016
> 1. Download the server package version you need here: http://the-1710-pack.com/repo
2. Extract the package to where you want your server to run. This will work side-by-side with a client installation, but unless your PC is a high-end monster, it is much recommended to use another PC for the server, if any is available.
3. Make sure your clients can see the server. If you are all on the same home network (LAN), this should just work. To have it work across the Internet, the server needs to have the port it will listen to (default: 25565) forwarded from the router. This will not (ever) work if your ISP puts you in the baby cage that is carrier-grade NAT, so let's hope yours doesn't.
4. Edit your server.properties file with all the settings you need. Guide is here: http://minecraft.gamepedia.com/Server.properties
5. If you want to import a singleplayer world, locate the worldsave and copy it over to the server directory. You need to set the world name in server.properties to the exact directory name of the worldsave for it to use the existing one. Even if you let it generate a world, the name that you set here will be used, default is just "world".
6. If you need it to work for more than just a couple of friends, give it more RAM. Edit the launch script and change the -Xms (minimum) and -Xmx (maximum) allocation values as needed. For a first try, defaults will be fine.
7. If you were wondering, launch.bat is your launch script on Windows, while launch.sh is the one for Linux/Unix/MacOS. ALWAYS use the script, never manually start the server.jar. If you do, you will start a vanilla (i.e. unmodded) server that will do weird shit.
8. Run the server, don't be intimidated by the millions of errors and give it time. Once it stops generating new lines while not falling back to the command line or closing, it should be up and running. Try connecting with a client, using the IP adress or a DNS-resolved name.
