### ISSUE TITLE
New mods added to the server but not our launchers?

### ISSUE THREAD

**Issue by DaBe00593** [xJon/The-1.7.10-Pack#1244]
I was about to join my game when i got an error that new mods have been added to the game but they havent released an update in over a month. Did something go wrong with my launcher?
![2016-10-12 1](https://cloud.githubusercontent.com/assets/22800882/19325790/2523d386-909e-11e6-979c-c80617854245.png)

**Comment by xJon** [comment]
The update is going to be released in a few minutes!
