### ISSUE TITLE
Updating Server

### ISSUE THREAD

**Issue by HYDN150** [xJon/The-1.7.10-Pack#1246]
Hey Jon! Excited about this new update, going to make it a TON easier to get all that sweet compressed cobble. Anyways, a friend of mine has a server that both of us, along with some others all play on, and we are having some trouble understanding how to update the server itself, without basically starting all over again. Please excuse our idiocy as we have really only ever played modpacks together on servers that are old and don't get updated anymore, so we never had to deal with this. Some help would be very much appreciated! Thanks for taking the time to read this, and hope to hear from you soon!  

P.S. What are the chances of adding VeinMiner to the modpack in the future? I don't know if it's compatible with the other mods or not, but I was just wondering.

**Comment by xJon** [comment]
Just delete the `mods` and the `configs` folders of the old server and put the new ones, because only mods and configs updated in this update. :)
And VeinMiner won't be added
