### ISSUE TITLE
Survival World Un-Playable

### ISSUE THREAD

**Issue by flymasterz** [xJon/The-1.7.10-Pack#1247]
I updated my client to the new 0.9.4 and when I tried to load up my single player world the game just crashed. When I go to load up the world no error message occurs it just takes me back to the launcher. I was wondering if someone could help fix it because I have no idea what is wrong. (I do not use Optifine, I have a legitimize version of Minecraft and use the original Technic Launcher.

[crash-2016-10-13_12.26.48-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/527030/crash-2016-10-13_12.26.48-server.txt)

**Comment by xJon** [comment]
If you revert back to v0.9.3, are you able to load your world?
Also, did you try using one of the automatic backups?

**Comment by flymasterz** [comment]
I reverted back to the update and still did not work. I then copied the world and reinstalled the mod pack to check and still no luck. I believe when I reinstalled the mod pack it removed the backups Idk if I can get them back.

**Comment by flymasterz** [comment]
I have now restored to a early version of the mod pack that I deleted.

**Comment by xJon** [comment]
:+1:
