### ISSUE TITLE
Mod suggestion, Wireless Crafting Terminal

### ISSUE THREAD

**Issue by RobinEH** [xJon/The-1.7.10-Pack#1248]
I would like to request for the mod **Wireless Crafting Terminal** to be added to this modpack. This mod adds a wireless terminal with crafting as well as an infinite boost card. 

So far **Extra Cells 2** only supports Wireless terminal for gas and fluids and **Thaumic Energistics** only supports a wireless terminal for essentia. 

This mod is compatible with **Extra Cell 2**'s item **Wireless Universal Terminal**.

Direct link to mod: https://minecraft.curseforge.com/projects/wireless-crafting-terminal

**Comment by Curunir** [comment]
Jon still takes suggestions, but has no intention to consider any of them, because he is a dick.
