### ISSUE TITLE
Help wanted 

### ISSUE THREAD

**Issue by AntonioToni** [xJon/The-1.7.10-Pack#1249]
is there a way to get 14 million rf/t some other way then using lava gens x64 or nether star gens x64 please

**Comment by SneakTrap** [comment]
Wat do you need all that energy for?

**Comment by AntonioToni** [comment]
Well I play on a server and I have Public Power outputing in tesseract and well the power usage has gone up ... quite a lot it went from 100krf/t to 1.3mrf/t outputing .

**Comment by mandm635** [comment]
Try bigreactors x64

**Comment by AntonioToni** [comment]
Thanks for trying to help but i found a way to make 1 giga rf per second
