### ISSUE TITLE
Random fps drops after 20 minutes or so

### ISSUE THREAD

**Issue by xpapoose** [xJon/The-1.7.10-Pack#1250]
Just curious if there might be an idea as to why my fps would drop after 20 minutes or so of playing because it happens roughly every 20 minutes and I have to close minecraft completely and restart I never had this issue before. I just recently started playing the pack again and I thought maybe it was my texture pack but I tried to uninstall the pack and reinstall it and it still does it. We haven't updated to the newest version yet.
My avast pings it every time I start minecraft saying there is something wrong within my java folder but it shows a link to a website but every time I scan said folder it comes back that everything is fine. I'm not sure whats going on with that exactly but I dont want to say its a false alarm and allow it through if it is a virus.
So just thought I would see what might be wrong with my stuff.

**Comment by RobinEH** [comment]
The Avast warning is no problem. It's a false flag, nothing to worry about. You might be having a leak. Next time, monitor your CPU. See what it's at when you've just started the game and then when the fps drop starts happening. How much RAM have you dedicated to the pack btw?

**Comment by xpapoose** [comment]
Only reason with the avast I was worried is because it says its a website which seemed really random but I'll just ignore that for now and mess with it later. I believe I changed it recently to 6gb and I'll have to load up the game and check my cpu in a bit.

**Comment by oryfoxer7410** [comment]
Are you alt tab'ing out of the pack or switching from full screen to windowed? I have seen issues with this pack under those conditions.

**Comment by xJon** [comment]
Closed due to inactivity.
