### ISSUE TITLE
Weird crash on SP

### ISSUE THREAD

**Issue by flayner2** [xJon/The-1.7.10-Pack#1251]
When I try to play the pack on SP, I get a crash that says "A fatal error has occurred, this connection is terminated", and I get sent to the MP servers screen. It is happening with the 0.94 version, I'll downgrade and try out the 0.93 to see if it works, but I would love if anyone could help me fix it.

EDIT: Downgrade didn't work. Still waiting for help.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by flayner2** [comment]
<script src="https://gist.github.com/flayner2/9f1fef55665fe9d754d68320e0a0f971.js"></script>

**Comment by flayner2** [comment]
https://gist.githubusercontent.com/flayner2/9f1fef55665fe9d754d68320e0a0f971/raw/c0289e4ed0127728f219b435a67b28bc03e7820b/fml-client-lastest.log

**Comment by flayner2** [comment]
Anything yet?

**Comment by xJon** [comment]
Is this the full log? I couldn't find an error there that should stop you from playing.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
