### ISSUE TITLE
Mod Suggestion - Malisis Doors/Decocraft 2/ExtraTiC

### ISSUE THREAD

**Issue by SirKinji** [xJon/The-1.7.10-Pack#1252]
Hey,
I'm feeling like this Modpack is starting to become the ultimate one. But while playing for some time now, I feel like there are lacking more possibilities to decorate you base. I would like to suggest adding the Mods
"Decocraft" and "Malisis Doors".
Also I think that adding ExtraTiC, which adds more tool parts from mod materials would be a nice addon

Malisis Doors:
http://minecraftsix.com/malisis-doors-mod/

Decocraft:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292016-decocraft-2-2-decorations-for-minecraft-finally

ExtraTiC:
https://mods.curse.com/mc-mods/minecraft/extratic

**Comment by Curunir** [comment]
I have been disappointed with ExtraTiC. It is a great thing in principle, but the default config is rubbish. It needs a fine-tuned, ideally tiered config to introduce some sort of comprehensive progression of materials, not lump most of them on one or two low-grade tiers as it does by default. There is also the issue of it introducing liquid versions of most metals, which fail to register with other mods. These are worse than useless, and need to be properly integrated as well. I am not sure if anybody is capable and willing to integrate the mod properly.

MalisisDoors is nice, especially with the add-on BigDoors. I especially like the door animation it introduces.

I cannot say much for or against Decocraft.

**Comment by DraviteSlayer** [comment]
I believe we should get ExtraTiC. It adds a lot of new tools that make tinkers a whole lot better and more options to Tinkers as a whole. Its a very cool mod and makes tinkers more fun to play with.

**Comment by Curunir** [comment]
Did you even read what I wrote?

**Comment by ramorga** [comment]
For ExtraTiC configurations, I would look into Blightfall and how they have it set up. Never seen a cleaner modpack in terms of compatibility between different mods

**Comment by Curunir** [comment]
Jon still takes suggestions, but has no intention to consider any of them, because he is a dick.
