### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by FiroxHD** [xJon/The-1.7.10-Pack#1253]
[#1252] Pleaase add Minecraft come alives mod its cool and then you have a wife and can have children

Link to the mod: # [http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280154-minecraft-comes-alive-v5-2-3-mc-1-10-2-1-9-4-1-9-1](url)

**Comment by xJon** [comment]
Not going to happen currently. Thanks anyway for suggesting!
