### ISSUE TITLE
Block placement issues: meta-data being lost?

### ISSUE THREAD

**Issue by PocketOx** [xJon/The-1.7.10-Pack#1254]
Hello there, Hi It's Me. I've been having a weird problem lately and I don't know when it started or what's causing it, but certain blocks are defaulting to their "default" data when placed down. Such as, when I place the normal open blocks elevator in any color, upon placement it defaults to white. The directional elevators work 100% fine. Pam's sink blocks are also another I noticed giving me an issue. I made the black one, but it always defaults to the basic barrel one when placed.

Haven't noticed other blocks, but i certainly haven't tried them all, either.

**Comment by xJon** [comment]
Are you playing on a server?
Are you using the latest version?

**Comment by PocketOx** [comment]
I am playing on single player, version 9.4.

**Comment by Excepto** [comment]
Problem appears on my computer too. Does not seem to affect vanilla stuff and stuf from other mods for what ive seen

**Comment by xJon** [comment]
So this issue occurs just on these specific blocks?

**Comment by Excepto** [comment]
Have not checked all of them but bibliocraft coloured things work

**Comment by PocketOx** [comment]
As far as ive seen, it only occurs on those specific blocks. I did notice a similar issue when placijg a block into a carpenters block. The botania blocks (I can give you an exact list of which ones) do the same thing, but work fine when placed by themselves.

**Comment by Curunir** [comment]
The OpenBlocks Elevator was never meant to be obtained or placed while coloured. You are supposed to use a dye on it after it was placed, which should then colour it accordingly. It will probably not retain the colour after breaking, but you can always re-apply.
I do not know about HarvestCraft blocks, but if these show consistently problematic behaviour, you might inquire with the author if this is indeed a bug.

As this is likely not a general problem, I will close this ticket.
