### ISSUE TITLE
Mod Suggestion - Draconic Evolution.

### ISSUE THREAD

**Issue by AyuNex** [xJon/The-1.7.10-Pack#1256]
As there are many, many ways to generate  a TON of power, there are less ways to store this power.
That's why I would love to see this mod added to this modpack!

**Comment by SirKinji** [comment]
Hey there,
because you forgot the Link to the Mod, here's the Link 'cause I would also like to see this mod added.

Draconic Evolution
http://minecraft-forum.net/minecraft-mods-downloads/1-7-10-draconic-evolution-mod-download/#.WAkceCTXpug

**Comment by xJon** [comment]
This mod has been suggested already many times before and won't be added.
You can always add it manually if you wish.
Thanks anyway for suggesting!
