### ISSUE TITLE
Long loading time.

### ISSUE THREAD

**Issue by nuttapillar** [xJon/The-1.7.10-Pack#1257]
I've been stuck on the loading screen for quite a while now, probably more than 15 minutes, and most of that time, it has just said: "Calling late init for mod Voxelmap..."
How can I fix this? I have allocated 8gb of ram, and it is running on 64bit java 1.8

**Comment by nuttapillar** [comment]
After posting the first message, I went and had a shower, came back, and it had finally finished loading. so it gets in, but just takes a long time.

**Comment by xJon** [comment]
This is why showering is important.
Anyway, did you try to reinstall?

**Comment by nuttapillar** [comment]
In addition to that problem, I also noticed some very long delays when opening chests etc. Even after falling, it takes a couple seconds for the damage to be registered. It is like bad ping on a server, but I am playing local singleplayer.

**Comment by nuttapillar** [comment]
No, I didn't try to reinstall. I don't have good internet at the moment, so I cannot afford to redownload the whole pack, so that will have to wait a few days until I get home to good internet.

**Comment by nuttapillar** [comment]
i dont think a computer upgrade is necessary. I have 16gb of ddr4 ram, gtx 1080, intel 6700k, and the game is running on an ssd. Optimal environment, i'd say

**Comment by nuttapillar** [comment]
i have played other mod packs with loads of mods, such as ftb infinity, and that only takes a couple minutes

**Comment by nuttapillar** [comment]
anyway, since the game seems to get stuck on voxel map, maybe i should delete the mod from the mods folder, and install an alternative map mod. Is that a good idea?

**Comment by nuttapillar** [comment]
Strange. I just ran the game with no internet connection, and it was really fast! I guess when I'm connected to slow internet it tries to download something - I don't know what it wants to download or check though...

**Comment by xJon** [comment]
¯\_(ツ)_/¯

**Comment by Valiantiam** [comment]
This is happening for a friend of mine as well. He had to disable networking while it was trying to load Voxelmap, otherwise it just froze there and haulted forever.

Can this be looked into further?

**Comment by xJon** [comment]
@Valiantiam If it's still a problem, please open a new issue :)
