### ISSUE TITLE
Server wont start, please help

### ISSUE THREAD

**Issue by MrLimee** [xJon/The-1.7.10-Pack#1258]
So yesterday me and my friends where playing on our server, when it suddenly crashed, and now after that crash it wont start anymore. someone please help

crash log here.
[crash-2016-10-21_13.36.33-server (1).txt](https://github.com/xJon/The-1.7.10-Pack/files/544274/crash-2016-10-21_13.36.33-server.1.txt)

**Comment by xJon** [comment]
Your questing data inside of the save is corrupt. Reset it by deleting

**Comment by MrLimee** [comment]
Okay so we got the server up and running again by deleting the quest data, but now the server crashes with like half an hour in between crashes and everytime we have to go into to our player data and reset our positions, before we can join again, please help it's pretty much making the game unplayable

**Comment by xJon** [comment]
I'd suppose that something in your world is corrupt then. You could try using a really old backup, or post your new crash log here using a paste-tool.

**Comment by MrLimee** [comment]
okay heres the crash report http://paste.ubuntu.com/23369117/
the thing is, we can play on the server for a while then suddenly it crashes. and when we try to join again it  also immideatly crashes. but if we delete our player data or change the cordinates of the players, it works we can play again for another 20 minutes before it crashes again.

**Comment by xJon** [comment]
I'd try to go get help at the Forge Forums with this crash report. You might have a corrupted chunk or something like that in your world. There's nothing else I can do to help you (this issue is not pack specific).
