### ISSUE TITLE
[Suggestion] Modular Force Field System

### ISSUE THREAD

**Issue by oryfoxer7410** [xJon/The-1.7.10-Pack#1259]
In the past, I know MFFS was removed due to conflicts. My curiosity is if these conflicts have been resolved and if possible to add to the pack. 

It would be extremely useful and I feel it would fit the pack. I don't think I have go into detail on what benefits it offers and for the most part, servers can protect without it, but it would provide a great deal of protection on its own that I think everyone would benefit from.

**Comment by xJon** [comment]
Currently there are no stable builds for the mod, unfortunately.

**Comment by LemADEC** [comment]
WarpDrive includes modular force fields and it's stable, but then I'm partial :)

**Comment by Curunir** [comment]
Jon still takes suggestions, but has no intention to consider any of them, because he is a dick.

**Comment by xJon** [comment]
Actually, this mod suggestion still stands, and was considered heavily at v0.9.7. Unfortunately MFFS is just too unstable right now, but that could change in the future.

**Comment by Curunir** [comment]
MFFS has not been stable since Calclavia dropped it. That one guy who recently started working on all those abandoned 1.7.10 mod, including MFFS, has no track record. MFFS is a very hard thing to get right. I do not think it is even worth waiting for.

**Comment by xJon** [comment]
Eh, you're probably right.
Closed for now.

**Comment by LemADEC** [comment]
So I get you've tested the WarpDrive forcefields?

**Comment by xJon** [comment]
Didn't hear of the mod.

**Comment by LemADEC** [comment]
https://github.com/LemADEC/WarpDrive/wiki/Force-field-projector

**Comment by xJon** [comment]
Added! :)
