### ISSUE TITLE
[Suggestion] Back in Slime

### ISSUE THREAD

**Issue by SparkyBearBomb** [xJon/The-1.7.10-Pack#1262]
Could you please add the mod back in slime to enable the MC 1.8 ability to use slime the same way?

Link: https://mods.curse.com/mc-mods/minecraft/232264-back-in-slime-slime-blocks-for-1-7

**Comment by Curunir** [comment]
Please elaborate which functions this mod would add. From what I can see, it adds nothing of value and you'll have to convince us first.

**Comment by SparkyBearBomb** [comment]
the back in slime adds the piston and slim behavior from 1.8+ into 1.7.10, allowing for lots of builds that take advantage of pistons and slime block to be built (eg. giant doors, piston elevators ect.) possibilities are literally endless
also allows for more compact piston based builds

**Comment by Curunir** [comment]
I have never played anything above 1.7.10, so I'm not familiar with that difference. Neither do I care for it.

**Comment by SparkyBearBomb** [comment]
A slime block becomes bouncy, so you can push things further, even make a slime-block launcher,
any moveable block touching the slime block will be moved when the slime is pushed with pistons,

it is quite a simple mod, and it won't require a server to reset it's map if it were to be included.

**Comment by xJon** [comment]
Thank you for suggesting but currently we're not planning to add new mods.
