### ISSUE TITLE
quits

### ISSUE THREAD

**Issue by darkfire2020** [xJon/The-1.7.10-Pack#1263]
it always quits responding when i launch it, teleport, and die
is there a way to fix this?

**Comment by mandm635** [comment]
Please provide more information, such as the logs.

**Comment by darkfire2020** [comment]
it doesnt give me logs, it just quits responding

**Comment by RobinEH** [comment]
What exactly quits responding? Does the TechnicLauncher stop responding or Minecraft during start up? Does it then re-respond? Are you trying to click on the Minecraft window while it's still loading the pack when it stops responding? Are you playing singleplayer or on a server? What exactly do you mean with you teleporting and dying?

**Comment by darkfire2020** [comment]
It the Minecraft, I play on a server

**Comment by mandm635** [comment]
The logs can be found in your .technic directory(where this pack installed), in a folder called logs. Please post the latest-log using a paste tool.

**Comment by xJon** [comment]
Closed due to inactivity. Will reopen with the required info.
