### ISSUE TITLE
Having trouble loading my world.

### ISSUE THREAD

**Issue by rockman4** [xJon/The-1.7.10-Pack#1264]
Hi,

A world I've been working on for a while now does not seem to load correctly as every time I try playing it, the game closes completely. This happened after I accidentally cut the power to my computer as the game was playing.

**Comment by mandm635** [comment]
Did aroma make a backup you can load from?

**Comment by rockman4** [comment]
how can I access aroma?

**Comment by rockman4** [comment]
Nevermind I figured it out. Thanks a lot this worked!

**Comment by xJon** [comment]
👍
