### ISSUE TITLE
[PSA] Disable the following biomes for Mystcraft

### ISSUE THREAD

**Issue by oryfoxer7410** [xJon/The-1.7.10-Pack#1265]
Magical Forest Biome will cause a crash for Mystcraft on load. I would suggest to disable this in the configuration file for biomes. Due to the issue, I have just gone ahead and disabled all Thaumcraft biomes for Mystcraft. Could be related to KCauldron.

Thaumcraft Biomes:
biome192
biome193
biome194
biome195

Here is an example of the crash log these biomes can produce:
http://pastebin.com/XTesun2U

**Comment by xJon** [comment]
Did you try reporting this to the [Mystcraft author](https://github.com/XCompWiz/Mystcraft-Issues)? Because that'd be much better, I don't want to disable biomes without an explanation

**Comment by Curunir** [comment]
There is one known issue with Mystcraft that I once heard about, which will apparently never be fixed. If snow falls on special liquids in a new dimension, that dimension will crash the server and/or client and be unusable entirely. It occurs not often enough to be a total game breaker, but often enough to be annoying. Blacklisting biomes might contain it, but it can even occur with pretty simple stuff. As far as I know, Mystcraft even has an internal hardcoded fluid blacklist to block access to "overpowered" metals in large quantities. Add to this the inescapable dimension lag we all know and hat.
The sum of all these observations makes one thing pretty clear: Mystcraft is very much broken and you should be prepared to manually delete a new dimension from the worldsave if it happens to be unusable. The only long-term solution I can think of is removing Mystcraft and replacing it with RFTools, which has none of these problems. Not likely for a large established pack, but good luck if you decide that is what you want for your local game.

**Comment by xJon** [comment]
Nothing else I can add or do.r do.
