### ISSUE TITLE
Pack Not installing or Running at all

### ISSUE THREAD

**Issue by Itz-Beanz** [xJon/The-1.7.10-Pack#1266]
So I've been playing the 1.7.10 pack for the past 2 weeks now with no big hitches really but just yesterday when I went to run it wouldn't get past the loading bar. I've had a problem similar to this a long time ago and I remember reinstalling it under a different version and the installing it to the latest version fixed it. Unfortunately when I uninstalled it, it wouldn't reinstall. It would load the bar twice, get to the end of the loading bar that says "Grabbing org.scala" in it and then the bar goes away and the install button comes back with the actual technic window unaffected. I've tried deleting the pack and downloading it back but it still wouldn't download. All of the other packs on technic work absolutely fine but this pack is the only one causing problems. I have 6 GB allocated to the pack which, although not a ton, seemed to run the pack just fine for awhile. I don't know a lot about all this stuff so I don't know if I'm missing something obvious or whatnot. I don't have any antivirus software that would cause a problem
Also today it stopped showing the amount of total Installs and Runs of the pack instead saying they're both zero... don't know if that has something to do with it...
If you need more info please ask.
Thank you

**Comment by xJon** [comment]
Let's start from the end: The stats were broken on Technic's side.
As for your issues: Did you try to reinstall the launcher? Because I suspect something is wrong with your installation, if the *launcher* loading bar can't complete. And also you shouldn't allocate more than 4GB of RAM.

**Comment by xJon** [comment]
Just restart the PC, would be the easiest, then delete the folder.

**Comment by Itz-Beanz** [comment]
Alright, reset my computer and I was able to reinstall the launcher. Starting the pack back up worked fine and everything seems to be fixed.
Thanks for all the help mate!

**Comment by xJon** [comment]
:)
