### ISSUE TITLE
[Help Wanted] Crash Report Analysis 

### ISSUE THREAD

**Issue by oryfoxer7410** [xJon/The-1.7.10-Pack#1267]
Any thoughts? Log doesn't seem to give me much to go on, maybe you guys notice something I didn't. I have seen this crash 2x. Not sure which mod is causing the issue. Some guidance would be appreciated. 

http://pastebin.com/V0xp38nv
http://pastebin.com/8LQT7XCv

Much thanks in advance!

**Comment by Excepto** [comment]
Might be line 1439, 1440
   EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from Flans Mod-1.7.10-4.10.0.jar).

**Comment by mandm635** [comment]
No, that is a normal message with this pack.

Are you playing on a server? If not, I think you have allocated too much ram. When does this crash cur? From what I can see, you have either a corrupted item close to your player, or you loaded your player with a ton of backpacks/equivalent and tried to move you base in one trip.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if needed.
