### ISSUE TITLE
Hi jon 

### ISSUE THREAD

**Issue by AntonioToni** [xJon/The-1.7.10-Pack#1268]
I have seen the new reliquary update and i don't like it in fact i hate it can it be downgraded please?

**Comment by xJon** [comment]
Any reasons behind it or should I simply downgrade it in the next update without any questions?

**Comment by AntonioToni** [comment]
just because the crafting recepies changed  it made everything extremly hard to make cause almost everything includes slime pearls (10% chance a slime will drop it when killed no other way to get it)
i just don't like the SUPER hard recepies everything was ok before
please downgrade it Thank you very much for fast reply and i hope you do downgrade it

**Comment by xJon** [comment]
Did you check the mod's config file to see if you can change anything?

**Comment by AntonioToni** [comment]
I play on a server so i don't think it's going to work

**Comment by Curunir** [comment]
Mods updating to be more difficult is the way of the world. You need to do way better than "I don't like the changes" to hold up progress like that, or even revert it. So far, you have convinced nobody.
