### ISSUE TITLE
Crashing while starting

### ISSUE THREAD

**Issue by DaeZ1337** [xJon/The-1.7.10-Pack#1269]
when i try to play this modpack its loading like normal but at the end of the loading its just crashing. i tried everything. re install technic launcher re install java the modpack i tried to use an older java version EVERYTHING with optifine without like srsly everything. my pc is good enogh to play gta 5 on high graphic settings. I5 4460 3.2 GHZ GTX 750 Ti 8GB Ram

**Comment by mandm635** [comment]
Does it crash or go nonresponsive and you kill it? If it's crashing, please post a crash log.

**Comment by Flukethoughts** [comment]
please post crash logs

**Comment by DaeZ1337** [comment]
[crash-2016-11-02_18.01.34-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/567212/crash-2016-11-02_18.01.34-client.txt)

**Comment by mandm635** [comment]
Something is wrong with the ChickenChunks config file, try deleting the pack and reinstalling.

**Comment by DaeZ1337** [comment]
already tryed it many times still crashing

**Comment by xJon** [comment]
It might be an anti virus or something locking the access to the file, I'm not sure.
Your best bet would be to ask [here](https://github.com/Chicken-Bones/ChickenChunks/issues).
