### ISSUE TITLE
Carpenter's block, Internal Server Error

### ISSUE THREAD

**Issue by RobinEH** [xJon/The-1.7.10-Pack#1271]
I've been having issues on and off with receiving the message "Internal Server Error" and getting kicked from the server I play on. This happened when I was placing glowstone dust in a carpenter's block (which makes the block a light source). At first it seemed to happen sporadically, however I noticed today that it happened whenever I used the last piece of glowstone dust in my hand. 

I don't know if you're able to work around this, or if it has to be resolved by the mod developer directly.

**Comment by xJon** [comment]
This should be reported directly to the [mod author](https://github.com/Mineshopper/carpentersblocks/issues) with the `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).
Nothing else I can really suggest.
