### ISSUE TITLE
Modpack won't install AND initializing issue

### ISSUE THREAD

**Issue by kelly053** [xJon/The-1.7.10-Pack#1273]
I have been having issues with this modpack. At first, I downloaded it with the technic launcher and it got stuck on initializing. I upgraded my RAM and set it to 8 gb on launcher options and it still got stuck on initializing. So to try and fix this, I uninstalled the modpack and tried to reinstall, and now it won't even install again! Help please!

**Comment by xJon** [comment]
You don't need to allocate 8 GB of RAM. 4 is enough. And also let it load, be patient.
If you still encounter problems gives please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if needed.
