### ISSUE TITLE
Mod suggestion: iguanas tinker tweaks

### ISSUE THREAD

**Issue by Scyrus42** [xJon/The-1.7.10-Pack#1274]
This mod is a very useful mod, it might unbalance things because of the xp system, but it removes unnecessary clutter and adds a necessary incline to the progression curve of the game, this is easily added to personal clients, but as I am on a server with a friend, that is a problem. 

Sincerely,
Scyrus A. Pyro

**Comment by xJon** [comment]
This has been suggested many times before.
Currently it won't be added, but you can always add it manually if you wish.
Thanks anyway for suggesting!
