### ISSUE TITLE
Adding Mods to servers, and client compatibility

### ISSUE THREAD

**Issue by GrimmsterZ** [xJon/The-1.7.10-Pack#1275]
Hello,
I recently created a 1.7.10 pack server for my friends, and it works great! [Thanks to @xJon for help] With that, I have one question.
I am new to modded servers, but I noticed the server has a mods folder with all the 1.7.10p mods in it.
I was wondering if you could add to this folder to add mods to the server, and if you'd need every person joining the server to get them as well. I am assuming this is correct, but I would like someone to confirm that.
Thanks 👍

**Comment by xJon** [comment]
Yes, that is correct. Most of the mods (95% or so) need to be installed on client side too if they are installed on server side.
