### ISSUE TITLE
Server will not run

### ISSUE THREAD

**Issue by SillyMoofin** [xJon/The-1.7.10-Pack#1276]
I've tried using different versions of java as the problem apparently is something to do with 'Ignoring option PermSize=256m' . Is there anything I can do? (I'm trying to use the latest server version)

**Comment by mandm635** [comment]
Can you post server logs, and also make sure your run.bat file is something like this: 
java -Xmx1024M -Xms1024M -jar minecraft_server.jar nogui
PAUSE
The 1024M refers to running the server with 1024megabytes of ram. You should not put this higher than what you see available in task manager. If your run.bat file looks right, please post the code that's in it as well.

**Comment by xJon** [comment]
`Ignoring option PermSize=256m` Shouldn't stop your server from running.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if needed.
