### ISSUE TITLE
The 1.7.10 Pack Crashing on startup?

### ISSUE THREAD

**Issue by rradt2001** [xJon/The-1.7.10-Pack#1277]
log: http://pastebin.com/QxXudric

IT starts a box, then the box thing closes and it goes back to the launcher. Please help.

**Comment by xJon** [comment]
That's a problem on your end. Did you try to Google it for help?

**Comment by rradt2001** [comment]
I did, nothing really came up with this exact bug report.

**Comment by Curunir** [comment]
You do not have a proper openGL context for the game to run in, which usually means you have no proper graphics drivers installed. Find out what you are using, then obtain the latest graphics drivers for your system. If you want help with that, post the name of your graphics card and/or mainboard here, or at least the name of the computer model.

**Comment by xJon** [comment]
Closed due to inactivity.
