### ISSUE TITLE
Error in the initialization of minecraft with technic launcher

### ISSUE THREAD

**Issue by Naklics** [xJon/The-1.7.10-Pack#1279]
Everytime I try start the modpack, it happens : 

[B#219] Analytics Response [runModpack]: 200
 ummm User data ? 
[B#219]  [12:37:19] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[B#219]  [12:37:19] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[B#219]  [12:37:19] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[B#219]  [12:37:19] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[B#219]  [12:37:19] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_111, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_111
[B#219]  [12:37:19] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[B#219]  [12:37:19] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[B#219]  [12:37:19] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[B#219]  [12:37:19] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[B#219]  [12:37:19] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#219]  [12:37:21] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[B#219]  [12:37:21] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[B#219]  [12:37:21] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[B#219]  [12:37:21] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[B#219]  Exception in thread "main" [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoSuchMethodError: com.google.common.io.CharSource.readLines(Lcom/google/common/io/LineProcessor;)Ljava/lang/Object;
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.asm.transformers.AccessTransformer.processATFile(AccessTransformer.java:125)
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.asm.transformers.AccessTransformer.readMapFile(AccessTransformer.java:120)
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:101)
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.asm.transformers.AccessTransformer.<init>(AccessTransformer.java:97)
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:32)
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[B#219]  [12:37:21] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

someone can help me?

**Comment by mandm635** [comment]
Use a paste site... Try reinstalling the pack.

**Comment by Naklics** [comment]
Hey bro, I did this and remains the same error. Do you have another possible solution?

**Comment by Curunir** [comment]
There only will be a solution when we have a chance to see the actual problem. You have not shared anything meaningful with us yet, just a fraction of a much larger log.

**Comment by Naklics** [comment]
sorry man, but this is all log that technic launcher shows

**Comment by Curunir** [comment]
These are normal, and this is still just a very small part of the log. Cannot diagnose anything from it.

**Comment by Naklics** [comment]
So where can I find the full log?

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Naklics** [comment]
Bro, not exists fml-client-latest.log in the folder modpack, just a text documment written 'latest', is this?

**Comment by mandm635** [comment]
Try the log above that one.

**Comment by Naklics** [comment]
I didn't understand, have just a text documment written 'latest' in log paste

**Comment by mandm635** [comment]
Try the log above that in the folder, it should be named a date.

**Comment by Naklics** [comment]
https://cloud.githubusercontent.com/assets/23360681/20180675/3766670e-a73a-11e6-8708-e9b6b1643a6d.png

where?

**Comment by Naklics** [comment]
someone?

**Comment by Curunir** [comment]
If this is all you have in terms of logs, then we cannot diagnose anything. Sorry.

**Comment by xJon** [comment]
I can only recommend you to try to re-install the launcher.
