### ISSUE TITLE
Entire Modpack incredibly slow

### ISSUE THREAD

**Issue by Tormago** [xJon/The-1.7.10-Pack#1282]
I'm not sure exactly where the issue is here. Other modpacks on the techniclauncher run fine at 60fps with very nice texture packs, but even without a texture pack I barely get 30 fps, and with Sphax at 64x it stays lower that 20fps. Not to mention that without any textures, it takes about a full 5 minutes for the main Minecraft window to open and be usable after pressing play on the launcher. I'm not sure if this is a Java issue or what, but I don't know where to look for a fix

**Comment by Tormago** [comment]
just standing around without a pack, the memory usage is 2.5 gb out of the 3gb allocated

**Comment by mandm635** [comment]
This is a very large pack, you may try to install Optifine + fastcraft

**Comment by Curunir** [comment]
If anything, don't install Optifine and Fastcraft concurrently, this can cause issues.
Generally, a heavy pack with 200+ mods will usually run slower. If you prefer the 60fps over functionality, then you should probably play those other packs.

**Comment by Tormago** [comment]
That's pretty bad advice. It's not like my computer is incapable of running
this mod pack. Basically what I'm hearing is "this mod pack is really huge,
so if you want something that actually runs normally you shouldn't play
this one"

**Comment by Curunir** [comment]
What do you want to hear? That we will wave a wand to make it suddenly run much better on your box? I have a pretty decent machine and it runs around 20-30fps, which I consider normal for a fat kitchen-sink pack. Some people report 40+ fps with it, but these are running workstation-class socket 2011 systems or highly-clocked quadcores from Intel's newest lines. It's an inefficient game engine, hacked to be expanded in a thousand different ways. Take it or leave it.

**Comment by Tormago** [comment]
Didn't say anything about some magic wand. I had questions about this modpack in general, didn't realize it was just the pack that requires the highest quality computers out right now. I mean, its Minecraft, I didn't expect mods (even that many) to be that large of an issue
