### ISSUE TITLE
Problem - Game crashes when I try to lode my Wold.

### ISSUE THREAD

**Issue by Gharth** [xJon/The-1.7.10-Pack#1286]
Everytime I try to lode my Wold the game chrashes, I already tryd to lode the backups, but the same problem happens, youst a crash without any notification after the "Loding Wold" apert.
 
What can I do to safe my countles houhers of work and what to start the wold again?

**Comment by oryfoxer7410** [comment]
Please, provide the Crash Log.

That being said, in the forge configuration file (forge.cfg), you can enable to remove errorring entities and tiles. Set both to true then try to start your server.

**Comment by xJon** [comment]
Closed due to missing information.
