### ISSUE TITLE
Crash Server

### ISSUE THREAD

**Issue by Tommyboulianne** [xJon/The-1.7.10-Pack#1287]
#I need help my server crash at startup
I close it then, the tomorrow it doesn't work

>Log file

>   http://www.mediafire.com/file/ao40no1zqi94uoo/HELP.zip

**Comment by oryfoxer7410** [comment]
First off, NO. Not opening your zip file, especially from mediafire. 

If you want someone to actually review your logs, please, use pastebin.com and paste a link.

**Comment by Tommyboulianne** [comment]
I have the 3 logs files in the ZIP

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).te-tool](http://paste.ubuntu.com/).

**Comment by Tommyboulianne** [comment]
http://paste.ubuntu.com/23481513/

**Comment by xJon** [comment]
No crash in this log.

**Comment by Tommyboulianne** [comment]
Yes, it has one, but nevermind 
I used a backup

**Comment by Tommyboulianne** [comment]
Now it works

**Comment by xJon** [comment]
👍
