### ISSUE TITLE
Terrible lag on single player world (not FPS)

### ISSUE THREAD

**Issue by TikeRike** [xJon/The-1.7.10-Pack#1288]
It's as if my connection is really horrible, but that doesn't make sense since it's a single player world. I have several seconds delay, can't destroy blocks, open chests, or change pages in my inventory.

**Comment by mandm635** [comment]
Try running with your computers internet turned off.

**Comment by Wharblar** [comment]
Download and install Opis-1.2.5_1.7.10 and MobiusCore-1.2.5_1.7.10. Extract the jars to your mods folder on your server and your PC.

When in game, type in /opis to open up the opis window and debug the lag. I had 1800 villagers spawned in a village, and I selected them under entities group and clicked Kill All. Fixed my server lag.

You can test your server lag by typing in /cofh tps. 100% means there's no server side processing lag.

**Comment by Curunir** [comment]
Before you bring out the big guns for diagnosis. check your RAM assignment. The 1.7.10 Pack needs 3.5 GiB, and this needs to be assigned in the launcher.

**Comment by TikeRike** [comment]
@Cununir, I've already assigned 4Gb to the game.

**Comment by Curunir** [comment]
Is the performance that bad everywhere, including a new-generated world? If it only occurs in your regularly-used world, you might have some luck with Opis. It's a tool that will enable you to check on entities and tile entities, which are often the cause of performance issues.
Beyond that, we'll need more information on your system before we have any chance of diagnosing the issue.

**Comment by xJon** [comment]
Closed due to inactivity.
