### ISSUE TITLE
Can't create mod items. Please Help

### ISSUE THREAD

**Issue by datthingdoh** [xJon/The-1.7.10-Pack#1290]
I can create vanilla minecraft items but it wont let me create the items from the mods it shows them in the craft box then i click it, it lags it back.

**Comment by Curunir** [comment]
That happens when you run a modded client, but play on a vanilla Minecraft server. Is this your own dedicated server? If so, you started it wrong. You need to start it with the launch script, never by just clicking on jar files.

**Comment by xJon** [comment]
Closed due to inactivity. Shouldn't be a modpack issue anyway.
