### ISSUE TITLE
Server crashing, due to something happening in or to player data

### ISSUE THREAD

**Issue by aleern** [xJon/The-1.7.10-Pack#1292]
server keeps crashing on startup , and i have to delete player data to fix this, understandably, this is obnoxious, any suggestions? here's the full crash log http://pastebin.com/yvmv719W . don't quote me on this, but i believe it has something to do with the questing mod, if that helps at all.

**Comment by mandm635** [comment]
I agree that it has something to do with the quest mod. Try deleting all players questing data, or load from an Aroma backup of when it was working. Be sure to make a backup of the questing data before doing this as it will reset all quests.

**Comment by xJon** [comment]
Delete the `hqm` folder inside your save folder to reset your corrupt questing data.
