### ISSUE TITLE
Mods Suggestion

### ISSUE THREAD

**Issue by Anhilyx** [xJon/The-1.7.10-Pack#1293]
I have some mods who can be added to the modpack : 
- Lanteacraft / Stargate Tech to add teleportation things from the Star Gate serie
- Decocraft to have better decoration items
- A mod like Archimede's ships to create an entire flying base. If the mod can move an unlimited amount of blocks, it's better to make an entire base.
- An easyer version of GregTech (by editing .cfg file and with minetweaker) to add high level things to industrialcraft.
- A recipe with uu matter for more items (it can be added by editing the config file of IC2)
- Better Dungeon and/or Dungeon pack to explore the world at the start and start with a better stuff and more difficulty
- Draconic Evolution for powerful things
- New quests for mods like Mekanism (for example for the Matrix or the Reactor)
I hope some of this things will be added.

**Comment by mandm635** [comment]
Please search through the clised issues before suggesting. For the other things, Jon will have to weigh in.

**Comment by orjanj5** [comment]
Really would love to see metallurgy and mo'creatures in here

**Comment by Curunir** [comment]
Jon still takes suggestions, but has no intention to consider any of them, because he is a dick.
