### ISSUE TITLE
issue with recipe switching

### ISSUE THREAD

**Issue by fg094** [xJon/The-1.7.10-Pack#1294]
I am able to switch the output of certain recipes (default 'num+' key)  such as the bronze armors, but I am unable to do it with steel armor and tools.

**Comment by xJon** [comment]
You're using the NoMoreRecipeConflict recipe switch?

**Comment by fg094** [comment]
yes. I can switch other materials but not steel. Also I can't seem to repair Mekanism steel items with steel from any of the other mods.

**Comment by Curunir** [comment]
I used that mod, too. It can lose some or all function on non-vanilla crafting tables, so try using a vanilla one and see if that helps. Other than that, we can neither diagnose nor debug this much.

**Comment by fg094** [comment]
yeah, it doesn't work no matter which crafting bench I use. I don't have this issue with any other material. as a side note I am still unable to repair mekanism steel items with steel from any other mod.

**Comment by xJon** [comment]
The other thing should be reported to Mekanism directly.
And about how you can't recipe switch the steel things - we're using this mod and doing the best we can with it. Are you sure they are conflicting recipes for these steel items?

**Comment by fg094** [comment]
yes, the items in question are the steel armor sets.

**Comment by xJon** [comment]
Well, if it doesn't work with specific items there's nothing I can do unfortunately.
