### ISSUE TITLE
Launch Faliure

### ISSUE THREAD

**Issue by TheLightOfNight** [xJon/The-1.7.10-Pack#1295]
Launcher used crash. It was super effective!

Upon launching the pack i simply get a black screen, sometimes responding, sometimes not. (according to the task manager) This, without fail, then closes and returns me to the launcher. 

What worries me is that i have done nothing, seem to be able to do nothing and it was working yesterday without fail.

Below are the appropriate lines of code that my console threw up regarding the crash.
[crash log 1.7.10 pack.txt](https://github.com/xJon/The-1.7.10-Pack/files/616946/crash.log.1.7.10.pack.txt)

Edit: 
I have found this line in the code upon repeating attempted opening.

EnderIO: Found the following problem(s) with your installation:
[B#347]                    * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.1.0 from EnderTech-1.7.10-0.3.2.405.jar).
[B#347]                      It is a supported version, but that difference may lead to problems.

I hope this helps

**Comment by xJon** [comment]
Try to either re-install or manually reset the PneumaticCraft config files by deleting them.
