### ISSUE TITLE
Multiple Mod Issues

### ISSUE THREAD

**Issue by Fumetsu1** [xJon/The-1.7.10-Pack#1296]
Hi there!

Today I've finally managed to get a sever running for this mod pack! Woohoo :)
After a few solid hours of playing we've found that we cant use A LOT of the mods, eg. IC2, Applied Energetics, bibliocraft ect ect.
When trying to craft items from these mods, we cannot seem to take them from the crafting bench and when spawning from NEI we either get a "There is no such item with ID xxxx" or if we can spawn it, once we place it it dissapears.
There are more issues that we've noticed such as no extra ores spawning and crashing when using PiP, too name a few.
Sorry to list so many issues but I just wanna enjoy this awesome mod pack to it's full extent!
[fml-server-latest.txt](https://github.com/xJon/The-1.7.10-Pack/files/624659/fml-server-latest.txt)

Let me know if you need anything else :)
Thanks!

**Comment by xJon** [comment]
I guess you fixed it?
