### ISSUE TITLE
It wont let me play

### ISSUE THREAD

**Issue by SnarlingGecko** [xJon/The-1.7.10-Pack#1299]
Everytime i press play in the technic launcher it starts up but then goes back to the technic launcher...
I have the newest version of java and have 10 gigs of memory.
I have also reinstalled the modpack and deleted it countless times.
Please help...
~SnarlingGecko

**Comment by xJon** [comment]
Did you try to restart your computer?

**Comment by SnarlingGecko** [comment]
yes i did

**Comment by Curunir** [comment]
See if you can find any recent crash logs under /crash-reports. If you can't, try sharing the launcher log with us, using a service like https://paste.ubuntu.com/.

**Comment by xJon** [comment]
Closed due to missing information.
