### ISSUE TITLE
A Mod Suggestion

### ISSUE THREAD

**Issue by iMystikal** [xJon/The-1.7.10-Pack#1303]
So. Ive been working on Infinite Energy.
And then I realized It's going to be way too hard to craft Tessrecats.
So Ive downloaded a mod called "Additional Pipes"
And its just GREAT!
It has the teleport pipe that helps you save SO MUCH Space!
And can teleport between different dimensions.

Mod link: https://github.com/tcooc/AdditionalPipesBC/releases

**Comment by Curunir** [comment]
Tesseracts are late midgame or endgame items. They require some effort, but are actually easy to get once you know your way around. We will not add redundant mods just because somebody can't figure out how the more advanced crafting methods work.

**Comment by xJon** [comment]
Currently we prefer not to add Additional Pipes, thanks anyway for suggesting @iMystikal!
