### ISSUE TITLE
[Help Wanted] Necromod - Generating Structures

### ISSUE THREAD

**Issue by oryfoxer7410** [xJon/The-1.7.10-Pack#1305]
Having some issues locating which mod is reporting this in console. 

I have noticed that it generates quite of bit of lag when this mod is loaded into Mystcraft and I want to disable this. 

I checked Necromancies configuration, but I was unable to locate anything for the Graveyards that are being generated. 

Can someone point me in the right direction? I am attempted to stop Graveyards from being generated within Mystcraft.

**Comment by oryfoxer7410** [comment]
I think I fixed the issue. Its necromancy caausing the lag with MystCraft. I edited the Mod and removed the generation seed and no longer get the lag from mystcraft. This will only work if your overworld is already per-generated.

This can be closed.

**Comment by xJon** [comment]
👍
