### ISSUE TITLE
Singleplayer issue

### ISSUE THREAD

**Issue by vamatyi** [xJon/The-1.7.10-Pack#1306]
I've created a sp world with default world type cheats off but when i try to play it says:"Connection lost A fatal error has occured, this connection is terminated."

I am using version 0.9.5

**Comment by vamatyi** [comment]
Missing information? Tell me what do you need.

**Comment by xJon** [comment]
[This](https://github.com/xJon/The-1.7.10-Pack#if-you-have-all-that-required-post-an-issue-with).

**Comment by vamatyi** [comment]
http://paste.ubuntu.com/23682595/
Here's the latest log.

**Comment by vamatyi** [comment]
Anything else? Becouse i don't have any crash reports in the dir it mentions.

**Comment by xJon** [comment]
This doesn't seem like the full log as it's very short, but in any case I see here that you've successfully managed to enter your world.
Can you please duplicate the issue and *then* post your latest log, with the error, again?

**Comment by vamatyi** [comment]
http://paste.ubuntu.com/23684168/
Here it is. By the way it was the full log and yes the world loads but before i can see/do anything i get sent back in the menu with the message i wrote before.

**Comment by xJon** [comment]
Okay so this is just not the log I need. Is this named `fml-client-latest.log`?

**Comment by vamatyi** [comment]
Oh i am sorry i thought u needed the one simply called "latest". Here's the one you want:
http://paste.ubuntu.com/23686668/

**Comment by vamatyi** [comment]
Is there a way to disable the internal server so SP would run whitout it? Becouse that might solve the problem.

**Comment by adiga002** [comment]
I have the same problem i fix it all have to do is disconnect the internet and enter world it well take some time but it will work

**Comment by vamatyi** [comment]
Wow, that worked! Thanks!

**Comment by xJon** [comment]
👍
