### ISSUE TITLE
Electrotine Ore generation is disabled

### ISSUE THREAD

**Issue by Teraku** [xJon/The-1.7.10-Pack#1307]
The generation for Electrotine Ore seems to be disabled in Project Red's config. This makes it impossible to use any of the blutricity-related machines, because Electrotine and Electrotine Alloy Ingots are unobtainable.

In ProjectRed.cfg, `B:"Electrotine Ore"=false` should be changed to `true` instead.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.7.10-Pack/issues/956#issuecomment-166724560
