### ISSUE TITLE
Can't pick up XP from mobs

### ISSUE THREAD

**Issue by JohnLovesJeepin** [xJon/The-1.7.10-Pack#1308]
I have downloaded and freshly installed the 1.7.10 pack through the technic launcher on 2 separate PC's and cannot collect/pick up XP on either one. A friend of mine is having the same problem and he has a fresh download and install as well. The XP drops to the ground and dissapears in about 10-15 seconds.

**Comment by Curunir** [comment]
Are you sure these are XP orbs you are looking at? Because Thaumcraft has mobs drop some kind of aspect orb that cannot be picked up unless you have advanced into the mod a bit.

**Comment by xJon** [comment]
Closed due to inactivity.
