### ISSUE TITLE
Crash to menu on chat

### ISSUE THREAD

**Issue by Dmitchell94** [xJon/The-1.7.10-Pack#1317]
Hello,
I have a server running this modpack using Thermos(allows forge and bukkit to work together) and every time a player chats they get an out of bounds exception but no further info is given:

`_BlackMage_ lost connection: Internal Exception: java.lang.ArrayIndexOutOfBoundsException: -1`

I can walk around the server and interact I can even issue commands but I can not chat! I've tried disabling the liteloader chat mods to see if that would resolve the issue with no results.

**Comment by Dmitchell94** [comment]
solved by removing colorchat

**Comment by xJon** [comment]
👍
