### ISSUE TITLE
Mod updates

### ISSUE THREAD

**Issue by AntonioToni** [xJon/The-1.7.10-Pack#1318]
Any new updates for thaumcraft?

**Comment by xJon** [comment]
Thaumcraft didn't update for Minecraft 1.7.10.

**Comment by AntonioToni** [comment]
damn...

**Comment by Curunir** [comment]
There should be a "stupid question" label. You can track updates for most mods on Curseforge, and if you do, you will see that new versions for 1.7.10 mods are few and far in between now.
https://minecraft.curseforge.com/projects/thaumcraft/files
