### ISSUE TITLE
Help with a crash

### ISSUE THREAD

**Issue by Milmaxleo** [xJon/The-1.7.10-Pack#1319]
I am a bit new to this but I saw this link in the crash report, I don't know why I am crashing but maybe I can find some help here. I have tried reinstalling the pack, Java, Downgrading java, upgrading it but I can't get the pack to work. It will try to launch and get to the initialization screen but after that, it crashes. Here is a haste bin link to my crash report if anyone wants to try to make heads or tails of it
https://hastebin.com/eyuxiloloq.sql

**Comment by Milmaxleo** [comment]
Update: I tried a few different versions and the newest one (0.9.4) seems to give a different error again here is a haste bin link https://hastebin.com/ocigifakob.sql

**Comment by Curunir** [comment]
Well, both your reports have the same error, some Pneumaticraft thing going wrong. Is this happening right when you try to start the game, or when you try to enter a world? In the latter case, try with a fresh new world for comparison. If it's the former, perform a clean-sweep install:
- make a backup of your world, if it's stored locally
- uninstall the modpack
- find the modpack directory and delete all residue files in it
- reinstall the modpack from the launcher

Oh, and you might also disable anti-virus software or make an exception for Technic.

**Comment by xJon** [comment]
Closed due to inactivity.
