### ISSUE TITLE
Modpack Startup Time & Constant Lag

### ISSUE THREAD

**Issue by ToTheMax101** [xJon/The-1.7.10-Pack#1322]
Hi, I've played The 1.7.10 pack in the past and quite enjoyed it, but when my friends and I decided to redownload it and relive some old, fun memories, I soon discovered that my modpack had (and still has) an issue.

As you can tell by the topic name, my 1.7.10 pack is taking 25-30 minutes to start up and when it finally does, I'll get a constant 6-7 fps. In more demanding modpacks with even more mods (and the addition of shaders) it is no problem for me to run at 60 fps. I'd like to know what the problem is and if there is a possible solution.

I've allocated 5 gigabytes (out of my 12 installed) and the latest log is here
[techniclauncher_2017-01-17.txt](https://github.com/xJon/The-1.7.10-Pack/files/711949/techniclauncher_2017-01-17.txt)

Thanks, and I hope to be hearing from you soon,
Max

**Comment by ToTheMax101** [comment]
Also, I've tried reinstalling the 1.7.10 pack, the Technic Launcher itself, and Java (Of which I definitely have the latest version)

And none of this has worked.

**Comment by Curunir** [comment]
Check memory allocation and if you are using the latest Java. Test with a new singleplayer world for performance.
I can't see anything obviously wrong with that log.

**Comment by Teraku** [comment]
Could you post your system specs?

If you're on a laptop, you may have to go into your GPU driver settings, and make sure that the Technic Launcher and Java are set to run on your Dedicated GPU, rather than your integrated graphics.

Even if you're not on a laptop, set your Windows power plan to High Performance as well, see if that helps.

You could try allocating 4 GB instead of 5, that might alleviate your performance problems somewhat. Make sure you go to the game's video options, disable VSync, and set the frame limiter to "Unlimited". I've had similar problems when I left the frame limiter at 120.

**Comment by ToTheMax101** [comment]
I've definitely got the latest version of Java, and I've already tested with multiple single player worlds, and multiplayer worlds alike. They all run at a solid 6-7fps. 

Asus ROG Strix GL502
970m graphics card
12gb of installed ram

I'll try the dedicated GPU, and see if that fixes it. I've already set my windows to high performance, and I'll try allocating 4gb instead of 5, disabling VSync, and setting the frame limiter to unlimited. 

Thank you for responding so soon, but if none of this works, is there any way I could strip another modpack of mods and put the 1.7.10 pack's mods in?

**Comment by Curunir** [comment]
The pack should basically work, and at more than 6-7fps, too. Are you sure you don't have any resource packs and/or shader mods bogging you down?

**Comment by ToTheMax101** [comment]
I'm running Sphax's 1.7.10 textures, along with Sphax's 1.7.10 pack textures, but they've never been a problem in the past. I've tried running the game without textures, and still get 6-7fps. No shaders at all throughout.

**Comment by xJon** [comment]
Can you run other large modpacks with higher fps?

**Comment by ToTheMax101** [comment]
Yes. I've run up to 300+ mods before with above 40fps no problem

**Comment by xJon** [comment]
Is this still an issue?

**Comment by ToTheMax101** [comment]
Yes

**Comment by banshee599** [comment]
Try turning off anisotropic filtering.

**Comment by ToTheMax101** [comment]
Didn't work

**Comment by xJon** [comment]
Try to disable VSync and set Max FPS on unlimited.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
