### ISSUE TITLE
Server does not start up.

### ISSUE THREAD

**Issue by GaryWhopper** [xJon/The-1.7.10-Pack#1325]
I have not had this problem until now. It just randomly happened today even after about 3 days of the server being functional.

Log: http://pastebin.com/SpV0eu1V

**Comment by xJon** [comment]
Please post your **full** `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by eletronic007** [comment]
server down for maintenance help please!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
