### ISSUE TITLE
Server does not start up.

### ISSUE THREAD

**Issue by mrsomedude456** [xJon/The-1.7.10-Pack#1326]
Here is the fml-server-latest log: http://paste.ubuntu.com/23894292/

**Comment by mrsomedude456** [comment]
This is my first time launching the server btw.

**Comment by xJon** [comment]
Did you launch the server with the `LaunchServer.bat`?

**Comment by mrsomedude456** [comment]
Yes I did. Was I not supposed to do that?

**Comment by xJon** [comment]
You were supposed to do that, yes. Did you try to reinstall it?

**Comment by mrsomedude456** [comment]
I've tried reinstalling it multiple times but the same thing keeps happening.

**Comment by mrsomedude456** [comment]
I have fixed the problem. Turns out I just needed to agree with the EULA and it works fine. Thanks for the speedy replies though.

**Comment by xJon** [comment]
👍
