### ISSUE TITLE
Galaxy Space Mod suggestion

### ISSUE THREAD

**Issue by MaxiHuHe04** [xJon/The-1.7.10-Pack#1328]
## Galaxy Space is an addon for Galacticraft which adds many more planets and rockets
I think Galacticraft without Galaxy Space is not so funny because there are not so many planets

### [Download](https://minecraft.curseforge.com/projects/galaxy-space-addon-for-galacticraft-3)

**Comment by xJon** [comment]
Thank you for suggesting but currently we're not planning to add new mods.
