### ISSUE TITLE
server never starts up, please help <3

### ISSUE THREAD

**Issue by DanS189** [xJon/The-1.7.10-Pack#1329]
everytime i launch the batch file, it never loads up a server and always says at the end of the cmd "press any key to continue. any help would be greatly appreciated

my full log - http://pastebin.com/Hdzpi5vm

**Comment by Curunir** [comment]
> [16:44:35] [main/ERROR] [LaunchWrapper/]: Unable to launch
> java.lang.RuntimeException: Failed to read config from file .\config\OpenModsLibCore.json
That looks like something is preventing the server from accessing its own files. Disable anti-virus and try-again.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
