### ISSUE TITLE
Crashing when going into the nether (through nether portal)

### ISSUE THREAD

**Issue by TheChildd** [xJon/The-1.7.10-Pack#1330]
Hey, whenever i try to travel into the nether, the game loads for a bit then just crashes instantly. Nothing else seems wrong except for when going into the nether. After crashing from the nether portal, i am unable to re-log onto the same world (used a backup to test if the same thing happens). Thanks in advance. # #

**Comment by TheChildd** [comment]
[crash-2017-02-02_20.46.13-server.txt]

Update: Tried to log onto the world again, won't let me in. I'm guessing something thats loaded in the nether is crashing me somehow. before now, i used to be able to get into the nether though.

**Comment by xJon** [comment]
Delete the `hqm` folder inside your save folder to reset your corrupt questing data.

**Comment by TheChildd** [comment]
@xJon Hey, just to clarify, should the hqm folder be inside of the saves folder or the config folder? On mine, i couldn't find a hqm folder in the saves folder but i found one in my config folder.

**Comment by xJon** [comment]
Inside of the saves folder. Could be also named `HardcoreQuesting` or something similar.

**Comment by TheChildd** [comment]
http://paste.ubuntu.com/23919780/

**The link above is my latest latest.log**

Update: Deleted the HarcoreQuesting folder and i was able to log onto the world, however, when i went to check if i was able to go into the nether and got into the portal, it crashed me once more. Thanks for taking the time to help me here! @xJon

**Comment by Curunir** [comment]
If you have a new problem, then we need a new log. Could be an entirely different problem, or a sign that you have an erroring entity in your save.

**Comment by TheChildd** [comment]
http://paste.ubuntu.com/23979860/ 

Ok so i loaded up the world again and it didn't even let me in. i crashed while loading the world. Above is my Latest Crash Report from when i tried to access the world. hope that helps. if any other files are needed then you can just ask me. Thanks for helping.
