### ISSUE TITLE
Single player not working

### ISSUE THREAD

**Issue by Pcoshirey** [xJon/The-1.7.10-Pack#1331]
This pack works perfectly when im connected to any server. But whenever I try to start a single player world it shows the "downloading terrain" message and then Dcs. I've tried reinstalling, updating, etc. Also the problem is not my nvidia driver as I have already rolled it back. I have no idea how to read the log for you guys to see exactly what it is saying the problem is. But I have the recommended amount of RAM allocated (not too much either) and I have never had this problem before. I've played single player worlds on this modpack before (on older versions). Any help would be appreciated as I love this modpack and really do  not want to switch to another. 
Thanks.

**Comment by Curunir** [comment]
Singleplayer has somewhat higher requirements than running a multiplayer client, because you are effectively running your own server alongside the client. Make sure anti-virus software is not interfering with the game, and check if your system may be running out of diskspace. Other than that, you could try to reinstall the pack.

**Comment by Pcoshirey** [comment]
Thanks!!

**Comment by Pcoshirey** [comment]
I tried increasing ram and reinstalling the pack. It still doesnt work. I have no idea how to check if my antivirus is interfering with SP but i have played single player before (on previous versions of the modpack) and it worked just fine. I give up though I guess I am doomed to only playing on servers. :(

**Comment by Curunir** [comment]
If you are running an anti-virus tool, disable it or make an exception for Technic.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
