### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by anikopp** [xJon/The-1.7.10-Pack#1332]
Hello i created a server and i played on for a long time but then after like 4-5 days an error appired failed to bind port i went so my firewall and gain all acces to java but now thi crash report appers and i don't anderstand what i need to do plese help and thank you.
[crash-2017-02-04_12.22.04-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/752234/crash-2017-02-04_12.22.04-server.txt)

**Comment by anikopp** [comment]
Guys i fixit i don't need help anymore

**Comment by xJon** [comment]
👍
