### ISSUE TITLE
Unable to access jarfile Forge

### ISSUE THREAD

**Issue by Vranto** [xJon/The-1.7.10-Pack#1335]
Hi, 
I'm running Mac OS X 10.12 and I'm trying to set up a server. The only changes I've made to the 0.9.4 server download are the name of the folder, saving LaunchServer.sh as LaunchServer.command and giving it 5 GB, and running minecraft_server.1.7.10.jar once so I could change the EULA to true. [This](http://pastebin.com/qhftmCDH) is what's in LaunchServer.command. I also gave LaunchServer.command run permissions with chmod a+x in Terminal. When I run LaunchServer.command, it opens a terminal window which outputs [this](http://pastebin.com/unKwY52G). [This](http://pastebin.com/HSueMeqp) is my only log, since the server hasn't actually set itself up yet. [These](http://imgur.com/a/VCMIv) are all the files in the folder. This is my second reinstall of the server download, but on the first one, running the server jar did open a joinable server that didn't have the mods, exactly like in [this](https://github.com/xJon/The-1.7.10-Pack/issues/1036) issue. On the first install, I also tried replacing the forge jar with the one from Forge's website, as well as putting the entire filepath of the forge jar in LaunchServer.command, but it didn't change anything. Does anybody know how to fix this? 
Thanks!

**Comment by Curunir** [comment]
This might be a case of missing permissions, or the script looking in the wrong directory for some reason. I cannot support Macs, on account of never even having been close to one. The only thing I can think of that you are maybe trying to run this from a directory that needs extra privileges, or is generally not meant for this kind of application. When you manage to start a server without mods, you bypassed the entire modpack and are just running the included vanilla Minecraft server (which needs to be there for the modpack, but is not meant to be run directly).
Maybe retry this in a directory within your userspace, or re-download the server package in case something got corrupted.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
