### ISSUE TITLE
SP not opening

### ISSUE THREAD

**Issue by Magirus-Deutz** [xJon/The-1.7.10-Pack#1336]
it's loading building terrain and crashing. Please help!
http://paste.ubuntu.com/23948473/

**Comment by Curunir** [comment]
It looks like some item from Modular Powersuits is erroring out. If you placed anything from that mod, you can either open the worldsave in an editor (like MCEdit) and remove that item, or set this in /config/forge.cfg:
B:removeErroringEntities=true

This will tell Forge to delete anything that causes errors from the worldsave on load. If this resolves it, change that setting back to false.

**Comment by xJon** [comment]
Closed due to inactivity. Will reopen if required.
