### ISSUE TITLE
One Player Cannot Connect to Custom Server

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [xJon/The-1.7.10-Pack#1338]
I created a custom server for this modpack, and I added Iguana's Tinker Tweaks. This is the only extra mod I added, and two of my friends can connect using it just fine (I sent them a direct link to download the exact version of the mod I have). However, when my one friend tries to join, the server rejects his copy of this mod, even though it is exactly the same version the server is running. Help is appreciated.

**Comment by Curunir** [comment]
It is likely that the download got corrupted for that player. Tell them to disable anti-virus software and try again. Other than that, this cannot be solved without logs.

**Comment by xJon** [comment]
Just make sure the clients fit the modified server. I can't provide further support with additional mods.
