### ISSUE TITLE
Can´t start Modpack

### ISSUE THREAD

**Issue by Hassoa** [xJon/The-1.7.10-Pack#1340]
I cant start the pack. When i press play this appears in the console: 

[B#349] Analytics Response [runModpack]: 200
[B#349]  [17:13:26] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[B#349]  [17:13:26] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[B#349]  [17:13:26] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[B#349]  [17:13:26] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[B#349]  [17:13:26] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_121, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_121
[B#349]  [17:13:26] [main/INFO] [FML]: [AppEng] Core Init
[B#349]  [17:13:26] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#349]  [17:13:26] [main/WARN] [FML]: The coremod cartfixes.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#349]  [17:13:27] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#349] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1472599742, with 3 tries remaining

PS: Nice Pack

**Comment by Curunir** [comment]
That log fragment doesn't show anything. Check if this applies to you: https://www.reddit.com/r/feedthebeast/comments/5pydv9/dont_install_nvidia_gpu_driver_version_37849_it/

**Comment by xJon** [comment]
Closed due to inactivity. Will reopen if required.
