### ISSUE TITLE
Pack won't open

### ISSUE THREAD

**Issue by ArielZ2** [xJon/The-1.7.10-Pack#1342]
Whenever I click play it loads the modpack, all looks fine but when it closes the launcher, to open the game it just reopens the launcher.
Please answer ASAP

**Comment by Curunir** [comment]
Check if this applies: https://www.reddit.com/r/feedthebeast/comments/5pydv9/dont_install_nvidia_gpu_driver_version_37849_it/

**Comment by xJon** [comment]
Closed due to inactivity.
