### ISSUE TITLE
Server Failed to Start

### ISSUE THREAD

**Issue by nushibo** [xJon/The-1.7.10-Pack#1344]
Server has been running smoothly for days until a few days ago. This is one of the first crashes and just wanted some help. Currently running version .95 Tried rolling back but still the same fate

Specs Server Side
OS: Unbuntu 16.04
Mod Build: .95
8 GB of Ram: 5 Dedicated
GPU: 4670

Client Side: Technic Launcher
All requirements exceeded.
@
http://paste.ubuntu.com/24034720/ #

**Comment by Curunir** [comment]
It says it's running out of memory, more specifically out of heap space. Try assigning more RAM and see if that helps.
Other than that, you can try and temporarily have it create a new world to see how that works. Just change the world name to something else in server.properties and change it back later.
How many players are on that server usually?

**Comment by nushibo** [comment]
Alright will drop a little bit extra ram to see if that helps. Usually between 6-7, 10 max at one time and available slots 15. 

Server specs to be exact are a 
Pentium G3258
8GB of Ram
128GBs Radeon SSD
Gigabit LAN

Managed to get the dimensions and such restored. So we're back in business just going to load up an extra gig to allieviate then.

**Comment by xJon** [comment]
👍
