### ISSUE TITLE
A fatal error has occured, this connection is terminated

### ISSUE THREAD

**Issue by Willy244** [xJon/The-1.7.10-Pack#1346]
I've been trying to get this mod to work for me for some time now and it's really been hard. Here's the error message I get (http://prntscr.com/ecjbi4) and my log (http://pastebin.com/c0b9fTU3). So basically what happens is that when I try creating or joining a Singleplayer world or a Server I am able to load in (I even get the "You've been installed" achievement) and then suddenly the window closes and that warning I posted above appears. Sometimes I am able to load and see this screen (http://prntscr.com/ecjeqj) but if I click on one of the option or close the menu to play the game, it shuts down again and I see that warning again, which sends be back to the main screen.

I have double checked my Java settings to make sure I have an updated version and allowed a 4G for the mod to run. I have also tried completely reinstalling the modpack with my anti-virus temporarily disabled, but still no change. The only thing I found on forums throughout the Internet was something about NEI plugins that may need to be removed. I even tried removing the NEI mods and nothing happened. I have pretty much tried everything at this point and really know what to do to be able to play this modpack.

**Comment by xJon** [comment]
Please post your *full* `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by NetGearM** [comment]
I have the same problem, what do I do?

**Comment by Curunir** [comment]
Upload or share your fml-client-latest.log, like Jon keeps asking everybody to.

**Comment by Curunir** [comment]
Issue owner seems to have lost interest in this.
