### ISSUE TITLE
ProjectE mod

### ISSUE THREAD

**Issue by S1mps0n** [xJon/The-1.7.10-Pack#1347]
I would like you to add this mod because it has one of my favourite items , collector and energy condenser (ranks : mk1,mk2,mk3)
You put item in energy condenser and energy collector near it , collector uses Suns energy and energy condenser duplicates that item . Item is from nature like ore,wood,block. It can't duplicate machines or some more  (too) complex things. Sorry I know someone made same suggestion before , I didn't see it before I wrote it.

**Comment by Curunir** [comment]
Unless you can convince Jon, no new mods will be added to The 1.7.10 Pack any more.

**Comment by xJon** [comment]
Thank you for suggesting but currently we're not planning to add new mods as Curunir said.
