### ISSUE TITLE
Fatal Error Occurred

### ISSUE THREAD

**Issue by IsraelDesu** [xJon/The-1.7.10-Pack#1348]
I recently downloaded 1.7.10 pack, and then i've got the Fatal Error
log right here: http://pastebin.com/CfH2qi1T

**Comment by xJon** [comment]
Please post your *full* `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by DarumanKek** [comment]
i have same issue so i assue same log ? who knows anyway here is mine please help me fast i bought a server before trying the pack.. (im on 0.8.5 of your pack (cant update ))´
http://paste.ubuntu.com/24098214/

**Comment by DarumanKek** [comment]
litle update .. it was happening on 0.8.5 so i tryed latest versions where this happens aswell

**Comment by Curunir** [comment]
Not a clearly-defined issue, no valid data. Open a new ticket with a proper description and logs if you really want help.
