### ISSUE TITLE
Problem Entering MultPlayer (Connection Lost A fatal error has occurred, this connection is terminated)

### ISSUE THREAD

**Issue by KidPerneta** [xJon/The-1.7.10-Pack#1350]
My friend can't join my game, because everytime that he tries to join in my game or create a new world appears that Connection Lost A fatal error has occurred, this connection is terminated)

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Curunir** [comment]
Issue owner seems to have lost interest in this.
