### ISSUE TITLE
problem loading the mod pack

### ISSUE THREAD

**Issue by spitzie** [xJon/The-1.7.10-Pack#1351]
[2017-03-05_18.49.15.zip](https://github.com/xJon/The-1.7.10-Pack/files/819589/2017-03-05_18.49.15.zip)

[2017-03-05-5.log.gz](https://github.com/xJon/The-1.7.10-Pack/files/819591/2017-03-05-5.log.gz)
[DxDiag.txt](https://github.com/xJon/The-1.7.10-Pack/files/819592/DxDiag.txt)
 i am having this problem when i am loading the pack it stops when initalising and doesn't go further
i don't use optifine.
this problem started when i update my windows two days ago.
how can i fix this problem

**Comment by Curunir** [comment]
Looks like you are already using the nvidia hotfix driver that fixed the startup issue. Can you switch to Intel graphics anyway and see if the problem remains the same when using that? I do hope the drivers allow you that kind of switching on your machine.

**Comment by spitzie** [comment]
http://paste.ubuntu.com/24119965/plain/
i think this is how it works this is the fml-client-latest.log

**Comment by spitzie** [comment]
i solved it with downgading windows 10 to windows 8.1 other reasons for dowing this than only modpack
