### ISSUE TITLE
The Game Won't Start with Sphax BDcraft Resource Pack

### ISSUE THREAD

**Issue by TrolledUsoO** [xJon/The-1.7.10-Pack#1355]
I've started a world about 2 weeks ago with just the base minecraft texture pack. But I really hate playing minecraft without any resourcepack so I decided to download the Sphax 1.7.10 patch and the base Sphax resource pack (in the .zip format of course). I did all the steps needed to get the Sphax pack to work for this modpack: Open up both the patch and base Sphax, highlight stuff in patch and extract to base, extract with "Add and Replace Files," move the new Sphax to resource pack in the folder that opens in game. Whenever I open up the game, the program gets to the "initializing" stage in opening up the game and then just closes and returns to the Technic Launcher after like 10 minutes of a frozen screen. 

Its really frustrating after redoing the steps again and again to no avail. (normal minecraft looks really ugly to me) Some one please help.

**Comment by xJon** [comment]
Try to use the x64 or x32 versions.
