### ISSUE TITLE
Mod suggestion 

### ISSUE THREAD

**Issue by nukacola99** [xJon/The-1.7.10-Pack#1356]
Immersive Engineering is a great mod with technology, it's professionally made, and adds a lot to the game.

Immersive Engineering wires can also accept IndustrialCraft 2's Energy Units (EU), converting them into Redstone Flux for transport. They can also convert RF into EU on output, allowing EU-powered machines to be powered with RF. So it is very compatible.

**Comment by ramorga** [comment]
Mekanism has universal cables that are pretty cheap and are lossless, unlike immersive engineering cables. Plus, they have a much higher transfer rate

**Comment by xJon** [comment]
:arrow_up: 
We're not planning on adding Immersive Engineering anytime soon.
