### ISSUE TITLE
issue : can't craft gravity suit

### ISSUE THREAD

**Issue by onkha** [xJon/The-1.7.10-Pack#1358]
(hope this is not duplicate of an other post.)

hi.
First of all thx for this pack I really do enjoy.

I am having touble crafting Gravity suit stuff.
For exemple the Advance electric jet pack 6634:27 from GraviSuit require an electric jetpack from IC2 with full durability 27/27 and I only can manage to get the durability to 26/27.
Then the item keep a damage value of 1. (4181:1 instead of just 4181)
I think that is why the craft doesn't work.

Am I missing a way to get it to full durability?

A similar issue seems to be known and a few options for fixing it are described in this link :
[http://forum.industrial-craft.net/index.php?page=Thread&threadID=11959]

I haven't tried them yet, but i feel like it would be nice for this great mod pack to intagrate a fix. ;)

Have a good day and thanks for all the fun I am having.
Onkha.

**Comment by xJon** [comment]
Hi, what version of the modpack are you using?

**Comment by onkha** [comment]
Hello Jon!
Thank for taking interested, i was using the 9.6 version.

I played on local server hosted by a friend on a local network.

Weird thing is that the craft did work on his client. So it obviously had
something to do with my client. I used Tehnic launcher on a Mac.

Anyway I saw that this problem was known on other mod pack but i invetigate
a little i conclude from the version of your pack that it should not be
happening.

Thanks again for coming back at me. Keep the great work on.

Take care.

PS : I you ever go for a 1.10 pack let me know ;)

2017-07-02 21:46 GMT+02:00 Jon <notifications@github.com>:

**Comment by xJon** [comment]
We fixed most of the GraviSuite mod issues back in version 0.8.4 by adding a fixing mod, so it should be fine. If it works for him, it should work for you as well. Do you have OP in the server?

**Comment by onkha** [comment]
server was just a shared local game on a local network. (using the open to
lane option) so i am not sure i was 'OP'. cheats where sometimes activated
when needed but i don't know if that has anything to do With player being
operator or not


2017-07-03 17:15 GMT+02:00 Jon <notifications@github.com>:

**Comment by xJon** [comment]
![screenshot_2](https://user-images.githubusercontent.com/8945347/36557768-de404c0e-1811-11e8-859d-4c715815a686.png)
![screenshot_1](https://user-images.githubusercontent.com/8945347/36557772-df9a4b54-1811-11e8-96fd-d53f672d31a0.png)
