### ISSUE TITLE
The game won't start with optifine!! (pack 0.9.6)

### ISSUE THREAD

**Issue by tyaghoty** [xJon/The-1.7.10-Pack#1359]
hi.
Thx for this pack I really do enjoy.
The game won't start with optifine.
Have a good day and thanks.

" Crash Report ;
---- Minecraft Crash Report ----
// You're mean.

Time: 02/04/17 15:30
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/TextureMap
	at fastcraft.Z.<clinit>(F:11)
	at fastcraft.ab.<clinit>(F:16125)
	at fastcraft.HC.j(F:70)
	at net.minecraft.client.renderer.texture.DynamicTexture.func_110564_a(DynamicTexture.java)
	at net.minecraft.client.renderer.texture.TextureUtil.<clinit>(TextureUtil.java:460)
	at net.minecraft.client.shader.Framebuffer.func_147605_b(Framebuffer.java:104)
	at net.minecraft.client.shader.Framebuffer.func_147613_a(Framebuffer.java:56)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:37)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.TextureMap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at fastcraft.Z.<clinit>(F:11)
	at fastcraft.ab.<clinit>(F:16125)
	at fastcraft.HC.j(F:70)
	at net.minecraft.client.renderer.texture.DynamicTexture.func_110564_a(DynamicTexture.java)
	at net.minecraft.client.renderer.texture.TextureUtil.<clinit>(TextureUtil.java:460)
	at net.minecraft.client.shader.Framebuffer.func_147605_b(Framebuffer.java:104)
	at net.minecraft.client.shader.Framebuffer.func_147613_a(Framebuffer.java:56)
	at net.minecraft.client.shader.Framebuffer.<init>(Framebuffer.java:37)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5129837544 bytes (4892 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	Mod Pack: ~~ERROR~~ NullPointerException: null
	LiteLoader Mods: ~~ERROR~~ NullPointerException: null
	LaunchWrapper: 64 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: cartfixes.asm.CartTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: atomicstryker.dynamiclights.common.DLTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: logisticspipes.asm.LogisticsClassTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: li.cil.oc.common.asm.ClassTransformer
          - Transformer: openeye.asm.MultiTransformer
          - Transformer: api.player.forge.PlayerAPITransformer
          - Transformer: api.player.forge.RenderPlayerAPITransformer
          - Transformer: stevesaddons.asm.StevesAddonsTransformer
          - Transformer: thaumicenergistics.fml.ASMTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: factorization.coremod.ASMTransformer
          - Transformer: chocohead.patcher.PatcherPlugin
          - Transformer: openmods.core.OpenModsClassTransformer
          - Transformer: openblocks.asm.OpenBlocksClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: aroma1997.core.coremod.asm.AromaAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: factorization.coremod.FzAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: logisticspipes.asm.LogisticsAccessTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleAccessTransformer
          - Transformer: stevesaddons.asm.StevesAddonsTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.darkhax.bookshelf.asm.BookshelfTransformerManager
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: com.olafski.fastleafdecay.FldTransformer
          - Transformer: chocohead.patcher.BinniePatcher
          - Transformer: com.enderio.core.common.transform.EnderCoreTransformer
          - Transformer: com.enderio.core.common.transform.EnderCoreTransformerClient
          - Transformer: fastcraft.J
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.thevoxelbox.voxelmenu.SlotTransformer
          - Transformer: com.thevoxelbox.common.TimeUpdateTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmenu.PanoramaTransformer
          - Transformer: com.thatapplefreak.voxelcam.VoxelCamTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: com.mamiyaotaru.chatbubbles.litemod.ChatBubblesTransformer
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms5120m -Xmx5120m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:MaxPermSize=256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4531, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4531
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 4 "

**Comment by ramorga** [comment]
This doesn't seem to be an issue with optifine itself. Do you have any texture packs installed?

**Comment by tyaghoty** [comment]
I don't have texture packs.

**Comment by tyaghoty** [comment]
I finally discover the issue, the optifine 1.7.10 HD U D7 is not compatible with that modpack.Thx for this modpack i really like it.

**Comment by xJon** [comment]
:+1:
