### ISSUE TITLE
Should I add Equivalent Exchange?

### ISSUE THREAD

**Issue by MrHAndHisForthReich** [xJon/The-1.7.10-Pack#1360]
I'm wondering if I should add the mod Equivalent Exchange 3, because i'm not sure if its gonna break the pack, and make it unresponsive. Because Minecraft is touchy like that.

**Comment by ramorga** [comment]
I didn't think EE3 was stable in 1.7; this might be worth some experimentation

**Comment by xJon** [comment]
You can try if you want :)
