### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by GeneticCyber** [xJon/The-1.7.10-Pack#1363]
Username: GeneticCyber Name: Chase

I havent played for a while and i missed the pack so i wanted to get on the raiding server with all the items and wanted to have a shit load of fun like old times but every time i try to connect to the server i crash i mean i know how to fix this just erase my player data in the server files or whatever i honestly dont care about what i had just want to be able to play again

**Comment by xJon** [comment]
The server is not under our support, and it is only recommended.
Please contact its authors directly.
