### ISSUE TITLE
World will not load

### ISSUE THREAD

**Issue by Dominik1345** [xJon/The-1.7.10-Pack#1364]
I am trying to load my SP-world and afte some seconds the game colse.
Can some one help me?
[crash-2017-04-13_11.07.38-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/919005/crash-2017-04-13_11.07.38-server.txt)

**Comment by ramorga** [comment]
What sort of machines did you have? From what I can tell, minefactory reloaded is not enabled/installed, and if you had any of those machines set up, that would be causing the issue. I would try repairing your install by reselecting your current version in the installer settings (the gear in the upper right corner). Don't delete your install without backing up your world!

**Comment by xJon** [comment]
Is this still an issue?

**Comment by nuttapillar** [comment]
I've been having a similar issue, but my crash log file is slightly different.
**OP has this error**: 

EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.10 from Mekanism-1.7.10-9.1.1-clienthax.jar).

**While I have this error**:  EnderIO: Found the following problem(s) with your installation:
[B#349] 
2017/09/11 22:11:56 [INFO]                    * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
[B#349] 
2017/09/11 22:11:56 [INFO]                      Ender IO was build against API version rv2 and may or may not work with a newer version.
[B#349] 
2017/09/11 22:11:56 [INFO]                    * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from Flans Mod-1.7.10-4.10.0.jar).
[B#349]

**Comment by xJon** [comment]
I doubt that this is the issue, as this can be found in many logs that have no issues.
Can you provide the entire log @nuttapillar?

**Comment by nuttapillar** [comment]
[fml-client-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/1731930/fml-client-latest.log)
[latest.log](https://github.com/xJon/The-1.7.10-Pack/files/1731931/latest.log)
[crash-2018-02-17_02.32.58-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/1731932/crash-2018-02-17_02.32.58-server.txt)
I'm not sure which log file is the most useful, so I uploaded 3 that I could find. I spoke to some other people about my issue, and they seem to think that my world may be corrupt. However I didn't end up learning how to fix a corrupt world.

**Comment by xJon** [comment]
Unfortunately this just looks like a corrupted save. Load a backup, there's nothing else I can suggest.
