### ISSUE TITLE
Thaumcraft crasher

### ISSUE THREAD

**Issue by LtBlackmist** [xJon/The-1.7.10-Pack#1366]
Whenever I look at the NEI inputs for thaumcraft's aspects game does a complete lag out and freezes, doesn't fully crash but becomes unplayable until reload as I can't get anything to work "controls or other recipes"
Does not change dependant on memory given,
Does not change on chunk load change
Help??

**Comment by LtBlackmist** [comment]
UPDATE: Was a resource pack issue "I use JSTR_Universal for 1.7 modded" just has an issue for some reason, works fine in vanilla

**Comment by xJon** [comment]
:+1:
