### ISSUE TITLE
Mod Suggestion: Power Converters

### ISSUE THREAD

**Issue by eddi2345** [xJon/The-1.7.10-Pack#1367]
Hey!

You should really add the "Power Converters 3" mod!
its pain if you cant convert eu to rj or any other energyforms.
https://mods.curse.com/mc-mods/minecraft/225064-power-converters3
I am using this Mod on my local server and its running fine :)

**Comment by ramorga** [comment]
Mekanism literally has universal cables that perform this function

**Comment by xJon** [comment]
:arrow_up:
