### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by CrippledJew** [xJon/The-1.7.10-Pack#1368]
Upon startup of the modpack forge will load the contents and the minecraft screen will open, however it will be black and then proceed to crash a few seconds after. I have tried updating/trying many versions of java, I have tried changing the amount of RAM even up to the point of allocating 10 gigs to no avail and deleting and reinstalling the modpack and the launcher.
This is the crash log : https://pastebin.com/LqqYWXyR
This is the latest log : https://pastebin.com/wTKuLL9G

**Comment by CrippledJew** [comment]
Please Help. I would like to play on my friends server.

**Comment by xJon** [comment]
Please try to reset OpenComputer's configs.

**Comment by xJon** [comment]
Closed due to inactivity.
