### ISSUE TITLE
 Crash (Exception preparing structure feature)

### ISSUE THREAD

**Issue by Excepto** [xJon/The-1.7.10-Pack#1369]
Loaded a world and then it crashed.
I'm playing with the normal pack + Ex nihilo installed.
[techniclauncher_2016-05-20.txt.txt](https://github.com/xJon/The-1.7.10-Pack/files/951676/techniclauncher_2016-05-20.txt.txt)

**Comment by xJon** [comment]
To delete the ticking block, use [NBTExplorer](https://www.youtube.com/watch?v=fWUUsdp3pJ8).
Please reply here for further help if required.
