### ISSUE TITLE
A fatal error has occured, this conection is terminated

### ISSUE THREAD

**Issue by Sashka25** [xJon/The-1.7.10-Pack#1374]
World loads, but in few seconds it says "A fatal error has occured, this conection is terminated"
here is my fml-client-latest.log in txt format
[fml-client-latest.txt](https://github.com/xJon/The-1.7.10-Pack/files/967455/fml-client-latest.txt)

**Comment by xJon** [comment]
Try to remove Morph temporarily and see if the issue persists.

**Comment by xJon** [comment]
Closed due to inactivity.
