### ISSUE TITLE
Modpack Loading Crash?

### ISSUE THREAD

**Issue by ConstructionArch** [xJon/The-1.7.10-Pack#1377]
So, when I launch the modpack the Technic Launcher Close's then it re-opens. 
I have tried to re-install the Modpack and the Technic Launcher still didn't work. I also updated my java and increased my RAM to 5. 

Please tell me what is wrong.

Pastebin: https://pastebin.com/bgddDUpX

That is my log file above.
Please, tell me what is wrong with my Technic Launcher and what is the fix.

Thank You.

**Comment by xJon** [comment]
Updating your graphic drivers should help. If the issue still persists please reply here again.
