### ISSUE TITLE
DefenseTech issue with hypersonics

### ISSUE THREAD

**Issue by AntonioToni** [xJon/The-1.7.10-Pack#1378]
So when hypersonic explosives explode they should work like sonics but bigger but instead they make the whole server time out for a couple of minutes and when server starts responding it's just like nothing happend only the high pitched wind sound can be heared. Hypersonics were working on the server about 6 months ago.
Sonic explosives work normally.

**Comment by Curunir** [comment]
Then probably the server config changed. Ask the server admins for advice. DefenseTech is provided as-is, does not receive updates any longer and has not been changed since its inclusion.
