### ISSUE TITLE
ForgeModLoader state engine corrupted? Refuses to even launch Minecraft.

### ISSUE THREAD

**Issue by Pixelstormer** [xJon/The-1.7.10-Pack#1379]
I have a major issue which means that I can no longer even launch the modpack. It occured when I attempted to load a single-player world shortly after leaving a multiplayer server. It refused to load the world, and when I tried again on a different singleplayer world, it refused again, kicking me out to the main menu both times.
When I closed Minecraft and attempted to relaunch it, it refused to launch Minecraft.
The first singleplayer world I attempted to launch was a superflat world I had created after struggling with a certain mod that automatically sets all worlds to the default terrain generation The second one was a normal world with normal terrain generation.
I do not know which log(s) will be needed, and my information is from the Technic Launcher Console, not the logs saved in .technic/modpacks/the-1.7.10-pack/logs. I looked through the console log, and found some messages which appeared to suggest the ForgeModLoader had become corrupted, which I suspect is the cause of the issue.

Edit: I am currently reinstalling the modpack, I will provide an update once it has reinstalled.
Edit 2: It appears that reinstalling the modpack has fixed the issue. I am able to play normal, superflat and multiplayer worlds without issues.

'fml-client-latest.log': http://paste.ubuntu.com/24538346/

**Comment by xJon** [comment]
:+1:
