### ISSUE TITLE
Game not Starting, please help

### ISSUE THREAD

**Issue by Katatsu** [xJon/The-1.7.10-Pack#1380]
When I open the modpack it opens but it eventually closes then simply.
I have assigned the game enough Ram and the latest version of Java. Have the game re-installs as well as jave nothing helped.

https://pastebin.com/DTgaMvmk

**Comment by xJon** [comment]
Try to remove the Factorization mod, start your world and then re-add it. It'll reset all of the Factorization blocks (and errors) in your world. If the issue still persists, please post here again.
