### ISSUE TITLE
Twilight Forest and Mobs

### ISSUE THREAD

**Issue by Aurelium161** [xJon/The-1.7.10-Pack#1381]
So, you know that Twilight Forest mod? And how it's supposed to be unique mobs?

I encountered a bit of a bug.

The blue slimes from Tinker's Construct and the Basalz from Thermal Expansion spawn friggin everywhere in huge numbers - numbers large enough to prevent the natural spawning of normal mobs. I have attached screenshots of three Twilight Forest Dungeons of varying size and difficulty: - A large hollow hill, an ice castle, and a hydra lair. 

The hollow hill had first had huge basalz numbers when I first found it - enough to make it impossible to loot without the aid of a digital miner. When I returned, however, it was filled with blue slimes.

The Hydra Lair had a hydra that was constantly killing the immense basalz numbers. I had finished the hydra off (it sees through the morph and hydras hurt) only to be constantly battered by basalz (which also see through morphs). Worse part about them is the weakness effect, which makes them hard to kill when there's sixty of the things shooting at you.

I had used my pretty little wisp morph to get to the top of the ice queen tower to off the boss in a quick go, but even then on the way down I had noticed that, on my minimap, there were a ton of basalz and none of the mobs supposed to be unique to the ice tower.

Is it at all possible to turn down their spawn rates drastically? Not completely eliminate them but at least calm them down? 
![2017-05-10_21 07 17](https://cloud.githubusercontent.com/assets/28613140/25927882/fbdb2c30-35c6-11e7-8ac8-dd294804dc0c.png)
![2017-05-10_21 08 12](https://cloud.githubusercontent.com/assets/28613140/25927883/fbdd4bdc-35c6-11e7-829f-6cd691d1bc11.png)
![2017-05-10_21 10 04](https://cloud.githubusercontent.com/assets/28613140/25927884/fbdd62ca-35c6-11e7-89c7-f60cdbc40a09.png)

**Comment by Curunir** [comment]
I do not think that investigation will ever happen. Twilight Forest is a bug hell, and it doesn't help that BoP is the default worldgen in The 1.7.10 Pack. Sorry, this is the state of affairs. Consider it a challenge.
