### ISSUE TITLE
Mod Suggestion

### ISSUE THREAD

**Issue by spitfire1824** [xJon/The-1.7.10-Pack#1382]
Hello Jon,
                I am submitting a request or more a suggestion that you consider adding this mod I found, a galacticraft add-on. I ask because I love Galacticraft but once I have done all there is, thats it. nothing else to do, and yes, you may say "go find another pack with that mod" which is fair enough, but I dont want to do that, becuase this pack has literally every mod I love in it, and more! so there is always something to do, but when I found this mod (I will link it below) I thought "oooh, that looks really cool", so I started looking into making my own modpack similar to this one, but I couldnt figure out for the life of me how to get that to work, and I already have a nice little server with my friends going on your modpack. So I am asking you to please consider it, I know its a long shot that this will be put in, but I thought it may be worth asking. :) thanks anyway

Mod Link: https://mods.curse.com/mc-mods/minecraft/238770-galaxy-space-addon-for-galacticraft-3

Lincoln.

**Comment by luigimike** [comment]
My name is mike, and I stand by this mans side while I **agree** with him.

**Comment by Curunir** [comment]
With the inclusion of ExtraPlanets in 0.9.7, the boat is full where Galacticraft add-ons are concerned. The pack generally is closed to new additions, because 1.7.10 is dead as a doornail. Move on, nothing to see here.
