### ISSUE TITLE
Mystcraft crash

### ISSUE THREAD

**Issue by thestrategist97** [xJon/The-1.7.10-Pack#1383]
I just decided to try getting into Mystcraft stuff in my single player world, and ran into a problem with the writing desk. Whenever I right click on it, the game crashes.

The following is the crash report
[crash-2017-05-18_21.18.41-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/1012876/crash-2017-05-18_21.18.41-server.txt)

**Comment by zmutchler** [comment]
Not sure if this matters but I run a personal server and it also happens on there.  but it only crashes the client not the server.

**Comment by xJon** [comment]
Will be fixed in the next version of the modpack, that contains the new version of Mystcraft, with the fix for the issue.
