### ISSUE TITLE
Ender Pearl + Witchery BUG

### ISSUE THREAD

**Issue by adamj0805** [xJon/The-1.7.10-Pack#1385]
Ender pearl is currently not being accepted by cauldron, reason unknown. Hoping this is a fixable bug - I can throw just about any other item at the cauldron and it will be accepted but the Ender Pearl just sits on top when thrown at it.

**Comment by adamj0805** [comment]
This obviously prevents me from being able to create Otherwhere Chalk.

**Comment by Curunir** [comment]
This sounds like a mod bug. Only the mod developer can fix this, and mod developers have generally stopped fixing bugs for 1.7.10 versions. Try them, if you still have hope.
