### ISSUE TITLE
Mod Sugestion

### ISSUE THREAD

**Issue by Gilfir** [xJon/The-1.7.10-Pack#1386]
hello i would like to suggest the addition of the mod Extra TiC 

i would like it because it adds integration for a long list of mods as well as adding 2 new alloys witch are fairy and pokefenium.

the mods it curently adds intergration for the following mods:
Metallurgy, Natura, Mekanism, Applied Energistics, Biomes O’ Plenty, Tinkers’ Steelworks, Botania, Simpleores, Twilight forest, Thaumcraft, EnderIO, Better Storage, RotaryCraft, Gany’s End, Draconic Evolution, Big Reactors, Extra Utils, HarvestCraft, Progressive Automation, Thermal Expansion, Nevermine 2: Advent of Ascension (AoA), Immersive Engineering.

plesse use this link if you decide to download it http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445212-extratic-tinkers-construct-mod-support-add-on

**Comment by Curunir** [comment]
Jon is still taking suggestions, but has no intention to consider any of them, because he is a dick. Sorry, pal.

**Comment by Gilfir** [comment]
thankyou for your time
