### ISSUE TITLE
Uncrafting Diamond Sword

### ISSUE THREAD

**Issue by zmutchler** [xJon/The-1.7.10-Pack#1389]
Not sure if this is a Twilight Forest bug or just The Modpack but when you uncraft a diamond sword you get Wither Diamonds instead of normal Diamonds.  It doesn't happen with anything else that I have noticed just the sword.  I have got this to happen on both a single player world and a personal server.

**Comment by Curunir** [comment]
The Uncrafting Table is a bug hell that you should not use at all. Do so at your own peril. We cannot fix this except by removing Twilight Forest entirely.
