### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by DarkDann** [xJon/The-1.7.10-Pack#1390]
So, i'm creating a private server for a few friends using Hamachi, the problem is blocks and items are loading in but when I go to spawn them in it says for example "There is no such item with ID1532". I don't know why it does this and i don't know how to fix it.

**Comment by zmutchler** [comment]
Did you make sure everyone is using the same version?  I run my onw private server just downloaded again bout a week and we haven't had a problem.  Also are you using the recommended build or the latest?

**Comment by DarkDann** [comment]
Turns out I was only launching the vanilla minecraft server and not the forge. Oops, simple mistake, haha

**Comment by xJon** [comment]
:)
