### ISSUE TITLE
Crashing when opening inventory

### ISSUE THREAD

**Issue by TheGSoul** [xJon/The-1.7.10-Pack#1392]
I was playing on a LAN server with a friend for a while. I took a break for a bit, and logged on again. However, whenever I tried to open my inventory, the entire game just crashed. Is it something I may have accidentally done?
[crash-2017-06-06_14.04.34-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/1056138/crash-2017-06-06_14.04.34-client.txt)

**Comment by xJon** [comment]
The modpack does not support LAN worlds, nor does any other modpack.
Modded LAN worlds aren't a good thing.
