### ISSUE TITLE
Mod suggestion: Iguanas Tinker Tweaks

### ISSUE THREAD

**Issue by tigartar** [xJon/The-1.7.10-Pack#1393]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2176855-iguanas-tinker-tweaks

i think it would actually add some nice things that would fit with the mod pack

**Comment by Curunir** [comment]
While Jon is still taking suggestions, he has no intention to consider any of them, because he is a dick. Move on, nothing to see here.
