### ISSUE TITLE
Error when opening pack.

### ISSUE THREAD

**Issue by LuisPM77** [xJon/The-1.7.10-Pack#1395]
![ogh](https://user-images.githubusercontent.com/29415707/27109382-72eebb7a-5070-11e7-832a-002a5dad419d.PNG)

I get this error when I try playing the pack and I tried downloading from the link but it doesn't work. Also, my wifi works and hasn't had any issues. how do I fix this?

**Comment by Nightmare1447** [comment]
Mute the thread

**Comment by xJon** [comment]
Shouldn't be an issue now, but regardless, from version 0.9.7 the modpack will contain the Baubles library by default.
