### ISSUE TITLE
Won't Run

### ISSUE THREAD

**Issue by Ameno-Sagiri** [xJon/The-1.7.10-Pack#1402]
Upon launching the pack in the Technic Launcher, nothing happens. The Minecraft window doesn't even start. Play this occasionally with a group of friends and I've never had a problem with it before.

Launching client version
Java version 1.8.0_131 64-Bit, pack version 0.9.5 (Also tried 0.9.4 and 0.9.6)
100 Megabit upstream and downstream, solid connection
No Optifine unless it's included in the pack

i7-4770
12GB Ram (3.5GB allocated)
Windows 10 64-Bit
GTX 770 2GB

https://pastebin.com/LuzQaC6f

That's all that shows up in the console. I tried a fresh reinstall of everything, including Java, and I've also changed the installation directories and tried a portable installation.

**Comment by xJon** [comment]
Please post your *full* `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Ameno-Sagiri** [comment]
http://paste.ubuntu.com/25006667/

**Comment by xJon** [comment]
Is that the full log? If so, please give me your latest *technic* log, found in `.technic/logs/`.

**Comment by Ameno-Sagiri** [comment]
That was the Pastebin link in the OP
https://pastebin.com/LuzQaC6f
http://paste.ubuntu.com/25006881/

**Comment by xJon** [comment]
That makes no sense. Do other modpacks work? Did you try to reinstall the launcher?

**Comment by Ameno-Sagiri** [comment]
It just kind of pre-maturely ends without any real error, and the actual game window never even opens. I tested Vanilla Minecraft and Blightfall and they both run fine.

**Comment by Ameno-Sagiri** [comment]
Yes, I re-installed the launcher and also tried running as Administrator and compatibility modes just in case.

**Comment by Ameno-Sagiri** [comment]
[https://dl.dropboxusercontent.com/s/3b0t1f0opuf49p4/2017-07-02_16-56-35.mp4](url)
There's a recording of it in action.

**Comment by Ameno-Sagiri** [comment]
Alright well now none of the modpacks will launch so this isn't an issue related specifically to this pack. The Technic forums are swamped in threads of people also having this problem and none of their solutions are working. Closing?

**Comment by xJon** [comment]
Try to go to Technic's Discord server and ask there for help :)

**Comment by Ameno-Sagiri** [comment]
Issue was solved. My very specific nvidia driver version was incompatible with Minecraft versions under 1.11. I tried an update earlier but it only updated the nvidia client and didn't fetch a driver update so I had to manually get the newest version.

**Comment by xJon** [comment]
I'm glad!
