### ISSUE TITLE
Updating to 0.9.7

### ISSUE THREAD

**Issue by CitrusFruit** [xJon/The-1.7.10-Pack#1403]
I took the leap and updated to 0.9.7 and now my server will not start, it just freezes.

Error - https://pastebin.com/i79vvTYa

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by CitrusFruit** [comment]
Where can I find the fml-server-latest.log? I've literally been searching and cannot find it anywhere.

**Comment by CitrusFruit** [comment]
Nevermind, managed to solve it :)

**Comment by xJon** [comment]
👍
