### ISSUE TITLE
Game does not start

### ISSUE THREAD

**Issue by finiboy1993** [xJon/The-1.7.10-Pack#1405]
* The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.10 from Mekanism-1.7.10-9.1.1-clienthax.jar).

What is the fix? 

Thx

**Comment by xJon** [comment]
This is no bug nor any error. This is normal for modded Minecraft in modpacks.
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by finiboy1993** [comment]
http://paste.ubuntu.com/25038068/ 

Thx

**Comment by xJon** [comment]
Is that the full log? Can you write more about the problem?
Is there any error on the screen? Does the client launch? What does not start and when?

**Comment by finiboy1993** [comment]
Yes 

http://paste.ubuntu.com/25038138/ -> Crash report 

I start the pack with the launcher. It's working. and then it is quitting and go back to the launcher.

**Comment by xJon** [comment]
Try to reset OpenComputer's configuration files by deleting them, or reinstall the pack.

**Comment by Curunir** [comment]
Issue owner seems to have lost interest in this.
