### ISSUE TITLE
can not connect to the server that is pre-loaded in multiplayer 

### ISSUE THREAD

**Issue by timmetalgod** [xJon/The-1.7.10-Pack#1406]
tried again last night and this morning. says "Java.net.ConnectException: Connection refused

I reinstalled the .9.7 version several times now. 
My PC is 64 bit. i-7 with 16GB of ram
the sever is a .uk server and I'm in the California. don't know if that makes a difference. 
I am able to connect to most of the mod pack's servers with no problem. 

thanks
tim

**Comment by xJon** [comment]
You need to make sure that your client's version is the same as the server's version.
