### ISSUE TITLE
Can't Open Things...

### ISSUE THREAD

**Issue by BobSagettttt** [xJon/The-1.7.10-Pack#1408]
When making a new world I cannot open the quest book (though I can open the other two spawn books). I spawned in a fresh world with everything default exception being a bonus chest (which I could not open either). I even ended up breaking the chest and nothing was produced... so I really don't know the issue here. I'm coming up from 1.4.7 and I have never seen this issue in anything from back then -- closest being issues with Nvidia and their 3d priority options and mc not knowing the location of the mouse compared to blocks... but I broke the chest sooooo....

**Comment by xJon** [comment]
Are you on singleplayer?

**Comment by BobSagettttt** [comment]
Yes, I am on singleplayer.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
