### ISSUE TITLE
Very low FPS Issue - Please help.

### ISSUE THREAD

**Issue by jonesyboppa** [xJon/The-1.7.10-Pack#1413]
I can load the game, but as soon as I spawn into the world it gets extremely laggy on Singleplayer (I'm talking between 0-6fps). 

Even if I change my render distance from 1 chunk to 32 chunks, it doesn't make a difference, nor does OpenGL, nor does it affect my FPS if I change graphics from Fancy to Standard. 

Anyone know an Issue with this? I've tried re-installing, I've updated my drivers... what next? Any clues?

Hardware I'm running:
Windows 7 64bit
AMD FX 8350 Octacore
16GB Corsair Vengeance (2x8GB)
Nvidia GTX1060

**Comment by xJon** [comment]
Try to disable vSync and change the FPS limitation to unlimited.

**Comment by jonesyboppa** [comment]
Still exactly the same. Between 0-6fps, the only time it ever goes up to my normal FPS rate (60+) is when I'm on the menu... any other ideas?

**Comment by xJon** [comment]
Do you open other programs on your computer at the time? I have a GTX 670 which's a little old but with only Minecraft open I can get 60-120 FPS.

**Comment by jonesyboppa** [comment]
I do, the weird thing is I've tried and tested it with nothing (literally) running on my PC. It doesn't matter if I mess about with graphics settings or the resource packs, it still stays at 0-6fps. Strange thing is I can run FTB/Tekkit Legends/Tekkit Space/Tekkit Lite without a problem, this is the only modpack I've played which I've encountered this problem with

**Comment by xJon** [comment]
Are you sure that your computer is using your graphics card?

**Comment by jonesyboppa** [comment]
Yeah, I've checked while running other mod packs and it still uses the Graphics Card

**Comment by xJon** [comment]
Did you try to reinstall? Also if you want, you can try to add Optifine (only use version D6 out of the latest ones).

**Comment by jonesyboppa** [comment]
Also tried both of them, Re-installed like 6 times now, optifine doesn't even touch it

**Comment by Curunir** [comment]
Check your memory allocation. The 1.7.10 Pack needs 3.5GiB to run comfortably. Less will result in swap wars, which can lead to the situation you are describing.

**Comment by xJon** [comment]
Closed due to inactivity.
