### ISSUE TITLE
Mod Rejections - Please Help

### ISSUE THREAD

**Issue by TrixieTrix09** [xJon/The-1.7.10-Pack#1416]
Every time i try to join the main servers i use it says mod rejections and a huge list of mods, this was after the new update but it still happens when i use previous versions. Please help ?!?!?

**Comment by xJon** [comment]
You need to make sure that you're connecting to a server that's running The 1.7.10 Pack with the same version of your client.

**Comment by TrixieTrix09** [comment]
if not then what should i do and how do i find what version the server is running ???
