### ISSUE TITLE
File Dose Not Exist

### ISSUE THREAD

**Issue by LordAqua** [xJon/The-1.7.10-Pack#1418]
When I tried to update to the newest version (0.9.7) it comes up with this:

Error unzipping a file for the following pack: The 1.7.10 Pack

Attempting to extract file the-1710-pack-0.9.7.zip, but it did not exist

Please consult the modpack author.

**Comment by xJon** [comment]
Try to reinstall. If the issue persists, please reply here again.

**Comment by LordAqua** [comment]
Sorry about the late response, but reinstalling didn't help

**Comment by xJon** [comment]
Completely delete the pack from the launcher, and then search it and install it again.

**Comment by LordAqua** [comment]
Same thing happens

**Comment by LordAqua** [comment]
Can you maybe make an update to an older version of the pack temporarily, I haven't found any other pack that compares to this one.

**Comment by Curunir** [comment]
You likely have no access rights to the download space. Either because your Windows user profile is fubar, or because you are trying to install in a stupid place. Get your Windows sorted out and it will work. Or switch to Linux, which is superior anyway.

**Comment by LordAqua** [comment]
I literally did nothing and now I can download the pack. I'm kind of confused, but happy I can play the pack again.

**Comment by xJon** [comment]
Welp. 👍
