### ISSUE TITLE
Same issue with any modpack

### ISSUE THREAD

**Issue by SandMan4Real** [xJon/The-1.7.10-Pack#1420]
Hi i have recent problem with any modpack i download from Technic Plattform.

Please Help.

B#349] Analytics Response [runModpack]: 200
[B#349]  [19:02:57] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[B#349]  [19:02:57] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[B#349]  [19:02:57] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[B#349]  [19:02:57] [main/INFO] [FML]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[B#349]  [19:02:57] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_74, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_74
[B#349]  [19:02:57] [main/INFO] [FML]: [AppEng] Core Init
[B#349]  [19:02:57] [main/WARN] [FML]: The coremod aroma1997.core.coremod.CoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#349]  [19:02:57] [main/WARN] [FML]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#349]  [19:02:57] [main/WARN] [FML]: The coremod atomicstryker.dynamiclights.common.DLFMLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#349]  [19:02:57] [main/INFO] [FML]: Loading tweaker fastcraft.Tweaker from fastcraft-1.23-client.jar
[B#349]  [19:02:57] [main/INFO] [FML]: Loading tweaker forestry.shade.javacheck.Java7Checker from forestry_1.7.10-4.2.16.64.jar
[B#349]  [19:02:57] [main/WARN] [FML]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#349]  [19:02:57] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#349]  [19:02:57] [main/WARN] [FML]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#349]  [19:02:58] [main/INFO] [FML]: Loading tweaker com.mumfrey.liteloader.launch.LiteLoaderTweaker from liteloader-1.7.10-client.jar
[B#349]  [19:02:58] [main/WARN] [FML]: The coremod logisticspipes.asm.LogisticsPipesCoreLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#349]  [19:02:58] [main/WARN] [FML]: The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[B#349] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1499186920, with 3 tries remaining

**Comment by Curunir** [comment]
If all modpacks fail, ask the Technic guys for support. You are likely having anti-virus software interfering, or are suffering from having that ancient Java version (update 74, when the current one is 144). Java can be had here: https://www.java.com/en/download/manual.jsp
