### ISSUE TITLE
DefenceTech - Cruise launcher not craftable. 

### ISSUE THREAD

**Issue by ICallHax** [xJon/The-1.7.10-Pack#1424]
I recently tried crafting the cruise launcher from defence tech only to find that I can't. 

Basically the issue is that the crafting recipe contains a invisible item called error.name from the DefenceTech mod which you can find by hovering over the top left slot of the recipe for the cruise launcher. 

[http://imgur.com/a/HJzkI](url)

I am running the recommended version of the modpack 0.9.7.

**Comment by xJon** [comment]
Both the redmatter and the antimatter recepies are disabled in the config.
