### ISSUE TITLE
World missing?

### ISSUE THREAD

**Issue by AUraord** [xJon/The-1.7.10-Pack#1425]
im not sure what caused it but i was playing single player and I left the game for lunch. I closed out of minecraft completely before turning my pc off but when i logged back in my world wasnt there under my list of worlds i checked the folder for saved worlds and its there but it wont show up in game

**Comment by Curunir** [comment]
That means the game did not shut down properly and the world got corrupted. Restore from a recent backup, if possible. If not, this is the standard way to retrieve the world:

1. quit Minecraft
2. open your modpack folder (Technic Launcher can direct you), navigate to /saves
3. locate the directory that contains your world
4. move that directory to a safe backup location
5. start Minecraft (the modpack you were using, obviously)
6. create a new singleplayer world with the exact same name as the one you are trying to recover - any wrong letter, blank space or comma will defeat this, so be precise
7. after that world loaded and is confirmed working, quit Minecraft
8. copy your old worldsave (now in the safe backup location) over the newly-created world, overwriting all files when prompted
9. start Minecraft (the modpack you were using, obviously)
10. check if you can load your world now
