### ISSUE TITLE
Server cant setup

### ISSUE THREAD

**Issue by cshandsome** [xJon/The-1.7.10-Pack#1427]
I set all setting for server and at last I start the LaunchServer.bat. when the setup is finish,it told me press any keys to skip.If I skip the cmd will close.So I start it again and dont skip,but I cant join my sever.I can setup other modpacks server but only this modpack cant.So I need help here thx. Sorry for bad English

**Comment by xJon** [comment]
Make sure that `eula.txt` is set to true.
