### ISSUE TITLE
Creative Mode Crash

### ISSUE THREAD

**Issue by Lauschi** [xJon/The-1.7.10-Pack#1428]
I played in singelplayer in creative mode and every time i go in the third section layer in the creative menu it crahes. I'm from germany, sry for my english ^^

Crashreport:  https://pastebin.com/P7Bkfmjw

**Comment by Lauschi** [comment]
Her is the FML Client Log when this is needed:

[fml-client-latest.zip](https://github.com/xJon/The-1.7.10-Pack/files/1170630/fml-client-latest.zip)

**Comment by Curunir** [comment]
No logs needed. This is a known issue that cannot be fixed (because Mojang would have to fix it). Your workaround is using NEI also in Creative.
