### ISSUE TITLE
I havent been able to join the server for about an year

### ISSUE THREAD

**Issue by GeneticCyber** [xJon/The-1.7.10-Pack#1429]
Username: TasteyToons :I've done msged the face book discord and even the mod pack page and nothing can someone please help me i can't join the server every time i try to join the server i just crash and i just want to play on the server i enjoy it but i havent been able to login to it for the longest time heres my crash report http://haxys-hideout.enjin.com/forum/m/22374076/viewthread/29070751-cant-join-server-when-i-try-crash/page/1 please help me out

**Comment by Curunir** [comment]
There is no server. If you are having issues with a server run by other people, ask those other people.
