### ISSUE TITLE
Crash upon opening Creative Menu page 3

### ISSUE THREAD

**Issue by Prowler1000** [xJon/The-1.7.10-Pack#1432]
As the title says, I get a crash when opening the creative menus third page. The crash log doesn't name any specific mod though. Any help?

[2017-08-04-6.log.gz](https://github.com/xJon/The-1.7.10-Pack/files/1201430/2017-08-04-6.log.gz)

**Comment by Curunir** [comment]
Everybody is getting that crash. It is a known issue that cannot be fixed. Your workaround is using NEI also in Creative.
