### ISSUE TITLE
I can't even play the pack?

### ISSUE THREAD

**Issue by HexanovaLTD** [xJon/The-1.7.10-Pack#1435]
I've tried nearly everything that I could.
I've reinstalled Technic
I've reinstalled the pack
I've restarted my computer, made sure I have the latest version of java, tried multiple versions of the pack
I still get the same issue
Pack takes about 15 minutes to load up, and then I tab into it, then tab out, and this happens

![image](https://user-images.githubusercontent.com/30876846/29139719-be4132de-7cfc-11e7-9c3d-e466bf67a90c.png)

**Comment by HexanovaLTD** [comment]
UPDATE: Works until i minimize. Then the image above happens. Music will play as if it is still working.

**Comment by xJon** [comment]
Did you change any settings of the pack or the launcher?

**Comment by xJon** [comment]
Closed due to inactivity.
