### ISSUE TITLE
1.7.10 Pack crashing whenever I try to open chat. 

### ISSUE THREAD

**Issue by StarWarp** [xJon/The-1.7.10-Pack#1436]
#ive got a good PC that can run the pack with decent frames, but whenever I try to open the minecraft chat. it crashes. and was wondering if any of you guys knew why?

crash log :  #http://paste.ubuntu.com/25291654/
processor: Intel(R) Core(TM) i5-4210U CPU @ 1.70 GHZ 
installed RAM : 8gb
system type: 64x operator 64x processor
java: most recent version

the issue started today. I have no idea what caused it, and it happens to me on both SP and MP. but to no one else on the server. I am not using any other mods. and the pack is up to date

**Comment by xJon** [comment]
Try to remove the TabbyChat mod. Launch up the game and see if it works. If it does, try to re-add the mod back.

**Comment by xJon** [comment]
Closed due to inactivity.
