### ISSUE TITLE
Disabling specific mods

### ISSUE THREAD

**Issue by vortaqthemighty** [xJon/The-1.7.10-Pack#1439]
Hi, I run a server on my network with my kids. Mods like Blood Magic, Forbidden Magic and Necromancy are a little intense for them though. Is a way to remove them or prevent building the items for those mods? Initially, I tried renaming those three .jar files on both the server and client. The server would run normally but the client would crash on connect with a "Ticking screen" error. Things started working again when I disabled the Hardcore Questing Mod which included some Blood Magic specific quests. I tried using the instructions here https://ftb.gamepedia.com/Hardcore_Questing_Mode:_An_In-Depth_Guide to remove the Blood Magic quests but got the following crash report. 
[crash-2017-08-13_16.51.13-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/1226331/crash-2017-08-13_16.51.13-client.txt). Here's the modified quest file as well: [quests.zip](https://github.com/xJon/The-1.7.10-Pack/files/1226340/quests.zip). Any ideas of what I might have missed? Thanks for your help!

**Comment by xJon** [comment]
Did you update the modified quests and removed the mods in both client and server side?

**Comment by vortaqthemighty** [comment]
Quick update to keep this thread open, I made sure that Blood Magic was disabled and my client didn't crash but I wasn't able to join the server. Let me check my settings and I'll upload a crash report when I have the chance. Thanks!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if asked to.
