### ISSUE TITLE
Runnong the Server on Ubuntu 16.0.4

### ISSUE THREAD

**Issue by Groganj89** [xJon/The-1.7.10-Pack#1442]
[drive-download-20170819T124215Z-001.zip](https://github.com/xJon/The-1.7.10-Pack/files/1236348/drive-download-20170819T124215Z-001.zip)

Hi Guys

Having some issues loading the server on ubuntu 16.0.4. it goes through the process then fails towards the end. I have attached my log files in a zip if that would help. 

TIA

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
