### ISSUE TITLE
crash on creative menu page 3

### ISSUE THREAD

**Issue by Wizart1999** [xJon/The-1.7.10-Pack#1444]
everytime i start a new world all works untill i go into my creative inventory page 3. Even when im playing around placing some blocks all is just fine then you walkaround an bam game crashes and the world is unstartable.
[techniclauncher_2017-08-25.txt](https://github.com/xJon/The-1.7.10-Pack/files/1251919/techniclauncher_2017-08-25.txt)

**Comment by xJon** [comment]
https://github.com/xJon/The-1.7.10-Pack/issues/1432#issuecomment-320436769
🤷‍♂️
