### ISSUE TITLE
Can't connect to any servers

### ISSUE THREAD

**Issue by HarrietTubman20** [xJon/The-1.7.10-Pack#1445]
I have been having an issue for several days that is preventing me from connecting to any server at all. It is always the same error message: "java.net.ConnectException: Connection timed out: no further information:"

I can ping servers in the Command Prompt and get a perfectly normal response which implies that the issue is Minecraft, Technic, or Java, not the network.

I have tried just about everything I can think to do. I have tried restarting my computer, logging out and back in, letting Java through the firewall, disabling my firewall altogether, using different versions of Java, allocating more memory, using a VPN, brute forcing, unplugging the Ethernet cable and putting it back in, disabling my antivirus software, running as administrator, and reinstalling my modpack, but nothing has worked.

I'm all out of ideas.

**Comment by xJon** [comment]
Can you connect to Minecraft servers while playing Vanilla or other modpacks?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
