### ISSUE TITLE
Can't start a Server with this modpack

### ISSUE THREAD

**Issue by CreeperHD** [xJon/The-1.7.10-Pack#1446]
Hello, I have voher ready a server with this modapck then I wanted to update the server to the version 0.9.7 but when I now the server start dan crasht the server and does not load the map and the mods

Crash Report: http://paste.ubuntu.com/25452475/

**Comment by xJon** [comment]
You can try to open the world in an editor and remove the problematic Buildcraft block at 
> Location: World: (6,82,-139)

Or edit /config/forge.cfg to set
> B:removeErroringEntities=trueue

Or just remove the Buildcraft mod, enter your world and then re-add the mod back.

**Comment by CreeperHD** [comment]
You can try to open the world in an editor and remove the problematic Buildcraft block at

Block location: World: (-105,23,182)
Or edit /config/forge.cfg to set

B:removeErroringEntities=trueue
Or just remove the Buildcraft mod, enter your world and then re-add the mod back.


I tried everything they wrote but it still does not work and without the mod Buildcraft starts the server not at all

**Comment by xJon** [comment]
If you're running on a server you need to do all of these things on the server side.

**Comment by CreeperHD** [comment]
yes I have done all this on the server but it is still not and who I the Mod Buildcraft rausnehme starts the server not more because the mod is missing

**Comment by xJon** [comment]
Do that in both server and client side.

**Comment by CreeperHD** [comment]
ok I have made but the server still crashes from here the current crashlog: http://paste.ubuntu.com/25460531/

**Comment by xJon** [comment]
Try removing the Mekanism mod.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
