### ISSUE TITLE
Problem with the launch

### ISSUE THREAD

**Issue by Leozao21** [xJon/The-1.7.10-Pack#1448]
Hey, I've a friend that has the exact same computer as me,but I can perfectly enter in a minecraft server but he can't. His screen is always black and when He is able to enter a server he is lagging to hard ( He only enters the server past 3/4 tries ) ... We really need help because He has already dedicated 3.5 Ram in his technic launcher :c 
The thing is that I dont lag, he lags , same computer and in other games he has more FPS than me !
Thank you

**Comment by nuttapillar** [comment]
It's almost impossible that this would be a fix, but one thing that could make one computer lag more than another identical one could be the disk usage. Make sure none of the internal hard drives are close to full.

**Comment by xJon** [comment]
I'd make sure that his drivers are up to date, and that in the graphic settings VSync is turned off and Max FPS is unlimited.
