### ISSUE TITLE
Game crashing when loading my world.

### ISSUE THREAD

**Issue by nuttapillar** [xJon/The-1.7.10-Pack#1449]
I played this game for months in the same world. Then I took a break for a month or so, and now when I try to load my world, it just crashes.
I checked out the log, and found the problem area of the log: 
2017/09/11 22:11:56 [INFO]  	EnderIO: Found the following problem(s) with your installation:
[B#349] 
2017/09/11 22:11:56 [INFO]                    * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
[B#349] 
2017/09/11 22:11:56 [INFO]                      Ender IO was build against API version rv2 and may or may not work with a newer version.
[B#349] 
2017/09/11 22:11:56 [INFO]                    * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from Flans Mod-1.7.10-4.10.0.jar).
[B#349] 

I don't know why this has happened, as I have not even touched anything related to ender IO and AE2 lately. So I tried replacing the AE2 version with an older stable build, and I got an error saying I need a newer version. So I downloaded the stable RV4 version, and with that, the game won't even launch. The launcher says it's downloading some stuff down the bottom, but then that finishes, and the game doesn't launch.

Interestingly I'm able to load into other worlds fine, so there is something wrong in my main survival world.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
