### ISSUE TITLE
Crashing while playing on a server

### ISSUE THREAD

**Issue by Menon836** [xJon/The-1.7.10-Pack#1450]
Edit: I removed a Magic mirror from thaumcraft and the crashing stopped, not sure if that was the problem or not.

Almost anywhere if fine but where me and my friend have set up our thaumcraft stuff I crash whenever I go down there. The only mod I have added is "tcinventoryscan-mc1.7.10-1.0.11.jar"(https://mods.curse.com/mc-mods/minecraft/238003-thaumcraft-inventory-scanning#t1:other-downloads).

This just started with about maybe a month playing with this pack and on the server.

http://paste.ubuntu.com/25518085/

**Comment by xJon** [comment]
Glad you managed to fix it :)
