### ISSUE TITLE
1.7.10 sphax pureBD patch issue

### ISSUE THREAD

**Issue by nyvric** [xJon/The-1.7.10-Pack#1451]
When I add the patch my game lags severely, removing the patch with just the 64x texture pack alone it runs great. However on my desktop both run fine. My laptop is extremely powerful and I haven't been able to find a reason why the patch causes lag on one system but not the other. Any suggestions?

**Comment by xJon** [comment]
How much RAM are you allocating to the pack?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
