### ISSUE TITLE
cant craft with normal wood planks

### ISSUE THREAD

**Issue by rpropp12** [xJon/The-1.7.10-Pack#1452]
so me and my friend where playing and out of no where we could not craft with the normal wood planks it just says burn time need help please

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).
I'll open the issue with the required information.

**Comment by BugReportThrowaway** [comment]
https://paste.ubuntu.com/p/9MrH8QFc7M/

I saw the same issue, seems like recipes for certain planks are broken. Cannot use acacia or oak wood planks to craft anything, such as sticks, chests, crafting tables, etc.

**Comment by xJon** [comment]
@BugReportThrowaway Just confirming - are you using the latest version of the modpack?

**Comment by BugReportThrowaway** [comment]
Hey, sorry for the delay.

So I was, but reinstalling Java fixed the issue. I believe I saw a thread about having non-64 bit Java being correlated with the issue.

**Comment by xJon** [comment]
👍
