### ISSUE TITLE
Teleportation Help

### ISSUE THREAD

**Issue by Ansvar** [xJon/The-1.7.10-Pack#1454]
Hello,
     A friend and I were playing on a raiding server running the 1.7.10 modpack and were raided due to some teleportation trick. Unfortunately someone told me that they can still teleport to us even after death meaning we can't play until we figure this out. There were no witchery taglocks involved. Is there anything specifically related to Thaumcraft or a different mod that allows teleporting to a parasite on a player after attaching the parasite to them? We are at a loss because the only item named parasite in the game is the parasitic louse, which I am pretty sure doesn't function in this manner. Any help would be greatly appreciated. Thank you.

**Comment by xJon** [comment]
If you need support in the HaxysHideout server - please go to (their forums)[https://forums.haxyshideout.co.uk/].
