### ISSUE TITLE
Universal cables not transferring power

### ISSUE THREAD

**Issue by bendertherobo** [xJon/The-1.7.10-Pack#1455]
the universal cables from mekanism wont transfer different types of power specifically EU, from what i read it means one on the CoFH folders in one of the mod .jars is outdated, but i have no clue how to find out which one

**Comment by xJon** [comment]
https://github.com/aidancbrady/Mekanism/issues/2014#issuecomment-66856825
![screenshot_1](https://user-images.githubusercontent.com/8945347/36558295-3e83eade-1813-11e8-869d-8ea132b1fd86.png)

**Comment by StormdragonDesigns** [comment]
Regression? Not getting power from EU sources.
![image](https://user-images.githubusercontent.com/30184151/76160638-f0fbdc00-617f-11ea-96fb-e44dd5de0b6c.png)
