### ISSUE TITLE
Error Launching

### ISSUE THREAD

**Issue by Aurastrider** [xJon/The-1.7.10-Pack#1456]
So i'm attempting to run a server for some friends of mine, and I believe i've also had this issue before, as well. The pack worked fine right up until I started testing items in creative, but the entire thing crashed when I tried to access the third item page. Now, whenever I try to launch, I get an error saying An error was raised while attempting to read pack info for modpack the-1710-pack, build 0.9.7: solder.endermedia.com. I would love some assistance fixing this error.

**Comment by xJon** [comment]
Simply try to uninstall, it should fix it :)
