### ISSUE TITLE
Failing to download extra cells

### ISSUE THREAD

**Issue by nano912** [xJon/The-1.7.10-Pack#1461]
I tried to reinstall The 1.7.10 Pack today, and I got the message that I cannot download the Extra cells files.
![image](https://user-images.githubusercontent.com/20424858/31888962-5240bd2e-b7fe-11e7-872c-c8f2d90abace.png)

**Comment by nano912** [comment]
The issue resolved itself on try #6 apparently

**Comment by xJon** [comment]
That is weird, might've had a problem on our end, but I'm glad it was fixed.
