### ISSUE TITLE
Crash Report: Can't Play Server Anymore

### ISSUE THREAD

**Issue by BlindedIsaac** [xJon/The-1.7.10-Pack#1462]
[Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.

Get This Error When Loading The Server.

Crash Report: https://pastebin.com/7h2gshvG

Tried Taking Some Mods Out But Just Makes It Worse.

**Comment by xJon** [comment]
The paste is no longer available.
