### ISSUE TITLE
Game not starting at all (Halp)

### ISSUE THREAD

**Issue by STHelios** [xJon/The-1.7.10-Pack#1463]
So, I installed Technipack and The 1.7.10 pack recently but sadly i can't seem to play this one
What happens is 
Click play > launcher disapear > nothing > launcher comes back
https://pastebin.com/zsd4h8Uq (last launch log)
https://pastebin.com/PBE0Cu5T (crash report)

[crash-2017-11-13_18.35.40-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/1467994/crash-2017-11-13_18.35.40-client.txt)
[techniclauncher_2017-11-13.log](https://github.com/xJon/The-1.7.10-Pack/files/1467995/techniclauncher_2017-11-13.log)

It's worth noting that i reinstalled both the pack and the launcher, checked java, did the graphic drivers and checked if enough memory was allocated (5GB out of 8GB)

Halp please

**Comment by xJon** [comment]
Update your graphic's card driver.
