### ISSUE TITLE
Cannot load up the minecraft forge file

### ISSUE THREAD

**Issue by HysterixLive** [xJon/The-1.7.10-Pack#1464]
I don't know why but i am trying to host a server for the 1.7.10 pack but every time i start to load up the forge file it loads all the way and then right as it should be done it closes itself and i have no idea what to do. I have port forwarded, i make sure to load up the "launch server" file first and have made the correct changes to the server properties file.

HELP!!!

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
