### ISSUE TITLE
Server crashed, and won't work

### ISSUE THREAD

**Issue by ToTheMax101** [xJon/The-1.7.10-Pack#1465]
[crash-2017-12-08_21.35.10-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/1544285/crash-2017-12-08_21.35.10-server.txt)
restored my deletion of endercore, then got this 
[crash-2017-12-08_21.38.28-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/1544286/crash-2017-12-08_21.38.28-server.txt)
restored enderio, then got this
[crash-2017-12-08_21.42.31-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/1544289/crash-2017-12-08_21.42.31-server.txt)
deleted railcraft, got this
[crash-2017-12-08_21.53.02-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/1544295/crash-2017-12-08_21.53.02-server.txt)
reinstalled server, transferred world files, player data and still crashing
[crash-2017-12-08_22.23.30-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/1544310/crash-2017-12-08_22.23.30-server.txt)

**Comment by xJon** [comment]
You have corrupted questing data - simply reset (delete) the inside of `HardcoreQuesting` within your server's world folder.
