### ISSUE TITLE
NEI Hidden and no keybind found

### ISSUE THREAD

**Issue by shadekeeper** [xJon/The-1.7.10-Pack#1466]
My NEI is hidden and I can't unhide it. I've looked in all the mod menus, even the mod config, and I can't figure out how to unhide it. 

I've already tried pressing every key on my keyboard, to no avail.

**Comment by shadekeeper** [comment]
Edit: there was in fact a "hidden:true" in the config that I didn't see before. changed it to false, it's there now.

**Comment by xJon** [comment]
I'm pretty sure you can change it with the `O` key, you should be able to hide and unhide it in-game.
