### ISSUE TITLE
forge relocation mod and game not launching at all problems

### ISSUE THREAD

**Issue by andrew11095** [xJon/The-1.7.10-Pack#1467]
hi
whenever i try and play the 1.7.10 mod, i get this error/ how can i resolve it because the link doesn't even work
![image](https://user-images.githubusercontent.com/34747766/34264148-d1476ad4-e669-11e7-948d-5d55f2edfbb7.png)
thanks

**Comment by gogobebe2** [comment]
![image](https://user-images.githubusercontent.com/6384447/34283835-f202b368-e732-11e7-9f02-5e15127de364.png)

**Comment by andrew11095** [comment]
i found the link and put the file into the mods folder but now the game doesn't even open. i click play and the stuff is downloaded at the bottom of the Technic launcher page and then the Technic launcher dissapears. after 10 seconds it appears again and the 1.7.10 pack hasn't even launched. please help

**Comment by gogobebe2** [comment]
It should work normally now. It's working for me. The server was down.
