### ISSUE TITLE
Keeps crashing ;-;

### ISSUE THREAD

**Issue by Moochez** [xJon/The-1.7.10-Pack#1470]
Whenever I try launching Minecraft with this pack, it crashes on the last step. I am keeping the log on but I didn't see any bad errors.
If someone could help me, that would be great.
- Moochez

**Comment by MJRLegends** [comment]
Best to include the crash log when reporting issues as the crash log shows the cause/reason of the issue

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
