### ISSUE TITLE
"Unsupported modded version of the game"

### ISSUE THREAD

**Issue by Moochez** [xJon/The-1.7.10-Pack#1471]
When I try to launch the game, after a few minutes it crashes saying the modded version of the game isn't supported anymore.
Help?

**Comment by MJRLegends** [comment]
You need to make sure your using java 8, this messages shows when using below java 8

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
