### ISSUE TITLE
PLEASE HELPP

### ISSUE THREAD

**Issue by Moochez** [xJon/The-1.7.10-Pack#1474]
Whenever I try launching it says: 
The game crashed whilst initializing  #game
Error: java.lang.OutOfMemoryError: Java heap 
**please help I want to fix this**

**Comment by Moochez** [comment]
PLEASE HELP

**Comment by Ph4ntom3** [comment]
This is actually very simple to fix if im right. "OutOfMemoryError" means that the game doesn't have enough memory, right? So you just have to give it more. Go to the "Profiles" page in the launcher, click on your profile (the one you're using play), activate "JVM Arguments" and replace the first part of the line next to it, which should look something like -Xmx1G, and replace the 1 with the amount of RAM you want minecraft to have. I recommend half of the RAM of your computer.

**Comment by xJon** [comment]
👍
