### ISSUE TITLE
Magic Bees causing crashes

### ISSUE THREAD

**Issue by HugoZink** [xJon/The-1.7.10-Pack#1475]
In some rare cases, Magic Bees might cause crashes while trying to generate Ars Magica bees. This is caused by the bee's effect being null sometimes.

[Here is a crash report of the issue.](https://pastebin.com/qQUC0zU4)

I do not know the cause of the bug. Reading the source code of Magic Bees indicates that the AMLightning effect is not being set if Extra Bees is not also present.

**Comment by HugoZink** [comment]
I initially reported this crash because I thought it was a config bug. After some more research, the culprit is probably an over-active antivirus. This issue can be ignored.

**Comment by xJon** [comment]
Interesting, that's weird.
Anyway hopefully quite soon we'll be updating Binnie's Mods and remove the ASM BinniePatcher, which might help things be more simple.
