### ISSUE TITLE
Can't break blocks

### ISSUE THREAD

**Issue by JorikDx** [xJon/The-1.7.10-Pack#1477]
Both in single and multiplayer I can't seem to break blocks, I've tried turning on cheats or making myself OP in multiplayer but nothing works. I also checked if I was in adventure mode but that is not the case and I also can't break blocks if I'm in creative.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Great :)
