### ISSUE TITLE
Can't change RAM setting

### ISSUE THREAD

**Issue by EpicJunJun** [xJon/The-1.7.10-Pack#1478]
Got this from trying to play using the modpack. I tried to go into my settings and change the RAM but the highest it will go to is 1 GB.
![image](https://user-images.githubusercontent.com/36123868/35775049-f316b482-0935-11e8-9d57-c39cd1a675e7.png)

**Comment by captain50000** [comment]
u need 64bit

**Comment by MJRLegends** [comment]
64 bit java is needed for 4GB+

**Comment by xJon** [comment]
⬆️
