### ISSUE TITLE
client crashes when loading world

### ISSUE THREAD

**Issue by poke-chop** [xJon/The-1.7.10-Pack#1480]
my computer bluescreened while in-game. cant load my world since then; possibly corrupted?  world seems to load, but them client crashes and returns me to the tekkit launcher. 
reinstalled the pack and still cant open from backup. can create new world and re-create old world from seed.

[crash-2018-02-21_11.50.55-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/1745510/crash-2018-02-21_11.50.55-server.txt)

is there any way to recover from this?

**Comment by xJon** [comment]
This looks like a corrupted world. Try using older backups, there's simply nothing else I can suggest. Minecraft is very sensitive about how you close and save your game.
