### ISSUE TITLE
Exoflame + Alchemical Furnace Compatibility.

### ISSUE THREAD

**Issue by Math321** [xJon/The-1.7.10-Pack#1483]
This mod lets Botania's Exoflame power the Alchemical Furnace from Thaumcraft. It does a couple of other minor things, but that's its main function. If you decide to update the pack, please consider adding this.

https://minecraft.curseforge.com/projects/tcbotaniaexoflame

**Comment by xJon** [comment]
Probably won't be added to the main modpack, but you can always add it yourself manually. :)
