### ISSUE TITLE
Server Keeps crashing

### ISSUE THREAD

**Issue by alliedspice** [xJon/The-1.7.10-Pack#1484]
My server worked fine about 4 days ago, but it recently crashed and won't restart. Crash report is below.

[crash-2018-02-25_20.41.42-server (1).txt](https://github.com/xJon/The-1.7.10-Pack/files/1757015/crash-2018-02-25_20.41.42-server.1.txt)

**Comment by xJon** [comment]
Can't you just load a backup?

**Comment by alliedspice** [comment]
Negative, I get the same crash report with all my backups :(

**Comment by xJon** [comment]
Did you try to reinstall?

**Comment by alliedspice** [comment]
Yes, I even tried earlier versions

**Comment by xJon** [comment]
Welp, your save unfortunately is corrupted, and the stack-trace doesn't tell us which mods corrupts it. You can try to backup your world, trying to remove one mod at the time so the game will remove all of its items from the game and possibly also the corrupted one, but this is a lot of work.
Unfortunately without a backup, there's nothing else I can help you.
It is strange you're getting the same crash with a backup, as it should've been backed up when the game was running well.
You can try updating the modpack to v0.9.8, which might help, but that's all I can say.
