### ISSUE TITLE
Stuttering every second?

### ISSUE THREAD

**Issue by thederpmachine** [xJon/The-1.7.10-Pack#1485]
About once per second running this modpack, the game stutters for a few frames and then goes back to smooth 60fps. What's causing this, and how do I fix it? Running windows 10, i7, gtx 1060

**Comment by xJon** [comment]
How much RAM are you allocating? Are you using a resource pack?

**Comment by thederpmachine** [comment]
Currently set at 6 GB in the launcher Java settings, using the default minecraft texture pack. It's strange, because the game runs very smoothly otherwise, it's just stuttery

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by thederpmachine** [comment]
https://paste.ubuntu.com/p/rXM5FjNg9J/

**Comment by xJon** [comment]
This log looks like you just booted up the game but haven't entered a world yet, can you enter a world and experience the lag again and then provide the latest log?

**Comment by xJon** [comment]
Closed per your request.

**Comment by EmilJohan** [comment]
This is a longshot, but I am having the same issue right now with the same modpack. Do you remember how the issue was resolved?
