### ISSUE TITLE
The 1.7.10 modpack crash

### ISSUE THREAD

**Issue by joew1987** [xJon/The-1.7.10-Pack#1487]
Hi All, 
I get into game fine, but after a minute each time I crash to desktop and get the following crash report:

**EDITED BY JON - Please use a paste tool: https://pastebin.com/Nbtvc5J9**

**Comment by xJon** [comment]
Try to load a backup. Why is your game installed in a Dropbox folder? Minecraft saves are very touchy about each and every file.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
