### ISSUE TITLE
How to make a multiplayer server? FML Errors

### ISSUE THREAD

**Issue by TheDarkSeraphim** [xJon/The-1.7.10-Pack#1489]
I have tried creating a multiplayer server for this pack, however, I keep getting FML errors ("The state engine was in incorrect state ERRORED and forces into state SERVER_STOPPED").

What do I do to fix this problem?

**Comment by xJon** [comment]
Make sure that the `eula.txt` file is set to true.
If that's already the case, post your latest server log using a paste-tool and I'll re-open the issue.
