### ISSUE TITLE
Huge laggs/stuttering

### ISSUE THREAD

**Issue by Schokio** [xJon/The-1.7.10-Pack#1490]
Hey,
dunno if you can help in this case.
A friend of mine, who wanted to play with me/us, got this pack and started it, but in his case
he has huge stutters and a cpu usage of 100%.
What do I mean with stuttering ?
E.g. he is panning his mouse, and it isn't smooth but his camera suddenly jumps to the new angle.
He already got OptiFine installed, but it didn't help.
He has literally the same computer like me.

In addition to that, his client freezes and windows is telling the typical "no response" thingy, and during that it closes by itself.
Is there any crash-log that I can post for him or anything like that :?

Greetings

**Comment by xJon** [comment]
Your friend might need a better machine to run modded Minecraft.
He can try to manually download Optifine version D6 and tweak the video settings, set VSync off and put Max FPS on unlimited.

**Comment by Schokio** [comment]
He has the same rig like me.
i5-6600k
16GB RAM
GTX 980

It's only stuttering when moving the mouse.
He already tried using Optifine and Fastcraft together.
FPS is 100-200, but it stutters everty 5-10 (when moving mouse etc.)

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Schokio** [comment]
Found out it is a general minecraft problem about mouse spazzing.
Nothing with the modpack.
Dunno if you have a solution for mouse spazzing, otherwise this issue is solved ^^

**Comment by xJon** [comment]
👍
