### ISSUE TITLE
Screen freezing but game still interactable

### ISSUE THREAD

**Issue by Onetimelogin** [xJon/The-1.7.10-Pack#1491]
Recently some friends and I set up a server and have been trying to play but about 5 minutes after I get into the game my screen freezes. While the screen is frozen I can still interact with the game and my friends can see me moving around while none of them have this issue. Is this super bad lag or something else? thanks in advance.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Onetimelogin** [comment]
https://paste.ubuntu.com/p/BnNwtF9gPF/
Here you go thanks for the quick reply :)

**Comment by xJon** [comment]
I can see a weird HardcoreQuesting error in your log, but that's it - also it doesn't seem that you were online for about 5 minutes in the log?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if asked for.
