### ISSUE TITLE
Game crashes after the world loads 

### ISSUE THREAD

**Issue by Dewar57** [xJon/The-1.7.10-Pack#1492]
Hey , so when I load my world it crashes.
I don't use Optifine or any other mods/addons in this pack.
Also I tried to reinstall the modpack ... didn't work.
I appreciate any help thx !

Here's the crash report : https://pastebin.com/Pb92LDBv

**Comment by xJon** [comment]
Try to remove the VoxelMap mod.

**Comment by Dewar57** [comment]
Thanks this worked 👍 but when I was loading the world it said "A fatal error has occurred, this connection is terminated". After disabling internet connection I finally loaded.
Please respond if you know what could that error solve.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
