### ISSUE TITLE
Game keeps crashing when loading up the mods

### ISSUE THREAD

**Issue by Satsurns** [xJon/The-1.7.10-Pack#1495]
[crash-2018-03-14_13.04.17-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/1812426/crash-2018-03-14_13.04.17-client.txt)

Happens when loading up game from the technic launcher, I'm not using optifine

**Comment by xJon** [comment]
Did you try to reinstall the modpack?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
