### ISSUE TITLE
Server Keeps Crashing

### ISSUE THREAD

**Issue by MessyPath** [xJon/The-1.7.10-Pack#1497]
So my server for this modpack keeps crashing and all the mods were working fine until today when it decided that it didn't want to work anymore.

Here is the Crash report
[crash-2018-03-19_20.57.11-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/1827629/crash-2018-03-19_20.57.11-server.txt)

**Comment by xJon** [comment]
You have corrupted questing data - simply reset (delete) the inside of `HardcoreQuesting` within your server's world folder.
