### ISSUE TITLE
0.9.8 Server crash

### ISSUE THREAD

**Issue by Slapperino** [xJon/The-1.7.10-Pack#1499]
Server ran fine for a while, until I restarted it. Now it won't start. I changed spawn protection from 16 to 0 is server properties and this was the only change. I reverted that and it still won't work.

Any help is appreciated, thank you for your time.

crash log: https://pastebin.com/EH3vQsp0

EDIT: I put the world from the 0.9.8 server into a 0.9.7 server and now the 0.9.7 server won't start. Seems to be a world problem.

**Comment by xJon** [comment]
You simply have corrupted questing data - simply reset (delete) the inside of `HardcoreQuesting` within your server's world folder.
