### ISSUE TITLE
Error when trying to join server

### ISSUE THREAD

**Issue by steellz** [xJon/The-1.7.10-Pack#1500]
i removed Flans Mods and got the server to start., but i get an error when trying to join, ive tried many things deleting player data, removing all plugins, deleting the world and samething everytime.
i uploaded my log below
[latest.log](https://github.com/xJon/The-1.7.10-Pack/files/1870124/latest.log)

**Comment by xJon** [comment]
Do you have the same version of the modpack and same mods installed on both client and server?
Also, how did you remove Flans Mods?

**Comment by steellz** [comment]
Im going to assume you didnt read the log, after much research it seems to be a HQM problem, i dont know why the problem occurred after removing flans mods. and i still cant fix the problem without removing the HQM mod itself,

**Comment by xJon** [comment]
I didn't notice the log, hah. Anyway, probably because the HQM quests have a Flan's Mod quest line using the mod's files. Still, did you remove the mod from both client and server side?

**Comment by steellz** [comment]
Once i removed HQM from serverside the players were able to join no problem,.

**Comment by xJon** [comment]
Yup, sounds about right.

**Comment by xJon** [comment]
Congratulations for issue #1500 by the way! 🎉
