### ISSUE TITLE
DefenseTech mod has a error item in recipe, minor feature breaking.

### ISSUE THREAD

**Issue by JurasTW** [xJon/The-1.7.10-Pack#1501]
Tried to explore the DefenseTech mod and found that it's impossible to craft Cruise Launcher that is needed for the better half of the mod.
Issue is that the recipe uses an item in the upper left corner that is invisible and has an error name.
Would love this to be fixed.
![2018-04-03_10 20 31](https://user-images.githubusercontent.com/38030680/38235236-0c6e6ca6-3729-11e8-84e1-c7b74ecc9150.png)

**Comment by xJon** [comment]
I mean, it is used only for the portable Rocket Launcher, and not for launching all missiles, but I can confirm it's bugged in v0.9.8. Was it the same in v0.9.7?

**Comment by JurasTW** [comment]
yeah, it was like that before the update.

**Comment by xJon** [comment]
Unfortunately this bug has been reported to the mod author over a year ago yet development is not on unfortunately. This can be manually fixed using MineTweaker if necessary but won't be implemented in the modpack.
