### ISSUE TITLE
Can't connect to any server nor play in singlepalyer

### ISSUE THREAD

**Issue by Ceslawi** [xJon/The-1.7.10-Pack#1503]
Hi !
As the title says, I can't connect to any server, I get the error "Failed to login: The authentifiaction are currently down for maintenance."

I already tried re-installing both minecraft and the modpack and tried de-activating my firewall.

I also can't play in sigle player, the game just goes back to the title screen after loading the world and I get the error "Connection Lost A fatal error as occured, this connection is terminated"

**Comment by xJon** [comment]
It should be a problem on Mojang's end and you can see their statues' here: https://help.mojang.com/
