### ISSUE TITLE
Client crashes when joining a server

### ISSUE THREAD

**Issue by SkillerFiftyOne** [xJon/The-1.7.10-Pack#1504]
https://pastebin.com/iwp71rfh

I recently wanted to play this pack again, and when I try to join a server my friends play on the client crashes without a prompt. That's all I know, I've tried reinstalling both the client and the launcher twice and it doesn't work.

**Comment by xJon** [comment]
Try removing the VoxelMap mod temporarily from your client - do you still get the crash?

**Comment by SkillerFiftyOne** [comment]
All the voxel mods or just voxelmap?

**Comment by SkillerFiftyOne** [comment]
I was unsure if you meant all the voxel mods or just voxelmap, but in both cases (me deleting the mods) it gives the same crash.

**Comment by xJon** [comment]
It's impossible to give the same crash with the same stack-trace if all voxel mods are successfully uninstalled.
Are you sure it's the same crash log?

**Comment by SkillerFiftyOne** [comment]
By removing- do you mean just removing them from the mods folder or is there a second step?

**Comment by xJon** [comment]
And also remove LiteLoader from the `\mods\1.7.10` folder.

**Comment by SkillerFiftyOne** [comment]
It still gives the same result, crashing without a prompt.

https://pastebin.com/8c7frnQW

**Comment by xJon** [comment]
This is a different crash log. Try to also remove the Factorization mod.

**Comment by SkillerFiftyOne** [comment]
It still doesn't work, but now I'm getting a Nullpointerexception.

https://pastebin.com/i6PyMX6G

**Comment by xJon** [comment]
Probably because Factorization also needs to be removed server-side.

**Comment by SkillerFiftyOne** [comment]
Alright, so what do you propose I do?

**Comment by xJon** [comment]
Remove it from server-side as well. Always remove the same mods from client-side and server-side.

**Comment by SkillerFiftyOne** [comment]
I am unable to remove it from the server, is there any other step I could do? perhaps the thing conflicting with the mods can be solved instead?

**Comment by SkillerFiftyOne** [comment]
Found the problem, server had not updated to 0.9.8
