### ISSUE TITLE
Technic not downloading 'The 1.7.10 Pack' mods v0.9.8

### ISSUE THREAD

**Issue by SeaJayIshOtaku** [xJon/The-1.7.10-Pack#1505]
First off, please don't murder me, I'm new to the forum xD

My friend and I have played 'The 1.7.10 pack' modpack from Technic for about 2 months or so, and so far haven't had any problems with loading packs and their assets, downloading updates, etc, etc.

Today, we all decided to go for the latest update on The 1.7.10 pack which is v0.9.8.

A mutual friend of ours that plays on the server (let's call them 'Ash') and I updated, and I injected our old world into the new server files, making the appropriate changes to the server.config and MagicalCrops.cfg files. Everything worked perfectly fine, and we played for about an hour or so until another friend joined (Let's call him 'Fetoose'.), and tried to download the update for the pack so he could play with us. No dice. Ash AND I deleted our modpacks, and redownloaded them to see if it was maybe a file hosting issue, but we all live within 20 miles of each other, and Fetoose was the only one that was NOT able to download/install the pack.

He says that the download would get stuck at 0% for whatever mod would start downloading first, and he tried 5 different times, to no avail. He tried deleting the pack, the .technic file in %appdata% altogether and practically decimating any technic anything he could find on his computer and redownloading the launcher with no luck, also restarting in between at various intervals. After he deleted the technic launcher and packs, he would get stuck with the same first error listed below.

Just for clarification, his firewall was off and his antivirus is nonexistent.

Some of the errors that were thrown up were as follows:

[B#360] Starting download of http://solder.endermedia.com/repository/mods/witchery/witchery-0.24.1.zip, with 3 tries remaining
[B#360] Download of http://solder.endermedia.com/repository/mods/witchery/witchery-0.24.1.zip Failed!
[B#360] Starting download of http://solder.endermedia.com/repository/mods/witchery/witchery-0.24.1.zip, with 2 tries remaining

AND:

Failed to load class org.slf4j.impl.StaticLoggerBinder

He gave up about 30 mins ago trying to fix it and went to bed.
I want to fix this problem, and try to prevent it from happening again.

Any ideas? Solutions? PLEASE HELP?

**Comment by xJon** [comment]
Did he just try to reinstall the Technic Launcher completely?

**Comment by SeaJayIshOtaku** [comment]
Yeah, he tried reinstalling the launcher completely, and when it didn't work, he deleted it again, restarted his computer and it still didn't work... the weird thing is that other modpacks could download just fine, only 1.7.10 wouldn't, which I found really strange. Apparently, its was a solder issue?

Also, THANK YOU SO MUCH for replying :o I've looked everywhere for a forum that actually responds, and practically no one does xD

**Comment by SeaJayIshOtaku** [comment]
He isn't home yet, I'll ask him when he gets home from college.
He wasn't able to download it this morning before he left, though.

**Comment by xJon** [comment]
Well, other people are able to download from these links, so he probably needs to check firewalls or ISP blocking on his end.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
