### ISSUE TITLE
Voxelmap from worlds merging together, help please!

### ISSUE THREAD

**Issue by queenizzy** [xJon/The-1.7.10-Pack#1506]
Everytime I make a world, the map and waypoints from other worlds show up.  How do i fix this so i am able to have more then one world?

**Comment by xJon** [comment]
What modpack version are you using?

**Comment by queenizzy** [comment]
v0.9.8, also a quick question a little off topic, does anyone know which mod adds the castle ruins?(sorry for going of topic, i was just curious)

**Comment by queenizzy** [comment]
So I'm assuming you mean tell you how to recreate my problem?
All I did was start a world, then leave that world and create another.  I went into that other world, and I went into the world map by clicking 'm'.  I saw the world map from the previous world I made, and all the waypoints as well.  I then went into the previous world and I don't know what happened, but all my waypoints were gone.  So I ended up deleting and re-installing the modpack.  This happens everytime I make more then one world, and I would love to know how to keep this from happening.
Also thanks so much for the quick response <3

**Comment by queenizzy** [comment]
Also just for curiosity's sake (I'm working on a project which involves fixing an old castle I found in a world), would you mind telling me the other structure generating mods?  Sorry for going off topic.

**Comment by xJon** [comment]
I don't know if I can even call it a bug, as it's how VoxelMap waypoints work - based on world names.
If you have two worlds with the same names, they will share their waypoints. But it only happens in that case.
Thank you for reporting the issue regardless!
