### ISSUE TITLE
NEED HELP WITH MODPACK NOT LETTING ME LOAD WORLD

### ISSUE THREAD

**Issue by MrNoNoYT** [xJon/The-1.7.10-Pack#1509]
I got a mod pack on the technic launcher called "Modern Millenaire (1.7.10) Version 3.0.3.2"  i left my computer for a bit and and when i came back my computer crashed and i tried to reload the world and it just said make sure you back up your world and stuff and i hit yes now when i try to load the world is just load opens the world for a sec then goes back to the launcher anything i can do?

Crash report :
---- Minecraft Crash Report ----
// You're mean.

Time: 05/04/18 11:01 PM
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: -6
	at net.minecraft.world.chunk.NibbleArray.func_76582_a(SourceFile:26)
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76665_b(SourceFile:75)
	at net.minecraft.world.chunk.Chunk.func_76628_c(Chunk.java:548)
	at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:878)
	at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:862)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:500)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2932964384 bytes (2797 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 119 mods loaded, 111 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (modpack.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-5} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	backpacks16840{3.0.8} [Backpacks!] (backpack-3.0.8.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	MorePlanetsASM{} [More Planets Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (notenoughitems-1.0.5.120.jar) 
	UCHIJAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-5} [Applied Energistics 2] (appliedenergistics2-rv3-beta-5.jar) 
	UCHIJAAAA	betterrain{0.15} [Better Rain] (betterrain-0.15.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (bibliocraft-1.11.4.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.1} [CoFH Core] (cofhcore-3.1.1-324.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.2} [Thermal Foundation] (thermalfoundation-1.2.2-111.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.1} [Thermal Expansion] (thermalexpansion-4.1.1-237.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (bigreactors-0.4.3A.jar) 
	UCHIJAAAA	IC2{2.2.811-experimental} [IndustrialCraft 2] (industrialcraft2-2.2.811.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.18} [BuildCraft] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	Forestry{3.6.12.3} [Forestry for Minecraft] (forestry-3.6.12.3.jar) 
	UCHIJAAAA	BinnieCore{2.0-pre14} [Binnie Core] (binniemods-2.0-pre14.jar) 
	UCHIJAAAA	Botany{2.0-pre14} [Botany] (binniemods-2.0-pre14.jar) 
	UCHIJAAAA	ExtraBees{2.0-pre14} [Extra Bees] (binniemods-2.0-pre14.jar) 
	UCHIJAAAA	ExtraTrees{2.0-pre14} [Extra Trees] (binniemods-2.0-pre14.jar) 
	UCHIJAAAA	Genetics{2.0-pre14} [Genetics] (binniemods-2.0-pre14.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.18} [BC Transport] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.18} [BC Silicon] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.18} [BC Energy] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.18} [BC Factory] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.18} [BC Builders] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.18} [BC Robotics] (buildcraft-7.1.18.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7 DEV} [Carpenter's Blocks] (carpentersblocks-3.3.7.jar) 
	UCHIJAAAA	Railcraft{9.8.0.0} [Railcraft] (railcraft-9.8.0.0.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.5.1.44} [Chisel 2] (chisel2-2.5.1.44.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (computercraft-1.75.jar) 
	UCHIJAAAA	creativecore{1.3.14} [CreativeCore] (creativecore-1.3.21.jar) 
	UCHIJAAAA	CustomMainMenu{1.9.2} [Custom Main Menu] (custommainmenu-1.9.2.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.3} [Damage Indicators] (damageindicators-3.2.3.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (decocraft-2.2.1.jar) 
	UCHIJAAAA	props{2.2.1} [Decocraft] (decocraft-2.2.1.jar) 
	UCHIJAAAA	DynamicLights{1.3.9} [Dynamic Lights] (dynamic-lights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (dynamic-lights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (dynamic-lights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (dynamic-lights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (dynamic-lights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (dynamic-lights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (dynamic-lights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (dynamic-lights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (dynamic-lights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (dynamic-lights-1.7.10.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.31_beta} [EnderCore] (endercore-0.2.0.31.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (minefactory-reloaded-2.8.1-174.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (waila-1.5.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.421_beta} [Ender IO] (enderio-2.3.0.421-beta.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.38} [EnderStorage] (enderstorage-1.4.7.38.jar) 
	UCHIJAAAA	extracells{2.3.9} [Extra Cells 2] (extracells-2.3.9b.188.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (harvestcraft-1.7.10Lb.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (mantle-0.3.2b.jar) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (mb-battlegear2-bullseye-1.0.8.2.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] (tinkers-construct-1.8.8.build991.jar) 
	UCHIJAAAA	ExtraTiC{1.4.5} [ExtraTiC] (extratic-1.4.5.jar) 
	UCHIJAAAA	fairylights{1.4.0} [Fairy Lights] (fairy-lights-1.4.0.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (minetweaker-3.0.10B.jar) 
	UCHIJAAAA	FTBL{1.0.18.2} [FTBLib] (ftblib-1.0.18.3.jar) 
	UCHIJAAAA	FTBU{1.0.18.2} [FTBUtilities] (ftb-utilities-1.0.18.3.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (galacticraftcore-3.0.12.464.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (galacticraftplanets-3.0.12.464.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (inventorytweaks-1.59-152.jar) 
	UCHIJAAAA	JABBA{1.2.1} [JABBA] (jabba-1.2.1a.jar) 
	UCHIJAAAA	journeymap{@JMVERSION@} [JourneyMap] (journeymap-5.1.0-fairpl.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.1} [MalisisCore] (malisiscore-0.14.1.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.0} [Malisis' Doors] (malisisdoors-1.13.0.jar) 
	UCHIJAAAA	millenaire{6.0.0} [MillÃ©naire] (millenaire-6.0.0.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (minefactory-reloaded-2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (minefactory-reloaded-2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (minefactory-reloaded-2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (minefactory-reloaded-2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (minefactory-reloaded-2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (minefactory-reloaded-2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (minefactory-reloaded-2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (minefactory-reloaded-2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (minefactory-reloaded-2.8.1-174.jar) 
	UCHIJAAAA	modtweaker2{0.9.2} [Mod Tweaker 2] (modtweaker-2.0.9.3.jar) 
	UCHIJAAAA	MorePlanet{1.3.0} [More Planets] (more-planets-1.3.0-Pre6.jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (mrcrayfishfurnituremod-3.4.8.jar) 
	UCHIJAAAA	NEIAddons{1.12.15.41} [NEI Addons] (neiaddons-1.12.15.41.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.15.41} [NEI Addons: Developer Tools] (neiaddons-1.12.15.41.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.15.41} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.15.41.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.15.41} [NEI Addons: Botany] (neiaddons-1.12.15.41.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.15.41} [NEI Addons: Forestry] (neiaddons-1.12.15.41.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.15.41} [NEI Addons: Crafting Tables] (neiaddons-1.12.15.41.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.15.41} [NEI Addons: Ex Nihilo] (neiaddons-1.12.15.41.jar) 
	UCHIJAAAA	OpenMods{0.9.1} [OpenMods] (openmodslib-0.9.1.jar) 
	UCHIJAAAA	OpenBlocks{1.5.1} [OpenBlocks] (openblocks-1.5.1.jar) 
	UCHIJAAAA	RandomThings{2.2.4} [Random Things] (randomthings-2.2.4.jar) 
	UCHIJAAAA	ResourceLoader{1.2} [Resource Loader] (resource-loader-1.2.jar) 
	UCHIJAAAA	corerm{1.0c} [RikMuld's Core] (rikmuldscore-1.0c.jar) 
	UCHIJAAAA	securitycraft{v1.8.1} [SecurityCraft] (securitycraft-1.8.1.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.7.9} [Storage Drawers] (storage-drawers-1.7.9.jar) 
	UCHIJAAAA	tabbychat{1.11.2.2} [TabbyChat] (tabbychat-1.11.2.2.jar) 
	UCHIJAAAA	camping{2.1g} [The Camping Mod 2] (the-camping-mod-2.1g.jar) 
	UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (tic-tooltips-1.2.5.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] (treecapitator-2.0.4.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (minefactory-reloaded-2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (minefactory-reloaded-2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (minefactory-reloaded-2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (minefactory-reloaded-2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (minefactory-reloaded-2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (minefactory-reloaded-2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (minefactory-reloaded-2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (minefactory-reloaded-2.8.1-174.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:ACTIVATED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-5 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.1.1-324
	ThermalFoundation: -[1.7.10]1.2.2-111
	ThermalExpansion: -[1.7.10]4.1.1-237
	MineFactoryReloaded: -[1.7.10]2.8.1-174
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	EnderIO: Found the following problem(s) with your installation: "An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-5.jar). Ender IO was build against API version rv2." This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['MoncheGaming'/1311, l='First Life', x=-444.42, y=88.00, z=-189.91]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by xJon** [comment]
We're not Technic, we do not provide support for other modpacks.
