### ISSUE TITLE
Celestial Crystal in End?

### ISSUE THREAD

**Issue by emman117** [xJon/The-1.7.10-Pack#1512]
I recently made a discovery when searching in the End for Celestial Crystal, I'm assuming its because of Ender Expansion but there doesn't seem to spawn any at all which gets rid of any chance of making ambrosia from biomes o' plenty, or is there another way i am unaware of?

**Comment by xJon** [comment]
That is very odd as:
```
    # Prevents other mods from adding worldgen features to the End.
    B:overrideWorldGen=false
```
I'm not sure what can cause it. Will look further into it.

**Comment by xJon** [comment]
Seems to not generate the celestial crystals with or without the HEE mod.
I've checked the config files for BoP and couldn't find anything for the crystals.
Plus, the authors of BoP don't provide support for 1.7.10 anymore.
Do you know if it works in other 1.7.10 modpacks?

**Comment by xJon** [comment]
Upon investigating, and looking through BoP 1.7.10 code, it seems like this is a mod issue that was later fixed in newer versions of Minecraft.
Luckily the celestial crystals are only used to craft one item, which has other similar alternatives.
