### ISSUE TITLE
Crash on startup. Please help ASAP

### ISSUE THREAD

**Issue by TheDarknessLives** [xJon/The-1.7.10-Pack#1513]
![capture1](https://user-images.githubusercontent.com/38275204/38599742-b353dad6-3d2f-11e8-8a64-617916c51665.PNG)
![capture2](https://user-images.githubusercontent.com/38275204/38599743-b36644a0-3d2f-11e8-941e-cd951c2dc02c.PNG)

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
