### ISSUE TITLE
My unsolved problem

### ISSUE THREAD

**Issue by Filmuti** [xJon/The-1.7.10-Pack#1514]
Hi!
I wanted to play on server with my friends but i get this:
https://paste.ubuntu.com/p/Z6nTVKHKT4/
I delete a thaumicenergetics and other mods with thaumic because it seems like it was it but it wasnt. Help please :)

**Comment by xJon** [comment]
What happens in practice? Does the game crash or what?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
