### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dimmetrodon** [xJon/The-1.7.10-Pack#1515]
Sorry, cant download the pic
The problem:
Failed to download https://libraries.minecraft.net/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

**Comment by xJon** [comment]
Did you try to just install again?

**Comment by Dimmetrodon** [comment]
Yep, tried that

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
