### ISSUE TITLE
Friends Can't connect to my server

### ISSUE THREAD

**Issue by Meruru33** [xJon/The-1.7.10-Pack#1516]
![image](https://user-images.githubusercontent.com/38637831/39102227-b8833a9e-4656-11e8-9652-97a694a655d3.jpg)
Here's the error message that pops up for them. If someone could help me that would be amazing! :) Thanks <3
The server shows up for them and I can connect to it, it's just that they can't connect sadly.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
