### ISSUE TITLE
Skin loading issue

### ISSUE THREAD

**Issue by TrueGamerAlex** [xJon/The-1.7.10-Pack#1517]
There's a client-side glitch I've noticed when it comes to the player's skin. If the player dies, their skin is reset to Steve. At least, that's what it would appear. The game still recognizes there's a skin to be loaded, as if you look at the human form in the Morph Mod you can still see the player's intended skin. However, in the first person and inventory views, it can be seen that that player's skin has been replaced with the default "Steve" skin. The only 2 ways I have found to "fix" this issue is by swapping dimensions a few times until the skin corrects itself on its own, or just re-logging. This is nothing major or anything that could be seen as a "top priority", but it can be mildly annoying as I myself don't like the Steve skin very much. And yes, it also affects the Twilight Forest Giants.

One other thing, it seems as though when the player changes from any other morph body into their Human form, the original skin shows up for a second or two before swapping back to Steve. I have no idea what could be causing this, and I also don't know if this is the cause of a specific mod or the game itself, but it does not happen in vanilla 1.7.10 so I doubt it's a vanilla issue.

I have a few screenshots showing the Steve glitch in action, and if you look in the Morph menus you'll see the intended player skin. In the final screenshot, you'll see that the intended skin appears in first-person after changing from a different body, but only for a moment before changing back to Steve.

![2018-04-27_17 26 49](https://user-images.githubusercontent.com/17580578/39385978-79a8346c-4a40-11e8-93ee-52fa6953c977.png)
![2018-04-27_17 26 58](https://user-images.githubusercontent.com/17580578/39385979-79bd0e50-4a40-11e8-9571-1983f6241670.png)
![2018-04-27_17 27 09](https://user-images.githubusercontent.com/17580578/39385980-79dfada2-4a40-11e8-8eea-2703e7dd792e.png)
![2018-04-27_17 27 51](https://user-images.githubusercontent.com/17580578/39385981-79f502ec-4a40-11e8-91d5-643694641abc.png)

**Comment by xJon** [comment]
This is a known issue. But try to test something I've been looking to see - try to install this mod and see if there's any difference: https://minecraft.curseforge.com/projects/lumy-skin-patch/files/2543190

**Comment by xJon** [comment]
Does this mod consistently make things worse?

**Comment by TrueGamerAlex** [comment]
It would appear so. Before installing this mod, my skin would only change when I died. With the mod, my skin changes when I travel to another dimension. Seeing as there's quite a few dimensions and I travel to many of them on a regular basis for various materials, I'll just stick to not having this mod installed and simply relog if I die.

**Comment by xJon** [comment]
That's unfortunate. Oh well. Nothing much we can do unless you can find the problematic mod and maybe report the issue to the mod author.

**Comment by xJon** [comment]
@TrueGamerAlex I was trying out the LumySkinPatcher mod as it fixes other modded-Minecraft problems, and looked after the issue you mentioned, of the skin resetting between dimensions, and couldn't reproduce it.
Using the mod the problem seemed to be the same - skin resetting after death.
Could you help me reproduce the issues you were described? Thanks.
