### ISSUE TITLE
Server is crashing after working fine last night

### ISSUE THREAD

**Issue by Loriaan** [xJon/The-1.7.10-Pack#1519]
I have a really simple server for version 0.9.8, last night it was working fine however as i tried to open it today it has stopped working. In the server console it has the normal "The state engine was in incorrect state" and when i try to connect it gives me "java.net.ConnectException: Connection refused: No further information.  Crash log is below. Any help would be greatly appreciated, thanks in advance.
[crash-2018-04-30_16.02.26-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/1962455/crash-2018-04-30_16.02.26-server.txt)

**Comment by xJon** [comment]
You simply have corrupted questing data - simply reset (delete) the inside of `HardcoreQuesting` within your server's world folder.
