### ISSUE TITLE
My 1.7.10 Pack server doesn't start, I get an error message 

### ISSUE THREAD

**Issue by PhantomBoy27** [xJon/The-1.7.10-Pack#1520]
Hey guys!
I'm running a hamachi server, but today it's stopped because the PC restarted. When I wanted to restart my server I got an error message: "**The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.**"
I even downloaded a new server and tried it with the old 'world' folder of course, but this error didn't fixed. How could I fix it without lose our progress on the server? :/
Here is the full message: 
**http://www.kepfeltoltes.eu/images/hdd1/2018/04/26/708error.png**

**Comment by xJon** [comment]
Minecraft, especially modded, really does not like being forced shut like this and as you can see it corrupts saves. Did you try to load a backup?

**Comment by PhantomBoy27** [comment]
Yes, I tried and that helped. Now the server works again. It's very good, that there are automatic backups.
Thank you for your help! :)

**Comment by xJon** [comment]
:)
