### ISSUE TITLE
is there a way to remove the menu ui for the pack

### ISSUE THREAD

**Issue by captainvimes** [xJon/The-1.7.10-Pack#1521]
I'm trying to install an additional mod so that my brother and I can play this pack on a server with some friends in splitscreen, but the interface is making it difficult to navigate with the custom menu screen and I believe it's removed the ability for me to switch out controllers, if someone can tell me how to revert back the the old menu it would be wonderful and much easier to find out what's going wrong.

would very much appreciate any help

**Comment by xJon** [comment]
Simply click on "Lite Mods" button in the menu and disable the mod called Voxel Menu or just remove the `mod_voxelmenu_4.1.4_mc1.7.10.litemod` file from the `\mods\` folder.
