### ISSUE TITLE
Can't connect to the hamachi server.

### ISSUE THREAD

**Issue by Igorexus** [xJon/The-1.7.10-Pack#1522]
I created server, configured server.properties, launched hamachi, opened ports in my router. Friends still can't join, only I can. When my friend was hosting he could join but the rest can't. With normal minecraft server it works.

**Comment by xJon** [comment]
I'm sorry but we can't provide networking support, you should go to somewhere else like the Minecraft forums or a Discord server.

**Comment by Igorexus** [comment]
KK
