### ISSUE TITLE
cant download rhapsodia-.0.6.zip

### ISSUE THREAD

**Issue by Cchunkii** [xJon/The-1.7.10-Pack#1526]
my download speed is roughly 20 mbps and i can easily download other modpacks but this modpack is slower and this specific file wont make any progress
my os is windows 10 i have the latest verison of flash my hdd card is running perfectly fine and technic launcher is using 5 gb of memory

**Comment by xJon** [comment]
You can try to download it directly through here: http://solder.endermedia.com/repository/mods/rhapsodia/rhapsodia-0.6.zip
