### ISSUE TITLE
Factorization colossus bug

### ISSUE THREAD

**Issue by MrTangoPIG** [xJon/The-1.7.10-Pack#1527]
I triggered one of the factorization forgotten sentinels, moved too far away; it sat down; and now wont stand up and has no more health bar.

![image](https://user-images.githubusercontent.com/11806859/39828912-a2a21d24-53b4-11e8-9478-586c93766e74.png)

**Comment by xJon** [comment]
I'm not sure exactly if it's a bug or a feature but regardless Factorization is out of development so welp. Nothing we can do.
