### ISSUE TITLE
Qcraft

### ISSUE THREAD

**Issue by GeneticCyber** [xJon/The-1.7.10-Pack#1530]
I'm trying to make the  Quantizer / De-Quantizer Matrix from qcraft
I got it to work now but it's saying area is not transportable help?
The qC / pylon matrix dimensions don’t exactly match at origin and destination
Destination is abutting water or lava that could flow in and damage structures
Source / destination contains blocks with extra info (Tile Entities) that would be lost in the transfer (e.g. any blocks with an inventory, like chests, furnaces and hoppers and blocks from other mods with unusual data storage methods.) 

I checked all of these and non are the problem I've looked on thw wiki and videos and everything checked out I tried in multi player it didn't work either

**Comment by xJon** [comment]
I found it hard to try to replicate what you were trying to do, but does it work on other modpacks for 1.7.10?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
