### ISSUE TITLE
Personal Hosted server lag

### ISSUE THREAD

**Issue by BigNate69** [xJon/The-1.7.10-Pack#1531]
Whenever I try and host a dedicated server the server lags alot, I have followed your instructions (here:https://github.com/xJon/The-1.7.10-Pack/issues/1353) step by step to no avail, I have increased the ram, decreased the ram and done just about everything under the sun. The lag in question is serverside lag, me and my friends that attempt to join it all experience it as when we mine blocks the blocks only drop a few seconds after they have been mined and mobs jitter all over the place, making it close to unplayable. Im almost certain my PC is not the problem as its pretty hefty.
I appreciate any support anybody could give me.

Thanks in advance
Nathaniel

**Comment by xJon** [comment]
When you run the server, what's the CPU usage in your machine?
And, what's your internet download/upload speed?

**Comment by BigNate69** [comment]
CPU usage is at arround 70%ish and my speeds are 10mb/s down and 4 mb/s up

**Comment by xJon** [comment]
What's the results when you type `/forge tps` in the command line?
