### ISSUE TITLE
0.9.8 SERVER crash on launch

### ISSUE THREAD

**Issue by Virgo113** [xJon/The-1.7.10-Pack#1533]
[Forge log](https://paste.ubuntu.com/p/CpY9VNmhhb/) from running a fresh install downloaded from [HERE](http://solder.endermedia.com/repository/downloads/the-1710-pack/the-1710-pack_0.9.8.zip) All I did was changing the launch batch script to add 2 additional gigabytes of memory to the JVM.

So. Server closes immediately upon launching, the log reads something about a few errored mods. I have no idea what its on about and plain plucking said mods off the mods folder only makes things worse (not that I was expecting it to make things better)

So, any tips or suggestions? What am I doing wrong?

**Comment by Virgo113** [comment]
This *is* a log from a fresh install of the pack. I did not remove any mods
from the folder before first trying to run it. Only after, in an admittedly
ignorant attempt to fix it.

**Comment by xJon** [comment]
eula.txt is set to true, right?

**Comment by sambm2509** [comment]
Having the same issue, EULA set to true

**Comment by xJon** [comment]
It just seems like the server is closing whilst launching, not due to an error but due to closing it.
I'd need more logs of fresh installments to compare and try to gather more information.
I'll re-open the issue with that information.
