### ISSUE TITLE
Can't open the modpack

### ISSUE THREAD

**Issue by Noname1010** [xJon/The-1.7.10-Pack#1536]
Hi, so I was recently discovering an issue where I can load get to the start menu but playing worlds won't work, Please respond asap if you know how to fix it.

**Comment by Noname1010** [comment]
If you don't understand I mean after I join it, it takes me to the main menu I press resume games then it takes me to the server list.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Noname1010** [comment]
Thanks, My fml-client latest.log is                                               


[New Text Document.txt](https://github.com/xJon/The-1.7.10-Pack/files/2087984/New.Text.Document.txt)

**Comment by xJon** [comment]
Please use a paste-tool.

**Comment by Noname1010** [comment]
Sorry, this is the link     





file:///C:/Users/Mohamed/Desktop/Files/Ubuntu%20Pastebin.html

**Comment by xJon** [comment]
This is not a valid link
