### ISSUE TITLE
A fatal error has occured problem

### ISSUE THREAD

**Issue by unnamand** [xJon/The-1.7.10-Pack#1538]
So when i installed the modpack, I tried to join my friend's server and then this error occured "A fatal error has occured the connection has been terminated". I tried to fix it but i do not know how! I have cracked version. I know the problem is probably in the morph mod. I tried to join singleplayer and had same trouble, but i tried with no internet connection and it worked. But i want to play with my friends. How can i fix it?? And can my friend (server owner) do something to fix it?? 

I also got the latest version of java 8.

**Comment by xJon** [comment]
We do not support cracked versions of the game, sorry.
