### ISSUE TITLE
Morph Mod deletes (Temporarily) custom skins

### ISSUE THREAD

**Issue by YuiJaguar** [xJon/The-1.7.10-Pack#1542]
We have an issue that's been consistant on our personal server of like 30 people that the custom skins refuse to load due to a bug in the Morph Mod included. Killing another player allows you to permanently warp into their character model (with the custom skin visible) but warping back will make your skin MC steve. Even if you don't use the Morph mod, your skin is always MC steve to everyone unless they kill you and morph to your skin to see it. 
Have we any clue why this coding is like this?

**Comment by xJon** [comment]
It's a known bug that's been happening for years with Morph and unfortunately there's nothing we know we can do. The good news is that it's a client-side bug, so you're always supposed to see other people's skins properly.
You're saying that's not the case which's strange. Are you sure it's not just a client-side only bug?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if needed.
