### ISSUE TITLE
Problems w/ launching the pack

### ISSUE THREAD

**Issue by Shizukanii** [xJon/The-1.7.10-Pack#1546]
My problem is pretty simple: The pack won't start. I already tried to fix it on my own but with no success. First I came to the idea to check the crash-log, but weirdly there was no crash-log file or folder in the 1.7.10-Pack folder. After that I looked into the console of the launcher in the hope to find my problem. Now after about 2h I don't know what to do anymore.
To be exact what happens when I try to start the pack: After I click on 'play' it loades a few seconds. Then the launcher closes and opens up immediatly. The same goes for some other packs but not all (weirdly).
The probably weirdest thing is that the pack worked fine about 3 or 4 months ago but now causes problems. That's all I can tell right now.

**Comment by Shizukanii** [comment]
Okay, after trying to fix my problem for a few days I've managed it now to acually fix it but unfortunalty I do not know how to delete/ close this post. I am very sorry about that. Thank you for your comprehension.

**Comment by xJon** [comment]
You just click `Close issue` :)
