### ISSUE TITLE
How to properly remove/disable Flan's Mod?

### ISSUE THREAD

**Issue by Elequii** [xJon/The-1.7.10-Pack#1548]
As the title says, how would I go about removing or disabling everything about Flan's Mod server side so it does not affect clients (them crashing)? If I remove the mod from the server simply by deleting it, the client crashes upon connection or says "Internal Server Error".

**Comment by xJon** [comment]
You need to remove the mod from the `mods` folder, and you can also delete the `Flan` folder in the server's folder.
If that doesn't work I'll re-open the issue, just please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).
