### ISSUE TITLE
Server crash from Thaumic Bell

### ISSUE THREAD

**Issue by AcrazyD** [xJon/The-1.7.10-Pack#1550]
Should be easy to fix with CraftTweaker, but that would need my members to add a mod.
[2018-07-16-2.log.gz](https://github.com/xJon/The-1.7.10-Pack/files/2199583/2018-07-16-2.log.gz)
[2018-07-16-3.log.gz](https://github.com/xJon/The-1.7.10-Pack/files/2199584/2018-07-16-3.log.gz)
The Config In Thaumic Horizons that ment to fix the issue only made things worst. We want our users to enjoy the pack with as little bugs as we can mange to fix without makeing them downloading more mods.

**Comment by xJon** [comment]
https://github.com/xJon/The-1.7.10-Pack/issues/1539
As the modpack tries to avoid recipe tweak mods, there's currently nothing to do on our end, sorry.

**Comment by xJon** [comment]
Fixed in version `0.10.5`!
