### ISSUE TITLE
My world doesn't load

### ISSUE THREAD

**Issue by Kalfe** [xJon/The-1.7.10-Pack#1551]
When I click to start the world it starts, but after this he come back to the menu. I've already search a solution on this site, but needs to delete one file that in this version 0.9.8 does't exist (the mod colorchat).
Anyone can help me please? (Sorry if there is something writed wrong, i don't speak english very well)

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by RitoGomes** [comment]
im having the same problem,i click on Play, it blinks, and it returns to the menu
https://paste.ubuntu.com/p/qKVX5DFktp/ this is the link to the Paste Bin with the fml-client-lastest
[fml-client-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/2238598/fml-client-latest.log)
i also sent the .txt file

**Comment by xJon** [comment]
@RitoGomes Try to remove the EnderStorage manually and start again.

**Comment by RitoGomes** [comment]
@xJon remove the mod, and try again?

**Comment by xJon** [comment]
Yes, and if you still experience issues please post the crash report.

**Comment by Kalfe** [comment]
What i need to do??

**Comment by Kalfe** [comment]
hey @xJon , please tell me what i need to do, i really want to play this map

**Comment by xJon** [comment]
@Kalfe Can you load a backup?

**Comment by Kalfe** [comment]
@RitoGomes a backup of the map? or the game/mods?

**Comment by xJon** [comment]
@Kalfe A backup of your save. You can find game backups at `the-1710-pack\backups\`.

**Comment by Kalfe** [comment]
@xJon i already reinstalled this modpack lot of times, so i dont have the backup

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if needed.
