### ISSUE TITLE
Can't create a world

### ISSUE THREAD

**Issue by ZoaMaster** [xJon/The-1.7.10-Pack#1552]
First of all,sorry for my english,now going to the mod: I downloaded the modpack from technic,it open and was all good,but when I try creating a world,It comes back to the main menu.Sometimes a mensage saying "A fatal error has occured,this connection is terminated" appears.What I do?I read many topics but I don't find my question anywhere
![screenshot_305](https://user-images.githubusercontent.com/41567369/43063611-ba4dc4ce-8e32-11e8-9b32-3d446dbd13db.png)

**Comment by ZoaMaster** [comment]
@The-1-7-10-Pack

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by ZoaMaster** [comment]
Hey,I am new using the technic launcher,where can I find this?

**Comment by xJon** [comment]
`.technic\modpacks\the-1710-pack\logs`

**Comment by ZoaMaster** [comment]
https://paste.ubuntu.com/p/FYR3ZY8xjk/

**Comment by xJon** [comment]
`java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\User\AppData\Roaming\.technic\modpacks\the-1710-pack\saves\New World-\NEI\server.cfg (O arquivo já está sendo usado por outro processo)`

Do you have an anti virus scanning or multiple instances open at the same time? Have you tried restarting your computer?

**Comment by ZoaMaster** [comment]
Well, I tried in different computers,and the same error appeared in both.Yes I have an antivirus (avast) and yes I have multiple instances open at the same time,my friends tried and said the error was on RAM but even with multiple instances,I have much ram left over on my pc

**Comment by ZoaMaster** [comment]
again,sorry my english

**Comment by xJon** [comment]
Why do you have multiple instances open at the same time? That's the problem then, probably.

**Comment by ZoaMaster** [comment]
I will try closing everything and open the modpack.Most of time I am chating with friends on discord,watching a live on twitch or listen to spotfy,this is why I have so much intances open

**Comment by ZoaMaster** [comment]
I closed everything and don't worked

**Comment by ZoaMaster** [comment]
My friend suggested that my technic is not original,and this could be causing the error,can you confirm?

**Comment by ZoaMaster** [comment]
I was playing with some friends,one of them have the minecraft and the technic pirate and the others have the original,my friend with the pirate technic can't open,while my others friends with the original have no problems to open,could it be the problem?

**Comment by xJon** [comment]
Yes, but regardless I'm sorry - we don't provide support for non-original copies of Minecraft.
