### ISSUE TITLE
Mod Suggestion

### ISSUE THREAD

**Issue by zpain572** [xJon/The-1.7.10-Pack#1558]
I would personally recommend the mod "Ex-Nihilo" mostly for the reason that, Lava can be an very scare resource unless you venture deep into the caves, although i know the mod can be used to gather resources such as cobalt using the sieve, but cant that be normally disabled? But back to the topic i was speaking about, using this mod, you can slowly turn stone into buckets of lava, although its an semi-long process, and it can help for somewhat early-game users of Tinker's Construct

**Comment by zpain572** [comment]
In addition, although, this mod CANNOT be automated using the mods standard to this modpack, as well as i can see mostly (The Auto Sieve is Unavailable to craft, Cobblestone must be put into crucible to make into lava manually, and sieving is semi-slow anyways to yield noticeable results at first)

**Comment by xJon** [comment]
Probably won't be added to the main modpack, but you can always add it yourself manually. :)
Thank you!
