### ISSUE TITLE
My server wont work

### ISSUE THREAD

**Issue by LoliKidnapper** [xJon/The-1.7.10-Pack#1559]
I've been trying to run my server on my server pc but it doesnt work. Any help would be Appreciated! I'll leave a picture of the error on the post. 
https://cdn.discordapp.com/attachments/466704937368158228/473208976494821387/Capture.PNG

**Comment by xJon** [comment]
Please post your _entire_ `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
