### ISSUE TITLE
Game crashes from kill

### ISSUE THREAD

**Issue by Yohaku90** [xJon/The-1.7.10-Pack#1560]
The game crashes every time I kill something (like a chicken, or a spider) for the first time, since I started the game.

**Comment by xJon** [comment]
Please post your crash report using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Yohaku90** [comment]
I don't have a normal crash log, so this is one of the forge logs.
I hope this will help

https://paste.ubuntu.com/p/SbVbWr6H5T/

**Comment by xJon** [comment]
There is no specific error in the log, are you sure it's the right one?
Anyway, I do know the bug and it may occur due to added mods. Try to downgrade Optifine to version D6.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
