### ISSUE TITLE
Game does not open, CTD before opening

### ISSUE THREAD

**Issue by HydraTek** [xJon/The-1.7.10-Pack#1561]
Latest Log
http://pastetool.com/pastebin/1114076

Crash Report
http://pastetool.com/pastebin/1114078

**Comment by xJon** [comment]
Seems like you're missing the CodeChickenLib mod, try to download it manually and place it in the `mods\1.7.10` folder.

**Comment by HydraTek** [comment]
CodeChickenLib was already installed and in the correct folder, I attempted to use a different version, but still 1.7.10. CTD persists. Which mods in the pack require the CodeChickenCore and CodeChickenLib mods to work? I would probably be fine with removing the associated mods and playing without them, even if it removes some existing items and blocks from saves. Thanks.

**Comment by xJon** [comment]
Can you post the crash report, then? Because your link shows nothing.

**Comment by xJon** [comment]
Try to reset (delete) the configs of the PneumaticCraft mod.

**Comment by HydraTek** [comment]
That was the issue, game works great now. Thank you so much for helping me, I really appreciate it!

**Comment by xJon** [comment]
:)
