### ISSUE TITLE
a fatal error has occurred this connection is terminated

### ISSUE THREAD

**Issue by HPiTeS** [xJon/The-1.7.10-Pack#1562]
My friends when enter in my server this error, they enter in the server and like, 0.5sec afterhave this error

**Comment by HPiTeS** [comment]
When my friend "Thiagodx" trys to enter he's have the fatal error
https://paste.ubuntu.com/p/DkMtGVvFYq/

**Comment by xJon** [comment]
The log doesn't contain the error, can you find the right log?

**Comment by HPiTeS** [comment]
I think I discovered, My friend was using pirate minecraft

**Comment by xJon** [comment]
Well, we do not support it.
