### ISSUE TITLE
Generation problems leading to crash

### ISSUE THREAD

**Issue by Mimi4Craft** [xJon/The-1.7.10-Pack#1564]
Hello i'm here because well i started a new solo game and while exploring i saw a complete empty chunk (i did F3 + a but nothing) then continuing an other way the game crashed i haven't added any mods here is the crash log
[crash-2018-08-12_17.13.15-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/2281062/crash-2018-08-12_17.13.15-client.txt)
Personnaly i'm suspecting bioms'o plenty gen but i'm not an expert 

I'm using the 0.9.8 version of the modpack.

**Comment by Mimi4Craft** [comment]
Well i was trying to send the fml latest log via a pasttool but it seems it didn't worked so i'm sorry but here it is 
[fml-client-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/2281081/fml-client-latest.log)

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file **using a [paste-tool](http://paste.ubuntu.com/)**.

**Comment by Mimi4Craft** [comment]
Here part 1 https://paste.ubuntu.com/p/FRFw4xFYXw/ (sorry but the file was 4Mb so i had to cut it )
Part 2 https://paste.ubuntu.com/p/yZjDqxGPWx/ 
part 3 https://paste.ubuntu.com/p/sFM9tzMkXx/
part 4 https://paste.ubuntu.com/p/Rp7YvNG4qh/
part 5 https://paste.ubuntu.com/p/SmCFrb7V8x/

**Comment by xJon** [comment]
You don't have to cut it as http://paste.ubuntu.com/ supports very large logs.
Anyway, could you please just post your crash report, then?

**Comment by Mimi4Craft** [comment]
https://paste.ubuntu.com/p/9bDtQf9VPj/ Sorry for the delay

**Comment by xJon** [comment]
Go to `\configs\forge.cfg` and change `B:removeErroringTileEntities=false` to `true`.

**Comment by Mimi4Craft** [comment]
Okay thanks the problem is now solved
