### ISSUE TITLE
Texture Issue

### ISSUE THREAD

**Issue by Dejiek** [xJon/The-1.7.10-Pack#1565]
This has been an issue since the first time I launched the pack. It seems the wrapping function for textures is not working. I have attached screenshots to help demonstrate the problem. If I re-install the pack, the issue is temporarily fixed but comes back within around 5-10 minutes of playing (on a multiplayer private server).
Any help is appreciated, thanks!

(Link to image https://imgur.com/gallery/1Fzavpe)

**Comment by xJon** [comment]
Weird, can you test this issue with vanilla Minecraft or other modpacks?

**Comment by Dejiek** [comment]
How strange! I just tested vanilla 1.7.10 and the glitch continues to happen. I've found the cause, it happens 100% of the time after I go into the nether. However, this seems not to be an issue with the modpack and just my client. My bad!

**Comment by xJon** [comment]
I'd suggest you too Google the problem and see if other people online are experiencing it.
Might be a problem with your graphic's driver or something along these lines.
