### ISSUE TITLE
Mod Suggestion

### ISSUE THREAD

**Issue by SirHaxe** [xJon/The-1.7.10-Pack#1569]
"the river mod", it adds some nice looking river (picture attached) and i think this would be really cool with the wolrd gen

![](https://i.imgur.com/lupGduc.png)

![](https://i.imgur.com/MgII401.png)

![](https://i.imgur.com/4iYcE4x.png)

![](https://i.imgur.com/p6sET5d.png)

![](https://i.imgur.com/xNGinQ2.png)

![](https://i.imgur.com/lX2sssR.png)

![](https://i.imgur.com/SFtig28.png)

**Comment by xJon** [comment]
Probably won't be added to the main modpack, but you can always add it yourself manually. :)
Thank you!
