### ISSUE TITLE
Insights and evolutions of Quests

### ISSUE THREAD

**Issue by studiodev** [xJon/The-1.7.10-Pack#157]
Hello !

I've played a lot with your (excellent) modpack and I want to share with you some ideas to improve the quest mechanism. Just keep the ideas you like, and sweep the others, I don't expect justification :)

Bugs :
 * Quantum armor and I believe I can float quests cannot be achieved (I've crafted all the stuff but it's not detected)
 * Promise land : the staff is no longer craftable

Improvement :
* Big reactor is good as a step 1. You can add a step 2 introducing recycling (craft a cyanite reprocessor, have some bluetorium ingot). And a third step, build an actively-cooled reactor (2x reactor coolant port, turbine cases, turbine glasses, turbine controller, turbine power port, 2x turbine coolant port, rotor shafts, rotor blades, and some coil materials)
* Make the Galacticraft quest more incremental: Step 1 to the moon, step 2 to mars, step 3 to asteroid. It will be more motivating.
* Thaumcraft : You can add a "fight" quest : defeat the crimson knights (they spawn in the word). Validated if the player wear a complete crimson cult armor, and own the crimson rites book (rare loot).

New quests for high-end stuff
* Construct a complete IC2 UU-Matter system to clone items from scrap. (Craft Mass Fabricator, Replicator, Pattern Storage, Scanner, (Combined) Recycler, and maybe some mB of UU-Mater)
* Ender quarry (a lot better than BC quarry) with some upgrades

I think it's a good idea that quests allow the player to discover very usefull items/engines. The difficulty is to create original quests, better that "Craft this stuff, you will see it's good"
 * Tesseract
 * Chests from the IronChest mod (iron/gold/diamond/ender/crystal)
 * Uncrafting table
 * Advanced Enchantment table
 * Auto-anvil
 * MmmMmmMmmMmm (easy one!)
 * and many more  

You should add quest related to more mods. For example :
 * Flan's mod (craft a copter, an ak47 and an rpg !)
 * RailsCraft (craft an electric locomotive, rails and all the stuff related)
 * Pam's Harvestcraft (craft fun foods like delexu cheeseburger, epic bacon, cherry cheesecake, banana split, nutella, marsmallows, frosted donut....). And some wine (grape wine, ale, apple cider)
 * Raid a RogueLike Dungeon (I don't now how to validate this quest, maybe we can configure this mod to loot something unique)
 * Automate some tasks (automatic farm for example)

Some others ideas :
 * Guide the player to craft the best non-electronic stuff, in obsidian ingots.
 * Guide the player to raid many dunjons : loot all minecraft disk and craft a jukebox.
 * Find something that require the player to build a full automatic mining/sorting/smelting system. Something like : have 1 M cobblestone (usefull for the Bedrockium quest), and 2000+ diamond/emerald/gold/iron ingots.

Voilà, it's all i've in my head. 
Thanks for this awesome mod :)

**Comment by da404lewzer** [comment]
Looks good. Breaking Galacticraft into more bite-sized pieces would be a great move by the way. RailCraft would be another good one because nobody uses carts anymore :/

**Comment by The-1-7-10-Pack** [comment]
- The bugs have already been reported:
- Improvements: You have very good ideas but I can implement them all. If you wish to help the HQM Project, while keeping the main theme, I'll support it. I should note that I really like your ideas and I do think they keep the main theme.
More to that:
 - The "improvements" part: just make the quests better
 - The "New quests for high-end stuff" part: I accept both ideas, they should be both on the tech block of the quests
 - The third part: Very cool ideas. You can put the really cool & Useful stuff each on his type of the three blocks: Tesseract and chests on tech, Uncrafting table on adventure, Advanced Enchantment table on magic, and so on.
 - The last part: It doesn't really connect to the "high-end" theme.

**Comment by The-1-7-10-Pack** [comment]
Any comment?

**Comment by The-1-7-10-Pack** [comment]
Would like to implemet more of the ideas here, any way to reach you?

**Comment by studiodev** [comment]
Sorry I don't play anymore to Minecraft. Maybe I will retry in the future :)

**Comment by The-1-7-10-Pack** [comment]
@studiodev That's a shame!

**Comment by xJon** [comment]
Would still like to implement more of the ideas provided here. Reopening.
