### ISSUE TITLE
Game crashes on loading

### ISSUE THREAD

**Issue by xBurqer** [xJon/The-1.7.10-Pack#1570]
I really do need help when i start it crashes when it tries to open

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xBurqer** [comment]
[fml-client-latest.log] https://github.com/xJon/The-1.7.10-Pack/files/2323840/fml-client-latest.log

**Comment by SirHaxe** [comment]
until jon provides a fix you could remove the magic bee mod, thats casuing the crash! (line 16357)

**Comment by TheSaiyanGod** [comment]
@SirHaxe Can you see the problem in this log?

https://paste.ubuntu.com/p/TYrtYvJ3yZ/

**Comment by SirHaxe** [comment]
@TheSaiyanGod openblocks, try redownloading the pack, did you change some mods?

**Comment by xJon** [comment]
Currently there's no further support to MagicBees so as long as you didn't modify the modpack things should work. If they don't anyway, consider re-installing, reporting the bug in [their repo](https://github.com/MagicBees/MagicBees/issues) or removing the MagicBees mod.
