### ISSUE TITLE
The world doesn't load

### ISSUE THREAD

**Issue by TheSaiyanGod** [xJon/The-1.7.10-Pack#1571]
I added some mods in this pack (Mo Creatures and Aether) and remove some others so it does not get so heavy. And the first time I got into the game and play a little, but after a while it crashes and I can't load the world anymore. Could anyone help?

https://paste.ubuntu.com/p/WCrvrzQR3X/

**Comment by xJon** [comment]
I'm sorry but the modpack doesn't provide support for custom versions and extra mods.
Regardless, it seems like the NotEnoughResources mod doesn't like the changes you made; you can consider removing it.

**Comment by TheSaiyanGod** [comment]
a

**Comment by TheSaiyanGod** [comment]
I know that modpack doesn't provide support for extra mods, but I really need help. I deleted NotEnoughResources and the game didn't  crash, but after I left and tried to log in again but could not, the game keeps loading. Suggestions?

**Comment by TheSaiyanGod** [comment]
Here the latest log

https://paste.ubuntu.com/p/TYrtYvJ3yZ/

**Comment by xJon** [comment]
Well, now `wirelessredstone` is appearing in the logs, so maybe that could be related.
Anyway, it does say it's crashed:
`[12:27:32] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Fabiano\AppData\Roaming\.technic\modpacks\the-1710-pack\crash-reports\crash-2018-08-27_12.27.32-server.txt`

**Comment by TheSaiyanGod** [comment]
@xJon Yes he crashes, because when I try to load the game he stays a long time in the '' loading the world '' part and nothing happens, and soon after he comes back to the technic.
I tried deleting Open Blocks mod as the guy said in another thread, but it did not work. I've reinstalled modpack several times but I always stop at that part.

Crash report:

https://paste.ubuntu.com/p/hpx6gCCDdN/

**Comment by xJon** [comment]
No idea. You can try to ask online at mods support forums
