### ISSUE TITLE
Error downloading the modpack on the technic launcher

### ISSUE THREAD

**Issue by FlutterButters22** [xJon/The-1.7.10-Pack#1573]
So when I start downloading the the modpack on the Technic Launcher everything is fine but right when I get to downloading tconstruct-1.8.8.zip it stops and gives me an download error window saying "Failed to download http://solder.endermedia.com/repository/mods/tconstruct/tconstruct-1.8.8.zip. please consult the modpack author" any help would be appreciated c:

**Comment by xJon** [comment]
Well, trying to download from the link right now is working for me. Try to test it yourself.
Maybe just try to re-install, that's all. Everything should be working.
