### ISSUE TITLE
Cannot connect to my own server.

### ISSUE THREAD

**Issue by Zelongdragon** [xJon/The-1.7.10-Pack#1575]
I cannot connect to a server hosted on another local computer. My friends have been able to connect through my IP, but I myself am not able to connect. I have used my own ip, 0.0.0.0, 127.0.0.1, and localhost. I have also tried adding :25565 to the end. The error message I receive is "Java.Net.ConnectException: Connection Refused: no further information:" (Without quotes). Thank you for your time.

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Zelongdragon** [comment]
https://paste.ubuntu.com/p/6rs7nb3gvk/

Hope this is useful enough.

**Comment by xJon** [comment]
Can you please include a log of the server while you're trying to log in? Doesn't show here.

**Comment by Zelongdragon** [comment]
I have tried to log on multiple times in this instance. My Minecraft is not noticing that I have the server open at all, and not noticing a connection to the server on my other computer. I have tried multiple packs in the past and they all have worked.

**Comment by xJon** [comment]
Is this issue still unresolved?

**Comment by Zelongdragon** [comment]
It is, but feel free to close it if you wish. I couldn't make it work on my own, thank you for trying to help.

**Comment by xJon** [comment]
Odd.
