### ISSUE TITLE
My world is not loaded and after that it closes

### ISSUE THREAD

**Issue by Menininha** [xJon/The-1.7.10-Pack#1576]
Whenever I try to play in single-player mode, the following message appears: "A fatal error has occured, this conection is terminated"

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Menininha** [comment]
https://paste.ubuntu.com/p/fqfq8dcptj/

**Comment by Menininha** [comment]
> Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

https://paste.ubuntu.com/p/fqfq8dcptj/

**Comment by xJon** [comment]
In your log there's no such error. Can you find the log of the session in which you got that error?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
