### ISSUE TITLE
Issue Installing/Starting Server

### ISSUE THREAD

**Issue by C-Dorr** [xJon/The-1.7.10-Pack#1583]
Hi Jon, 

This looks like I might just be a dumb oversight on my part, but when running the server launcher, I receive this error: https://paste.ubuntu.com/p/6vjFqvMGZZ/

I've got Java 10 installed, but when I run the modpack through the Technic Launcher, it seems to use 1.8.0_171 64Bit. 

Provided this is an issue with the Java version I am using, will a friend with a different java version/32bit be able to connect? 

Thanks, Chris

**Comment by xJon** [comment]
Seems like the server is using Java Development Kit (JDK). What you need is Java Standard Edition (SE).
Also, you might want to consider downgrading back to Java 8 as I'm not sure how well Forge supports that version of it.
Also, while using Java 32 bit one cannot dedicate more than 1GB of RAM to the modpack, therefore it is not possible.
