### ISSUE TITLE
Server process killed after about 5 Hours.

### ISSUE THREAD

**Issue by Freshhalte** [xJon/The-1.7.10-Pack#1584]
Hello.

My problem is, that the server stops working after about 5 Hours. The console just says, that ./LaunchServer.sh has been killed. This happens after an AromaBackup, but I don't think that's the problem, since several backups have already been made within these 5 hours. Also the problem does not cause a crashlog.

**Comment by xJon** [comment]
Weird. Do you run the server on your machine?

**Comment by Freshhalte** [comment]
I run the server on a Debian V-Server.

**Comment by Freshhalte** [comment]
![console](https://user-images.githubusercontent.com/39203967/46249488-32844580-c42a-11e8-8efc-9bceb5fdc879.jpg) Here's a screenshot of the console after a crash.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
