### ISSUE TITLE
game crahes when mob dies

### ISSUE THREAD

**Issue by supersliser** [xJon/The-1.7.10-Pack#1586]
the game runs OK (a bit laggy) however as soon as I kill a mob or I die, I get sent back to the title screen

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by supersliser** [comment]
> Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

I don't mean to sound like a noob but where would I find that

**Comment by R3dPh0nix** [comment]
I have the same issue
Go to the Pack in the Launcher > Modpack options > open Folder > In the log Folder
My log file: https://paste.ubuntu.com/p/dTtdFnjH6V/

**Comment by supersliser** [comment]
https://paste.ubuntu.com/p/XncVvmshYh/

**Comment by xJon** [comment]
@supersliser Your log seems a lil empty, but you might have the same problem as @R3dPh0nix: you guys should mention if you have added extra mods. It's mentioned specifically in the guidelines of posting issues.
You can try to downgrade your Optifine version to D6, but we can't offer more than that support for modified versions of the pack.
