### ISSUE TITLE
Game crashes when launching the world

### ISSUE THREAD

**Issue by Accir** [xJon/The-1.7.10-Pack#1588]
https://paste.ubuntu.com/p/DXn3vtNNh6/
https://paste.ubuntu.com/p/sfYtCjbjnW/

**Comment by xJon** [comment]
Backup your save and try to remove the ChickenChunks mod and launch the server.

**Comment by Accir** [comment]
Now i get disconnected from the server with the message "A fatal error has occurred, this connection is terminated" https://paste.ubuntu.com/p/JXMV5tFfCT/

**Comment by xJon** [comment]
Did you remove it from both client and server side?
Also, is your server online and using a genuine version of Minecraft?

**Comment by Accir** [comment]
I'm not running it on single player so i only removed from my mods folder and I'm using genuine version of Minecraft

**Comment by Accir** [comment]
Reinstalled the modpack and the technic launcher, all working now. Thanks for the help :)

**Comment by xJon** [comment]
Okay, good, you're welcome :)
