### ISSUE TITLE
PureBD texture pack issues

### ISSUE THREAD

**Issue by mrrunedj4** [xJon/The-1.7.10-Pack#1589]
I download the 128x patch and the pureBDcraft texture pack off the official site, however when I go to turn either of them on in the resource pack folder the game freezes for a few moments to loed new textures only for it to just reset to defuelt and fail to look the texture pack and patch.
is this a fix for this?

**Comment by xJon** [comment]
You have to also download the vanilla texture pack for 1.7.10 and load it up as well.

**Comment by mrrunedj4** [comment]
I have both the patch and the texture pack off the official site as I stated.

**Comment by mrrunedj4** [comment]
I was unable to figure out whats going on with the texture pack, despite x128 having issues x64 works fine.

**Comment by mrrunedj4** [comment]
I have tried 4, 8, 12 GB of ram, the texture pack will not work with any of these amounts, as mentioned it seems to only be the 128x version that has this issue.

**Comment by xJon** [comment]
Could be. Unfortunately we can't really provide support for the Sphax patch, so simply use the x64 version.
