### ISSUE TITLE
How do I create a server?

### ISSUE THREAD

**Issue by heartstopper3** [xJon/The-1.7.10-Pack#1591]
I have downloaded the server file, the most recent one, and I have also gotten the correct java for this, and I opened it to the LaunchServer file and i get this error: 
![image](https://user-images.githubusercontent.com/44346866/47271286-17928600-d53d-11e8-9501-e93430c8832f.png) 
Then I go to edit it and I don't know what to do..
![image](https://user-images.githubusercontent.com/44346866/47271290-25480b80-d53d-11e8-9eb9-fc87324b13ed.png)
Am I supposed to change something in the notepad or something else? Help please!

**Comment by xJon** [comment]
You closed the issue?
