### ISSUE TITLE
Poor Performance without opdefine, errors and disconnects with it.

### ISSUE THREAD

**Issue by mrrunedj4** [xJon/The-1.7.10-Pack#1592]
I currently have a ryzen 7 1700 @4ghz, 16 gb of DDR4-2133 and a gtx 1080 along with the mod pack on a high end ssd, however it runs extermly poorly despite my beefy computer.

I've tried installing several versions of op define for 1.7.10 mine craft however every one of them has diffrent issues, the first when killing mobs it will kick me off the server, the second will randomly give me a forced disconnect error and I have even tried to disable fast craft to no avail.

When opdefine was installed prior to the occurrence of the errors and disconnects it seemed to run very well.

**Comment by xJon** [comment]
First of all, don't modify the pack and expect everything to work perfectly. The pack is stable as-is.
If you add Optifine, add only version D6 as it's the latest version supported by the pack.
Additionally, you should try to tweak some of the video settings, along side with using Optifine correctly.
Make sure VSync is off, FPS limit is on Unlimited, and try to use Fast Render, it might help significantly.
