### ISSUE TITLE
Looking for assistance with a crash

### ISSUE THREAD

**Issue by KabrTheLeigonless** [xJon/The-1.7.10-Pack#1593]
Hello, when i launch the pack, the screen goes black, stays black for about 2 minutes, then closes the game.

https://paste.ubuntu.com/p/ssgyxtFR65/

Any help i could get with this would be awesome

**Comment by xJon** [comment]
Try to reset PneumaticCraft's config files by backing them up and then deleting them.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
