### ISSUE TITLE
Can't join friends server please help

### ISSUE THREAD

**Issue by CaptainEthanz** [xJon/The-1.7.10-Pack#1594]
Every time I try joining my friends server I can't join but my others friends can, I've tried my firewall relaunching redownloading everything please help.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).
Additionally, try posting a screenshot of the error you're getting.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
