### ISSUE TITLE
Server Stuck unLoading Dimension 6

### ISSUE THREAD

**Issue by mrrunedj4** [xJon/The-1.7.10-Pack#1595]
Server Wont unload Dimension 6, have tried launching from the bat repeatedly with the same result. 

using server version 0.9.8

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
