### ISSUE TITLE
Invalid maximum heap sizs FIXED!

### ISSUE THREAD

**Issue by SweBear** [xJon/The-1.7.10-Pack#1596]
Hi dont know what problem are. But when i look in. LanchServer i Don¨t se any Xmx4g

When i launch the server this comes up. Please Help!
OS is 64
Invalid maximum heap size: -Xmx4G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to continue . . .

**Comment by SweBear** [comment]
FXED! I just updated Java

**Comment by xJon** [comment]
👍
