### ISSUE TITLE
Modpack download issue.

### ISSUE THREAD

**Issue by Crashpotato** [xJon/The-1.7.10-Pack#1597]
Hi there.
I wanted to download the 1.7.10 pack via the technic launcher but can´t get it to work. The download always stops when trying to download http://solder.endermedia.com/repository/mods/witchery/witchery-0.24.1.zip although i can download it via the link directly. Also my friends, which are my neighbours, did not have any problems downloading the pack. I have tried everything from re-installing the laucher and the pack to changing the hard drive that it will be installed to. But nothing works at all. It would be great if somebody could help me with this. 
Thank you

**Comment by xJon** [comment]
Try to uninstall and install again. The Technic Launcher was a little glitchy a couple of days ago.
Update of how it goes.
