### ISSUE TITLE
Game crashes on world open

### ISSUE THREAD

**Issue by Kiboko44** [xJon/The-1.7.10-Pack#1598]
Hello,
I need your help with some error that I'm getting. Every time I try to open my singleplayer world (that I created just while before that) my game crashes. 
Here are the crash logs: 
[https://paste.ubuntu.com/p/8rfXdDz8RH/](https://paste.ubuntu.com/p/8rfXdDz8RH/)

**Comment by xJon** [comment]
Try to manually remove the VoxelMap mod and then open your world again.
If that works, try to add it back in.

**Comment by Kiboko44** [comment]
Thank you, that solved my issue (I can now play even with VoxelMap). But there is another issue. If I open the world while I'm connected to the internet (when I'm not it works just fine, but I don't have my skin), the world immediately closes and a text pops up (something like "A fatal error occured, your connection was terminated"). Then I click close on the message and it puts me into the multiplayer server select screen. So I would like to know if there is any solution to that problem. Here is the log:
[fml-client-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/2544894/fml-client-latest.log)

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/)

**Comment by Kiboko44** [comment]
Here it is:
https://paste.ubuntu.com/p/F79xXb2xqX/

**Comment by Kiboko44** [comment]
The game doesn't crash, the world just won't open (it will close after opening it) and a message pops up saying "A fatal error occured, your connection was terminated".
Screenshot:
https://pasteboard.co/HMEyBnb.jpg

**Comment by Maniac142** [comment]
xJon i need your help. Like a https://github.com/xJon/The-1.7.10-Pack/issues/733 but my java is 64 bit. How can i fix this? (My english is bad sorry)

**Comment by xJon** [comment]
* @Kiboko44 Can you please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/)?
* @Maniac142 Please open your own issue and post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Kiboko44** [comment]
Here it is:
https://paste.ubuntu.com/p/v39Kn8MTxT/

But again, it has no crash log, because the game doesn't crash, it just shows the message.

**Comment by xJon** [comment]
@Kiboko44 Try to do the same thing you did with VoxelMap, but with the Morph mod.

**Comment by Kiboko44** [comment]
I tried it, and it didn't solve my problem. But that's ok, I can play offline just fine. You can close this issue now. Thanks.

**Comment by xJon** [comment]
That's very odd. I'd like a log of the error when VoxelMap is removed, but I can close the issue.
Don't refrain from posting what I've requested for further assistance.
