### ISSUE TITLE
I can't do nothing.

### ISSUE THREAD

**Issue by MisterMatiu** [xJon/The-1.7.10-Pack#1602]
I died suffocated on the floor, and when I died my game crashed so I relog and realized that I was leaving my grave but I live, I try to break the blocks to get out of the ground and I could not move as I returned to where I was, so I tried to use / spawn or / home but it said that I could not use the chat, and try to reinstall the modpack but it is not solved, and I would like to know if you can help me. I died in -14150 70 +4272

**Comment by xJon** [comment]
I don't know what you're referring to but this is modpack support.
The modpack doesn't have an official server it represents and so you should contact the staff of the server you're playing in.
