### ISSUE TITLE
Can't Download

### ISSUE THREAD

**Issue by madasher** [xJon/The-1.7.10-Pack#1603]
When ever I try to download, It can't download botania. I have deleted it and tried to redownload numerous times. I have also tried to download the mod and put it in the folder but it just deletes it. Please help, Thanks!!

**Comment by xJon** [comment]
Please try to completely uninstall the modpack and then try to install again.

**Comment by madasher** [comment]
I did, the same thing happened

**Comment by xJon** [comment]
Try to go to the Technic folder and manually delete the folder inside of `modpacks` named `the-1710-pack`.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
