### ISSUE TITLE
Game crashes when joining server

### ISSUE THREAD

**Issue by Skyminion** [xJon/The-1.7.10-Pack#1604]
My game crashes whenever I join a server, however I can join a single player server no problem. Here is my crash log, please help https://paste.ubuntu.com/p/bd5Ykk8vQx/ By the way I have tried completely reinstalling the modpack AND the technic launcher.

**Comment by xJon** [comment]
Can other players join the server?
Also you can try to load a backup of the world on the server side.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
