### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by titanic1216** [xJon/The-1.7.10-Pack#1605]
My game crashes and goes back to technic launcher before it can get to the minecraft menu screen where it gives single player and multiplayer options. I'm using 1.8.0_191 64 bit.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
