### ISSUE TITLE
Mod Rejection

### ISSUE THREAD

**Issue by LordxCthulhu** [xJon/The-1.7.10-Pack#1607]
I made my own server on forge and everytime somebody joins "Mod Rejections," without the quotations, and the mods rejected include squidless, ThermalExpansion, reccomplex, RedstoneArsenal, MineFactoryReloaded, TConstruct, ThermalDynamics, ThermalFoundations, NetherOres.

https://user-images.githubusercontent.com/29588110/48326009-1dcfcb80-e5ec-11e8-9210-f18139136668.png

**Comment by xJon** [comment]
Well, are you setting up a server and trying to login both with the modpack, and of the same version?
If so, please provide the `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by LordxCthulhu** [comment]
We got it after a bit of help, but thank you anyway

**Comment by xJon** [comment]
:+1:

**Comment by DarkVeneno** [comment]
I'd like to know how you solved it as I am getting the same issue

**Comment by xJon** [comment]
@DarkVeneno This probably means you are starting a vanilla server rather than a modded server. You need to use the launch script that targets the Forge jar.

**Comment by DarkVeneno** [comment]
I see. Guess the 0.676s start time WAS too good to be true xD.

Thing is, I'm using the LaunchServer.bat script, provided by the pack. And when I look at the console I still see FML messages.
After digging around a bit, it seems that if I double click the LaunchServer.bat script it runs correctly and loads all the mods, but if I create a shortcut to it on the desktop only 3 mods load!? This is weird. Well technically the issue has been solved. Thanks!
