### ISSUE TITLE
Error running server for 1.7.10PACK

### ISSUE THREAD

**Issue by hoshinokabii** [xJon/The-1.7.10-Pack#1609]
Hi,

I am having issues with trying to host a server, gives me a "The state engine was in incorrect state errored and forced into state available", attached are the logs.

Any help would be great, thanks! 

[fml-server-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/2588237/fml-server-latest.log)

**Comment by xJon** [comment]
Hi, you've closed this issue, is it resolved?

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file **using a [paste-tool](http://paste.ubuntu.com/)**.
