### ISSUE TITLE
Shaders button not showing up?

### ISSUE THREAD

**Issue by queenizzy** [xJon/The-1.7.10-Pack#1612]
I got optifine to work, but I don't see the ingame shaders button.

**Comment by xJon** [comment]
As I've already said in issue https://github.com/xJon/The-1.7.10-Pack/issues/1611, we can't provide support for all external mods here. You can try in the Technic forums/Discord guild or in Forge's. You can also try to simply Google for a tutorial for Minecraft 1.7.10.
