### ISSUE TITLE
Game crashes when playing singleplayer , please help

### ISSUE THREAD

**Issue by LuHaos2150** [xJon/The-1.7.10-Pack#1613]
Hello , i have issues with this modpack , i dedicated 4 gb ram for play , but when i create or play a singleplayer world, jumps an error ''Lost Connection'' ''A fatal error has ocurred, this connection is terminated'' i have an intel i5 6200U , 8 gb ram and a radeon R5 M335 maybe i have to dedicate more ram? i don't know because i don't have my pc (my brother needs it and he gives me my pc tomorrow)

I readed that i have to  share my logs , where i find that??? please help

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).
Read the [guidelines](https://github.com/xJon/The-1.7.10-Pack/blob/master/CONTRIBUTING.md) if you need help to understand where to find the log.

**Comment by LuHaos2150** [comment]
No problem , already fixed , thank you so much ;)

**Comment by xJon** [comment]
:)
