### ISSUE TITLE
server is crashing

### ISSUE THREAD

**Issue by aiakon** [xJon/The-1.7.10-Pack#1614]
i launched LaunchServer.bat and i set the eula.txt true but server is crashing 
[crash-2018-11-24_16.58.29-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/2612313/crash-2018-11-24_16.58.29-server.txt)
this is crash report

pls help

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
