### ISSUE TITLE
Server does not start anymore [PortalGun]: [4.0.0-beta-6] Save data does not exist!

### ISSUE THREAD

**Issue by v2gx** [xJon/The-1.7.10-Pack#1615]
Hello guys, I need help with an issue!
Im hosting a 1.7.10-Pack Server and everything went well over the past 2 weeks.
But now, when I restarted the root server, the 1.7.10Pack-Server won't start anymore.
It stucks on the point
"[12:39:38] [Server thread/INFO] [PortalGun]: [4.0.0-beta-6] Save data does not exist!"

**Comment by xJon** [comment]
You've closed the issue.
Is it resolved?

**Comment by xJon** [comment]
Yes, it might have a mod-bug with the stands, nothing we could do about it.
I think maybe @clienthax knows something about it. Maybe.
