### ISSUE TITLE
Weird crash after using sorting button on chest

### ISSUE THREAD

**Issue by thechubbypanda** [xJon/The-1.7.10-Pack#1620]
I pressed the z sort on a default Minecraft chest and the game crashed. Crash report: https://pastebin.com/kTsqjezp

**Comment by xJon** [comment]
Please post your crash log file **using a [paste-tool](http://paste.ubuntu.com/)**.

**Comment by thechubbypanda** [comment]
> Please post your crash log file **using a [paste-tool](http://paste.ubuntu.com/)**.

Sorry, I've changed it now.

**Comment by xJon** [comment]
Does it happen only with a specific chest?
Can you go back to your world again no problem?
Does that chest contain a Factorization-mod item?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
