### ISSUE TITLE
Can someone plz help me :c ? (Server Crashes)

### ISSUE THREAD

**Issue by AdrianDieDose** [xJon/The-1.7.10-Pack#1621]
Hey,
so i startet a server for me and my friends and everything seemed fine till it crashed and now doesn't stop crashing :c
I dont want to start a new world bc we worked quite a bit on the server :/
I think it happens when i walk in a specific direction ( Maybe something loads in that the server doesn't like ?)
I hope someone can help <3

Here is the crash report:

https://paste.ubuntu.com/p/DjrY4k5Stx/

**Comment by xJon** [comment]
Odd. Did you put down any chunk loaders?
Did you modify the pack in anyway?
Does the crash still happen if you remove FastCraft from server-side?

**Comment by AdrianDieDose** [comment]
Hey,
thx for the fast reply ! <3

-We did not put any chunk loaders in.

-I had some problems setting up the server at the beginning (Bc we switched providers) and moved the world map and server around but at the end I set up the server with a fresh and clean 0.9.8... started it and when it was finished I moved the world map in (I didnt use the world map that i moved 5 times i used the original that was fresh from the first Server that i didnt tinker with)
Idk if this world switcheru was the reason i broke something :/

I now removed FastCraft and join for 1 sec and when the map loads the server crashes :c

New Crash log if needed:
https://paste.ubuntu.com/p/VbPm898t8T/

**Comment by AdrianDieDose** [comment]
> Odd. Did you put down any chunk loaders?
> Did you modify the pack in anyway?
> Does the crash still happen if you remove FastCraft from server-side?

Hey,
thx for the fast reply ! <3

-We did not put any chunk loaders in.

-I had some problems setting up the server at the beginning (Bc we switched providers) and moved the world map and server around but at the end I set up the server with a fresh and clean 0.9.8... started it and when it was finished I moved the world map in (I didnt use the world map that i moved 5 times i used the original that was fresh from the first Server that i didnt tinker with)
Idk if this world switcheru was the reason i broke something :/

I now removed FastCraft and join for 1 sec and when the map loads the server crashes :c

New Crash log if needed:
https://paste.ubuntu.com/p/VbPm898t8T/

**Comment by AdrianDieDose** [comment]
I fixed it by not bambozling with the server and world.
I think its an bad idea to tinker with the server and the world and switching them around.
You can delet this thread (Idk how so ehh.. sorry xD)

And thx for replying so fast and trying to help.
Cool modpack btw !

**Comment by xJon** [comment]
Alright. Simply seems like corrupted chunks, maybe you closed the server while it was saving or something similar. 
* One solution would be to restore a world backup (the modpack makes backups automatically).
* A second solution would be deleting the corrupted region file, seems to be `2,0` but backup before deleting.
Good luck!
