### ISSUE TITLE
New Server doesn't start (no log created)

### ISSUE THREAD

**Issue by fbMarcel** [xJon/The-1.7.10-Pack#1622]
I tried to start a server but it won't even start.
There is no latest-server-fml.log created. It only shows this when I try to start it:

`A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more`

**Comment by fbMarcel** [comment]
I use a ubunt server with:
`openjdk version "10.0.2" 2018-07-17`
`OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)`
`OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)`

And the problem is that it doesn't create the log file because the server doesn't even start.

**Comment by xJon** [comment]
You'd need to make sure you have proper Java version 8 64 bit installed on your machine.

**Comment by fbMarcel** [comment]
It's a ubuntu server and the proper Java with the newest version is installed. I also tried other versions of Java but it will always give me the same results.

**Comment by fbMarcel** [comment]
Ok, my java was the newest so it didn't work. Now the forge server starts but there is the next problem.

Here is my latest log:
https://pastebin.com/raw/NfFJDGxx

**Comment by xJon** [comment]
You seem to have JDK installed on your computer, which stands Java Development Kit. You need Java SE, which stands for Java Standard Edition.

**Comment by fbMarcel** [comment]
The Java is working now. If I start a server without mods it's all working.

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by xJon** [comment]
As you're using Linux, did you click `LaunchServer.sh`?

**Comment by fbMarcel** [comment]
There was no such file. I created my own start script:

`#!/bin/sh
cd /var/minecraft/Modpack
screen -S "Modpack" -U -m java -server -Xmx5G -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar`

**Comment by fbMarcel** [comment]
I didn't know there was a server download. I used it now but it still doesn't work
https://paste.ubuntu.com/p/FxspNk8H75/

**Comment by xJon** [comment]
Seems like an okay server starting log only that it was stopped, maybe you can try again and send me a different log?
Also how could you setup a server without using the server package?

**Comment by fbMarcel** [comment]
Ok, I just realized my stupid mistake. I didn't agree to eula.
Now everything works thank you very much.

I only have one last question:
Do you know McMyAdmin and how I can get this to work with the modpack?

**Comment by xJon** [comment]
Nope. But I'm glad you solved your issue.
