### ISSUE TITLE
Attempting to use Plugins + this modpack, users get "Fatally missing blocks and items"

### ISSUE THREAD

**Issue by Ucxb** [xJon/The-1.7.10-Pack#1624]
Clients, when attempting to join my server, get the error "Fatally missing blocks and items" despite using the modpack I provided, which was this one. The server is working perfectly, but the logs are saying that users are missing "kimagine", which from what I've gathered, is the mod that updates KCauldron. Is there anyway AT ALL that I can fix this? Or perhaps another way I can use plugins + mods? I've tried Thermos and I encounter the same error. Please help

[Here's my log](https://github.com/xJon/The-1.7.10-Pack/files/2692910/latest.log)

**Comment by xJon** [comment]
Unfortunately I don't provide support for plugins.
I could try to help if you can post your log using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Ucxb** [comment]
https://paste.ubuntu.com/p/M5Mrv9F9Wc/

**Comment by Ucxb** [comment]
> 
> 
> Unfortunately we don't provide support for plugins with the modpack.
> I could try to help if you can post your log using a [paste-tool](http://paste.ubuntu.com/).

https://paste.ubuntu.com/p/M5Mrv9F9Wc/
