### ISSUE TITLE
Modpack Launches; Won't Let Me Load My World

### ISSUE THREAD

**Issue by JamesSchwellenbach** [xJon/The-1.7.10-Pack#1625]
I was actually just playing the 1.7.10 Pack earlier today. However, after I shut my laptop down, so it could rest, as well as I, when I booted my laptop back up, the modpack won't let me play. It would get to the main screen where I could choose Singleplayer or Multiplayer, but after I choose my world, it would take me back to the Technic Launcher.

I'm not sure what the problem could be, I checked all the areas I had seen suggested previously, but couldn't find the problem.

Here is the pastebin of the crash report:
[https://paste.ubuntu.com/p/cF2SCbRV73/](https://paste.ubuntu.com/p/cF2SCbRV73/)

**Comment by xJon** [comment]
It's absolutely known that leaving Minecraft without properly saving and exiting the game causes world corruptions. All I can suggest you is to use a world backup from `...\modpacks\the-1710-pack\backups`.
Good luck!
