### ISSUE TITLE
Custom Server Setup

### ISSUE THREAD

**Issue by DeathBot9000** [xJon/The-1.7.10-Pack#1626]
I am new to modding and am trying to set up a privet server and I am having trouble getting it started
Any help is appreciated
also what mods are client side only?
Cras Log 
**EDITED: Please use a paste-tool - https://pastebin.com/Yi59gD0v**

**Comment by DeathBot9000** [comment]
wow, I feel so dumb, but thanks.

**Comment by xJon** [comment]
👍
