### ISSUE TITLE
Black screen, nothing else

### ISSUE THREAD

**Issue by LevenLikesMilk** [xJon/The-1.7.10-Pack#1627]
okay okay okay,

when i start the game, it just shows a black screen, nothing else.
i tried uninstalling the pack, then reinstalling... but it did nothing. so oof
i am using 4 gb of ram, and i have 8 i can use, i have 64 bit java, AND its been loading for a few days perfectly fine.

i have no idea why this is happening

**Comment by LevenLikesMilk** [comment]
it does NOT crash, and it has been loading for about 35 maybe 40 mins now

**Comment by LevenLikesMilk** [comment]
oh okay now its loading for some reason, just give it 15 mins...

im closing this

**Comment by xJon** [comment]
👍
