### ISSUE TITLE
How Do I get access to permissions?

### ISSUE THREAD

**Issue by Bllayze** [xJon/The-1.7.10-Pack#1628]
I want to make my server on creative but it's saying that I don't have access to permissions when I type /gamemode 1 in game.

**Comment by xJon** [comment]
Did you op'd yourself?

**Comment by SpaceBeeGaming** [comment]
@Bllayze That means that did you give yourself admin rights by typing `/op <your_username>` in the server console. Otherwise, the server thinks that you are a regular player and doesn't allow you to enter commands in in-game chat.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
