### ISSUE TITLE
Error message when starting server

### ISSUE THREAD

**Issue by Alex12345678jour** [xJon/The-1.7.10-Pack#1630]
When i click on the start bat file, system 32 sows a message that says Unable to access file jarfile forge-1.7.10-10.13.4.1614-1.7.10-universal.jar    Press any key to continue...

How to fix this? Thx

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
