### ISSUE TITLE
unable to connect to server

### ISSUE THREAD

**Issue by CBarlow1** [xJon/The-1.7.10-Pack#1631]
all the console spits out is this
https://pastebin.com/v5javvfg

when I try to join I get
java.net.ConnectExeption: Connection refused: no further information:

could this have anything to do with the fact that I'm using a 3GB server package ?

Edit: got a crash report
https://pastebin.com/HVAbkSFe

**Comment by xJon** [comment]
Your crash report doesn't seem to be there.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
