### ISSUE TITLE
Server crash after being in Twilight Forest for 2h (Exception in server tick loop)

### ISSUE THREAD

**Issue by AdrianDieDose** [xJon/The-1.7.10-Pack#1632]
So my friend went to the Twilight Forest for 2 h and then the server Crashed after trying to fight an Boss and now the server doesn't start and this Error shows up in the crash report : Exception in server tick loop.
I really dont know that to do here so plz help :( 

Here is the full crash report: 
https://paste.ubuntu.com/p/kFbFBK5BsC/

**Comment by xJon** [comment]
Try to reset PneumaticCraft's config files by backing them up and then deleting them.

**Comment by AdrianDieDose** [comment]
Thx for the Reply !
Now I tried everything : 
I deleted every config one by one and AmadronTradingSettings.cfg is the one that crashes the server but when the Server starts and we try to join it says: Fatally missing blocks and items.
But at least it starts but idk what to do next :/

**Comment by xJon** [comment]
You'd need to make sure the server and client both have the same mods and configs.
You could just download again the server package for the modpack and put your world there so it'll all work as usual.

**Comment by AdrianDieDose** [comment]
I did what you told me i put the world in a new fresh server and it just crashed and the crash report told me again : Exception in server tick loop :/

**Comment by xJon** [comment]
Can you please post the crash report?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
