### ISSUE TITLE
Mod Suggestion: Tinkers' Steelworks

### ISSUE THREAD

**Issue by Delibirb** [xJon/The-1.7.10-Pack#1633]
I think this mod would be a great addition in order to make steel a more available resource within the pack, and to make it a viable tool source.

**Comment by wowwood** [comment]
Only 1.6.4 unfortunately - https://minecraft.curseforge.com/projects/tinkers-steelworks/files?filter-game-version=1738749986%3a6

**Comment by xJon** [comment]
There is this though: https://minecraft.curseforge.com/projects/tinkers-steelworks-fork

**Comment by xJon** [comment]
Currently the mod won't be added. Thank you for suggesting and remember you can always add it yourself manually!
