### ISSUE TITLE
Question about a suggested mod

### ISSUE THREAD

**Issue by NintendoN3rd64** [xJon/The-1.7.10-Pack#1635]
I would like to know why exactly the iguana tweaks mod isn’t likely to be added. Most of the suggestion topics for the mod don’t have much information as to why it won’t be added (Quotes below with the issue number they are from) This isn't mean to be degrading or rude, I am just legitimately curious as to why the mod won't be added. As I honestly feel like it would be a great addition to the modpack as a whole. If it’s due to an imbalance then it’s understandable, getting free modifiers is a bit op, but it’s justifiable as the materials to go into making one tool is pretty high(Depending on the tool)

> "Not going to happen, thanks anyway for suggesting though!"  -#1230

> "Sorry but the mod doesn't really fit the modpack and won't be added." -#1020
(Doesn't really say how it doesn't fit)

> "While Jon is still taking suggestions, he has no intention to consider any of them, because he is a Jon. Move on, nothing to see here." -#1393

> "This has been suggested many times before.
 Currently it won't be added, but you can always add it manually if you wish.
 Thanks anyway for suggesting!" -#1274

**Comment by xJon** [comment]
I suppose that the main reason is the change to the "vanilla" TiC mod style.

**Comment by NintendoN3rd64** [comment]
I mean, that makes sense, but it does seem like a silly reason, in my opinion, however, you are the one in control of this mod pack, I was only asking bc people on the server I moderate were asking and I said I'd ask.

**Comment by xJon** [comment]
Keep in mind you can always add it manually yourself :)

**Comment by xJon** [comment]
👍
