### ISSUE TITLE
Problem opening singleplayer

### ISSUE THREAD

**Issue by Guxxta** [xJon/The-1.7.10-Pack#1636]
When I trie to open any world at singleplayer, the game starts to load the world but when it is open the game take me back to the multiplayer menu or sometimes just shut down the game and show me a message ''a fatal error has occurred this connection is terminated''.

That's my latest https://paste.ubuntu.com/p/4d5jfR4Wcs/

**Comment by xJon** [comment]
Are you using an original version of the launcher

**Comment by xJon** [comment]
Well I'd need a different log with the original only.

**Comment by Guxxta** [comment]
Sorry to leave you waiting for an answer. I managed to fix the error, had to remove the technic from the firewall and start the world with the internet turned off, then I turned it back on and continued playing quietly. But thanks for any help!

**Comment by xJon** [comment]
Okay, you welcome.
