### ISSUE TITLE
MFFS GUI's are absolutely broken. 

### ISSUE THREAD

**Issue by MiloIsYumYum** [xJon/The-1.7.10-Pack#1637]
Whenever I open a GUI for a Modular ForceField System machine, everything is broken. The numbers are off the GUI, the buttons don't actually have words on them, the only two that seem semi-okay are the ForceField Projector and Coercion Driver, but even that doesn't look right. I'll attach some screenshots to prove my point. If there's something I can do on my end to fix it, please let me know. I wouldn't post this if I thought there was a fix I could find, but I host a private server and all the players I've asked see the same thing as I do and Google searches return nothing like this. 

Screenshots are attached.
![interdiction matrix](https://user-images.githubusercontent.com/7984648/50581114-77889f80-0e91-11e9-8980-ed02d51aec65.PNG)
![biometric identifier](https://user-images.githubusercontent.com/7984648/50581115-77889f80-0e91-11e9-8641-080ab27346bc.PNG)
![coercion driver](https://user-images.githubusercontent.com/7984648/50581116-78213600-0e91-11e9-9ffd-801fea1dfd81.png)
![forcefield projector](https://user-images.githubusercontent.com/7984648/50581117-78213600-0e91-11e9-92ad-2ea63e3089f8.png)
![fortron capacitor](https://user-images.githubusercontent.com/7984648/50581118-78213600-0e91-11e9-9854-8d8987d46f10.png)

**Comment by xJon** [comment]
These are known issues unfortunately and therefore we've posted a [poll](https://www.strawpoll.me/17059920) to whether we should remove the mod from the modpack.
