### ISSUE TITLE
Modpack wont open :(

### ISSUE THREAD

**Issue by Bielhogor** [xJon/The-1.7.10-Pack#1638]
I downloaded the modpack and it doesnt run when I hit play, instead it just comes back to the launcher window. I was using java 32 bits so i downloaded java 64 bits, now i have the options of choosing until 7GB, Ive tried playing it with 4GB of ram and after i tried unistalling the modpack  and it still with the same issue. Please help me I'm really trying to play the 1.7.10 modpack and i dont understand anything about programming.

**Comment by xJon** [comment]
Please go to the `.technic\modpacks\` folder and manually delete `the-1710-pack` folder.
Then try to download it again and install, with 3.5-4 GB of RAM allocated.
Good luck!

**Comment by Bielhogor** [comment]
Ive just tried and it didnt work :(

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).
Read more about where it is [here](https://github.com/xJon/The-1.7.10-Pack#if-you-have-all-that-required-post-an-issue-with).

**Comment by Bielhogor** [comment]
I just did it! Thank you so much for helping me! here it is: https://paste.ubuntu.com/p/kkrZJB3bbh/

**Comment by xJon** [comment]
You need to update your graphics card driver.
More information about your problem [here](http://hopper.minecraft.net/help/pixel-format-not-accelerated/).
Good luck!
