### ISSUE TITLE
Old World File Biome Change

### ISSUE THREAD

**Issue by kuroodo** [xJon/The-1.7.10-Pack#1639]
I have a server that i created around September 2017, don't know what version but it was the latest one around that time. 

When launching the same world but with a server running on 0.9.8, the area around my base switches to the Ominous Woods biome. It's only around the vicinity of my base. Across the river (like 10-15 blocks maybe) everything is normal, for example. Even some of the desert next to me became ominous woods. This issue is not present when I try running a server with 0.9.7

Here is the world file
https://drive.google.com/file/d/1oNZH73RbLqGm0GHzxSp8dq_0eKx7JS66/view?usp=sharing

**Comment by xJon** [comment]
If I'm not mistaken, at v0.9.8 we've fixed some biome ID conflicts and that's the reason for the biome change. Nothing we can do for that one, you'll just have to embrace the real truth of your base's biome.

**Comment by kuroodo** [comment]
That's what I suspected at first. It's just that the biome change seemed rather abnormal and specific to my location. It's also right where things that I built are located, like right across the river at a different biome. Could just be a coincidence though.
![img](https://user-images.githubusercontent.com/9257713/50629434-8c554980-0f0a-11e9-89fc-8b50c437d948.png)

**Comment by xJon** [comment]
If you can, take a look at the `.technic\modpacks\the-1710-pack\config\biomesoplenty\ids.cfg` and compare it with v0.9.7 (You can download them (here)[http://solder.endermedia.com/repository/mods/the-1.7.10-pack-configs/the-1.7.10-pack-configs-0.9.7.zip]).

**Comment by kuroodo** [comment]
Ok so in 0.9.7 Prairie is 78, and in 0.9.8 Ominous woods is 78.

So we can conclude that the issue is indeed due to the biome ID changes. Oh well. Thanks for the help!

**Comment by xJon** [comment]
👍
