### ISSUE TITLE
my game crashes before starting up 

### ISSUE THREAD

**Issue by Potatoflash** [xJon/The-1.7.10-Pack#1642]
hi my mod loads the launcher closes but before opening Minecraft the mod crashes and the launcher pops up again please can u help me solve this

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Potatoflash** [comment]
[techniclauncher_2019-01-13.log](https://github.com/xJon/The-1.7.10-Pack/files/2753272/techniclauncher_2019-01-13.log)

**Comment by xJon** [comment]
Please paste your logs **using a [paste-tool](http://paste.ubuntu.com/).**

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
