### ISSUE TITLE
Issues with flight across all mods

### ISSUE THREAD

**Issue by Webzayne** [xJon/The-1.7.10-Pack#1645]
After playing roughly two days into the modpack, we attempted to use the morph mod to fly.
For some reason that didn't work, mind you we also have visited the nether multiple times. Upon further investigation, it turns out that no item or ability giving flight seemed to work, outside of creative mode. 
Any idea about what could be causing this? The server is being hosted through nitrado, if that means anything.

**Comment by xJon** [comment]
Does the issue happen on Singleplayer too?
What modpack version are you using?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
