### ISSUE TITLE
Thaumcraft arcane workbench recipes

### ISSUE THREAD

**Issue by Dalvit15** [xJon/The-1.7.10-Pack#1647]
Arcane workbench recipes don't work since 0.9.8B update.

**Comment by Dalvit15** [comment]
![screen shot 2019-01-12 at 10 15 24 pm](https://user-images.githubusercontent.com/46635154/51078760-fd3ef300-16ba-11e9-81b3-0de0121f7fc5.png)

**Comment by xJon** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/8945347/60642376-f7a8b580-9e72-11e9-9389-bcaca0cc6064.png)
![Uploading Screenshot_1.png…]()
All I had to do is to make sure I have the arcane lamp researched in the Thaumonomicon.
