### ISSUE TITLE
Game isnt launching

### ISSUE THREAD

**Issue by McDaryan** [xJon/The-1.7.10-Pack#1648]
Every time I attempt to launch the pack it loads a bit of the pack and then just reboots the launcher, any idea why? I was playing fine right before this issue.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).
