### ISSUE TITLE
Mod Suggestion : Clay Soldiers mod

### ISSUE THREAD

**Issue by Randy50** [xJon/The-1.7.10-Pack#1649]
It's a really simple mod, and while it takes or adds nothing "real" to the game, I think it's just a small fun thing that does fit fairly well with other mods in this modpack.

**Comment by xJon** [comment]
Although this mod seems really cool for now it won't be added, as the pack is mostly complete as it is now and we don't want to add any other content mods. Thank you for suggesting and remember you can always add the mod manually for yourself.
