### ISSUE TITLE
Enable Project Red Tinkers Construct smeltery recipes

### ISSUE THREAD

**Issue by wowwood** [xJon/The-1.7.10-Pack#1650]
In the Project Red config file, (line 23) Tinkers Construct: Smeltery recipes are not enabled.

As Tinkers' is in the pack I think it should be enabled.

W

**Comment by xJon** [comment]
Actually, I just remembered - this was disabled in the past because of incompatibility it added.
More info: https://github.com/xJon/The-1.7.10-Pack/issues/1373
