### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by borisyukovich** [xJon/The-1.7.10-Pack#1652]
When i attempt to install it, at the end it just gets stuck at "Checking for Version File..."

Any help would be appreciated
![big lasagna](https://user-images.githubusercontent.com/46728294/51210957-3780ec80-1968-11e9-9d5b-0161c84779b1.png)

**Comment by lloydzx552** [comment]
This might not work and I'm not sure, so sorry if it doesn't work

**Comment by borisyukovich** [comment]
That worked, Thank you.

**Comment by xJon** [comment]
Glad the issue was solved 👍
