### ISSUE TITLE
Mod Suggestion: Advanced Solar Panels

### ISSUE THREAD

**Issue by Poldamer** [xJon/The-1.7.10-Pack#1653]
I would like to ask, if you would add the Advanced Solar Panels

This mod is more challenging yes, but at the same time more rewarding than the compact solar panels.
You see the Compact solar panels doesn't generate power at night Advanced do. But in less quantity. 

https://forum.industrial-craft.net/thread/3291-ic2-exp-1-7-10-advanced-solar-panels-v3-5-1-quantum-generator-solar-helmets/

As you can see advanced solar panel adds:

Advanced solar panel:
32 eu
8 eu/t at day
1 eu/t at night

Hybrid solar panel:
128 eu
64 eu/t at day
8 eu/t at night

Ultimate hybrid solar panel:
512 eu
512 eu/t at day
64 eu/t at night

Quantum solar panel:
8k eu
4k eu/t at day
2k eu/t at night

It is compensated by it's own machine "Molecular transformer" it needs energy a HUGE amount of energy and an item that it transforms into more rare element, but also need energy to do so, also ads "sunarium" an item to create hybrid, ultimate hybrid and quantum solar panel. Quantum generator is still "creative" i think, but it can be edited.

Also adds solar helmets for nano and quantum suits.
And a little patch for the vanilla lol.

All of the energy outputs can be edited to increase or decrease output from the Panels

**Comment by xJon** [comment]
Even though generating power at night and extra work for it is interesting, we don't want to add the mod as we currently don't want to make major changes to the pack.
Feel free to add the mod manually though, and thank you for your suggestion.

**Comment by xJon** [comment]
Advanced Solar Panels has been added in version `0.10.5`!
