### ISSUE TITLE
Adding Gregtech to the modpack

### ISSUE THREAD

**Issue by babyblackjesus** [xJon/The-1.7.10-Pack#1654]
I wanna add Gregtech to this Modpack but I have no idea which version I should use. I tried finding a Thread or anything regarding my Question but i couldn't find any that's why I am asking here. If someone could tell me which Versions are supported and which are not supported would be awesome. Thanks in regards.

**Comment by xJon** [comment]
You can download its latest version for 1.7.10 from here: https://gregtech.overminddl1.com/downloads/gregtech_1.7.10/index.html
Just make sure to read everything in the page first, so you won't get issues, or multiple ore-generations from multiple mods.
Good luck! :)
