### ISSUE TITLE
Mod Suggestion: UgoCraft

### ISSUE THREAD

**Issue by reaperguy101** [xJon/The-1.7.10-Pack#1659]
I have no idea if it is possible to get UgoCraft to work with the mod-pack but could you experiment with it. I think it would be cool to be able to have that kind of movement for blocks seeing as you would be able have the entire side of a mountain open up like a door instead of just sliding open.

**Comment by xJon** [comment]
The mod is not available for Minecraft 1.7.10 but the modpack does have the [Funky Locomotion](https://www.youtube.com/watch?v=egR01_eILXw) mod that could allow you do to some similar things.
