### ISSUE TITLE
My 1.7.10 pack is crashing

### ISSUE THREAD

**Issue by Redsquare007** [xJon/The-1.7.10-Pack#1660]
Hello, 

I have just installed the 1.7.10 pack on my new PC (Ryzen7 2700x, 16 Gb DDR4 2933 MHz, GPU 1080ti 11 Go). I can create a new world and play approximately 4 minutes. After that, it closes the world, it says "a fatal error has occured, the connection is terminated", then it comes to the server menu.

In my 1.7.10 pack folder, i can't find any "crash-reports" folder...

Can you help me, please ?

I use Optifine, and my Java build is build 1.8.0_201-b09).

Thank you !!

**Comment by xxmodxx788** [comment]
that happens to me when i kill an animal lol

**Comment by Redsquare007** [comment]
Thank you for your answers. Here is my log file :

https://paste.ubuntu.com/p/P5cBjxjcpm/

**Comment by xJon** [comment]
Yup, it is because of using the wrong version of Optifine. Please use version D6, it should fix your problems :)

**Comment by Redsquare007** [comment]
Thank you ! It works fine now !!

**Comment by xJon** [comment]
👍
