### ISSUE TITLE
The 1.7.10 pack server I'm trying to run on Linux won't start

### ISSUE THREAD

**Issue by clydethegreat** [xJon/The-1.7.10-Pack#1663]
Whenever I run the sh file it goes through a bunch of prosess as usual then crashes with this error 
[Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

**Comment by clydethegreat** [comment]
I actually fixed the problem. All you have to do is sudo nano into the eula.txt and set the value to true

**Comment by bobbobson52** [comment]
you are a life saver <3

**Comment by xJon** [comment]
:)
