### ISSUE TITLE
Enchantment plus issue

### ISSUE THREAD

**Issue by Infexis95** [xJon/The-1.7.10-Pack#1664]
I've seen a few other potsts about this, but my enchantment plus is not working at all. No enchants show up unless I put in an already enchanted item, and then only the enchantment thats already on it. I've set up tons of bookshelves, as well as read most of the scrolls there is. It seem to work fine in creative mode, but I really want access to it.

If the issue isnt getting fixed soon (by rolling back to an older working version, or the creator updating the mod), is there anything I can do to get it myself, for my own server thats running the latest version of the 1.7.10 pack?

**Comment by xJon** [comment]
The pack is using Enchanting Plus 4 Beta. This means, in order to use the mod, you need to find enchantment scrolls in dungeons for each enchantment you want to have access to.
