### ISSUE TITLE
Failed to login

### ISSUE THREAD

**Issue by PickMyLussy** [xJon/The-1.7.10-Pack#1666]
Hey, me and my few friends decided to play The 1.7.10 Pack together. One of them bought today a server and everthing works fine for him. I tried to conenct with warez and got some fail (moth mod doesn't work for warez) so I bought a new MC acc. Then I've tried to connect and as I connected I got insta DC with some fatal error. After some time, few restarts and so on, I got over fatal error and now I can't even connect and it says Failed to login: The authentication are currently down for mainteance. And still works fine for him, he's on the server. 

Thanks

**Comment by xJon** [comment]
This issue happened to a lot of players but should be resolved now. If not, please reply here.
