### ISSUE TITLE
Game Crash directly after start walking.

### ISSUE THREAD

**Issue by NyboTV** [xJon/The-1.7.10-Pack#1667]
My Friend installed the Pack. After i Teleported him. He wanted to change some Keys. There was the First Crash. After MC Restart he tryed to Walk and directly his game crashed again. Here is the Report:
[crash-2019-02-01_16.30.24-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/2822221/crash-2019-02-01_16.30.24-client.txt)

**Comment by NyboTV** [comment]
[fml-client-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/2822321/fml-client-latest.log)
Here is the FML-Client-Latest.log

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by NyboTV** [comment]
https://paste.ubuntu.com/p/8xXY2mG8VT/  Crash Report.
https://paste.ubuntu.com/p/gHcHF6snZN/ FML Client Latest Log.

**Comment by xJon** [comment]
Try to reset the problematic keybindings (and the settings of your client) by deleting the `options.txt` file inside of the modpack's folder.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
