### ISSUE TITLE
A fatal error has occured, this connection is terminated

### ISSUE THREAD

**Issue by fipsikus294** [xJon/The-1.7.10-Pack#1668]
[fml-client-1.log](https://github.com/xJon/The-1.7.10-Pack/files/2823588/fml-client-1.log)

Just help me...

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
