### ISSUE TITLE
Everytime i try to join my world i crash 

### ISSUE THREAD

**Issue by Derpypig** [xJon/The-1.7.10-Pack#1670]
https://paste.ubuntu.com/p/qSgt2cMSry/
when ever i try to join my world it gets to loading terrain and then just crashed back to technic launcher can i get some help.

**Comment by xJon** [comment]
Simply seems like corrupted chunks, probably the game wasn't closed properly.

* One solution would be to restore a world backup (the modpack makes backups automatically).
* A second solution would be trying to use [Region Fixer](https://github.com/Fenixin/Minecraft-Region-Fixer).


Good luck!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
