### ISSUE TITLE
Worlds with shared name load wrong map + Lock North for round map

### ISSUE THREAD

**Issue by Graywaren** [xJon/The-1.7.10-Pack#1675]
I'm using the 1.12.2 version and every time I create a world that has the same name as a previous world, even if it was deleted, Voxel Map loads the map and waypoints from the first world with that name. This is a serious issue when I'm trying to build a modpack and constantly creating and deleting worlds to test generation. Every world with the name "New World" loads the world I first created. I can solve this problem by deleting the cache and .points of any world I delete, but it seems like this mod should delete those when the world itself is deleted.

Also, is there any way to lock north with the round mini-map in the 1.12.2 version as there is in the 1.13 version?

**Comment by xJon** [comment]
This is a known problem with VoxelMap but there's nothing we can do about it.
Regardless, I see you're complaining about the mod for a different version of Minecraft, and I'm not the mod author. Go there for help: https://github.com/MamiyaOtaru/voxelmap/issues

**Comment by Graywaren** [comment]
I had no idea it was a known issue since my trying to check for that brought up nothing and it's hardly complaining to report a bug. I also have no idea how this got posted here since i've never heard of this pack. 0_o No clue how I managed to even end up on this github since I did in fact start off on Voxel's. Sorry about that! Moving back to where it should be.....

**Comment by xJon** [comment]
:)
