### ISSUE TITLE
1.7.10 pack server issues

### ISSUE THREAD

**Issue by banecat** [xJon/The-1.7.10-Pack#1676]
I have been hosting this server for the 1.7.10 modpack for minecraft ran through the technic launcher for a month with regular restarts and no issues today multiple players have reported the server being down. Currently as it stands i am unable to get the server to launch correctly and anytime a player attempts joins they are booted out due to an internal server error this is my lastest crash log could use some help figuring out whats going on and how to fix it.

**Edited: Please use a paste tool next time you post a log**

**Comment by xJon** [comment]
This means that one of the server's `.json` files has been incorrectly modified. It could be the banned players file, whitelist or something similar.
If you're still unable to identify the problem I will re-open the issue.
