### ISSUE TITLE
1.7.10 mod pack hamachi server friend crashes

### ISSUE THREAD

**Issue by ICYPACK** [xJon/The-1.7.10-Pack#1677]
[crash-2019-02-05_18.35.28-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/2834661/crash-2019-02-05_18.35.28-client.txt)

I have a hamachi server where some of my friends play for a couple days we played fine until now. All of a sudden when they open up their inventory, chest or anything else they crash

**Comment by cr998** [comment]
i dont know how esactly to do this, but i think the solution is this https://forum.feed-the-beast.com/threads/rendering-error-crash-when-opening-inventory.21539/

**Comment by xJon** [comment]
Please post your logs file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
