### ISSUE TITLE
When I try to join server it says "Failed to login: Invaild Session. (try restarting game)

### ISSUE THREAD

**Issue by SharkRider23** [xJon/The-1.7.10-Pack#1678]

**Comment by SharkRider23** [comment]
I have restarted my game multiple times but it still doesn't load.

**Comment by MonsterCWP** [comment]
Have you exited out of the entire Technic Launcher? Simply exiting and restarting The 1.7.10 Pack isn't enough to refresh your login session,  since the Technic Launcher handles logins- you need to restart the actual Technic Launcher to relog.

**Comment by xJon** [comment]
⏫
