### ISSUE TITLE
Fatal Error Upon Killing/Hitting Mob

### ISSUE THREAD

**Issue by pikashii** [xJon/The-1.7.10-Pack#1679]
I started playing this pack on an Aternos server with my friends yesterday, only to find that each time I killed a mob, the server would instantly boot me and display that a fatal error had occurred and the connection was closed. It's pretty irritating, because I can't play properly when I'm constantly being kicked. This happens to my friends as well. I'm not sure if it's the pack's fault or Aternos. 
Here's the crash log from my latest crash: 
https://pastebin.com/zLhscwiV

**Comment by xJon** [comment]
If you're using Optifine, make sure you use version D6.
If that's not the problem I will reopen the issue.
