### ISSUE TITLE
Flans mod cant fuel planes?

### ISSUE THREAD

**Issue by Zedstro** [xJon/The-1.7.10-Pack#1680]
I built the lancaster bomber and put fuel into the fuel slot but it does not fuel the plane?

**Comment by xJon** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/8945347/60643586-df3a9a00-9e76-11e9-8439-8c33985fbdf2.png)
It does require a lot of fuel but I can't see a problem there.
