### ISSUE TITLE
Crasg Report

### ISSUE THREAD

**Issue by Hajn04** [xJon/The-1.7.10-Pack#1681]
[crash-2018-11-09_15.16.40-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/2848848/crash-2018-11-09_15.16.40-server.txt)  If I use a backup it crashes again

**Comment by Blu3berry** [comment]
I have the same Problem : when i start loading world it just stops at one point and goes back to technik launcher

**Comment by Blu3berry** [comment]
[crash-2019-02-20_16.02.33-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/2897089/crash-2019-02-20_16.02.33-server.txt)

**Comment by xJon** [comment]
Please post your logs **using a [paste-tool](http://paste.ubuntu.com/)**.

**Comment by Blu3berry** [comment]
https://paste.ubuntu.com/p/HvM2rCntdf/plain/
So I managed to restore a recent backup but my main world would still not load

**Comment by xJon** [comment]
@Blu3berry 
You simply have corrupted questing data - simply reset (delete) the inside of `HardcoreQuesting` within your server's world folder.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
