### ISSUE TITLE
Server freezes when I'm idle

### ISSUE THREAD

**Issue by CDWC** [xJon/The-1.7.10-Pack#1682]
I'm having a bit of a unique issue running a server on the 1.7.10 modpack! Sometimes, starting up the server is fine, but other times (randomly) it stops initializing the mods until I press any key. Then, it continues as if it had no problems.

This also tends to happen after startup as well. At a random time, the server will stop responding and my players will crash until I "awaken" the server by typing in literally anything into the console. After typing things in, I usually see a message that says the server is however many ticks behind, so it disconnects everyone. In case it might be a factor, I have over 4GB of ram and no my computer isn't going into sleep mode. Help!

**Comment by xJon** [comment]
Seems like your machine can't handle the modpack and the world its running.
Do you have over 4GB dedicated to the server?
Also, what's the CPU utilization % shown in the task manager as you run the server?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
