### ISSUE TITLE
A Fatal Error has ocurred this conection is terminated

### ISSUE THREAD

**Issue by cr998** [xJon/The-1.7.10-Pack#1684]
I get this error when i tried to connect on my server

**Comment by cr998** [comment]
https://paste.ubuntu.com/p/MTqqnKtgh3/

**Comment by cr998** [comment]
techniclauncher -> [techniclauncher_2019-02-13.log](https://github.com/xJon/The-1.7.10-Pack/files/2860540/techniclauncher_2019-02-13.log)

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by cr998** [comment]
sorry i decline to play this modpack and delete all files

**Comment by xJon** [comment]
🤷‍♂️
