### ISSUE TITLE
Friends Minecraft crashes all of  a sudden after joining my Server

### ISSUE THREAD

**Issue by Alexandermesser** [xJon/The-1.7.10-Pack#1685]
So we were playing Minecraft as usual, yesterday and my friend Suddenly crashed after i started to go on the moon with galacticraft, but my 2 other friends didnt crash, so i dont think galacticraft is at fault but here is the server message when he tries to join and his error log

https://paste.ubuntu.com/p/XKMHq9WVq8/

**Comment by xJon** [comment]
The TabbyChat seems to be at fault here, try to launch the game without it and see if it works normally.
If it does, try then to add the mod back in.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
