### ISSUE TITLE
Stuck on "Logging In..."

### ISSUE THREAD

**Issue by Dheslin1** [xJon/The-1.7.10-Pack#1687]
I apologize in advance if this issue has been solved and I just didn't find it. I will provide what I think matters, but I have access to pretty much everything (including longer logs) if it is necessary.

When trying to join an SMP server I have with my friends, I get stuck on the "Logging In..." screen when connecting. This only occurs with me, but no other players on the server. This is obviously client-side, but my network doesn't seem to be the issue from what we have troubleshooted. I have tried any have been able to join on another device, just not my main device. Locally, my client logs just register me trying to connect to the server IP each time, but nothing else.

 When I try to connect, the server console will just provide a mixture of one of these messages:

Dheslin lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(15) + length(18542) exceeds writerIndex(118): UnpooledHeapByteBuf(ridx: 15, widx: 118, cap: 118)

Dheslin lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: VarInt too big

Dheslin lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: VarInt too big Internal Exception: io.netty.handler.codec.CorruptedFrameException: length wider than 21-bit

Dheslin lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 29 (Packet # varies)

Dheslin lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet was larger than I expected, found 16 bytes extra whilst reading packet 15

My friends and I are not experts on this stuff by any means, but everything we could think of trying has turned up unsuccessful. I appreciate any help/advice anyone could supply, thanks!

Edit: First issue was fixed but a new error message appeared.

Edit 2: Added another message I've been getting

**Comment by clienthax** [comment]
Looks like you managed to corrupt your inventory.

**Comment by Dheslin1** [comment]
I have never joined this server completely, I don’t even have player data. We changed modpacks recently (to this one) and since the pack and world change, I haven’t been able to join period.

**Comment by Dheslin1** [comment]
Found the Issue, gonna put it here in case anyone has the same issue. I have a Dell G7, and my laptop, along with others, comes with the software "SmartByte" installed. This software breaks a lot of stuff network wise and is just cruddy bloatware overall. 

-Issue Solved, Closing-

**Comment by xJon** [comment]
👍
