### ISSUE TITLE
FPS Drop Sphax with the New Update

### ISSUE THREAD

**Issue by TheDemonGER** [xJon/The-1.7.10-Pack#1689]
So i updated the Modpack and started an new World. But i cant play the Game with Sphax anymore. 
I played 2 months ago it was all fine. but now its laggy af

**Comment by xJon** [comment]
Are you using the x64 version?

**Comment by TheDemonGER** [comment]
Yes I tried both versions. 
2 months ago I used the 128x version. 
But now I tried the 64x version too but that one doesn't work either.

**Comment by kakashiis** [comment]
I have the same problem too. One time my game crashed but now it is stable. I don't really mind it because I was used to play on  a laggy pc

**Comment by xJon** [comment]
Is this still an issue? Anyway, for Sphax support please go there - https://bdcraft.net/community/releases-for-packs-f10/technic-the-1710-pack-t3729-s60.html?sid=655c3bd3bc67ef3b80f33dc310781e04
