### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by Crapclone** [xJon/The-1.7.10-Pack#1690]
My server which had been running perfectly has randomly stopped working here is the crash report https://pastebin.com/xkdWmgxA

**Comment by xJon** [comment]
You simply have corrupted questing data - simply reset (delete) the inside of `HardcoreQuesting` within your server's world folder. This will reset your quests progress, but you can always cheat the items you had back in if you want.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
