### ISSUE TITLE
Lilypads of Fertility NOT WORKING

### ISSUE THREAD

**Issue by ManticoreTx** [xJon/The-1.7.10-Pack#1691]
As the title states I have been messing around with the lilypads of fertility on my server and I can not get them to work at all, they do nothing, in fact I feel as if they grow slower when my magic crops are planted near one. I can not seem to find anything in the xreliquary config nor the magic crops config to fix this issue.

**Comment by xJon** [comment]
Can you confirm you're using the latest version of an unmodified The 1.7.10 Pack?

**Comment by xJon** [comment]
After some examining, it seems that the problem is to do with the mod's config file from the previous version. Upon deleting the config of the mod and letting it regenerate, the problem goes away.
Will make sure that the next version of the modpack shifts with the correct config file.
