### ISSUE TITLE
1.7.10 pack crashes on launch via Technic Launcher

### ISSUE THREAD

**Issue by Aviators23** [xJon/The-1.7.10-Pack#1692]
I'm trying to repair a problem with the Technic Launcher/1.7.10 pack where the pack launches, then goes to a black screen before crashing.

Will attach crashlog for people smarter than me to read through.

Any help is appreciated!
[techniclauncher_2019-02-18.log](https://github.com/xJon/The-1.7.10-Pack/files/2877859/techniclauncher_2019-02-18.log)

**Comment by Aviators23** [comment]
https://paste.ubuntu.com/p/KHFrXcss8V/

**Comment by xJon** [comment]
Try resetting (deleting) the `opencomputers` folder and the `OpenComputers.cfg` file inside `modpacks\the-1710-pack\config\`. Should solve your issue.
Also, understanding something others don't doesn't make one smarter, just more experienced.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
