### ISSUE TITLE
Crash when uploading

### ISSUE THREAD

**Issue by Dexter124** [xJon/The-1.7.10-Pack#1693]
http://prntscr.com/mns908 crash at here

[fml-client-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/2885764/fml-client-latest.log)

**Comment by xJon** [comment]
Please logs **using a [paste-tool](http://paste.ubuntu.com/)**.

**Comment by xJon** [comment]
Please post your logs **using a [paste-tool](http://paste.ubuntu.com/)**.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
