### ISSUE TITLE
'java.net.ConnectException: Connection refused: no further information:' server issues

### ISSUE THREAD

**Issue by EvolvedUK** [xJon/The-1.7.10-Pack#1694]
My mates keep getting 'java.net.ConnectException: Connection refused: no further information:' when trying to connect to my 1.7.10 pack server, I have tried everything I can think of, even turned my firewall off

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by EvolvedUK** [comment]
there isn't one

**Comment by xJon** [comment]
That's where you can find the logs: https://github.com/xJon/The-1.7.10-Pack#if-you-have-all-that-required-post-an-issue-with

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
