### ISSUE TITLE
Wraith's eye is gone? (Reliquary)

### ISSUE THREAD

**Issue by rdaro0311** [xJon/The-1.7.10-Pack#1695]
I want to use the Wraith's Eye to teleport back to my base from anywhere, however it does not seem to be in the game. In NEI, the Wraith Node shows up but the eye does not. I have tried crafting the eye as well to no avail. I'm not sure if the eye has been removed intentionally or not. I have researched this problem to no avail, any support would be greatly appreciated.

**Comment by xJon** [comment]
Upon Google research, I found that the Ender Staff replaced the Wraith's Eye in recent versions of Reliquary.
You can find proof here - https://github.com/TrainerGuy22/Reliquary/issues/84
And wiki explanation here - https://github.com/P3pp3rF1y/Reliquary/wiki/Chargeable-and-Toggleable-items#ender-staff
