### ISSUE TITLE
Mining Quartz gives me ore and not actual quartz?

### ISSUE THREAD

**Issue by yakk1** [xJon/The-1.7.10-Pack#1696]
When I mine quartz, I get the ore and not the actual item. It is as if I have silk touch, even though I dont. Anyone know a fix for this?

**Comment by KevinMagers** [comment]
thats how it is suppose to work... right? i might be mistaken but ive just accepted it as the truth so far

**Comment by xJon** [comment]
Hmm, it's interesting. This is due to the NetherOres mod's default configs.
Seems to be fair play, as automated processing is one of the points of the modpack.
Currently will leave it like this, but if you want to change it you can go to:
`the-1710-pack\config\powercrystals\netherores\common.cfg`
```
534:    # If true, Nether Quartz ore will be a NetherOre and will follow the same rules as all other NetherOres.
535:    B:OverrideNetherQuartz=true
```
