### ISSUE TITLE
Infinite XP Glitch with Bound Armor

### ISSUE THREAD

**Issue by chef109** [xJon/The-1.7.10-Pack#1698]
There's an area in my world that seems to give me infinite XP as long as I have the magnet mode on my Bound Armor activated. The dimensions of said are shown in attached photo. Anything inside the cobble stone walls and floor and up to the top of the cobble stone pillar are affected. The entire area is approximately 12X13X8 blocks. The area is part of 4 separate chunks.

[Link](https://imgur.com/xo1kjOO) to the Image.

**Comment by xJon** [comment]
Hi,
Can you post the seed of your world? (`/seed`)

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
