### ISSUE TITLE
Server Internal Error When Joining my server.

### ISSUE THREAD

**Issue by swordxxx** [xJon/The-1.7.10-Pack#1699]
### Whenever I join my own server my game crashes and I get the message "Internal Server Error". All my friends can join the server except for me. I have tried erasing config files containing my UUID for Minecraft but to no avail. 

I have the crash report for my Minecraft which I will paste below. Using modpack version 0.9.8b

Can someone PLEASE help me fix this. I am desperate. 

https://pastebin.com/zrr6MNMf

**Comment by xJon** [comment]
Please make sure you've setup the server correctly following this guide:
_"How to set up a dedicated server"_, by @Curunir, 2016

> 1. Download the server package version you need here: http://the-1710-pack.com/repo
> 2. Extract the package to where you want your server to run. This will work side-by-side with a client installation, but unless your PC is a high-end monster, it is much recommended to use another PC for the server, if any is available.
> 3. Make sure your clients can see the server. If you are all on the same home network (LAN), this should just work. To have it work across the Internet, the server needs to have the port it will listen to (default: 25565) forwarded from the router. This will not (ever) work if your ISP puts you in the baby cage that is carrier-grade NAT, so let's hope yours doesn't.
> 4. Edit your server.properties file with all the settings you need. Guide is here: http://minecraft.gamepedia.com/Server.properties
> 5. If you want to import a singleplayer world, locate the worldsave and copy it over to the server directory. You need to set the world name in server.properties to the exact directory name of the worldsave for it to use the existing one. Even if you let it generate a world, the name that you set here will be used, default is just "world".
> 6. If you need it to work for more than just a couple of friends, give it more RAM. Edit the launch script and change the -Xms (minimum) and -Xmx (maximum) allocation values as needed. For a first try, defaults will be fine.
> 7. If you were wondering, launch.bat is your launch script on Windows, while launch.sh is the one for Linux/Unix/MacOS. ALWAYS use the script, never manually start the server.jar. If you do, you will start a vanilla (i.e. unmodded) server that will do weird shit.
> 8. Run the server, don't be intimidated by the millions of errors and give it time. Once it stops generating new lines while not falling back to the command line or closing, it should be up and running. Try connecting with a client, using the IP adress or a DNS-resolved name.

**Comment by swordxxx** [comment]
> Please make sure you've setup the server correctly following this guide:
> _"How to set up a dedicated server"_, by @Curunir, 2016


Yeah, the server is fully set up and working. I have 6 friends that play on it regularly from different ip address each and it works no problem for them. I am the only one (The host of the server) who cannot connect.

**Comment by xJon** [comment]
Did you modify the pack at all? Can you play other servers or singleplayer?
Anyway, you can try to uninstall LiteLoader by removing it from the `\modpacks\the-1710-pack\mods\1.7.10\` folder. Good luck!

**Comment by swordxxx** [comment]
deleted LITELOADER and still wont let me on the server. I can join single player and other servers on this modpack perfectly fine it just seems to be my server thats not letting me on. My friends are still able to connect and play perfectly fine. 

Heres the crash report after deleting lite loader.
https://pastebin.com/hhYNa9P3

**Comment by xJon** [comment]
You can try to ask the server owners to (backup and) delete the player data of you in the server.
This will probably cause all the items you had in your inventory to delete, but it might help with the issue.

**Comment by swordxxx** [comment]
I’ve tried a few times to delete player data. Which files specifically should I delete? I’m not worried about losing my items I just wanna be able to get on hahaha.  I’ve deleted all of the player files with my player UUID on them.

**Comment by swordxxx** [comment]
Fixed the issue. Ended up having to delete the entire world file from the server and generate a new world.
