### ISSUE TITLE
My server keep rubber banding and timing me out.

### ISSUE THREAD

**Issue by Ollehugo** [xJon/The-1.7.10-Pack#1700]
The server dosnt skip and any ticks when players are rubber banding happening. 
this is also a fresh server just downloaded and set up, added 10gb ram.

Thanks for the help ^^/

**Comment by xJon** [comment]
You can try to post your `fml-server-latest.log` (file using a [paste-tool](http://paste.ubuntu.com/)), but it might just be your internet speeds. What are they?

**Comment by Ollehugo** [comment]
it Randomly stopped happening after running for a while and restarting a few times. thankyou for replying. love your modpack

**Comment by xJon** [comment]
:)
