### ISSUE TITLE
IC2 and TE Mods Compatible

### ISSUE THREAD

**Issue by PoostaJ** [xJon/The-1.7.10-Pack#1703]
I want to delve into IC2 but all the copper I find is from the TE mod. Now, I've read up on this and from what I can tell TE copper should work in IC2 recipes, for example I'm trying to craft Insulated Copper Wires, but it doesn't work. How do I fix this so either I can get IC2 copper or I can make it work interchangeably? And sorry I know Github is more from programming stuff but I literally can't find any help on this I tried Discord but nobody seemed to want to help me there.

**Comment by xJon** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/8945347/60645738-e369b600-9e7c-11e9-9a02-bc74501c34c9.png)
I couldn't really reproduce the issue you're talking about.
Maybe if you give me the exact example of the item you couldn't craft I could help better.
