### ISSUE TITLE
Ошибка мода, как исправить?

### ISSUE THREAD

**Issue by MrKharon** [xJon/The-1.7.10-Pack#1705]
Почему не запускается сервер с модами? вот в чём проблема...

**EDITED: Please do not post logs here.**

**Comment by xJon** [comment]
This is an English support place.
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
