### ISSUE TITLE
Opening-Loading-Crashing

### ISSUE THREAD

**Issue by GreenSkull8** [xJon/The-1.7.10-Pack#1707]
When i press PLAY game opening and waiting for about 3 minutes in black screen then its loading something and boom when fully loaded game closing and technic launcher opening.
any fix ?

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by GreenSkull8** [comment]
You can't comment at this time — your comment is too long (maximum is 65536 characters). it says ?
[fml-client-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/3000337/fml-client-latest.log)
[crash-2019-03-22_13.15.52-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3000338/crash-2019-03-22_13.15.52-client.txt)

**Comment by xJon** [comment]
Please use a **[paste-tool](http://paste.ubuntu.com/)**.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
