### ISSUE TITLE
Aroma1997 Dimensional World

### ISSUE THREAD

**Issue by benje312** [xJon/The-1.7.10-Pack#1708]
Decided to try out the Mining Dimension from "Armoa1997's Dimensional World" walked into the portal read "Downloading Terrain" and was popped back into my normal world. 
Also I remember when playing with friends seeing some option about multiworld, does that have anything to do with it?

**Comment by xJon** [comment]
You need to shift while you enter the portal, and then stop shifting when it's teleporting you.
Can you please post your `fml-client/server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/)?

**Comment by benje312** [comment]
1st I have no idea how to do that
and 2nd it seems to be working okay now..?

**Comment by xJon** [comment]
Oh well, that's good. Will re-open if the issue persists.

**Comment by benje312** [comment]
1st I have no idea how to do that
and 2nd it seems to be working okay now..?
