### ISSUE TITLE
Optifine Gives "Fatal Error" on Multiplayer

### ISSUE THREAD

**Issue by AlgebraManiacABC** [xJon/The-1.7.10-Pack#1710]
Recently I downloaded the most recent optifine build for 1.7.10 and placed it in my mods folder. Although it works I fine on singleplayer, whenever I join a server (tried two so far), it immediately kicks me with this message: "A fatal error has occurred, this connection is terminated."
I know that optifine has been installed, and, even further, I have been able to play on the server for a minute or two only to have the error appear again for no particular reason. Mostly, though, I cannot even enter for a second.
Other players say they have this issue too, and all we do is put OptiFine in our mods folder.

**Comment by xJon** [comment]
Make sure you use version D6.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
