### ISSUE TITLE
Auto smelt glitch.

### ISSUE THREAD

**Issue by theryno64** [xJon/The-1.7.10-Pack#1711]
Just a minor issue I wanted to bring to the attention of whom it may concern. While running a server with some friends we noticed that any smeltable item collected with an Auto-smelt item (particularly Tinkers' Construct tools enhanced with Lava Crystal and Liquefaction Focus from Thaumcraft is what we tested it on) Causes the items to not cook properly in any furnace, powered or otherwise. It will only cook 1 item and the rest will continue to cook but not stack wasting the rest of the items, we noticed this with cobblestone to stone and coal to granite bars.

I did not see this issue on the forums here so I felt the need to post. If this was already brought up and solved then I apologize, I didn't take the time to sort though the over 1000 solved issues already. 

Happy mining friends.

**Comment by xJon** [comment]
Hi,
I've tried to reproduce the issue you mentioned with the Tinkers' Lava Crystal pickaxe, and cobblestone.
All of the auto-smelt stone smelted successfully again in the furnace.
![Screenshot_1](https://user-images.githubusercontent.com/8945347/60756021-8b2ce280-a03b-11e9-8c42-a78af35d3341.png)
I've also tried other techniques and couldn't reproduce the issue.
I don't know what you mean by coal to granite bars, as using an auto-smelt pickaxe to mine coal ore makes granite bars which cannot be smelted again.
