### ISSUE TITLE
Black Screen & Crash

### ISSUE THREAD

**Issue by PureUke** [xJon/The-1.7.10-Pack#1712]
The game starts up in a rather unusual way.
First, it loads with a black screen (I don’t know if that’s normal or not). Second, three minutes into the loading process it crashes, and automatically closes the minecraft window. I looked into the logs, and noticed that there were strings of code that were something around the lines of “SSL Error” and “(Unknown Source) Error” when trying to pull files from the web using urls. 

I’m left scratching my head on this issue, and I’m sure many others out there are too. My laptop is up to date, is using the right version of Java, and there aren’t many issues when loading other modpacks like the Tekxit 3 Modpack. Any ideas of what it could be?

I will provide you the log file if it is necessary.

**Comment by PureUke** [comment]
It did mention in the strings that there were certification errors. Perhaps McAfee is blocking the modpack’s urls? 

If you can, please look into this as well.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
