### ISSUE TITLE
Server wont use more than 4 Gigolos of memory?

### ISSUE THREAD

**Issue by OskarMZ** [xJon/The-1.7.10-Pack#1715]
Also, i kinda thought this was the reason my server was crashing, it exits me and my friend every now and then which is no biggie, but every few hours server will crash, and corrupt world save so i have to use the previous save. The server is setup on a seperate pc with 8GB of ddr3 but it only uses 4G, and wont use more. This is my first server.

**Comment by OskarMZ** [comment]
Also, i kinda thought this was the reason my server was crashing, it exits me and my friend every now and then which is no biggie, but every few hours server will crash, and corrupt world save so i have to use the previous save. The server is setup on a seperate pc with 8GB of ddr3 but it only uses 4G, and wont use more. This is my first server.

**Comment by xJon** [comment]
Technically you really don't need more than 4 *gigabytes*. 
To help you with the server crashes, I'll need you to post a crash report using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.

**Comment by OskarMZ** [comment]
Apologies for late reply, crash issue solved, was just the pc hibernating after a few hours. I don't know anything about servers, is 4GB enough for like 4 or 5 people playing?

**Comment by xJon** [comment]
👍
Yes, 3-4 GB would be great.
