### ISSUE TITLE
Client crashes when connecting to the server through a proxy.

### ISSUE THREAD

**Issue by MagicSheep** [xJon/The-1.7.10-Pack#1716]
When I try to join the 1.7.10 Pack server through the /server command or a BungeePortal, my game crashes, however, upon reconnecting, I join the 1.7.10 Pack server without issue. This crash only occurs for clients and the server is unaffected.

Server info:
Proxy: Travertine-92
The "Lobby" server uses PaperSpigot on 1.8.8 and ViaVersion/ViaRewind for backwards compatibility.
All other servers use Paper on 1.13.2.

Other info:
Modpack version: 0.9.8b
Running on Java 8 64Bit with 10GB of ram allocated
No modification to the pack has been done

I have attached a crash log from an attempt to join the server through command.
[crash-2019-04-05_20.40.38-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3050023/crash-2019-04-05_20.40.38-client.txt)

**Comment by xJon** [comment]
Please post your crash log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by MagicSheep** [comment]
Oops, my bad. Here's the paste: https://paste.ubuntu.com/p/mRpGtS97vc/

**Comment by xJon** [comment]
A mod is sending an invalid packet that's causing the client to crash. Unfortunately it's not possible to find out which mod is it from the crash-log, and it'd require to remove one mod at the time to find out which mod causes it. ¯\_(ツ)_/¯

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
