### ISSUE TITLE
Mod Suggestion : RFTools (with balance suggestions)

### ISSUE THREAD

**Issue by Anhilyx** [xJon/The-1.7.10-Pack#1717]
Hello,
I've played a lot on The 1.7.10 Pack and I really love it, but when I play this modpack I often add RFTools (and RFTools Dimension) to replace Mystcraft.
One reason is Mystcraft makes a lot of bugs and instabilities on my server (maybe I'm the only with these problems, but I mention it in case of).
The other, and main reason, is because I think RFTools has a lot more potenty compared to Mystcraft. First, it add other things alongside making dimensions, like the Builder Block to move structures (I think the quarry mode is too op, but I'll talk about it after). And for the dimensions, they are a lot more customizable than Mystcraft's ones, and also more stable (no/less negative effects, ...). The RF cost make them also more balanced, and is probably the reason of the more stables worlds.
But recently I also played a skyblock modpack in 1.7.10 and RFTools broke the balancing of the pack. When you have access to the Deep Dark and a Builder Block in quarry mode, you can mine ores in 512x512x256 at an insane speed and for nearly no energy (a 3x3x3 Big Reactor is enough if i remember well), and if you have an Enderman farm with a Diamond Spike enchanted with Looting III, and a Dimlet Analyzer, in one day you can have nearly every Dimlets, except Tier 6 Dimlets, for Dragons, Withers, Draconium Ore (that is not in The 1.7.10 Pack) and some liquids. In the 1.7.10 Pack, this is less visible, but it's still OP.
In The 1.7.10 Pack, you have the Digital Miner to mine, but it's not as fast as the Builder Block, and it also cost more energy, even full upgraded. Also, the range is 128x128x256 max, even with computercraft, that is 16 times smaller. And the cost of the Digital Miner is higher than the Builder Block in quarry mode. In late game, you have Forestry and Magical Crops farm, but they're not as powerful as creating a world of RFTools full of ores. And even a bug that give infinite uses of the Tome of Alkalestry in a Crafter is less powerful than that. So I suggest something to add RFTools in The 1.7.10 Pack without breaking the balancing of the modpack : adding the mod, but with a lot of modifications in his .cfg file and in his crafts.
I've looked a bit in the config file, and it's possible to increase RF costs of every machines and dimlets maintain cost, increasing the rarity of dimlets (by rarity) and a lot of other things. For example, changing the rarity of Dimlets (by x1 for rarity 0, x2 for rarity 1, x4 for rarity 2, x8 for rarity 3, ...) makes the powerful dimlets more late game, when you just need to farm ores for insane projets, or increasing of the cost of the quarry module of the Builder Block to avoid abuse of this in early.
I hope you'll read this and take this in count.

PS : sorry if I make some mistakes in words/sentences, I tried to make as less as possible, but English isn't my native language.

**Comment by xJon** [comment]
Even though this mod was already suggested many times, this is one of the more in-depth suggestions yet. I am taking this into account, maybe for the future, but currently we don't want to make major changes to the pack, so the mod won't be added. Only small updates to the pack will be released for now.
Feel free to add the mod manually though, and thank you for your suggestion.
