### ISSUE TITLE
Server keeps on crashing on launch 

### ISSUE THREAD

**Issue by goldenky** [xJon/The-1.7.10-Pack#1718]
Already tried using the backup - this never used to happen before. Anyways I could fix it? ty.

![unknown](https://user-images.githubusercontent.com/49341463/55669872-9d4c8880-5874-11e9-9f11-5f864eff27b5.png)
![unknown](https://user-images.githubusercontent.com/49341463/55669876-a50c2d00-5874-11e9-9892-b3f0d2eef598.png)

**Comment by goldenky** [comment]
also tried removing the hardcore quests file shit

**Comment by gandhi01** [comment]
go into eula.txt and change it from false to true

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).
Also, please watch your language, this isn't school and the support you're receiving is voluntary.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
