### ISSUE TITLE
cannot get server to work

### ISSUE THREAD

**Issue by gandhi01** [xJon/The-1.7.10-Pack#1719]
hello, me and my mate cant get the server to work, the server loads up but when he try's to connect it just kicks him straight away.

so I tried making one on my laptop just to see if it works, and it worked and I could connect, the lag was bad but that's not the point. (he has a new gaming pc and I have normal laptop so he needs to run the server) so since his didn't work and mine did i thought i would send him my server to see if that works and he ran it and it still kicked him out....

also another issue were having is we cant connect to eachothers servers now there modded. the first time we attempted to make the server we messed up completely and launched it using the normal server.jar file, which obviously made a non modded server... but i could still connect to it and play on it without mods, but now we have it modded, it no longer shows up on my Minecraft, even though it does for him. the exact same happened when i ran the server on my laptop. i could connect but he couldent see it, only happens when the server is modded…..

[fml-server-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/3052225/fml-server-latest.log)

anyway heres the server log for his server cheers for reading:)

**Comment by gandhi01** [comment]
https://paste.ubuntu.com/p/KJQHkWwfPR/ in case you didn't wanna download it

**Comment by xJon** [comment]
_"How to set up a dedicated server"_, by @Curunir, 2016

> 1. Download the server package version you need here: http://the-1710-pack.com/repo
> 2. Extract the package to where you want your server to run. This will work side-by-side with a client installation, but unless your PC is a high-end monster, it is much recommended to use another PC for the server, if any is available.
> 3. Make sure your clients can see the server. If you are all on the same home network (LAN), this should just work. To have it work across the Internet, the server needs to have the port it will listen to (default: 25565) forwarded from the router. This will not (ever) work if your ISP puts you in the baby cage that is carrier-grade NAT, so let's hope yours doesn't.
> 4. Edit your server.properties file with all the settings you need. Guide is here: http://minecraft.gamepedia.com/Server.properties
> 5. If you want to import a singleplayer world, locate the worldsave and copy it over to the server directory. You need to set the world name in server.properties to the exact directory name of the worldsave for it to use the existing one. Even if you let it generate a world, the name that you set here will be used, default is just "world".
> 6. If you need it to work for more than just a couple of friends, give it more RAM. Edit the launch script and change the -Xms (minimum) and -Xmx (maximum) allocation values as needed. For a first try, defaults will be fine.
> 7. If you were wondering, launch.bat is your launch script on Windows, while launch.sh is the one for Linux/Unix/MacOS. ALWAYS use the script, never manually start the server.jar. If you do, you will start a vanilla (i.e. unmodded) server that will do weird shit.
> 8. Run the server, don't be intimidated by the millions of errors and give it time. Once it stops generating new lines while not falling back to the command line or closing, it should be up and running. Try connecting with a client, using the IP adress or a DNS-resolved name.

**Comment by gandhi01** [comment]
This is exactly what i done, it worked on my laptop but didnt work on my friends computer, i made sure he did exactly that when he created his own, and i also sent over my pre made one which worked and that didnt even work on his. Dont think how i made the server is the issue

**Comment by xJon** [comment]
It's unclear to me what the problem exactly is, because in the log you posted the server seemed to boot fine.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
