### ISSUE TITLE
The 1.7.10 Pack Crashes After Starting

### ISSUE THREAD

**Issue by Gurkan16** [xJon/The-1.7.10-Pack#1720]
firstly sorry for my bad english. i have downloaded 1.7.10 Pack and started
after a while without any errors began to crashes help me please game  is not starts
i have a 6 gb of ram my pc 

logs is here 
[crash-2019-04-08_15.20.23-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3054247/crash-2019-04-08_15.20.23-client.txt)
[fml-client-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/3054248/fml-client-latest.log)

**Comment by xJon** [comment]
Please post your logs **using a [paste-tool](http://paste.ubuntu.com/)**.

**Comment by Gurkan16** [comment]
it was solved now.
beacuse of this mod : EnderCore 
i deleted EnderCore and fixed.
