### ISSUE TITLE
Cant download 0.9.8b mystcraft

### ISSUE THREAD

**Issue by SavageSimon** [xJon/The-1.7.10-Pack#1722]
Everytime I tried to download 1.7.10pack it got an error when it was supposed to download the mystcraft mod, tried to reinstall launcher but same thing happend again.
what could I do

**Comment by xJon** [comment]
Download link seems to be working well for me: http://solder.endermedia.com/repository/mods/mystcraft/mystcraft-jon-0.12.3.04-0.9.8b.zip

**Comment by SavageSimon** [comment]
Well, I dont know what the problem was but as I tried to download it on another browser it worked, thanks for the quick answer

**Comment by xJon** [comment]
👍
