### ISSUE TITLE
 Fatal error occurred, this connection is terminated.

### ISSUE THREAD

**Issue by StrnyKo** [xJon/The-1.7.10-Pack#1723]
I wanted to create a new singleplayer world,it loaded but then i got kicked and i had message on screen:''Fatal error occurred, this connection is terminated''.Same problem with multiplayer mode.
What can i do?

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
