### ISSUE TITLE
A fatal error has ocurred this conection is terminated single and  multiplayer

### ISSUE THREAD

**Issue by PENA98** [xJon/The-1.7.10-Pack#1726]
Hi, i am having problems with the modpack 

[13:17:27] [Client thread/INFO] [TabbyChat/]: [CHAT] §6§o[The 1.7.10 Pack] §r§e§oThank you for 1000000 downloads!
[13:17:27] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel Morph
java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject
	
This is fixed by removing morph from the modpack files,
but the problem is that i am trying to conect to a server and it wont let me in because i dont have morph in mi mods, What can i do?

**Comment by xJon** [comment]
Hi,
Does the problem persist if you then re-add the Morph mod into the pack?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
