### ISSUE TITLE
Server stops when I join but not when other players do

### ISSUE THREAD

**Issue by 5ricc** [xJon/The-1.7.10-Pack#1729]
Hello! I have no idea what I'm doing or whats going on! Im using the 0.9.7 version because my friend says it has a mod that he really loves.

uhh.. but yeah I was playing with my friend and suddenly the server stops. when he rejoins nothing happens but when I rejoin the server stops again. Please help me, this is one of the only ways I can hang out with my friend!

Here is the crach report thing.. I'm sorry this is my firts post so if anything is kinda wonky thats why. Im using the serverminer service to run it as well

**Edited: please use a paste-tool to post logs**

**Comment by xJon** [comment]
Simply seems like corrupted chunks.

* One solution would be to restore a world backup (the modpack makes backups automatically).
* A second solution would be trying to use [Region Fixer](https://github.com/Fenixin/Minecraft-Region-Fixer).

Good luck!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
