### ISSUE TITLE
Fn (Function key, 196) opening up a "screenshot" menu

### ISSUE THREAD

**Issue by GangstaKev** [xJon/The-1.7.10-Pack#1730]
Is there any way to change the keybind for the screenshot menu or just disable it entirely? Thanks.

**Comment by xJon** [comment]
Hi,
Does that key not appear in the controls menu? Did you try the LiteLoader menu? (accessed through the main menu)

**Comment by GangstaKev** [comment]
No, it does not. I disabled all the VoxelMods because they were annoying and useless, and LiteLoader is loading VoxelMods I think. Now, the fn key opens this: https://imgur.com/a/t4ATBRH

The function keys also does something, which I don't like because I use them a lot. Can you give me a file where I can disable all those keys? (They're not in mod settings and I can't configure them.)

**Comment by xJon** [comment]
The screenshot you posted is from the MineMenu mod. If you want, you can delete it as well.
I am confused as it wasn't configured to use the `Fn` key.

**Comment by GangstaKev** [comment]
Thanks, also, when I press Fn, it opens a tinkers construct sort of thing where you make keybinds? Not too clear on that, anyway to disable that? (I checked configurations for the Tinkers Construct mods, they are not able to be configured.)

**Comment by xJon** [comment]
Hi,
I checked with my laptop that has the `Fn` key and no matter what I tried I could not reproduce this issue.
You could simply try to avoid using the key in your keyboard or look into whether this happens in other modpacks as well.
