### ISSUE TITLE
Crashing on the 1.7.10 mod pack

### ISSUE THREAD

**Issue by Kai20129123** [xJon/The-1.7.10-Pack#1731]
I try to open a world but it keeps crashing when I start moving or when I open the pause menu. I've tried reinstalling it and going into setting when it's not in a world but it keeps crashing. Any help is appreciated as this mudpack has become my favorite over the time I have played it and I'm very sad I can't play right now
[crash-2019-04-20_22.41.02-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3100953/crash-2019-04-20_22.41.02-client.txt)
[crash-2019-04-20_22.44.27-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3100954/crash-2019-04-20_22.44.27-client.txt)
[crash-2019-04-20_23.13.53-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3100955/crash-2019-04-20_23.13.53-client.txt)
[crash-2019-04-20_23.16.49-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3100956/crash-2019-04-20_23.16.49-client.txt)
[crash-2019-04-20_23.22.29-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3100957/crash-2019-04-20_23.22.29-client.txt)
[crash-2019-04-20_23.29.00-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3100958/crash-2019-04-20_23.29.00-client.txt)
[crash-2019-04-20_23.35.42-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3100959/crash-2019-04-20_23.35.42-client.txt)
[crash-2019-04-20_12.08.38-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/3100960/crash-2019-04-20_12.08.38-server.txt)
[crash-2019-04-20_21.37.47-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3100961/crash-2019-04-20_21.37.47-client.txt)
[crash-2019-04-20_22.33.21-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3100962/crash-2019-04-20_22.33.21-client.txt)
[crash-2019-04-20_22.37.42-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3100963/crash-2019-04-20_22.37.42-client.txt)

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
