### ISSUE TITLE
Crash on opening inventory

### ISSUE THREAD

**Issue by Pandinator** [xJon/The-1.7.10-Pack#1734]
Tried to join a friend's server, could run around fine, but crashes upon opening my inventory.

EDIT: Also on opening books.

[crash-2019-04-22_15.51.39-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3102671/crash-2019-04-22_15.51.39-client.txt)

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
