### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by OldestStern** [xJon/The-1.7.10-Pack#1735]
[crash-2019-04-26_17.29.46-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3123075/crash-2019-04-26_17.29.46-client.txt)

**Comment by OldestStern** [comment]
It says something about missing OpenGL in the console.

**Comment by OldestStern** [comment]
https://paste.ubuntu.com/p/6rzdYYJHmV/

**Comment by OldestStern** [comment]
I have resolved the issue. Not sure how, but my best guess is that my monitor had something to do with it.

**Comment by xJon** [comment]
👍
