### ISSUE TITLE
Crash on opening map (server)

### ISSUE THREAD

**Issue by Gabriel2536** [xJon/The-1.7.10-Pack#1736]
Hello,

I have a persistent issue, that makes my game crash completely to the technic launcher when I open the map. It happens in a specific area, but that in itself doesn't have anything special in it...except maybe a large number of carpenters blocks and those nether biomes in the overworld that spawned back when the server was started. Hoewer I had this issue in version 0.9.7 and it disappeared in 0.9.8 and is now back in 0.9.8b and I cannot even say it started the moment I updated since sometimes the game seems to have a great day and doesn't do this for an entire session, but after another start, it does this again. It happens only to me and nobody else on my server. If the game just kicked me off the server it would be ok, but since it crashes to the launcher, it gets quite annoying really fast and the map is necessary for building planning.

**Comment by xJon** [comment]
Please post your crash log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Gabriel2536** [comment]
Do I asume right, I'll find it here? C:\Users\XXX\AppData\Roaming\.technic\modpacks\the-1710-pack\reports

**Comment by xJon** [comment]
Crash logs, yes.

**Comment by Gabriel2536** [comment]
Finally, it happened again. Here's the report: https://paste.ubuntu.com/p/3fZjdbHsg4/

**Comment by xJon** [comment]
So basically you get this crash, when you open the full mini-map in a specific location?
Are you playing on single-player?

**Comment by Gabriel2536** [comment]
Full minimap yes. It isn't about opening it at that location but looking at the location on the minimap. I can be 3000 blocks away and open it just fine, but when I move the minimap near that location it crashes. I play on a server, but I'm the only one this happens to and I go straight to TechnicLauncher, so I don't believe it can be server related. Also, it is quite random when it happens. As you saw from the time it took me for it to happen again (and I was playing every day for a couple of hours).

**Comment by xJon** [comment]
You're the only one it happens to?
Can you try to (backup and) delete the files of the VoxelMap mod? (find them here: `\modpacks\the-1710-pack\mods\VoxelMods`.

**Comment by Gabriel2536** [comment]
Well, we only play 2 on the server, but yes, it doesn't happen to my friend. I tried deleting it and so far it didn't crash. I'll give it about 2 weeks to see if it happens again (it was never longer). If not, I'll close this issue. Thanks for the help so far.

**Comment by xJon** [comment]
👍

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
