### ISSUE TITLE
The 1.7.10 Pack not launching

### ISSUE THREAD

**Issue by ZurexX** [xJon/The-1.7.10-Pack#1737]
if I press on play the modpack loads briefly, the launcher closes and appears again and the modpack does not start

[hs_err_pid1368.log](https://github.com/xJon/The-1.7.10-Pack/files/3124861/hs_err_pid1368.log)

sorry for my bad english

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by voppe** [comment]
It seems you have not enough physical RAM.

```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 4294967296 bytes for Failed to commit area from 0x00000006c0000000 to 0x00000007c0000000 of length 4294967296.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
```
From the log.

How much RAM does your PC have?

**Comment by ZurexX** [comment]
> Please post your logs using a [paste-tool](http://paste.ubuntu.com/).



> It seems you have not enough physical RAM.
> 
> ```
> # There is insufficient memory for the Java Runtime Environment to continue.
> # Native memory allocation (mmap) failed to map 4294967296 bytes for Failed to commit area from 0x00000006c0000000 to 0x00000007c0000000 of length 4294967296.
> # Possible reasons:
> #   The system is out of physical RAM or swap space
> #   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
> # Possible solutions:
> #   Reduce memory load on the system
> #   Increase physical memory or swap space
> ```
> 
> From the log.
> 
> How much RAM does your PC have?

I already fixed it. It was my Graphics driver, i don't know why but yeah

**Comment by xJon** [comment]
👍
