### ISSUE TITLE
Chunk loaders appear to be nonfunctional

### ISSUE THREAD

**Issue by InterFelix** [xJon/The-1.7.10-Pack#1738]
I can't say this for sure, but on our server chunk loaders seem to be not working at all. Is there some kind of server setting that disables chunk loading? I'm fairly new to this pack and would like to use chunk loaders. When googling around I only found a permission in FTBUtilities that may ban them, but since FTBUtilities is not installed in this modpack that didn't lead me anywhere useful.

**Comment by xJon** [comment]
Which chunk loaders have you been using?

**Comment by xJon** [comment]
Hi,
Trying to use the chunk loader seems to work fine. I'm not sure why it doesn't work on your server, but you could try to re-install it.
