### ISSUE TITLE
Pack is now crashing after 2 previous successful loads

### ISSUE THREAD

**Issue by Dalogadro** [xJon/The-1.7.10-Pack#1740]
Hi there,

I have been trying to use this amazing modpack but am having some issues. I ran the pack earlier with no troubles but now suddenly the pack is crashing upon load. I read through the crash report and it mentioned "Ender IO", I tried removing all associated mods with this aswell as the ender io mod but am having no luck (I'm a chemist not a programmer so that was probably the worst thing to do).

Any help would be much appreciated as this is the best pack :(

Dalogadro

[crash-2019-05-07_10.31.07-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3153855/crash-2019-05-07_10.31.07-client.txt)

[crash-2019-05-07_10.31.07-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3153859/crash-2019-05-07_10.31.07-client.txt)

**Comment by ciak2009** [comment]
Put any mods you removed back, and try it with removing only Fastcraft.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
