### ISSUE TITLE
Game keeps crashing.

### ISSUE THREAD

**Issue by saintshifter** [xJon/The-1.7.10-Pack#1742]
[crash-2019-05-08_16.39.20-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3159392/crash-2019-05-08_16.39.20-client.txt)

**Comment by xJon** [comment]
Please post your log using a [paste-tool](http://paste.ubuntu.com/).

**Comment by clienthax** [comment]
Gpu driver bug.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
