### ISSUE TITLE
Technic launcher wont give me more ram

### ISSUE THREAD

**Issue by semenoid** [xJon/The-1.7.10-Pack#1744]
When launching the mudpack I'm given an error message saying "You don't have enough ram". It says I only have 1 gig allocated, but when I go to change it in the launcher, the max amount of ram I can allocate is 1 gig. (I have 16)

**Comment by xJon** [comment]
You need to install and select Java 64 bit.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
