### ISSUE TITLE
Server Crashing during launch

### ISSUE THREAD

**Issue by blap23** [xJon/The-1.7.10-Pack#1745]
My computer crashed while the server was running and now the server spits out errors during launch. I have tried taking the mod pack out that it says is the problem and then it says another mod pack is the issue. Not sure how to fix this. Looked on the forum and didn't see a problem like mine. Any help is greatly appreciated. Thanks.

Here is the Pastebin link: https://paste.ubuntu.com/p/zdmC5qsntb/

**Comment by xJon** [comment]
You have corrupted questing data - simply reset (delete) the inside of `HardcoreQuesting` within your server's world folder. This will reset your quests progress, but you can always cheat the items you had back in if you want.
