### ISSUE TITLE
Aluminium is very rare

### ISSUE THREAD

**Issue by anwarsaed** [xJon/The-1.7.10-Pack#1746]
Lately I have been finding a lot of ores except aluminium. I am trying to work on galacticraft stuff, but without aluminium I cannot work on it. Is there anyway I can increase the chances of me finding aluminium?

**Comment by xJon** [comment]
Although not super common, Tinkers' aluminium ore can be found pretty easily if you're looking in the right levels. I'd suggest Y=40 to Y=60.
