### ISSUE TITLE
Fatal error Occured

### ISSUE THREAD

**Issue by valij** [xJon/The-1.7.10-Pack#1747]
Everytime i try to start a world or something i get fatal error 

Here is the pastelink:    https://paste.ubuntu.com/p/P3N7rfxffv/

**Comment by xJon** [comment]
Hi, this log doesn't include any error. 
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by valij** [comment]
https://paste.ubuntu.com/p/zfCPQfwtwM/

**Comment by xJon** [comment]
Morph for 1.7.10 is buggy. Try to manually remove the mod and launch again. Should fix your issue.
