### ISSUE TITLE
Suggestion: some TiC addons for the modpack

### ISSUE THREAD

**Issue by 420BlazeItFaggot** [xJon/The-1.7.10-Pack#1748]
Hope this is the correct tab
My suggestion is that some TiC addons are added to the modpack. For example Extra TiC would add about 70 materials to make tools from; currently it's a bit lame that there are very few late game materials and it would be great if something more was added.

**Comment by xJon** [comment]
Currently we don't want to add the mod as we don't want to make major changes to the pack.
Feel free to add the mod manually though!
