### ISSUE TITLE
Pack wont launch

### ISSUE THREAD

**Issue by freeze61** [xJon/The-1.7.10-Pack#1749]
I try to launch the pack and it starts for a little with a black screen then fails.

log

**EDITED: Please use a [paste-tool](http://paste.ubuntu.com) to post your full log.**

**Comment by xJon** [comment]
Please post your full log using a paste-tool.

**Comment by freeze61** [comment]
> Please post your full log using a paste-tool.

[2019-05-19-5.log.gz](https://github.com/xJon/The-1.7.10-Pack/files/3200043/2019-05-19-5.log.gz)

**Comment by xJon** [comment]
Please use a [paste-tool](http://paste.ubuntu.com) to post your full log

**Comment by freeze61** [comment]
> Please use a [paste-tool](http://paste.ubuntu.com) to post your full log.

https://paste.ubuntu.com/p/RgWPjm6Z3X/plain/ is this what you mean. sorry about this im not to good with computers

**Comment by xJon** [comment]
This is an issue with the `It's the little things` mod that [has already been reported](https://github.com/zlepper/itlt/issues/11) to the mod author. Your two options are to re-install the modpack inside of a directory, or alternatively remove the problematic mod.

**Comment by freeze61** [comment]
Thank you very much for the help
