### ISSUE TITLE
Game crash when I try to Join a in particular server

### ISSUE THREAD

**Issue by Jarrett07** [xJon/The-1.7.10-Pack#1751]
When i try to join the Server NexusNet I load into the server like any other one, but right before I fully join the whole tab closes and sends me back to the Technic Launcher.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
