### ISSUE TITLE
Server Won't Start

### ISSUE THREAD

**Issue by ChubbyMooshroom** [xJon/The-1.7.10-Pack#1752]
I have downloaded everything, EULA is set to true, but after I run the bat and press any button to continue, the command prompt immediately closes. How can I fix this?

**Comment by userxxxx-coder** [comment]
This has happened to me. It turns out to be that i had a 32 bit version of Java. I uninstalled java and uninstalled this version of java : https://www.java.com/en/download/manual.jsp. Download the "Windows Offline (64-bit). Hope this helps!

**Comment by ChubbyMooshroom** [comment]
Would that be a problem if I have multiple java's installed? I do have 64 bit installed, but I thought x86 was better and apparently it's only 32 bit, but I've got multiple copies of that. Would that impact it?

Also, how would I delete all those files?

**Comment by userxxxx-coder** [comment]
Type in the search tab "Add or remove a program", let it load, the scroll down til you see 'Java' click it, then click uninstall. Then download the java i sent you then follow the normal installation process. If you change the destination file, it wont work(well for me). x86 is 32bit.

**Comment by ChubbyMooshroom** [comment]
Ok, I deleted anything with the name Java, didn't change folders from the download you sent me, still closing immediately once I click a button. 

It gives me the message "'java' is not recognized as an internal or external command,
operable program or batch file." above it though, could that mean anything?

**Comment by userxxxx-coder** [comment]
What does your batch file say? Open cmd and type " java -version" <no quotes.

**Comment by ChubbyMooshroom** [comment]
"'java-version' is not recognized as an internal or external command,
operable program or batch file."

**Comment by userxxxx-coder** [comment]
Not that. What did you write inside the batch file to launch your server? send that and the output from the cmd where you wrote "java -version".

**Comment by ChubbyMooshroom** [comment]
"@ECHO OFF

:: When setting the memory below make sure to include the amount of ram letter. M = MB, G = GB. Don't use 1GB for example, it's 1G ::

:: This is 64-bit memory ::
set memsixtyfour=4G

:: This is 32-bit memory - maximum 1.2G ish::
set memthirtytwo=1G

:: Don't edit past this point ::

if $SYSTEM_os_arch==x86 (
  echo OS is 32
  set mem=%memthirtytwo%
) else (
  echo OS is 64
  set mem=%memsixtyfour%
)
java -server -Xmx%mem% -XX:PermSize=256M -XX:+UseG1GC -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dfml.queryResult=confirm -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui
PAUSE
"

This is the bat-file as is. I might have added the pause, idr. I did do "java -version", I got the same thing but with java instead of "java-version".

**Comment by userxxxx-coder** [comment]
Try something simpler for your batch file. try this:

java -Xmx4096M -Xms1024M -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui 
pause

cut down ur forge file name to forge-1.7.10.jar for the actual file and in the batch.

**Comment by ChubbyMooshroom** [comment]
Java-version still giving the same dead message, did I install it wrong? Technic Launcher is recognizing it as downloaded.

Also, I put that command above in(with the replaced name ofc), and this message appeared.

> 'java' is not recognized as an internal or external command,
operable program or batch file.
'pausent' is not recognized as an internal or external command,
operable program or batch file.

**Comment by userxxxx-coder** [comment]
Ok lets leave the cmd part. try the other piece of java batch file code and tell me if that works

**Comment by ChubbyMooshroom** [comment]
Maybe I'm being dense, but...what other .bat file? I already tried the other jumble of code in this .bat file.

https://cdn.discordapp.com/attachments/568512578888925184/580951557302910987/unknown.png

**Comment by userxxxx-coder** [comment]
ok so make a .txt file and copy and paste this into it 
java -Xmx4096M -Xms1024M -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui
pause

click file>save as>forge.bat
run it and tell if that works

**Comment by ChubbyMooshroom** [comment]
Nope, same "java" isn't recognized thing, click a button then it disappears immediately.

**Comment by userxxxx-coder** [comment]
Try restarting your computer if you can. Maybe your computer needs refresher.

**Comment by ChubbyMooshroom** [comment]
Will do, and will get back to ya.

**Comment by ChubbyMooshroom** [comment]
OK so still getting the same java error. 

This is literally rocket science.

**Comment by userxxxx-coder** [comment]
omg haha. ok so do you have discord? we can talk through there

**Comment by ChubbyMooshroom** [comment]
I do, Chubbs#4330.

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
