### ISSUE TITLE
When i try and load up Tekkit it keeps crashing Help plz

### ISSUE THREAD

**Issue by Gucci1108** [xJon/The-1.7.10-Pack#1756]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 29/05/19 03:27
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.OutOfMemoryError
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:34)
	at net.minecraft.client.renderer.Tessellator.<clinit>(Tessellator.java:26)
	at moze_intel.projecte.events.ModelYue.<init>(ModelYue.java:15)
	at moze_intel.projecte.events.PlayerRender.<clinit>(PlayerRender.java:17)
	at moze_intel.projecte.proxies.ClientProxy.registerClientOnlyEvents(ClientProxy.java:109)
	at moze_intel.projecte.PECore.preInit(PECore.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 712620056 bytes (679 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -Xms1024m -Xmx1024m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCH	Forge{10.13.4.1492} [Minecraft Forge] (modpack.jar) 
	UCH	CodeChickenCore{1.0.6.41} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.4.102} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.102-universal.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	mcdiscord{2.0.0} [MC Discord] (minecraft.jar) 
	UCH	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCH	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCH	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCH	BuildCraft|Core{7.1.14} [BuildCraft] (buildcraft-7.1.14.jar) 
	UCH	BuildCraft|Transport{7.1.14} [BC Transport] (buildcraft-7.1.14.jar) 
	UCH	BuildCraft|Silicon{7.1.14} [BC Silicon] (buildcraft-7.1.14.jar) 
	UCH	BuildCraft|Factory{7.1.14} [BC Factory] (buildcraft-7.1.14.jar) 
	UCH	BuildCraft|Robotics{7.1.14} [BC Robotics] (buildcraft-7.1.14.jar) 
	UCH	ComputerCraft{1.74} [ComputerCraft] (ComputerCraftPlusComputerCraftEdu1.74.jar) 
	UCH	IC2{2.2.999} [Industrial Craft Classic] (IC2.Classic.Version.1.2.0.1.jar) 
	UCH	Forestry{3.6.12.3} [Forestry for Minecraft] (forestry_1.7.10-3.6.12.3.jar) 
	UCH	LogisticsPipes{0.9.3.83} [Logistics Pipes] (logisticspipes-0.9.3.83.jar) 
	UCH	additionalpipes{4.7.0} [Additional Pipes] (additionalpipes-4.7.0.jar) 
	UCH	asielib{0.4.5} [asielib] (AsieLib-1.7.10-0.4.5.jar) 
	UCH	bdlib{1.9.3.107} [BD Lib] (bdlib-1.9.3.107-mc1.7.10.jar) 
	UCH	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCH	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.114-universal.jar) 
	UCH	bluepower{0.2.962} [Blue Power] (BluePower-1.7.10-0.2.962-universal.jar) 
	UCH	BuildCraft|Builders{7.1.14} [BC Builders] (buildcraft-7.1.14.jar) 
	UCH	BuildCraft|Energy{7.1.14} [BC Energy] (buildcraft-7.1.14.jar) 
	UCH	BuildCraft|Compat{7.1.3} [BuildCraft Compat] (buildcraft-compat-7.1.3.jar) 
	UCH	CarpentersBlocks{3.3.8_dev_r8} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8_dev_r8 - MC 1.7.10.jar) 
	UCH	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCH	ComputerCraftEdu{1.74} [ComputerCraftEdu] (ComputerCraftPlusComputerCraftEdu1.74.jar) 
	UCH	Railcraft{9.10.0.0} [Railcraft] (Railcraft_1.7.10-9.10.0.0.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	computronics{1.6.0} [Computronics] (Computronics-1.7.10-1.6.0.jar) 
	UCH	defaultkeys{1.0.24} [Default Keyconfig] (defaultkeys-mc1.7.10-1.0.24.jar) 
	UCH	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCH	eng_toolbox{1.2.3.0} [Engineer's Toolbox] (EngineersToolbox-1.2.3.0-BETA.jar) 
	UCH	ForgeMultipart{1.2.0.344} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	UCH	McMultipart{1.2.0.344} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	UCH	gendustry{1.6.1.126} [GenDustry] (gendustry-1.6.1.126-mc1.7.10.jar) 
	UCH	IC2-Classic-Spmod{0.0.0.0} [IC2 Classic Detection Helper] (IC2.Classic.Version.1.2.0.1.jar) 
	UCH	IC2NuclearControl{2.3.3a-Exist} [Nuclear Control 2] (IC2NuclearControl-2.3.3a-Exist.jar) 
	UCH	ImmibisCore{59.1.2} [Immibis Core] (immibis-core-59.1.2.jar) 
	UCH	ImmibisPeripherals{59.0.2} [Immibis's Peripherals] (immibis-peripherals-59.0.2.jar) 
	UCH	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) 
	UCH	IronChest{6.0.60.741} [Iron Chest] (Ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCH	itlt{0.0.8} [It's the little things] (itlt-1.7.10-0.0.8.jar) 
	UCH	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCH	MapWriter{2.1.8} [MapWriter] (MapWriter-1.7.10-2.1.10.jar) 
	UCH	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10.jar) 
	UCH	modtweaker2{0.9.4} [Mod Tweaker 2] (ModTweaker2-0.9.4.jar) 
	UCH	numina{0.4.0.131} [Numina] (Numina-0.4.0.131.jar) 
	UCH	powersuits{0.11.0.300} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.300.jar) 
	UCH	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCH	NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCH	neiintegration{1.0.12} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.12.jar) 
	UCH	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCH	OCS{1.7.5} [OpenCCSensors] (openccsensors-1.7.5.jar) 
	UCH	planetguyLib{1.9} [planetguyLib] (PlanetguyLib-1.9.1.jar) 
	UCH	PowerConverters3{1.7.10-2.11} [Power Converters 3] (PowerConverters-1.7.10-2.11.jar) 
	UCE	ProjectE{1.7.10-PE1.9.5} [ProjectE] (ProjectE-1.7.10-PE1.9.5.jar) 
	UCH	quiverchevsky{b101c} [QuiverBow] (QuiverBow_1.7.10_b101d.zip) 
	UCH	RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.2-92.jar) 
	UCH	JAKJ_RedstoneInMotion{2.8.8} [Remain In Motion] (RemainInMotion-2.8.8.jar) 
	UCH	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
	UCH	Tubestuff{59.0.4} [Tubestuff] (tubestuff-59.0.4.jar) 
	UCH	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
	UCH	zettaindustries{1.1} [Zetta Industries] (zettaindustries-1.1-105.jar) 
	UCH	aobd{2.8.4} [Another One Bites The Dust] (AOBD-2.8.4.jar) 
	UCH	ForgeMicroblock{1.2.0.344} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	CoFHCore: -[1.7.10]3.1.2-325
	NetherOres: -[1.7.10]2.3.0-12
	RedstoneArsenal: -[1.7.10]1.1.2-92
	List of loaded APIs: 
		* apAPI (2) from additionalpipes-4.7.0.jar
		* asielibAPI (1.1) from AsieLib-1.7.10-0.4.5.jar
		* asielibAPI|chat (1.0) from AsieLib-1.7.10-0.4.5.jar
		* asielibAPI|tile (1.0) from AsieLib-1.7.10-0.4.5.jar
		* asielibAPI|tool (1.1) from AsieLib-1.7.10-0.4.5.jar
		* bluepowerAPI (1.0) from BluePower-1.7.10-0.2.962-universal.jar
		* BuildCraftAPI|blocks (1.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|blueprints (1.2) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|core (2.0) from Railcraft_1.7.10-9.10.0.0.jar
		* BuildCraftAPI|crops (1.1) from Railcraft_1.7.10-9.10.0.0.jar
		* BuildCraftAPI|events (1.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|facades (1.1) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|filler (4.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|gates (4.1) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.1.14.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|lists (1.0) from Railcraft_1.7.10-9.10.0.0.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.14.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|statements (1.1) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.14.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.1.14.jar
		* BuildCraftAPI|tools (1.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* BuildCraftAPI|transport (4.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.8_dev_r8 - MC 1.7.10.jar
		* CoFHAPI (1.7.10R1.0.1) from RemainInMotion-2.8.8.jar
		* CoFHAPI|block (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|core (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from forestry_1.7.10-3.6.12.3.jar
		* CoFHAPI|fluid (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|inventory (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|item (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|modhelpers (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|tileentity (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHAPI|transport (1.7.10R1.0.12) from EngineersToolbox-1.2.3.0-BETA.jar
		* CoFHAPI|world (1.7.10R1.1.0) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|audio (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui|container (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui|element (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|gui|slot (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|inventory (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|render (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|render|particle (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|util (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|util|helpers (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|util|position (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|world (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* CoFHLib|world|feature (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.2-325.jar
		* ComputerCraft|API (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
		* ComputerCraft|API|FileSystem (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
		* ComputerCraft|API|Lua (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
		* ComputerCraft|API|Media (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
		* ComputerCraft|API|Peripheral (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
		* ComputerCraft|API|Permissions (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
		* ComputerCraft|API|Redstone (1.74) from EngineersToolbox-1.2.3.0-BETA.jar
		* ComputerCraft|API|Turtle (1.74) from ComputerCraftPlusComputerCraftEdu1.74.jar
		* computronicsAPI (1.3) from Computronics-1.7.10-1.6.0.jar
		* computronicsAPI|audio (1.0) from Computronics-1.7.10-1.6.0.jar
		* computronicsAPI|chat (1.3) from Computronics-1.7.10-1.6.0.jar
		* computronicsAPI|multiperipheral (1.1) from Computronics-1.7.10-1.6.0.jar
		* computronicsAPI|tape (1.0) from Computronics-1.7.10-1.6.0.jar
		* ForestryAPI|apiculture (3.5.0) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|circuits (2.0.0) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|core (3.2.0) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|genetics (3.3.0) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|recipes (3.1.0) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-3.6.12.3.jar
		* ForestryAPI|world (1.1.0) from forestry_1.7.10-3.6.12.3.jar
		* gendustryAPI (2.2.0) from gendustry-1.6.1.126-mc1.7.10.jar
		* IC2API (1.0) from IC2.Classic.Version.1.2.0.1.jar
		* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.3.3a-Exist.jar
		* ProjectEAPI (7) from ProjectE-1.7.10-PE1.9.5.jar
		* RailcraftAPI|bore (1.0.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|carts (1.6.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|core (1.5.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|crafting (1.0.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|electricity (1.6.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|events (1.0.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|items (1.0.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.10.0.0.jar
		* RailcraftAPI|signals (1.3.0) from EngineersToolbox-1.2.3.0-BETA.jar
		* RailcraftAPI|tracks (2.2.0) from Railcraft_1.7.10-9.10.0.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.10.0.0.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar

**Comment by clienthax** [comment]
OutOfMemoryError, give it more memory.

**Comment by xJon** [comment]
As @clienthax wrote, but also this is not a support channel for Tekkit, this is the repository for The 1.7.10 Pack.
