### ISSUE TITLE
Server Doesn't Start

### ISSUE THREAD

**Issue by llsuperl** [xJon/The-1.7.10-Pack#1757]
The server was previously working for 3 days until I opened my inventory and suddenly my computer bluescreened.  When I go to launch the server now it says, "The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.  Press any button to continue...".  It then closes the command prompt and does this everytime I launch the server.  Any way to fix this?

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
