### ISSUE TITLE
Crash every time join any server

### ISSUE THREAD

**Issue by GeneticCyber** [xJon/The-1.7.10-Pack#1758]
I've already reinstalled the pack and tweeked with the ram and everything crash report here https://cdn.discordapp.com/attachments/96558260349333504/583511070266621952/crash-2019-05-29_23.15.58-client.txt

**Comment by ciak2009** [comment]
Try temporarily disabling TabbyChat, it looks like that might be the crash reason. Let us know the outcome and we will troubleshoot from there

**Comment by xJon** [comment]
⏫

**Comment by GeneticCyber** [comment]
Yes it was ty

**Comment by xJon** [comment]
👍
