### ISSUE TITLE
I cant play. Every time i start singleplayer, it crashes to main menu

### ISSUE THREAD

**Issue by TadMik** [xJon/The-1.7.10-Pack#1759]
Game always crashes when i start singleplayer world why ?

**Comment by TadMik** [comment]
[2019-05-31_00.51.26.zip](https://github.com/xJon/The-1.7.10-Pack/files/3239017/2019-05-31_00.51.26.zip)

**Comment by TadMik** [comment]
[2019-05-31_00.51.26.zip](https://github.com/xJon/The-1.7.10-Pack/files/3239033/2019-05-31_00.51.26.zip)

**Comment by xJon** [comment]
Please post your logs **using a [paste-tool](http://paste.ubuntu.com/)**.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.

**Comment by Nokiroq** [comment]
I have the same issue @xJon here is crash report(s)
https://paste.ubuntu.com/p/3bDNn3GSC7/
https://paste.ubuntu.com/p/qqdZyh2GK3/

This last one is after reinstalling the pack.
https://paste.ubuntu.com/p/KSS6HQvHrR/

**Comment by xJon** [comment]
@Nokiroq I'd recommend you to load a backup. If you need further support please open your own issue.

**Comment by Nokiroq** [comment]
@xJon I opened my own issue https://github.com/xJon/The-1.7.10-Pack/issues/1894
