### ISSUE TITLE
Game lags upon entitys fires projectile

### ISSUE THREAD

**Issue by FriendlyPanda** [xJon/The-1.7.10-Pack#1761]
As mentioned above, every time a ghast, or any other entity fires a projectile the game lags mercilessly, despite turning all settings to minimum. I play on single player, I use 8 GB of RAM to run it, I also use latest 64 bit java. it does not happen on any other modpacks (1.7.10)

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
