### ISSUE TITLE
Server Crash when certain player joins.

### ISSUE THREAD

**Issue by NemisesNick** [xJon/The-1.7.10-Pack#1762]
Whenever my friend joins my server, the server crashes with the error: State engine was in the incorrect state. I am attaching the crash report.
[crash-2019-06-05_14.18.48-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/3259134/crash-2019-06-05_14.18.48-server.txt)

**Comment by xJon** [comment]
Please post your logs **using a [paste-tool](http://paste.ubuntu.com/)**.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
