### ISSUE TITLE
Can't download Server pack 

### ISSUE THREAD

**Issue by IronKenneth** [xJon/The-1.7.10-Pack#1763]
Can't download server pack located at: http://solder.endermedia.com/repository/downloads/the-1710-pack/the-1710-pack_0.9.8b.zip just brings up a Puffer login with no option to register or anything

**Comment by xJon** [comment]
Hi, is it resolved now?

**Comment by IronKenneth** [comment]
Yes! Thank you

**Comment by xJon** [comment]
:)
