### ISSUE TITLE
My game crashes when I try joining the official server.

### ISSUE THREAD

**Issue by Michalicek** [xJon/The-1.7.10-Pack#1764]
I was playing it yesterday and it was normal, but when I started it today it worked for a while, but then it crashed. When I try joining the official server now it just says joining server, gives blackscreen and crashes back to technic launcher. 

Here is my crash log: https://paste.ubuntu.com/p/RSJkxVNJG5/

**Comment by xJon** [comment]
There's no official server to the modpack.
If you mean you need support for HaxysHideout, the *recommended* server, you can go directly to them at  here: https://helpme.brixazure.com/
Or at their Discord server: https://discord.gg/ack4s8D
