### ISSUE TITLE
Remove Haxy's server from server list?

### ISSUE THREAD

**Issue by CustosAeternam** [xJon/The-1.7.10-Pack#1766]
I have the pack on a personal server for me and family, and this "Haxy's Hideout" server keeps popping up no matter how many times I remove it. I don't want it showing up in my server list, and I have tried almost everything to get rid of it; I say almost everything because it is still showing up, which means there is something I have not thought of that would get rid of it. I cant find how to get that annoying server off of my list. I just need to know what mod is adding it to my server list and I will be set, because even if there is no setting to stop it I can remove the mod or take other drastic measures if removing the mod is not an option.
Thank you in advance for any help provided.

**Comment by xJon** [comment]
This modpack setting can be altered by going to the `itlt.cfg` file within the config folder of the pack.
