### ISSUE TITLE
The packs wont download

### ISSUE THREAD

**Issue by FredGuyStupid** [xJon/The-1.7.10-Pack#1767]
Hey so basically. I've already said this in the discord server but i really cant wait. And i'll just do what i can do. So the problem is. Whenever i tried to download the pack it wont continue **(Look at the picture)**. I have tried a couple of stuff now. I've tried to disabling the antivirus. I've also tried to reinstalling it couple of times now. And i actually reset my pc and try to do it again. And non of it work. Thanks for helping and making minecraft alot better.
-Fred. 

![Capture](https://user-images.githubusercontent.com/51812969/59501278-c2d9bc00-8ecd-11e9-9adc-0d4fc2005785.PNG)

**Comment by xJon** [comment]
Hi,
Is this still an issue?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
