### ISSUE TITLE
Server launches but wont finish starting up

### ISSUE THREAD

**Issue by mjmarkby** [xJon/The-1.7.10-Pack#1768]
I start the server and everything launches fine but after waiting for around 5 mins, it will stop running through code when it has to load the hats for the hats mod. please help

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by kakashiis** [comment]
This can be a port forwarding issue also but I cant tell if I don't see the log

**Comment by mjmarkby** [comment]
dont worry, i was able to fix the issue with help from rokk in the discord,
any chance you could help me with giving moderator or admin or players on a
server?

**Comment by xJon** [comment]
Hi,
I'm glad you solved your issue. Unfortunately we do not provide here this kind of server support.
You can try to use Google or ask in different modded Minecraft Discord servers.
