### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by Quelho** [xJon/The-1.7.10-Pack#1769]
I start the modpack in launcher and he crash on loading screen.
https://paste.ubuntu.com/p/FxCdpFw977/

**Comment by Quelho** [comment]
https://paste.ubuntu.com/p/FxCdpFw977/ Sorry

**Comment by xJon** [comment]
Is this a new install of the modpack?
If so, can you try to re-install?

**Comment by Quelho** [comment]
i tried re install. dont work.

**Comment by xJon** [comment]
What happened after you've reinstalled?

**Comment by Quelho** [comment]
the same i reinstall and crash on loading screen

**Comment by xJon** [comment]
Is it the same crash report?
Can you reinstall by completely removing the modpack's files folder and then installing it again?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
