### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by RebelGunzz** [xJon/The-1.7.10-Pack#1770]
We had an issue on our server with certain blocks were placed.

- Turbine Casing
- Turbine Vent

These are part of the mekanism mod and am wondering why these would be causing our server to crash? We have since removed all blocks associated with the turbine that was being built and it solved the issue but would like to bring it to your attention that something isnt working together. 

Please see attached crash reports for reference.

[crash-2019-06-16_19.02.59-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/3298825/crash-2019-06-16_19.02.59-server.txt)
[crash-2019-06-16_18.24.07-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/3298830/crash-2019-06-16_18.24.07-server.txt)

**Comment by xJon** [comment]
Can you please post your logs using a [paste-tool](http://paste.ubuntu.com/)?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
