### ISSUE TITLE
1.7.10 pack crashing on startup

### ISSUE THREAD

**Issue by MrBigFeet** [xJon/The-1.7.10-Pack#1771]
Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
[B#407]  	EnderIO: Found the following problem(s) with your installation:
[B#407]                    * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from Flans Mod-1.7.10-4.10.0.jar).
[B#407]                      It is a supported version, but that difference may lead to problems.
[B#407]                   This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
[B#407]  	The 1.7.10 Pack - v0.9.8b: 

here is the crash report

**Comment by xJon** [comment]
Please post your crash report file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
