### ISSUE TITLE
Downloader Stuck at rhapsodia-0.6.zip

### ISSUE THREAD

**Issue by RiiVu** [xJon/The-1.7.10-Pack#1773]
whats poppin
the technic launcher downloader stucks at rhapsodia-0.6.zip
i tryed reinstall the modpack and reinstall the technic launcher
i dont know what to do :c
it stuck always at 23%

**Comment by xJon** [comment]
The Rhapsodia file is significantly larger, which would cause the download to appear to be stuck. It is not, you just have to wait for it to fully download.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
