### ISSUE TITLE
Can't fill galacticraft canisters with LOX

### ISSUE THREAD

**Issue by Hi-May** [xJon/The-1.7.10-Pack#1775]
I can't seem to fill empty galacticraft canisters with Liquid Oxygen. I've tried a fluid transposer, bottler, and buildcraft tanks. Oddly, if I empty an already full canister with a fluid transposer, I can fill the canister with the transposer. I can also fill the canisters with other liquids such as fuel. Also of note, when attached to my oxygen supply, the bottler complains that it requires more liquid resources, despite being filled to capacity. This makes me believe that some mod conflict is causing the machinery to believe that it is empty, despite the opposite being true. This is all using version 0.9.8b on a server with the only two added mods being worldedit and lag'b'gone. The LOX is being generated with a mekanism electrolytic separator and rotary condensentator. 
log: [2019-06-23-1.log.gz](https://github.com/xJon/The-1.7.10-Pack/files/3319066/2019-06-23-1.log.gz)
edit: I have since found that there are two types of LOX in the pack, one which works fine, one which is glitched. It seems that every machine I have tried (now including the galacticraft water electrolyzer) produces the glitched version. In NEI both versions have identical textures and item id's, I'm not sure why it produces one over the other or why there are two versions but if anyone can help I'd greatly appreciate it.
edit 2: I have found two other things. The glitched LOX is just empty tanks that for some reason the game thinks is LOX. Two, the issue is not with my added mods on the server as it persists in singleplayer.

**Comment by Hi-May** [comment]
I have since found that there are two types of LOX in the pack, one which works fine, one which is glitched. It seems that every machine I have tried (now including the galacticraft water electrolyzer) produces the glitched version. In NEI both versions have identical textures and item id's, I'm not sure why it produces one over the other or why there are two versions but if anyone can help I'd greatly appreciate it.

**Comment by xJon** [comment]
Following the instructions from [the wiki](https://wiki.micdoodle8.com/wiki/Liquid_Oxygen_Canister), I've made this sophisticated setup which consists of an Oxygen Collector, Gas Liquefier and Oxygen Pipes connecting them. As you can see, the canister seems to be filling with LOX.
![Screenshot_2](https://user-images.githubusercontent.com/8945347/60756806-8b31e000-a045-11e9-8ec1-502c3b6ba762.png)
![Screenshot_1](https://user-images.githubusercontent.com/8945347/60756807-8b31e000-a045-11e9-8a4e-30dcb8ae2b01.png)
