### ISSUE TITLE
The 1.7.10 modpack : EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by Enderax123** [xJon/The-1.7.10-Pack#1776]
[hs_err_pid3500.log](https://github.com/xJon/The-1.7.10-Pack/files/3323176/hs_err_pid3500.log)
[hs_err_pid5156.log](https://github.com/xJon/The-1.7.10-Pack/files/3323177/hs_err_pid5156.log)
[hs_err_pid6816.log](https://github.com/xJon/The-1.7.10-Pack/files/3323178/hs_err_pid6816.log)
[hs_err_pid9984.log](https://github.com/xJon/The-1.7.10-Pack/files/3323179/hs_err_pid9984.log)
[hs_err_pid1696.log](https://github.com/xJon/The-1.7.10-Pack/files/3323180/hs_err_pid1696.log)
[hs_err_pid3388.log](https://github.com/xJon/The-1.7.10-Pack/files/3323181/hs_err_pid3388.log)
[Error log.txt](https://github.com/xJon/The-1.7.10-Pack/files/3323162/Error.log.txt)
So, for the first time, everything is working but for the second time, it load everything but in the next minute it automatically close minecraft and bring me to the technic launcher, btw i used optifine and veinminer in the modpack, I am using the original launcher, with java version of 8u51 and allocated 3 GB of memory,

**Comment by xJon** [comment]
Make sure you use Optifine version D6.
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
