### ISSUE TITLE
State engine in incorrect state

### ISSUE THREAD

**Issue by calbright98** [xJon/The-1.7.10-Pack#1777]
A friend is hosting his server and we keep getting an error saying that the state engine is in an incorrect state. Attached is the crash report we got after.
[crash-2019-06-25_19.01.41-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/3328027/crash-2019-06-25_19.01.41-server.txt)

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by calbright98** [comment]
https://paste.ubuntu.com/p/bQWqvfv4Rc/

**Comment by xJon** [comment]
Simply seems like corrupted chunks, probably the game wasn't closed properly.

* One solution would be to restore a world backup (the modpack makes backups automatically).
* A second solution would be trying to use [Region Fixer](https://github.com/Fenixin/Minecraft-Region-Fixer).


Good luck!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
