### ISSUE TITLE
maxpermsize issue and i was wondering if i could fix it

### ISSUE THREAD

**Issue by isaacrocks27** [xJon/The-1.7.10-Pack#1778]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[techniclauncher_2019-06-27.log](https://github.com/xJon/The-1.7.10-Pack/files/3337545/techniclauncher_2019-06-27.log)
Down at the bottom

**Comment by xJon** [comment]
That's fine and not an issue. It was originally implemented in order to support Java 7 users.

**Comment by isaacrocks27** [comment]
How do I make it not do that?

**Comment by xJon** [comment]
It should affect your gameplay at all.

**Comment by isaacrocks27** [comment]
It's crashing my game

**Comment by xJon** [comment]
Please post your crash log file using a [paste-tool](http://paste.ubuntu.com/).
