### ISSUE TITLE
Modpack crash when trying to change control

### ISSUE THREAD

**Issue by Nico8400** [xJon/The-1.7.10-Pack#1779]
[crash-2019-07-02_17.46.38-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3350894/crash-2019-07-02_17.46.38-client.txt)
I just opened the option menu, then the control menu and it crashed
This didn't happened on the first time but occurs every time now

**Comment by xJon** [comment]
Please post your log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Nico8400** [comment]
Here is the log [https://pastebin.com/nsRBace8](url)

**Comment by xJon** [comment]
This is not the full log but I can still see the error. How did this issue start?
You can try to remove the VoxelMenu mod and see if the crash still happens.

**Comment by Nico8400** [comment]
The crash does not occur when I remove voxel menu
It crashes when I use the scroll bra on the right by click and drag to scroll

**Comment by xJon** [comment]
I tried and could not reproduce the issue with the way you described.
I could advise to keep the VoxelMenu mod removed, or try to reinstall the modpack.
