### ISSUE TITLE
Minecraft modpack 1.7.10 crashing!

### ISSUE THREAD

**Issue by snyderplayz** [xJon/The-1.7.10-Pack#1780]
I recently got back into minecraft after a while with some friends, and we decided to play mods. We installed and played the modpack for a couple of days with no issues. Today though, I loaded minecraft up and started the world, but after a quick second of being in the world my game crashes. I've tried some solutions but non of them seem to be working so as a last resort I thought I'd ask someone else who has real experience. 

Here is my crash report:  [crash-2019-07-04_13.07.53-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/3360398/crash-2019-07-04_13.07.53-server.txt)

Please help! We've spent a lot of time on this world and I can't imagine losing it already!!!

**Comment by xJon** [comment]
Please post your log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by snyderplayz** [comment]
> Please post your log file using a [paste-tool](http://paste.ubuntu.com/).

I hope this is correct:   https://pastebin.com/7GMpctQp

**Comment by xJon** [comment]
Hi,
As you can read for yourself, I can't. This log is not in English.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
