### ISSUE TITLE
Game crashes at every start

### ISSUE THREAD

**Issue by Gosi2** [xJon/The-1.7.10-Pack#1781]
The modpack has always worked but since 2 weeks it just won't start anymore. When I press play it loads in the Technic launcher then the Minecraft window opens and after that it just crashes.

https://paste.ubuntu.com/p/Rtp4gg5Crp/

[crash-2019-07-07_10.47.07-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3365432/crash-2019-07-07_10.47.07-client.txt)

**Comment by xJon** [comment]
Try to reset (delete) the configs of the PneumaticCraft mod.

**Comment by Gosi2** [comment]
Yeah, it worked. Thanks for the fast and great support.

**Comment by xJon** [comment]
:)
