### ISSUE TITLE
Server not launching

### ISSUE THREAD

**Issue by rumplestein** [xJon/The-1.7.10-Pack#1782]
Hello, I'm new to both holding a server and this website. I've been looking at similer problems and used their solutions, but they aren't working.

Using a site called Scalacube, I have access to one of the servers, however when I try to launch the server, an error occurs as shown

![Scalacube3](https://user-images.githubusercontent.com/52638838/60775327-6abe6000-a0ef-11e9-8fdd-a8aaa4fb0503.PNG)

Common fixes were to turn the eula.txt file to true, but its already on in my case and still not working. Again, I'm new to this, and I don't know what's wrong. Any help would be greatly appriciated.

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by rumplestein** [comment]
Is this what you're looking for?

https://paste.ubuntu.com/p/NG3JMNphvt/

If it helps, I'm using the Tecnic launcher

**Comment by xJon** [comment]
No. You can read [here](https://github.com/xJon/The-1.7.10-Pack#if-you-have-all-that-required-post-an-issue-with) where to find it.

**Comment by rumplestein** [comment]
https://paste.ubuntu.com/p/G8hbRNR7fX/

Is this it?

**Comment by xJon** [comment]
Yes. Thank you.
Try to reset (delete) the configs of the PneumaticCraft mod.

**Comment by rumplestein** [comment]
It worked! Thank you so much!

**Comment by xJon** [comment]
👍
