### ISSUE TITLE
A fatal error has occured, this connection is terminated 

### ISSUE THREAD

**Issue by HELPmeplzIwanttoplayit** [xJon/The-1.7.10-Pack#1783]
I installed ,, The 1.7.10 pack and wanted to play but this appear (look screenshot)
I really dont know why but when i'm trying to open singleplayer world or join my friend's this error showing:
,,A fatal error has occured, this connection is terminated"
My java version: 8.
Technic launcher original.
I have 8 GB Ram I choosed 4 GB in launcher settings.
I already tried older warsions-same problem.
I hope you will help me.
No crash reports because it's not crash. It just dont let me get into game.
![234](https://user-images.githubusercontent.com/52710096/60913648-25816600-a288-11e9-8d49-4393b3be4667.png)

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by HELPmeplzIwanttoplayit** [comment]
Here it is: https://paste.ubuntu.com/p/tW6VqztN2X/

**Comment by xJon** [comment]
Doesn't seem to be the right log, as I do not see the error in the screenshot in it.

**Comment by HELPmeplzIwanttoplayit** [comment]
![0](https://user-images.githubusercontent.com/52710096/60965667-ac7d1f80-a316-11e9-9885-3eb159e9ce8d.png)
which should I paste?

**Comment by HELPmeplzIwanttoplayit** [comment]
latest : https://paste.ubuntu.com/p/R3xJ8CMdvs/

**Comment by HELPmeplzIwanttoplayit** [comment]
But I have an idea, maybe someone will give me the-1710-pack folder trough any fiel share

**Comment by xJon** [comment]
`fml-client-latest.log` is the correct log, but I shows only the latest run of the game. Please make sure this error appears and then post the log.

**Comment by HELPmeplzIwanttoplayit** [comment]
btw this is from ,,latest'' log that 
![10](https://user-images.githubusercontent.com/52710096/60989552-98511680-a346-11e9-93ea-68e8ca9f5b66.png)
I pasted here 
Which error do you mean? When am opening minecraft am trying to connect server or join/create singleplayer world this message ,,A fatal error has occured, this connection is terminated'' always showing. 
Here is log where I tried few times to join to single player world. I didn't see any error it's just disconnecting me from singleplayer world even when i turn off my internet. And when i'm joining world my mc was ,,not responding" for while and then am joining game for 1 s and then it kicking me with this message. Log: https://paste.ubuntu.com/p/xHrThjvZS3/ I tried to join game last time on 19.54

**Comment by HELPmeplzIwanttoplayit** [comment]
There was a critical exception handling a packet on channel Morph
![13](https://user-images.githubusercontent.com/52710096/60992778-773ff400-a34d-11e9-86ba-1aa0c07ecf2d.png)
This error?

**Comment by xJon** [comment]
Yup, that'd probably be it. Try to manually remove the Morph mod.

**Comment by HELPmeplzIwanttoplayit** [comment]
YEAH IT WORKS!
but I can't enter any server with the 1.7.10 modpack 
I created server on this modpack trough aternos, to play with friends, but I need this morph mod to join the server. Is there something I can do?

**Comment by HELPmeplzIwanttoplayit** [comment]
Is there any way that you can delete this morph mod in next version of The 1.7.10 pack?
I tried a few version of this mod but none of them worked.

**Comment by HELPmeplzIwanttoplayit** [comment]
I think people better enjoy playing the best pack with best mods and no issues. My friend has same problem I will tell him to remove morph mod but still! we can't play together :(

**Comment by xJon** [comment]
Did you try to re-add the Morph mod and see whether this issue persists?

**Comment by HELPmeplzIwanttoplayit** [comment]
yes I tried re adding it 
and tried other versions of this mod every version of this mod don't work

**Comment by HELPmeplzIwanttoplayit** [comment]
But what if i disable this mod ? Will I get into server with disabled mod?

**Comment by HELPmeplzIwanttoplayit** [comment]
so
Will you remove morph mod in next version?
Yes I know  when people see that this modpack doesn't work for them they just don't play it.
When 2 my friends wanted to play this pack but they had same problem as me, they just go to play other pack but this pack was the best. Best mods. Includes every important mod. We don't need morph mod. We don't need to change us into zombies or something to gain fire resistant. WE NEED TO PLAY MODPACK WITH BEST MODS. plzz can you remove moprh mod in next update ??? 
it is really unnecessary to play with morph

**Comment by HELPmeplzIwanttoplayit** [comment]
morph mod has too many issues to be in this legendary modpack

**Comment by xJon** [comment]
You can just remove it from your and your friends' game & server :)

**Comment by HELPmeplzIwanttoplayit** [comment]
Is there any guide how to launch server after downloading it from https://www.technicpack.net/modpack/the-1710-pack.453902
?

**Comment by xJon** [comment]
_"How to set up a dedicated server"_, by @Curunir, 2016

> 1. Download the server package version you need here: http://the-1710-pack.com/repo
> 2. Extract the package to where you want your server to run. This will work side-by-side with a client installation, but unless your PC is a high-end monster, it is much recommended to use another PC for the server, if any is available.
> 3. Make sure your clients can see the server. If you are all on the same home network (LAN), this should just work. To have it work across the Internet, the server needs to have the port it will listen to (default: 25565) forwarded from the router. This will not (ever) work if your ISP puts you in the baby cage that is carrier-grade NAT, so let's hope yours doesn't.
> 4. Edit your server.properties file with all the settings you need. Guide is here: http://minecraft.gamepedia.com/Server.properties
> 5. If you want to import a singleplayer world, locate the worldsave and copy it over to the server directory. You need to set the world name in server.properties to the exact directory name of the worldsave for it to use the existing one. Even if you let it generate a world, the name that you set here will be used, default is just "world".
> 6. If you need it to work for more than just a couple of friends, give it more RAM. Edit the launch script and change the -Xms (minimum) and -Xmx (maximum) allocation values as needed. For a first try, defaults will be fine.
> 7. If you were wondering, launch.bat is your launch script on Windows, while launch.sh is the one for Linux/Unix/MacOS. ALWAYS use the script, never manually start the server.jar. If you do, you will start a vanilla (i.e. unmodded) server that will do weird shit.
> 8. Run the server, don't be intimidated by the millions of errors and give it time. Once it stops generating new lines while not falling back to the command line or closing, it should be up and running. Try connecting with a client, using the IP adress or a DNS-resolved name.

**Comment by HELPmeplzIwanttoplayit** [comment]
Thanks for help :)

**Comment by xJon** [comment]
👍
