### ISSUE TITLE
Heey, my game keeps crashing

### ISSUE THREAD

**Issue by knowmeforever** [xJon/The-1.7.10-Pack#1784]
https://paste.ubuntu.com/p/nnVmWgDGDj/plain/ 
Is the crash report

**Comment by knowmeforever** [comment]
https://pastebin.com/rH2DhfH8

**Comment by xJon** [comment]
These are not crash reports, which you can find at `\.technic\modpacks\the-1710-pack\crash-reports\`.

**Comment by knowmeforever** [comment]
Sorry about that!
I have one crash report

https://pastebin.com/ALRhL9XB

**Comment by knowmeforever** [comment]
Sorry, I should explain the problem. My game freezes from time to time. Thanks to that I don't get a crash report. I am using the latest version of everything and have no additional mods installed. When the game freezes it doesn't tell me it isn't responding the screen just freezes on what I was looking at.

Thanks for the time!

**Comment by knowmeforever** [comment]
https://pastebin.com/pjFAdB5N
Is the latest log, Couldn't include most of it since it exceeds the max data on the site

**Comment by xJon** [comment]
Try to remove the FastCraft mod.

**Comment by knowmeforever** [comment]
Thanks! I'll try that!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
