### ISSUE TITLE
Lagspike every second

### ISSUE THREAD

**Issue by Yoshey** [xJon/The-1.7.10-Pack#1785]
I tried everything I could find online, but my issue still didn't go away and I'm starting to get desperate.

Basically, every second I have a lagspike for a few frames.
clean 1.7.10 install doesn't have them even with forge. So it has to be something about the modpack/mods.
Optifine is installed. Changing settings did not make a difference to the lag spike.

I have 18GB ram and usually allocate 7gb to Minecraft. allocating 4 did not make a difference.

The Java arguments from https://www.reddit.com/r/feedthebeast/comments/5jhuk9/modded_mc_and_memory_usage_a_history_with_a/ did not fix the lagspikes as well.

Removing Fastcraft did not make a difference.

I also tried reinstalling the modpack completely.

Specs:
Geforce GTX 1080
Intel Core i7 4790K
They are definitely not bottlenecking.

How the lagspikes look like in the fps graph:
![2019-07-11_01 29 56](https://user-images.githubusercontent.com/34254960/61011598-7e7df680-a37b-11e9-8a72-661be82ceb9c.png)

Log File:
[fml-client-latest.log](https://github.com/xJon/The-1.7.10-Pack/files/3379705/fml-client-latest.log)

**Comment by Yoshey** [comment]
* Java 8 Update 211 (64 bit)
latest 1.7.10 Pack version 0.9.8b

**Comment by xJon** [comment]
Hmm, odd. Did you try to install Optifine? (version D6).

**Comment by Yoshey** [comment]
I'll try to install the D6 version, as I currently had the E7 version.

Also, after now playing for a couple of hours with the insanely annoying lags (I basically wasn't able to do anything but build a little house) the lags became worse. What I was able to observe was that the lagspikes consisted of like 3-5 lag-frames. And with time, those spread in time so instead of having one significant lagspike every second, I then had a couple minilags within a second.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Yoshey** [comment]
After testing the D6 version of Optifine, it did not help with the lagspikes.

Here's the log. I was ingame at roughly 3:58. While I also looked at the log of the few hours session, and there wasn't an event or error every second for the lagspike.
https://paste.ubuntu.com/p/F2n6Wh3qMD/

**Comment by xJon** [comment]
Okay, can you try to see whether this happens with another similarly built 1.7.10 pack?

**Comment by Yoshey** [comment]
I think I have the newest technic launcher, atleast from here https://www.technicpack.net/download and the Windows version.

I'll try it with Attack of the B-Team, Blightfall and Hexxit

**Comment by xJon** [comment]
They are not all exactly 1.7.10, if you have another launcher like the Twitch one maybe you could try a big pack from there.

**Comment by Yoshey** [comment]
Yeah I just realised that too. Though Blightfall is 1.7.10 too with 100+ mods and I did not have the lagspikes. I'll try a few others

**Comment by Yoshey** [comment]
Tekxit 2 with 129 mods didn't as well. I'll download the Twitch one and try a few modpacks from that then, as I can't find larger 1.7.10 packs on the technic launcher.

**Comment by Yoshey** [comment]
Alright I'm not sure what you mean with the Twitch one. I found Curse/Twitch but that doesn't look like a mod launcher?

**Comment by Yoshey** [comment]
"Official Ultra Modded RE" with 56 mods works fine.
Last mod I'll try is the "FTB Presents Direwolf20" for 1.7.10 can't find other large 1.7.10 packs otherwise.

**Comment by xJon** [comment]
Interesting. Did you try to completely delete the modpack's folder and do a clean reinstall?

**Comment by Yoshey** [comment]
Yup. Keybinds and all were reset by doing so, and it sadly didn't help.

**Comment by xJon** [comment]
And you did that without adding Optifine or anything?

**Comment by Yoshey** [comment]
I think I then tried without installing Optifine, not sure though. I'll try a fresh install without optifine again.

**Comment by Yoshey** [comment]
Nope. Installed fresh, didn't even change the window size and without optifine, still those lagspikes.

**Comment by Yoshey** [comment]
0.9.8 has the same issue. I'm starting to get desperate :c

**Comment by Yoshey** [comment]
Alright. I deinstalled all mods and tried to pinpoint the mod that caused the lagspike.

And it worked! I was able to pinpoint the exact mod that caused these lagspikes. It was DynamicLights-1.7.10.jar
Deleting Dynamic Lights has fixed those bloody lagspikes!

**Comment by xJon** [comment]
Weird. I'm glad you could find the problematic mod, even if it took a long time.
DynamicLights might not work well with your PC, but you could also try to reset the mod's configs and re-add it to see whether that can help.
