### ISSUE TITLE
Game Crashes After Initializing

### ISSUE THREAD

**Issue by Tatydf** [xJon/The-1.7.10-Pack#1786]
Hey, every time I load up the modpack it goes through the process of booting up, but then shuts down after the initialization stage. I've tried adding more ram, reinstalling, updating my drivers and restarting my pc, but I've yet to figure any way to fix it. It was working earlier today. Here's the latest crash report: 
[crash-2019-07-11_19.32.58-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3384360/crash-2019-07-11_19.32.58-client.txt)

**Comment by Tatydf** [comment]
Nevermind, I've resolved the problem. The issue wasn't with the modpack itself, it was a problem with my drivers and the java version I had installed. If anyone has the same issue, try manually downloading the most recent drivers (Not the automatically detected version) for your PC and reupdate java.

**Comment by xJon** [comment]
👍
