### ISSUE TITLE
Ram allocation

### ISSUE THREAD

**Issue by tapion289** [xJon/The-1.7.10-Pack#1787]
so i need to increase my ram to 3gb but i need to use a 64 bit java but the only one i have is one that is incompatable with minecraft i only have a 32 bit java that is compatable with the mod pack but then i cant increase my ram allowance can anyone help me get the 64 bit 1.8.0_211 java

**Comment by JurassicSalt** [comment]
Im having the same issue with no insight

**Comment by xJon** [comment]
You need to use Java 8 64 bit. You can download it from [here](https://javadl.oracle.com/webapps/download/AutoDL?BundleId=238729_478a62b7d4e34b78b671c754eaaf38ab).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
