### ISSUE TITLE
How can I add a mod?

### ISSUE THREAD

**Issue by Magnacorde** [xJon/The-1.7.10-Pack#1788]
I love this modpack. So much in fact, I'd like to play it with some friends that don't have computers. I found this mod when looking for a solution. It seems to be quite simple, and I almost got it working myself, I just can't get it to load properly (I have very little modding experience). It adds support for controllers and in doing so makes playing two instances of minecraft at the same time possible. If you could let me know how to add it or add it to the modpack yourself, it would be much appreciated. Thank you for your time!

Mod link: http://retro-hack.blogspot.com/p/minecraft-joypad-mod.html

**Comment by xJon** [comment]
Usually you just need to put the mod file inside of `\.technic\modpacks\the-1710-pack\mods\`.

**Comment by Magnacorde** [comment]
I tried that, and also installed forge, because it needs it, but it didn't load it. It came up in the mod list in game, it just wasn't working.

**Comment by xJon** [comment]
You don't need to install Forge, it is shipped with the pack. If you want specific technical support for that specific mod, you should probably contact the author, because I have as much idea as you do. Good luck!
