### ISSUE TITLE
Server starting was forced into server stopped

### ISSUE THREAD

**Issue by Brendan22** [xJon/The-1.7.10-Pack#1789]
When my friend launches our 1.7.10 pack Server it starts out as normal then says The state engine was in incorrect state STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.

We do not know how to load a backup to the world and cannot find out.

Crash Report

**Comment by xJon** [comment]
Is `eula.txt` set to true? Also please use http://pastebin.com to post crash logs.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
