### ISSUE TITLE
Problem with 2nd player on server

### ISSUE THREAD

**Issue by Gosi2** [xJon/The-1.7.10-Pack#1790]
I have uploaded my map to a server for performance reasons since it is actually running really well, but since yesterday I play together with a friend and at irregular intervals the game only outputs "is not responding". Even after a few minutes the game still doesn't crash, so I don't have a crash report. The server keeps running without any problems and my friend can continue playing without any problems. I run the server and the game on the same computer and I never had any problems with that. At first I thought it was the RAM, but the server is not at the limit and the game itself is not. My PC: I7 6700k stable at 4.5 GHz, 16 GB Hyper X 2666 MHz, EVGA GTX 1070, MSI Z170 Gaming Pro Carbon.
Game and server are located on one SSD.

I hope that somebody can help me despite the little information.

**Comment by xJon** [comment]
So the server is not responding or the client?

**Comment by Gosi2** [comment]
The client

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Gosi2** [comment]
https://paste.ubuntu.com/p/DX5CFmcMZn/

**Comment by xJon** [comment]
I don't see you joining any world in this log. Please make sure to encounter the problem and then post your latest log.

**Comment by Gosi2** [comment]
https://paste.ubuntu.com/p/MwHm7MDzqx/
32394 [15:42:48] 
At 15:42 my friend joined the Sever before I played alone. At 16:05 the game is not responding anymore.

**Comment by xJon** [comment]
Is this still an issue?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
