### ISSUE TITLE
Server disconnect

### ISSUE THREAD

**Issue by Keizerhoofd** [xJon/The-1.7.10-Pack#1791]
I have been playing on the server for a couple of days now, without a problem. Today however, the server restarted, and since then i can't access the server anymore. Once I join, I see where I join, but two seconds later the entire game crashes. Anyone know what to do?

**Comment by xJon** [comment]
Which server?

**Comment by Keizerhoofd** [comment]
The regular server, I use techniclauncher.

**Comment by xJon** [comment]
If by the "regular server" you mean HaxysHideout, the recommended server, you need to contact them.
> HaxysHideout
Contact: https://helpme.brixazure.com/
Or at their Discord server: https://discord.gg/ack4s8D
