### ISSUE TITLE
Skin has changed to pink arms and black body

### ISSUE THREAD

**Issue by NicName757** [xJon/The-1.7.10-Pack#1792]
After jumping through end portal while morphed as a blaze,  i demorphed at my bed to sleep but my skin is now completely black with pinkish arms.  Even after death and reloading the world it does not come back. I posted this even though other threads have gone through similar issues but i noticed that they all turned into steves and not 2 different colors. And to add on to that, i had about 97 levels before going through the portal but now i do not.
![2019-07-18_02 39 32](https://user-images.githubusercontent.com/53041143/61447182-4f303200-a905-11e9-9a93-9bae251e884c.png)

**Comment by xJon** [comment]
First of all, that's style.
Modded is weird, I can't say exactly what caused this but you can cheat your levels back in with `/experience set <player> 111 levels`.
Regarding your skin, try to re-log or restart the game.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
