### ISSUE TITLE
Admin on singleplayer

### ISSUE THREAD

**Issue by empZealoth** [xJon/The-1.7.10-Pack#1793]
For the love of my life I can't figure it out.
Don't know where **exactly** to find an admins or ops file in file explorer
(I looked through C:\Users\emp_zealoth\AppData\Roaming\.technic\modpacks\the-1710-pack)

Neither the game recognizes /op command, just says unknown command

How do I give myself admin?

**Comment by xJon** [comment]
You should be able to `/op <username>`, if you're playing on a server, and the file should be named `ops.json` inside of the server's folder. If you're playing on singleplayer you should've allowed cheats upon the creation of the world. You can still cheat by opening the game to LAN and click "allow cheats".

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
