### ISSUE TITLE
Server Stopping Error

### ISSUE THREAD

**Issue by Sliixy** [xJon/The-1.7.10-Pack#1794]
Crash report below.

Link: https://pastebin.com/TtaprgTJ

Whenever I start console for my server, I get an error that says "The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPING". I really need help and can't seem to fix this error.

Thanks in advance,
Sliix.

**Comment by xJon** [comment]
You have corrupted questing data - simply reset (delete) the inside of `HardcoreQuesting` within your server's world folder. This will reset your quests progress, but you can always cheat the items you had back in if you want.

**Comment by Sliixy** [comment]
Thank you so much! It works now. I really appreciate this man, we have months of dedication gone into this server. Thank you!

**Comment by xJon** [comment]
:)
