### ISSUE TITLE
Speed or Tick Issues (Breaking Blocks and Mobs)

### ISSUE THREAD

**Issue by FooFighter007** [xJon/The-1.7.10-Pack#1795]
I have been trying to play the pack again recently, but I have noticed an issue. When I place a block and break it, I break it faster than normal (Open Hand and Tools). Blocks generated by the world do not have the issue until placed by the player. Mobs also have noticeably faster movement. This is only appearing after I had made changes to the pack (Namely ProjectE), but i have reinstalled the pack back to its original state and still have the same issue. I believe it could be caused by some file somewhere leftover from by original install, but i'm not sure of anything.

**Comment by xJon** [comment]
If you want to make a complete re-install, go to the modpack's install directory and remove it  (you can keep the `cache` folder inside it though). Then, re-install it.

**Comment by FooFighter007** [comment]
I had removed all of the .technic folder just to be sure and it did not fix the issue.

**Comment by FooFighter007** [comment]
Mobs don't seem to be a problem anymore. It only appears to happen to blocks. I removed treecapitator to see if it fixed it but it did not.

**Comment by xJon** [comment]
When you do `/forge tps`, what are the results?
Please also post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by FooFighter007** [comment]
Overall : Mean tick time: 14.497 ms. Mean TPS: 20.000
https://paste.ubuntu.com/p/gvj8szwJCY/

**Comment by xJon** [comment]
That means no lag. Odd.
Does this issue happen to you with other modpacks as well?

**Comment by FooFighter007** [comment]
No Only with 1.7.10, I've tested Tekkit Legends, FTB Revelations and Ultimate Reloaded. The problem does appear to happen on a fresh install on my other computer as well.

**Comment by FooFighter007** [comment]
Ok So I did a bit more testing and it only seems to occur on the most recent block placed by the player.

**Comment by xJon** [comment]
Does this still happen?

**Comment by FooFighter007** [comment]
Yes this still occurs, i removed the .minecraft and .technic folders again as well as a test. It also seems to happen to every block placed by the player. Ignore what i said above.

**Comment by FooFighter007** [comment]
[Test Video](https://www.dropbox.com/s/odub2mue5cm5yd0/2019-08-25%2018-19-29.mp4?dl=0)

Here's a video displaying the issue. On Technic portable just to try something different, but no change.

**Comment by xJon** [comment]
Hi, can you please upload example videos to Youtube or equivalent?

**Comment by FooFighter007** [comment]
https://youtu.be/SJoUtZTqK0g

**Comment by xJon** [comment]
I am sorry but I have no idea what could cause this. If this is still an issue I would try again with the new modpack update that's supposed to be released in the next couple of days.
