### ISSUE TITLE
out of memory issue

### ISSUE THREAD

**Issue by Phantasticoo** [xJon/The-1.7.10-Pack#1796]
https://paste.ubuntu.com/p/2b48jgZzjy/ this is my crash log

I only have issues with this modpack.I have tried to reinstall the java 1 million times; I deleted the javaoptions in the enviromment ; I just dont know what to do now. I have a 6gb ram notebook and I still get the out of memory error.

Please help me!

**Comment by xJon** [comment]
Can you launch other Technic modpacks fine? How much RAM did you allocate to the pack in the launcher settings?

**Comment by Phantasticoo** [comment]
yes
3g

**Comment by Phantasticoo** [comment]
i have 64 bit java too
no one in the discord of the  pack solved my error and now im here

**Comment by xJon** [comment]
Did you try to do a clean re-install of the modpack?
What other Technic packs have you tested? Can you test a very big and heavy one?

**Comment by Phantasticoo** [comment]
Yes,Crafting dead,tekkit.But I have 6 Gb ram I dont know why i should be running out of memory.

**Comment by Phantasticoo** [comment]
Maybe its something about the environment variable but I really  dont know

**Comment by xJon** [comment]
Is there anything you modified when you first installed the modpack?

**Comment by Phantasticoo** [comment]
Nope

**Comment by Phantasticoo** [comment]
I made it work.I had to reinstall my os tho.Thanks for your time!

**Comment by xJon** [comment]
👍
