### ISSUE TITLE
fatal error shutting down internal server error single player

### ISSUE THREAD

**Issue by Oravore** [xJon/The-1.7.10-Pack#1797]
https://paste.ubuntu.com/p/Vf7QrSjfff/

Playing single player for maybe 5 minutes then the game crashes shutting down the internal server bringing me back to the home screen.

Additionally just to though in here every time I load the game into the main menu I am loaded into a world I never created. If I need to create a different post for this issue let me know!

Thanks in advance :)

Edit: whelp game crashes when it starts now. https://paste.ubuntu.com/p/9N4bYChsZ6/

**Comment by HELPmeplzIwanttoplayit** [comment]
https://github.com/xJon/The-1.7.10-Pack/issues/1783

**Comment by xJon** [comment]
All of these issues sound like they come out of modifying the modpack, which I cannot give support for.
Have you added any mods or modified the pack in any way?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
