### ISSUE TITLE
Incompatible FML Modded server when i have the correct version

### ISSUE THREAD

**Issue by Falleno** [xJon/The-1.7.10-Pack#1798]
I have both the client  and server version installed correctly but for some reason it keeps giving me this error when i try to log on.
![memelol](https://user-images.githubusercontent.com/19878600/61660824-a5fd8900-acc2-11e9-9600-2315452c5e30.PNG)
![errormine](https://user-images.githubusercontent.com/19878600/61660825-a5fd8900-acc2-11e9-9a46-d81fd368fe58.png)

![launcher](https://user-images.githubusercontent.com/19878600/61660873-c75e7500-acc2-11e9-978b-20e619a0a28a.PNG)
![host](https://user-images.githubusercontent.com/19878600/61660987-fd9bf480-acc2-11e9-9053-fc8bc7e27988.PNG)
Any clue to what this might be?

**Comment by xJon** [comment]
I see VoltzEngine there, which was removed in 0.9.8b. Something is not actually version 0.9.8b.

**Comment by Falleno** [comment]
> I see VoltzEngine there, which was removed in 0.9.8b. Something is not actually version 0.9.8b.

Yeah i've came to the same conclusion. I think the server provider is labeling the modpack as the wrong version.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
