### ISSUE TITLE
Minecraft is blank upon launch. 

### ISSUE THREAD

**Issue by deepakgangahar** [xJon/The-1.7.10-Pack#1799]
Hi, I have very recently purchased a new computer and I have been installing all of my favorite programs onto it. One of them being Technic and the 1.7.10 pack. 

I installed Java and even the 64 bit update. Despite all this, when I launch the modpack, it does not show up as a program. Task manager recognizes that the instance of java is running, and the music even plays, yet it is not displayed on my computer. 

here is my technic log. 
[techniclauncher_2019-07-24.log](https://github.com/xJon/The-1.7.10-Pack/files/3429173/techniclauncher_2019-07-24.log)

**Comment by xJon** [comment]
Hi! Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/), so I can further assist you.

**Comment by deepakgangahar** [comment]
> Hi! Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/), so I can further assist you.

I have tried to paste the log into the website, which leads to "502 bad gateway"

**Comment by deepakgangahar** [comment]
> Hi! Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/), so I can further assist you.

Disregard last message, here is the link

https://paste.ubuntu.com/p/Ttyzv7p77y/

**Comment by xJon** [comment]
Might be an issue with your machine. Did you install the graphics driver?
Do other modpacks/Minecraft work fine?

**Comment by deepakgangahar** [comment]
> Might be an issue with your machine. Did you install the graphics driver?
> Do other modpacks/Minecraft work fine?

Vanilla works fine. As far as I know, the drivers are up to date and installed.

**Comment by xJon** [comment]
Can you check other modded modpacks from the Technic launcher?

**Comment by deepakgangahar** [comment]
> Can you check other modded modpacks from the Technic launcher?

Will do. Installing Legends right now.

**Comment by deepakgangahar** [comment]
> Can you check other modded modpacks from the Technic launcher?

Tekkit Legends also has the same problem.

**Comment by xJon** [comment]
Hmm. What about modpacks from other launchers? Try to play one from the Twitch or ATLauncher.

**Comment by deepakgangahar** [comment]
> Hmm. What about modpacks from other launchers? Try to play one from the Twitch or ATLauncher.

Same problem with ATLauncher, it seems. 
[Log.txt](https://github.com/xJon/The-1.7.10-Pack/files/3438689/Log.txt)

Here's a log of when I launched it.

**Comment by xJon** [comment]
Odd. What I'd suggest is that you go to the support channels of Technic, ATLauncher or CurseForge and ask for their help with modded Minecraft. I'm not quite sure what's your problem as it is not modpack-related, and that's my area. Good luck!
