### ISSUE TITLE
Server Crash "The 1.7.10 Pack"

### ISSUE THREAD

**Issue by Skilltag** [xJon/The-1.7.10-Pack#1800]
I've been playing with my friends on a server for several days now and yesterday night the server just suddenly crashed as one of my friends tried to connect. Now we cannot restart the server since it closes itself after loading everything and showing about 10 errors.
The hosting team wasn't able to help by now so I'm asking here.

(Absolutely not an expert, just think the problem may be caused by flans mod or forge mod loader directly)

Log and Crash report are found below
[crash-2019-07-26_08.49.37-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/3435234/crash-2019-07-26_08.49.37-server.txt)
[Serverlog.txt](https://github.com/xJon/The-1.7.10-Pack/files/3435235/Serverlog.txt)

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
