### ISSUE TITLE
Launching error on 1.7.10 Pack

### ISSUE THREAD

**Issue by Falcelmo** [xJon/The-1.7.10-Pack#1801]
I have attempted to launch this pack several times and I can't figure out what the issue is.  I currently have Java 1.8.0_221 64-Bit and I have set the launcher to use 4GB of memory out of the 1 available to my computer.  
[latest.log](https://github.com/xJon/The-1.7.10-Pack/files/3436614/latest.log)
Anytime I attempt to launch it ends with the same error repeating continuously as shown in the log.  Please tell me if more information or logs are needed to resolve this issue.  The same error occurs on many other technic packs, with the only exception I have found being hexxit.

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Falcelmo** [comment]
https://paste.ubuntu.com/p/kx2tk4yxBq/

**Comment by xJon** [comment]
Hi, please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Falcelmo** [comment]
https://paste.ubuntu.com/p/7cBvKvKNMB/

**Comment by xJon** [comment]
Can you please tell me what the "error" is? I read your log and didn't notice any unusual error.

Modded Minecraft is a funny thing, you see, there are a lot of errors that can appear in the log but don't cause any issues.
You mentioned these errors happen on other Technic packs, which makes me think it's not an actual game-breaking error, but more like log-spam.

If you can direct me to exactly what the problem is, I might be able to offer better help.

**Comment by Falcelmo** [comment]
So I just attempted to launch it again so that I could better understand the error that is occurring.  It appears after certain point in loading the modpack, the console eventually starts to repeat an error about an empty sound event at the same time that the fml-client-latest log stops showing any new activity, and the window for minecraft is shown in the taskbar, however I am never able to open it. 
 I will include the logs of this attempt.
console log: https://paste.ubuntu.com/p/k2N7rY4sMC/
fml-client-latest: https://paste.ubuntu.com/p/q3JryfMdMm/

**Comment by xJon** [comment]
This is not an error that should bother you, it's all okay.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
