### ISSUE TITLE
Forge crashes in the end

### ISSUE THREAD

**Issue by Rand0mNight** [xJon/The-1.7.10-Pack#1802]
Hello,
I am trying to start the server and when I run the Forge Server it just shuts down after few minutes. Can someone plz help with this issue.

**Comment by xJon** [comment]
Did you set `eula.txt` to true?
Also, please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Rand0mNight** [comment]
Yes eula.txt is set to true, and here is the log: https://paste.ubuntu.com/p/Sk4HpBsY46/plain/

**Comment by xJon** [comment]
Please use a [paste-tool](http://paste.ubuntu.com/) to post your logs.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
