### ISSUE TITLE
IndustrialCraft 2/Mass Fabcricator UU-Matter 

### ISSUE THREAD

**Issue by TrikWilson** [xJon/The-1.7.10-Pack#1804]
I tried finding a related issue to this topic but since there is none I will make a new issue. Hope that's okay.

As the Title says I can't produce "UU-Matter" in the "Mass Fabricator"
The "Mass Fabricator" consumes energy and scrap boxes (what I used as an amplifier) but nothing comes out of it.

edit: I can't even find "UU-Matter" in the "Not Enough Items" item panel

Installed Version 0.9.8b
Minecraft Version 1.7.10

**Comment by xJon** [comment]
Are you aware that UU Matter in IC2 is liquid? Did you try to extract it as one?

**Comment by TrikWilson** [comment]
Oh okay I am stupid my bad ... I still thought it looks like this pink slime thing. I actually got it to work this time. 
Thank you

**Comment by xJon** [comment]
No worries, [IC2 Experimental](https://www.curseforge.com/minecraft/mc-mods/industrial-craft) for 1.7.10 is different than [IC2 Classic](https://www.curseforge.com/minecraft/mc-mods/ic2-classic). :)
