### ISSUE TITLE
Mod Suggestion: Better Invalid Session

### ISSUE THREAD

**Issue by kmecpp** [xJon/The-1.7.10-Pack#1805]
As you are probably already very familiar with, the invalid session message on MC 1.7.10 is pretty crappy. Only saying "try restarting your game" which leads to issues like #1401.

The Better Invalid Session mod (https://www.curseforge.com/minecraft/mc-mods/better-invalid-session) is an extremely lightweight mod that just changes this message to the much more informative "Invalid session (you logged in to MC somewhere else). Restart your game AND game launcher to login again". 

This solves the issue of people asking for help from the modpack maintainers and saves everyone a bunch of time and the mod itself has virtually zero impact on startup time or game play which is why I think it would make a great edition to the 1.7.10 pack which has so many servers

**Comment by xJon** [comment]
Currently the mod won't be added as we don't plan to add more mods to the pack.
Also this isn't a very common issue and most players know the solution.
Thank you for suggesting, and you can always add it for yourself!
