### ISSUE TITLE
Enabling Thauminomicon Cheat Sheet?

### ISSUE THREAD

**Issue by Stefo3000** [xJon/The-1.7.10-Pack#1806]
A little QoL tweak for thaumcraft:
Can you enable the Thauminomicon giving all research?
You can find it in the Thaumcraft config file under general.
It saves time when you first play thaumcraft and what to have research everything and is creative mode only.

You can of course modify the configs yourself, but not everyone is aware of it.

**Comment by xJon** [comment]
You can just do `/thaumcraft research <player> all`.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
