### ISSUE TITLE
Orespawn mod

### ISSUE THREAD

**Issue by HELPmeplzIwanttoplayit** [xJon/The-1.7.10-Pack#1808]
Can you plz add orespawn mod in next update?
I tried to add this mod to modpack but it crashing every time I try to launch minecraft.

**Comment by HELPmeplzIwanttoplayit** [comment]
Just question don't need help to fix it.

**Comment by xJon** [comment]
Hi, I'm sorry but the OreSpawn mod is very different from this modpack and I wouldn't recommend combining them. You should find other modpacks that are focused around OreSpawn.
