### ISSUE TITLE
I cant Join in my world

### ISSUE THREAD

**Issue by Creatinator** [xJon/The-1.7.10-Pack#1809]
after a few Starts i Cant Connect to the map ;-; I just get kicked into the main menu the log:

https://paste.ubuntu.com/p/fb3wz2pGwG/

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Creatinator** [comment]
like this https://paste.ubuntu.com/p/fb3wz2pGwG/

**Comment by xJon** [comment]
Your best bet would be to load a world backup. Have you tried that?

**Comment by Creatinator** [comment]
Yes I did Same Problem I need To Delete that I can join Somewhere else

**Comment by xJon** [comment]
What?

**Comment by Creatinator** [comment]
sorry Im bad  at English i need to delete the world that i can join In another world or server

**Comment by xJon** [comment]
You can just rename your world so you can load the backup separately, if that's your issue.

**Comment by Creatinator** [comment]
Nope Dont work I think Its the best when i just Leave it And delete The map and make a new one

**Comment by xJon** [comment]
I still don't understand why can't you load a world backup.

**Comment by BUTTERSKY11** [comment]
Ok I found out how to fix this all you have to do is uninstall 1.7.10 pack and reinstall it and make sure to back up yours saves and once it is done put your saves back and it should work cause that is what happened to me and xJon your update broke the modpack technically it just made old saves unable to be loaded and it happened to me

**Comment by Creatinator** [comment]
it still kicks me back in to the main menu Well goodbye map

**Comment by xJon** [comment]
@BUTTERSKY11 The update works perfectly to many players, also you can always revert versions if you want.

**Comment by xJon** [comment]
@Creatinator Your error is caused by the Galacticraft mod. If you really want, you can reset the mod's data in your world by manually removing it, that will allow you to enter your world.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
