### ISSUE TITLE
Can't download modpack

### ISSUE THREAD

**Issue by redd17** [xJon/The-1.7.10-Pack#1810]
![image](https://user-images.githubusercontent.com/47285335/62372330-8d228c80-b57a-11e9-8ddb-52f11f671732.png)

stuck on this cant get past

**Comment by lillrthor** [comment]
yeah i have the same problem

**Comment by kirav475** [comment]
me too

**Comment by lillrthor** [comment]
all tho if you go on the discord serve and into suport theres a google drive with all the files you just need to download them
or to make it easy for ya here you go
https://drive.google.com/open?id=1e6_3FT8Px9t4r2FXs6OSXbLyWUkY4bG6

**Comment by AlchemyJug** [comment]
me as well

**Comment by lillrthor** [comment]
Guys I posted a link to the google drive containing all the mods and other stuff you just need to download it to you’re pc and replace the existing stuff in there

**Comment by redd17** [comment]
thanks

**Comment by redd17** [comment]
it is fixed, downloaded and replaced the enitre 1.7.10 pack in the modpack file location. no install needed from technique just needed to press play

**Comment by xJon** [comment]
We're looking into the technical problems on our end stopping the modpack download. Hold on tight.

**Comment by xJon** [comment]
The issue has been fixed.
