### ISSUE TITLE
Unable to join world

### ISSUE THREAD

**Issue by hi1222222222** [xJon/The-1.7.10-Pack#1811]
On the initial starting of your world, you are able to play it just fine, but once you close and reopen Technic with this modpack enabled, you cannot join nor create a new world. The only fix is to reinstall every time you want to play.

Can you please fix this, Owner?

**Comment by nikasd** [comment]
So i had the same problem... I changed the version from 0.9.8c to 0.9.8b and now it works for me. I think the newest version is creating problems so try this out

**Comment by xJon** [comment]
@hi1222222222, please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
