### ISSUE TITLE
Crashes at launch

### ISSUE THREAD

**Issue by mehmetipekpatates** [xJon/The-1.7.10-Pack#1815]
[crash-2019-08-07_19.26.50-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3478004/crash-2019-08-07_19.26.50-client.txt)
Something about RF API. No idea what to do. Any help would be appreciated.

**Comment by xJon** [comment]
Please post your log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
