### ISSUE TITLE
Reauth Mod

### ISSUE THREAD

**Issue by SparkyBearBomb** [xJon/The-1.7.10-Pack#1817]
Hi, can you please add the mod Reauth

It is a client side only mod that allows users to relogin from the games main menu on "invalid session" errors

**Comment by xJon** [comment]
Hi,
Currently the mod won't be added as we don't plan of adding any new mods to the pack at this stage.
Additionally the modpack takes under 3 minutes to load and this isn't a very common issue.
Thanks for suggesting, and you can always add it for yourself!
