### ISSUE TITLE
Can't join, can't load worlds, computer specs should meet.

### ISSUE THREAD

**Issue by vinfer12** [xJon/The-1.7.10-Pack#1818]
I'm sure someone's already had the same issue as me, but I don't even know my issue, so I'm asking again. Any time I try to load an instance of the game, it hits the loading right before I can join, and then the game full crashes (no stalling) and goes back to launcher.

https://paste.ubuntu.com/p/5x4GP3tMPn/

**Comment by xJon** [comment]
Hi,
Try to temporarily remove the VoxelMap mod, and load your world. It should work.

**Comment by xJon** [comment]
Actually, found out this was a problem with LumySkinPatch's new update. Please reinstall the modpack as this will revert the mod's version and resolve your issue.

**Comment by VizShakenbake** [comment]
I'm having the same issue, so if I reinstall the mod pack will my world be deleted, because I can't seem to find my world anywhere in the files. However, when I load up the game it's there.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
