### ISSUE TITLE
Having a problem w/ keepInventory

### ISSUE THREAD

**Issue by MisterToots** [xJon/The-1.7.10-Pack#1819]
I disabled openBlocks graves successfully and turned keepInventory on. I am playing on easy and when I die my items stay but I still lose xp and my hunger does not return to full. I haven't played MC in awhile but I remember keepInventory resetting hunger and keeping xp. Is there another mod or setting or something preventing those? Thank you

**Comment by xJon** [comment]
Hi, is this still an issue?
