### ISSUE TITLE
A fatal error has occured, this connection is terminated.

### ISSUE THREAD

**Issue by Marcu2001** [xJon/The-1.7.10-Pack#1822]
When i try to create a world in singleplayer and play it, gives me this error 👍 https://gyazo.com/9ea7f6d8467cb73053935a645fc8b869

https://paste.ubuntu.com/p/pBMGfy7Fjt/

**Comment by xJon** [comment]
Manually remove the Morph mod from your game. Should fix your issue.

**Comment by Marcu2001** [comment]
It worked ! Thank you !

**Comment by xJon** [comment]
👍
