### ISSUE TITLE
Game crashes at launch - Technic launcher not supporting Java Args

### ISSUE THREAD

**Issue by erenkundakci** [xJon/The-1.7.10-Pack#1823]
my modpack crashes back to technic launcher when loading 100%. as far as i understand it's a forestry mod issue about rootBees genome or something. couldn't find a solution on the internet. i tried removing the pack completely and reinstalling, didn't work. i tried switching forestry mod versions and it also didn't work. i am using 64 bit java so i don't think there's an issue about there. here's the crash report if someone wants to take a look. thanks in advance.
https://paste.ubuntu.com/p/2dy9TpQZMh/

this is what happens:
https://i.vgy.me/2XYqRC.gif

**Comment by xJon** [comment]
Try to manually remove the MagicBees mod and see if this solves your issue.

**Comment by erenkundakci** [comment]
That worked but now i can't join a server because i deleted a mod, what can we do about that?

**Comment by xJon** [comment]
You can try to add the mod back again and see if the crash is gone.

**Comment by erenkundakci** [comment]
Same crash occured again.

https://paste.ubuntu.com/p/J632zWtDdr/

**Comment by xJon** [comment]
There has been a fix implemented in order to resolve this issue. Did you try reinstalling the modpack?
The config of MagicBees has been modified to disable the ArsMagica module.

**Comment by erenkundakci** [comment]
Yeah i tried reinstalling and still the same crash.

**Comment by xJon** [comment]
Please go to the modpack's installation folder, then to `config\MagicBees.cfg`, then make sure that in line 55 `B:ArsMagica=false`.

**Comment by xJon** [comment]
It might be possible to fix your issue if you add `-Duser-language=en` as an extra java argument in the launcher settings, or use [this](https://www.curseforge.com/minecraft/mc-mods/localefixer/files/2325417) mod.

**Comment by erenkundakci** [comment]
Mod worked like a charm! Thanks a ton for helping mate.

**Comment by xJon** [comment]
👍

**Comment by HugoZink** [comment]
I know the issue is closed but maybe this Locale Fixer mod should be added to the pack? People are still having these issues, and the Technic Launcher's "arguments" box does not seem to do anything. That's why the locale argument failed to work.

**Comment by xJon** [comment]
@HugoZink Yes this just came to my realization. I will consider either adding the mod or shipping the modpack itself with the argument.
