### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by bleeds-dragon** [xJon/The-1.7.10-Pack#1826]
Hey, I'm attempting to run the server (v0.9.8) with 64 bit Java on my VPS and i'm encountering these errors and unsure how to fix them. I have tried using the recommended server files and I'm experiencing the same issues.

https://hatebin.com/uqimrpqgup

**Comment by xJon** [comment]
Which errors are of concern?
Does the server not launch?

**Comment by bleeds-dragon** [comment]
The server launches but on 5 of the mods load, and the rest don’t load. I’ve tried different versions of the server and it doesn’t fix it. I’ve also tried 32 bit java on my VPS but the server doesn’t launch when that is installed.

**Comment by xJon** [comment]
You need 64 bit Java. The log you sent is not full and I can't see such errors. Please post the full `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by bleeds-dragon** [comment]
https://paste.ubuntu.com/p/dDDhrjChVj/

**Comment by xJon** [comment]
Looks like the server was loading fine and then closed manually. I see more than 5 mods loading.

**Comment by bleeds-dragon** [comment]
Me and some friends have tried to spawn in items from the mod packs and it says the item doesn’t exist, and custom biomes aren’t present in the world.

**Comment by xJon** [comment]
Are you using `LaunchServer` to start it?

**Comment by bleeds-dragon** [comment]
Yes

**Comment by xJon** [comment]
Make sure you're setting up the server according to this guide:
_"How to set up a dedicated server"_, by @Curunir, 2016

> 1. Download the server package version you need here: http://the-1710-pack.com/repo
> 2. Extract the package to where you want your server to run. This will work side-by-side with a client installation, but unless your PC is a high-end monster, it is much recommended to use another PC for the server, if any is available.
> 3. Make sure your clients can see the server. If you are all on the same home network (LAN), this should just work. To have it work across the Internet, the server needs to have the port it will listen to (default: 25565) forwarded from the router. This will not (ever) work if your ISP puts you in the baby cage that is carrier-grade NAT, so let's hope yours doesn't.
> 4. Edit your server.properties file with all the settings you need. Guide is here: http://minecraft.gamepedia.com/Server.properties
> 5. If you want to import a singleplayer world, locate the worldsave and copy it over to the server directory. You need to set the world name in server.properties to the exact directory name of the worldsave for it to use the existing one. Even if you let it generate a world, the name that you set here will be used, default is just "world".
> 6. If you need it to work for more than just a couple of friends, give it more RAM. Edit the launch script and change the -Xms (minimum) and -Xmx (maximum) allocation values as needed. For a first try, defaults will be fine.
> 7. If you were wondering, launch.bat is your launch script on Windows, while launch.sh is the one for Linux/Unix/MacOS. ALWAYS use the script, never manually start the server.jar. If you do, you will start a vanilla (i.e. unmodded) server that will do weird shit.
> 8. Run the server, don't be intimidated by the millions of errors and give it time. Once it stops generating new lines while not falling back to the command line or closing, it should be up and running. Try connecting with a client, using the IP adress or a DNS-resolved name.

**Comment by bleeds-dragon** [comment]
Following the guide fixed the issues and I can see mods have loaded and I can spawn in items without any issues, ty for the help.

**Comment by xJon** [comment]
👍

**Comment by bleeds-dragon** [comment]
Hey, everything is working fine but I'm seeing this in the console and unsure why it is happening.
[17:04:46] [Server thread/INFO] [FastCraft]: The server is lagging 100051 ms behind, 1001 ticks will be skipped.

The VPS has:
Intel Xeon E5-2680 V2 @ 2.8 GHz
16GB DDR4 RAM

**Comment by xJon** [comment]
Might happen only when it's starting, or when a lot of new chunks are being generated.
If it doesn't happen continuously, you shouldn't be worried. That's modded Minecraft.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
