### ISSUE TITLE
Server keeps crashing on launch

### ISSUE THREAD

**Issue by lastoneproductions** [xJon/The-1.7.10-Pack#1827]
My server was working fine, then in the morning it randomly started crashing, I tried to fix it for hours today no luck, any help would be appreciated.
If this helps it seems to be something with the world...
[cmd text.txt](https://github.com/xJon/The-1.7.10-Pack/files/3498753/cmd.text.txt)
[crash-2019-08-13_16.25.08-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/3498754/crash-2019-08-13_16.25.08-server.txt)

**Comment by xJon** [comment]
Please post your logs **using a [paste-tool](http://paste.ubuntu.com/)**.

**Comment by lastoneproductions** [comment]
https://paste.ubuntu.com/p/cBD22tsfz2/plain/
sorry, also I went to another backup but it keeps on crashing.

**Comment by xJon** [comment]
Simply seems like corrupted chunks, probably the game wasn't closed properly.

* One solution would be to restore a world backup (the modpack makes backups automatically).
(If you already tried a backup and it crashed again, please post the new crash log).
* A second solution would be trying to use [Region Fixer](https://github.com/Fenixin/Minecraft-Region-Fixer).


Good luck!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
