### ISSUE TITLE
An error was raised

### ISSUE THREAD

**Issue by washiiv** [xJon/The-1.7.10-Pack#1830]
I tried reading through closed issues to see if I could find the answer to this and only found similar cases, in which almost every time the issue somehow fixed itself. My error message reads "An error was raised while attempting to read pack info for modpack the-1710-pack, build 0.9.8c: connect timed out". I have tried reinstalling, restarting, and even checking my firewall, but nothing has seemed to work. The pack was running and working fine until now, and would love some help.

**Comment by washiiv** [comment]
Hey, turned out to be a technic issue, which I figured out. Thanks anyways!

**Comment by xJon** [comment]
👍
