### ISSUE TITLE
game repeatedly crashes after 20 minutes of playing

### ISSUE THREAD

**Issue by benril** [xJon/The-1.7.10-Pack#1831]
i can load up the game and it'll run pretty smoothly for about 20 or so minutes and then it will freeze and kick me from my friend's LAN world. Not sure why it crashes as it gives me no crash report after it shuts down. I haven't checked the folder to see if it has a report in the files yet.

**Comment by xJon** [comment]
LAN modded worlds aren't recommended. You should create a local server.
If you want further assistance, please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).
