### ISSUE TITLE
/summon Grenade broke everything

### ISSUE THREAD

**Issue by SirTwiggz** [xJon/The-1.7.10-Pack#1832]
Typed /Summon Grenade and it proceeded to break the server I was on, the solo world I tried to recreate the incident on, and the would force close the game. Please help

**Comment by xJon** [comment]
You can always restore one of the automatic world backups from the `backups` folder.
If you want further assistance, please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
#
Closed due to inactivity.
Will reopen with the required info.
