### ISSUE TITLE
Keep Crashing Servers

### ISSUE THREAD

**Issue by throwhuwei** [xJon/The-1.7.10-Pack#1833]
I have been running servers on this pack for over a year now and now that i moved in with somebody who also plays on these servers they keep crashing and ruining worlds any help would be very much appreciated

**Comment by throwhuwei** [comment]
I'm not exactly sure where to post the crash log but i have it

**Comment by xJon** [comment]
Please post your log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
