### ISSUE TITLE
No text in some menus 

### ISSUE THREAD

**Issue by LadyEcho** [xJon/The-1.7.10-Pack#1834]
In both the mod menu, and the video settings menu there is no text, there are just blank squares. I have already reinstalled the pack but it didn’t help.

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
