### ISSUE TITLE
Java 12.0.2 has issues with minecraft

### ISSUE THREAD

**Issue by ContentMaple15** [xJon/The-1.7.10-Pack#1835]
Whenever I try to launch the modpack from the technic launcher, I get a popup saying "You've selected Java 12.0.2, which is known to have issues with minecraft. Are you sure you want to continue?" With the options yes or no. When I click either, nothing happens and I'm taken back to the modpack page in the launcher.

**Comment by xJon** [comment]
The modpack officially supports only Java 8.
