### ISSUE TITLE
A fatal error occured, this connection is terminated.

### ISSUE THREAD

**Issue by Shaggyxoxo** [xJon/The-1.7.10-Pack#1838]
**_Loading world -> Menu pop up for milisecond -> Black screen -> Game pop up for milisecond ->_** 
> Connection lost
> A fatal error has occured, this connection is terminated. 

**Specs :** 
Proc : Intel Pentium G4560
Graphic : GTX 1050Ti 4GB stormX
Ram : 8Gb

I give the game 5Gb of ram, is that enough? Ther's a log or somethin' that i can give you for faster help? Thanks, greetings from Poland!

**Comment by xJon** [comment]
Have you tried to reinstall?
If you want further assistance, please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Shaggyxoxo** [comment]
Hi bro, here you have a link to log.
(https://paste.ubuntu.com/p/xfZvzMT8vj/)
Btw why Minecraft say that 251 mods loaded and 245 mods active? Why not 251 active? :/

**Comment by xJon** [comment]
Hi, did you make sure that this error occurred in the latest log? I can't find it in what you sent.

**Comment by Phong-Nam** [comment]
I have got the same problem, but... 1 I open the world, 2 I kill the chicken and when chicken die it tells me : Connection lost
A fatal error has occured, this connection is terminated.

**Comment by Shaggyxoxo** [comment]
@xJon  User>Appdata>Roaming>.technic>modpacks>the-1710-pack>logs>fml-client-latest text document i copy to paste-tool. Is that wrong? 
@Phong-Nam so make ur thread bro ><

**Comment by xJon** [comment]
Yes that's correct.
@Phong-Nam Please open your own issue but if you're using Optifine use version D6.

**Comment by Shaggyxoxo** [comment]
[https://paste.ubuntu.com/p/PfK9g86H54/](url)
I turn on game again and trying to make new world, this log is after this.
Same error ofc.

**Comment by xJon** [comment]
Please try to manually remove the Morph mod.

**Comment by Shaggyxoxo** [comment]
It works! Thank you :3 @xJon

**Comment by xJon** [comment]
👍
