### ISSUE TITLE
Regarding optional mod Optifine

### ISSUE THREAD

**Issue by Lexatiffy** [xJon/The-1.7.10-Pack#1841]
When using the latest 1.7.10 Optifine mod, as an optional plug for perfomance it causes some things to occur on some actions. As for Giants for example, it gives an internal server error and I'm p sure it shouldn't do that in the first place. It isn't a forge problem for sure, cuz when it happens it just puts me to MP. Is there a way to modify something to fix that problem? It just occurs the same when deleting the options.txt. It does the same for some other actions on what this modpack has to offer.

**Comment by xJon** [comment]
Optifine version D6 should cause you less issue.
