### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by MDG1Play** [xJon/The-1.7.10-Pack#1846]
When I load up it says server closed the crash report is "The game crashed whilst exception in server tick loop
Error: java.lang.IllegalArgumentException: Could not get provider type for dimension -37, does not exist" Help

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` or crash log files using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
