### ISSUE TITLE
fatal error connection terminated

### ISSUE THREAD

**Issue by PoopMaster42069** [xJon/The-1.7.10-Pack#1848]
i know you probably get that a lot, but im trying to host a server on aternos. When i try to join no matter if its singleplayer or server, i join for a second and then it kicks me out with the following message fatal error has ocurred this connection is terminated, I searched about it a lot and i still cant find the problem, I have 8gb ram and 4gb ram assigned to launcher. How do i fix this issue? My computer isnt that weak and i dont believe hes the problem.

**Comment by xJon** [comment]
Have you tried to reinstall?
It was found recently that another common solution would be to manually remove the Morph mod.
But if you want actual further assistance I'd need more information.
Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by PoopMaster42069** [comment]
where can i find it? should i post aternos console log? And i heard about removing the morph mod but i dont know how to remove it form aternos

**Comment by xJon** [comment]
You'd need to remove it from serve-side as well.

**Comment by flavio563030** [comment]
I deleted the Morph mod from my local folder "% appdata%". I do not know how to delete the mod, from the folder of ATERNOS. someone help me ?

**Comment by flavio563030** [comment]
> Have you tried to reinstall?
> It was found recently that another common solution would be to manually remove the Morph mod.
> But if you want actual further assistance I'd need more information.
> Please post your `fml-client-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

I deleted the Morph mod from the local folder and my game worked, but I want to know, as I delete the mod in the ATERNOS folder.

**Comment by xJon** [comment]
@flavio563030 Please open your own issue and thoroughly explain your issue.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
