### ISSUE TITLE
Visual bug while sleeping

### ISSUE THREAD

**Issue by dennyxD** [xJon/The-1.7.10-Pack#1850]
Hello, I just want to let you know about this visual bug, the problem is that when someone is sleeping, the other players dosn't see it sleeping, instead they watch it standing next to the bed..

I add a pic of my gf already sleeping in the bed, and how I see her. And is the same when she or a friend watch me sleeping.. 

![image](https://user-images.githubusercontent.com/25398332/63999910-9566dc80-cad2-11e9-9261-1dddb527feda.png)

I mean this don't make the modpack unplayeable, but I just wanted to let you know, because hey I want to help this great modpack to be more perfectly than it already is.. (and because when you're playing with someothers, and you put the beds together, sometimes is a bit messy to try know which bed is occupied and which one not.. xD because they can't see which bed I am using)

I love 1.7.10 Modpack! ♥

**Comment by xJon** [comment]
Are you using Optifine?
There might be many different mods that cause the visual glitch and unfortunately as they are no longer updating it wouldn't be possible to fix.
Thank you anyway for reporting!
