### ISSUE TITLE
Funky Locomotion causing server to crash while starting

### ISSUE THREAD

**Issue by abc123me** [xJon/The-1.7.10-Pack#1855]
The frames from funky locomotion are causing my server to crash when starting. Crash report below:
https://pastebin.com/JRx2rX91
It seems to be a common issue, even in the 1.1X versions.

This especially sucks for me because there is no alternative for the frames, other then cheating in electrotine from ProjectRed. And before knowing they would crash my server I built a big missile silo with them and a computercraft control system.

**Comment by xJon** [comment]
We'll see whether we can include a so called fix in the next modpack update.

**Comment by xJon** [comment]
@abc123me Can you please try to use [this](https://github.com/bit2shift/FunkyLocomotion/releases) version of the mod and see if the crash persists?

**Comment by abc123me** [comment]
No crashing on startup, and the mod works.
If needed I can send startup logs, etc.
