### ISSUE TITLE
1.7.10 tick loop issue CRASH

### ISSUE THREAD

**Issue by Alphaux013** [xJon/The-1.7.10-Pack#1856]
After using LocateFixer cuz of having  same problem as this guy https://github.com/xJon/The-1.7.10-Pack/issues/1823

Game crashes when I selected new created world

Here's crash report:
https://paste.ubuntu.com/p/mD7Vz9djvt/

**Comment by alleygm** [comment]
I have the same crash, i've played yesterday well, but today it crashes when launching the same world, but the new created world is going well for some time and then it crashes too, my other previous worlds doesn't crash.

**Comment by xJon** [comment]
@Alphaux013 Can you please give me more context to your issue? And why are you using an outdated version of the pack?
@alleygm Please open your own issue.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
