### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by PigLadAl** [xJon/The-1.7.10-Pack#1863]
Hello. I've been trying to get our server working (running on Debian) but it simply won't work, no matter what I do.
This is what happens whenever I try to run the server. It doesn't generate an error log.
![image](https://user-images.githubusercontent.com/28834446/65077579-34138a00-d969-11e9-92fb-8295ec4bf7ec.png)
If I'm missing something obvious, please tell me. I've already agreed to the eula.txt.
It's on a dedicated server that already has other vanilla minecraft servers running as well.

**Comment by xJon** [comment]
You need to make sure you have Java JRE installed and not only JDK.

**Comment by PigLadAl** [comment]
I've done that, and I've installed JDK too for good measure. Still nothing.

**Comment by xJon** [comment]
You should not have JDK installed unless you're using it. Try to uninstall it and try again.

**Comment by PigLadAl** [comment]
Turns out the JRE was already installed even when I didn't have the JDK. Uninstalled the JDK agin and I still have the issue.

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by PigLadAl** [comment]
It doesn't start up enough to even generate a logs folder.

**Comment by xJon** [comment]
Can you post an updated screenshot then?

**Comment by PigLadAl** [comment]
![image](https://user-images.githubusercontent.com/28834446/65393367-a7dcda80-dd4d-11e9-956b-30f41fe7101b.png)
Still the exact same error.

**Comment by xJon** [comment]
Are you sure you uninstalled JDK?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
