### ISSUE TITLE
Meterorite Compass not working

### ISSUE THREAD

**Issue by Wertoyou** [xJon/The-1.7.10-Pack#1865]
I have gone to 3 different sites pointed to by the meteorite compass (from Applied Energistics 2) and found no meteors. Am I doing something wrong? Are meteorites disabled? Help appreciated.

**Comment by xJon** [comment]
Did you try to dig down?

**Comment by Wertoyou** [comment]
Yes
I dug all the way to bedrock and flew to the top of the world on all three sites

**Comment by Wertoyou** [comment]
I found a meteroite without the compass by flying around in the world, so the problem is probably not with the pack, but with the mod.

**Comment by xJon** [comment]
Did you search all the way down in the entire chunk?

**Comment by RobinEH** [comment]
Dig up the entire area in which you get a nice spin. It doesn't have to be in the center. If you're on a server, someone else has likely found it already.
