### ISSUE TITLE
Immediate Crashing

### ISSUE THREAD

**Issue by ChairmanMeowJP** [xJon/The-1.7.10-Pack#1866]
In Technic Launcher, downloaded the modpack. I launch it, it takes about 5 seconds and then the launcher flashes off an back on.

I have reinstalled Java 64 bit, reinstalled both the launcher and the modpack. I've made sure the launcher uses 64bit version of Minecraft and has 7GB of Ram available. It just keeps on crashing to launcher.

**Comment by ChairmanMeowJP** [comment]
This is the only error log in Roaming > .technic > logs
https://pastebin.com/XpHx3g9h

**Comment by ChairmanMeowJP** [comment]
Just found this closed issue https://github.com/xJon/The-1.7.10-Pack/issues/1835

I am using Java 8 but currently the only option for a 64-Bit pack on the Technic Launcher is 12.0.1, which on this thread has been said is not supported? How does one get the correct version?

![image](https://user-images.githubusercontent.com/47898200/65891654-d2a5df00-e39c-11e9-805c-a796721b37c1.png)

**Comment by ChairmanMeowJP** [comment]
Aaaaaaaand I've fixed it. Used the find version tool to navigate to my minecraft install and select the current version. Thanks anyway but hopefully this makes it clear to anyone else as it seems this issue has occurred before but this solution not given.

**Comment by xJon** [comment]
👍
