### ISSUE TITLE
I can't install server help!

### ISSUE THREAD

**Issue by gotukolla** [xJon/The-1.7.10-Pack#1868]
[crash-2019-10-07_07.12.37-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/3695521/crash-2019-10-07_07.12.37-server.txt)

**Comment by xJon** [comment]
Please post your log using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if required.
