### ISSUE TITLE
Player client crash when joining

### ISSUE THREAD

**Issue by Ash2th** [xJon/The-1.7.10-Pack#1869]
Hi there,

I'm trying to setup a 0.9.8c server, seems to initialize fine and whatnot but whenever a player tries to join it'll either:
- If the player has started a singleplayer game before joining (Start game, quit to menu, join server): the player can see the server for a few seconds (map loads in and you can see your character) then it'll disconnect the player, subsequent joins will crash the player client
- If the player joins the server right after starting the client: the player client will crash 100% of the time

Here's the latest log:
https://jpst.it/1SJcC

Any and all help is appreciated to get this going properly :)

**Comment by xJon** [comment]
Does this still happen with v0.9.8d?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
