### ISSUE TITLE
Server taking exponentially longer to start due to flans mod errors

### ISSUE THREAD

**Issue by NilanthAnimosus** [xJon/The-1.7.10-Pack#1871]
version: 0.9.8d (Latest)

I have noticed flans mod giving an error every server start per-dimension (Which causes that dimension to take 5-15 seconds before progressing instead of 0-3).

The server is (loading off an SSD with 12 cores around 3.8-4.3Ghz and 32gb's of ram) with each dimension it finds throws 3 flans mod errors and hangs on that dimension for an extra 5-15 seconds. given the pack on average when using mystcraft has anywhere from 30 to 60+ dimensions - on average 30 by 10 seconds is easily 5 minutes on the loading time.

Disabling the mod (although forge states it will remove items/content from world data) has the dimensions part of server loading take around 3-5 seconds instead of 3-15 minutes, and does seem to be having a pretty large impact on server start times.

I found disabling the mod to be a bad idea however, since the server cannot be joined as it appears (In an existing save) to break the questing mod.

The link below is the specific issue with the specific mod, and what was stated on it there for info:

https://github.com/FlansMods/FlansMod/issues/806

**Comment by xJon** [comment]
Hi,
Can you please send me your server log?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
