### ISSUE TITLE
Hats mod includes no hats in the version used

### ISSUE THREAD

**Issue by NilanthAnimosus** [xJon/The-1.7.10-Pack#1872]
version: 0.9.8d (Latest)

There was a bug / issue in the 1.7.10 version of the hats mod.

It seems the hats files were neglected to be included in its download, I thought the mod may have been broken but it is simply a GUI with no hats included and is not corrected retroactively in older versions of his hats mod.

The below link is to a comment that provides the necessary hats files that should normally come with the hats mod as standard (As well as being its main issue report):
https://github.com/iChun/Hats/issues/189#issuecomment-533869057

**Comment by xJon** [comment]
Thank you for reporting!
Reinstalling the modpack through the launcher -> modpack settings should resolve this issue now.
