### ISSUE TITLE
Block error when loading in.

### ISSUE THREAD

**Issue by masterschief** [xJon/The-1.7.10-Pack#1874]
When launching in an older save from around April, (which was last successfully loaded in May 26th), I encounter an error. I believe a Mystcraft block is causing this problem, though I'm not too skilled in reading error logs. Can this be fixed? This world has a lot of history and I'd hate to see it go.
[crash-2019-11-02_04.10.41-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/3800271/crash-2019-11-02_04.10.41-server.txt)

**Comment by xJon** [comment]
Please post your crash log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by masterschief** [comment]
https://paste.ubuntu.com/p/Jf6rhcWzkt/

Here you are.

**Comment by xJon** [comment]
Hi,
First of all, did the world work fine but now crashes when you're using a newer version?
Does it not crash if you were using the version from April?
Did you try to load a backup?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
