### ISSUE TITLE
server crashes on startup 

### ISSUE THREAD

**Issue by dovakhiin783** [xJon/The-1.7.10-Pack#1875]
i think it was because of a wrong version of funky locomotives and deleted it but now i dont know what to do because it still crashes
[crash-2019-11-08_21.02.01-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/3826067/crash-2019-11-08_21.02.01-server.txt)

this is the crash report

**Comment by xJon** [comment]
Please post your crash log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
