### ISSUE TITLE
Crash on Server Join

### ISSUE THREAD

**Issue by krabbbbe** [xJon/The-1.7.10-Pack#1876]
I have issues with joining an a private Server by a friend of mine.
Last thing I did was Building a Crytal Growth Accelerator, and connecting it with EnderIO Cable
Then the game crashed. In the crash-rep in attachment i found out it's about the compability of AE2 and EnderIO I just haven't figgured out what it is, yet.

Mind helping me out w/ this?

[crash-2019-11-09_18.12.55-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/3827522/crash-2019-11-09_18.12.55-client.txt)

**Comment by xJon** [comment]
Please post your crash log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by krabbbbe** [comment]
Allright I figgured it out!
The issue in this case was the Conduit facade, which wasn't rendered propperly.
So I let a mate of mine tp me far away so it the rendering wasn't a problem.

The main issue was started by using the wrench from "Funky Locomotion" on EnderIO and TE conduits and cables.

**Comment by xJon** [comment]
👍
