### ISSUE TITLE
Recipe for Forge Microblocks iron saw not working

### ISSUE THREAD

**Issue by Zuurkern** [xJon/The-1.7.10-Pack#1877]
Haven't tried the other saws yet but I can't craft this one.

Tried with vanilla Minecraft sticks and iron as well, though all sticks should work according to NEI.

**Comment by xJon** [comment]
Have you used a combination of sticks and stone rods?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
