### ISSUE TITLE
Update MrCrayfish's Furniture Mod

### ISSUE THREAD

**Issue by Zuurkern** [xJon/The-1.7.10-Pack#1878]
https://mrcrayfish.com/mods?id=cfm

![image](https://user-images.githubusercontent.com/10333132/68997962-a5f64a00-08ac-11ea-8fc8-e996c1f44f79.png)

Is it possible to update this mod so we can have the modern furniture?

**Comment by xJon** [comment]
Hi,
The modpack uses the latest version available for MC 1.7.10.
