### ISSUE TITLE
Thaumcraft issues

### ISSUE THREAD

**Issue by BearAndose** [xJon/The-1.7.10-Pack#1879]
I seem to have lost all of the aspect knowledge that I had from "studying" items in thaumcraft. even though when I look through the thaumometer it shows me what the aspects are and doesn't allow me to rescan them but when I go to my research table I have almost nothing listed there as if I had never even started the research. 
Any suggestions or help with this would be greatly appreciated.

**Comment by xJon** [comment]
Hi,
You can regain certain Thaumcraft parameters through in-game commands.
These commands can be viewed [here](https://thaumcraft-4.fandom.com/wiki/Commands).

**Comment by BearAndose** [comment]
Thank you!

**Comment by xJon** [comment]
👍
