### ISSUE TITLE
Game keeps crashing on load

### ISSUE THREAD

**Issue by turddle** [xJon/The-1.7.10-Pack#1881]
I'm using a clean install of the game, no optifine, nothing. At first, my game kept crashing because of a "Ticking memory connection" Which I think is because my computer lost power while playing? (I think) So here's that crash report: https://pastebin.com/nErK5T3Q

So I decided to re-install the pack and now I'm getting a new error after loading the world. 
Crash report https://pastebin.com/LqYJpP8e 
Latest log: https://pastebin.com/KRGyVMAz

Sorry if I did anything wrong!

**Comment by xJon** [comment]
Yes, your computer losing power while playing has corrupted your save.
You should load one of the automatic generated backups.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
