### ISSUE TITLE
Scrolling down the controls menu causes crash

### ISSUE THREAD

**Issue by lagph0bia** [xJon/The-1.7.10-Pack#1883]
I'm having a crash when I'm scrolling down in the control options. Here's the latest [crashreport](https://cdn.discordapp.com/attachments/96558260349333504/650683525783093258/crash-2019-12-01_14.12.35-client.txt). 

I'm assuming there's something wrong with my textures, so I tried reinstalling the pack. Reinstalling the pack did not fix the issue. This issue had only started occurring after I tried to bind one of the controls with the ">" key. I'm using 0.9.8c for the 1.7.10 pack.

**Comment by xJon** [comment]
Go to the modpack's installation folder, and reset your game settings by deleting the `options.txt` file. That should resolve your issue!
