### ISSUE TITLE
It won't even load

### ISSUE THREAD

**Issue by DantixHD** [xJon/The-1.7.10-Pack#1884]
the game won't even load, and my pc reaches it requirements
[what why who how.zip](https://github.com/xJon/The-1.7.10-Pack/files/3913969/what.why.who.how.zip)

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
