### ISSUE TITLE
Game crashes as soon as I jumped in the twilight zone and now I can not play.

### ISSUE THREAD

**Issue by Justoffurmama** [xJon/The-1.7.10-Pack#1885]
As said in title I created a twilight portal and I was unable to play because it instantly crashes when I tried to start up the modpack. Now it sent me to where I spawned when I first started the world again today. Im now worried to enter the twilight zone again. Is there any way I can fix it while still having the twilight mod? Any help would be appreciated. Thanks~

**Comment by xJon** [comment]
Please post your `fml-client-latest.log` or crash log file file using a [paste-tool](http://paste.ubuntu.com/).
