### ISSUE TITLE
Crash Upon Opening GUI [v. 0.9.8d]

### ISSUE THREAD

**Issue by Electrimatics** [xJon/The-1.7.10-Pack#1887]
It seems whenever I open anything with a GUI (inventory, main menu) the server (single player world) instantly shuts down.  I am able to open up the main menu (settings, video settings, etc...) before loading into a world.  The game only crashes when I attempt to open a GUI while currently in a world.  Loading, creating, and walking around worlds has no issues.

I have attached the latest log files below, and I can attach any more upon request.

Thank you for your help in this issue.

[latest.log](https://github.com/xJon/The-1.7.10-Pack/files/4005898/latest.log)

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
