### ISSUE TITLE
Block lag in specific areas on server for only players in that area

### ISSUE THREAD

**Issue by ThomasGruszecki** [xJon/The-1.7.10-Pack#1888]
I'm experiencing something unique on a private server: In one specific area where a group of players have built a base, they will experience extreme block lag as if the server was lagging -- but it will show 100% in /cofh tps. 

At the same time in another area, while this group of players are lagging, another group of players will experience no block lag. 

If the players who were experiencing block lag leave their base then they too will experience no lag.

What should we do?

**Comment by xJon** [comment]
You can try to use Opis: https://www.curseforge.com/minecraft/mc-mods/opis

**Comment by ThomasGruszecki** [comment]
We ended up just moving, but our conclusion was that the factorization colossus was causing the issue -- and even removing it failed to assuage the lag. Seems like they're just really buggy all around.

**Comment by xJon** [comment]
That's unfortunate - Factorization is not an active mod anymore.
