### ISSUE TITLE
Game crashes when I join a server

### ISSUE THREAD

**Issue by Anonymous30027** [xJon/The-1.7.10-Pack#1891]
I open the game with technic Launcher the game starts but when i try to join on a server the game crashes. Please help me
[crash-2020-01-21_18.18.12-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/4092523/crash-2020-01-21_18.18.12-client.txt)

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
