### ISSUE TITLE
Client-side connection issue causing 2000+ ping upon trying to connect to server.

### ISSUE THREAD

**Issue by kingcrxmson** [xJon/The-1.7.10-Pack#1892]
Yesterday, I was playing on a server completely fine, but today the ping started fluctuating between 1000-3000, making it almost impossible to play. Upon trying to connect, it will sometimes crash after trying to log in for a while. I have an average ping of 50-70 in most applications, with a 5-minute trace route of the aforementioned server yielding a max ping of 270. I've ran malwarebytes, reinstalled the modpack, updated java, and also performed multiple other community fixes, but none of them have worked. 

I apologize ahead of time if this has nothing to do with the modpack itself, but it's one of the only things I haven't ruled out. 

Here's a crash log of when I was actually able to connect to the game, only to crash moments later:

https://paste.ubuntu.com/p/z3P7rcZxNJ/

**Comment by xJon** [comment]
Are you sure this is not an internet problem on your end?

**Comment by kingcrxmson** [comment]
I'm fairly confident that it wasn't, because I had a 10ms ping on a speed test and a max 270ms ping when running the trace route to the server directly, rather than the 3000ms ping through minecraft itself. I'm a bit irked, because it just magically went away after 5 or so hours. I'll close this for now. It's quite possible that it was an issue of something else entirely though. If the issue arises again in the future, I'll try to look into it a bit more before discussing it here.
