### ISSUE TITLE
Ticking Screen error

### ISSUE THREAD

**Issue by DrakeTheBeardie** [xJon/The-1.7.10-Pack#1893]
When connecting to the server I usually hop onto, the client crashes back to the technic launcher. I've been able to load into single-player worlds. I've had this issue once before in conjunction with two other of my friends and our crash logs looked almost exactly the same at that time, however, this time I'm the only one seeming to have issues. Not sure if that nugget of info would be useful. This error behaved the same way as the last one, although as that resolved itself, I'm not sure how I should go about fixing it. 

Most recent crash report: https://paste.ubuntu.com/p/hzhKRTXnjR/

Thanks for your time and I'll try hard not to ask about the ducks!

**Comment by xJon** [comment]
1. If you're crashing due to a problematic block or entity, you can try setting these two settings to true in `the-1710-pack\config\forge.cfg` **after you've backed up your save**:
```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```
2. If this doesn't solve the issue I'd recommend you to either backup and reset your player data on the server, or just load a backup from when this issue did not happen.

**Comment by DrakeTheBeardie** [comment]
Is this something I would have to do server-side or is it something I can do client-side? I only ask because the server isn't mine, and I would have to ask them to do something.

**Comment by DrakeTheBeardie** [comment]
@xJon Not sure if this would help at all, but before the crashing started happening, I was booted from the server under an error of a packet that was too large.

**Comment by xJon** [comment]
> Is this something I would have to do server-side or is it something I can do client-side? I only ask because the server isn't mine, and I would have to ask them to do something.

It'd have to be done on the server side. But it is not guaranteed to resolve your issue.

**Comment by DrakeTheBeardie** [comment]
Well, I went through their automated ticket system and now I'm waiting for them to reply. I'll probably add another comment to this saying whether or not it was fixed. Just a waiting game now.

**Comment by xJon** [comment]
I don't know what's your server hosting solution, but if you have file access you can change those files on your own.
Also loading a backup might be a good idea.
If you want I can recommend you [Akliz](http://bit.ly/The-1-12-2-Pack-Akliz) as they have excellent customer support & a good world backup system of their own (with support of the modpack's).

**Comment by DrakeTheBeardie** [comment]
No, I don't have file access, which is why I need to wait for the response to my ticket. It's a public server so I have no say over what gets backed up or rolled back. Best case scenario I might just get my player data wiped, worst case I can never play that server again. I'll take a look if I need a good server host, but I might stick with pebblehost if needed.

**Comment by DrakeTheBeardie** [comment]
if the erroring entity is in my inventory, how plausible would you think it would be to delete what I believe to be the offending item through editing my NBT data, (this is because I'm curious if I can provide a suggestion to avoid getting my player wiped.) Because other people have been able to go to the area I am having the error in and only get booted from the server when I log in around them. I presume that the erroring entity may be a satchel I was putting playerheads into. Would that make much of a problem?

**Comment by xJon** [comment]
I believe that you can give it a shot

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
