### ISSUE TITLE
Crashing on World Load

### ISSUE THREAD

**Issue by Nokiroq** [xJon/The-1.7.10-Pack#1894]
I will try to explain from start I'm playing on laptop while playing game my character stand and couldnt move for few seconds I could look around but couldnt move then my pc completely gone down I started again and started technic launcher (which is original as my minecraft account) and try to load in to my world but it only kicked me back to main menu after few seconds I looked internet for this issue and general solution is to wait but I left open there for hours and nothing happened only waited in main menu after that I tried to use backup and thats what caused everything after using backup my minecraft crashing this time when I try to load in here is crash report(s):
(all of these after using backups I dont have crash reports about before using backups cause it wasnt crashing it was just not loading kicking me back to main menu)
https://paste.ubuntu.com/p/3bDNn3GSC7/
https://paste.ubuntu.com/p/qqdZyh2GK3/

This last one is after reinstalling the pack.
https://paste.ubuntu.com/p/KSS6HQvHrR/

**Comment by xJon** [comment]
Did you try to load a backup?

**Comment by Nokiroq** [comment]
Yes before this crashing incident it was kicking me back to main menu when I try to load the world. After using backup it happened @xJon

**Comment by Nokiroq** [comment]
I tried one of older backups but still same result crashing and closing client after few seconds.https://paste.ubuntu.com/p/y44Vpff2MH/

**Comment by xJon** [comment]
I'd recommend you to manually remove the ChickenChunks mod (which will cause all blocks from it to delete in your world). This will probably resolve your issue.

**Comment by Nokiroq** [comment]
thanks for help but my save already fully corrupted I tried something else without copying, now I'm playing The 1.12.2 pack.(That looks better btw)

**Comment by xJon** [comment]
Haha okay, have fun playing and feel free to write any feedback you have!
