### ISSUE TITLE
Adding the Uncomplicated addon for IC2

### ISSUE THREAD

**Issue by PriceCZ** [xJon/The-1.7.10-Pack#1895]
I think that this mod would be a great addition to the pack since it replaces the "WIP" E-Net from IC2 exp. with a fully working E-Net from IC2 classic while keeping all other features intact. Machines explode if subjected to too high voltage, cables burn, you get damage from standing too close to powered uninsulated cables, as it was meant to be. It gives back meaning to transformers and expensive wires. I think that it's really stupid being able to connect a nuclear reactor with a tin wire straight into a macerator and everything being ok. It adds some complexity that makes perfect sense and a little bit more challenge. It also adds crafting recipes from classic (basically just replaces plates with ingots) but I personally don't like that, plates make sense to me but you can disable this feature in the config file.

**Comment by xJon** [comment]
The 1.7.10 version of this mod is not very stable, but nonetheless The 1.7.10 Pack is no longer in active development, which means that it will be updated only if major bugs are discovered and in need of an update.
Thank you for suggesting, and feel free to add it yourself manually!
