### ISSUE TITLE
BC and Extra Utilities quarrys stopping sometimes

### ISSUE THREAD

**Issue by R0botenique** [xJon/The-1.7.10-Pack#1896]
I put them on the Aroma dimension using the tesseract to supply energy (Mekanism fusion reactor), but they don't constantly mine, sometimes they stop for half a minute and then continue. I have a chickenchunks chunk loader in the reactor, so I have no idea what it might be (and since they mine, they only stop for a while, I don't think it's the chunks). This happens in Deep Dark too.

**Comment by xJon** [comment]
Is the power source chunk loaded?

**Comment by R0botenique** [comment]
Yes, a ChickenChunks chunk loader, I tried the Railcraft world anchor too and the same thing happens.

**Comment by xJon** [comment]
Does it happen in different worlds, too?

**Comment by R0botenique** [comment]
I'm playing on an Aternos server, but I tested it in a singleplayer world and it looks normal.

**Comment by xJon** [comment]
I'd suggest to talk to them for help then!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
