### ISSUE TITLE
My backup will not load. I have deleted chickenchunks. No difference

### ISSUE THREAD

**Issue by Jervin98** [xJon/The-1.7.10-Pack#1898]
will provide necessary info

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
