### ISSUE TITLE
Error when i connecting to server

### ISSUE THREAD

**Issue by zzdenda** [xJon/The-1.7.10-Pack#1899]
Hello i have problem with connection to hamachi server... when i join on server so it will write to me a fatal error has occured, this connection is terminated Please help ... Thank you

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
