### ISSUE TITLE
Universal Cables not transferring from EU sources.

### ISSUE THREAD

**Issue by StormdragonDesigns** [xJon/The-1.7.10-Pack#1900]
EU Generators (Solar Panels, Generator, etc) are not transmitting power into Universal Cables. EU consumers can consume from the cable, however.

![image](https://user-images.githubusercontent.com/30184151/76160656-1e488a00-6180-11ea-8acd-3218c87363f5.png)

**Comment by xJon** [comment]
As stated over https://github.com/xJon/The-1.7.10-Pack/issues/1455#issuecomment-367784452, you need to manually change the connection type to `PULL` using a Configurator.
