### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by PepBabie420** [xJon/The-1.7.10-Pack#1901]
I don't what it is but when I try to join a world it crashes
[crash-2020-03-08_17.27.00-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/4303936/crash-2020-03-08_17.27.00-server.txt)

**Comment by xJon** [comment]
Please post your logs using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
