### ISSUE TITLE
Fluid yellorium and Molten yellorium

### ISSUE THREAD

**Issue by OskarMZ** [xJon/The-1.7.10-Pack#1902]
Fluid yellorium oceans can be created in mystcraft. Issue is that its fluid yellorium, not molten yellorium.
Fluid yellorium is obtained in creative mode usually and has no use, it is the fluid inside rods. Unsure of whether it can be used to bucket into rods directly, but using drums, translocators, tinkers has no effect.   It's not too big of a deal apart from me wanting to get a billion yellorium ingots. But still I guess its a bug nevertheless.

**Comment by rfcardona22** [comment]
Having the same issue, i just started playing on this pack recently since some friends wanted to check it out. I Mainly play on FTB Infinity Evolved 1.7.10, and fluid yellorium can be used as molten yellorium, at least for use in casting basins, so maybe this modpack is missing a mod or crafting recipe that can allow it to be used.

**Comment by LordWafflton** [comment]
The ExtraTiC mod can help you do this, it adds a bunch of mods to the tinkers construct compatibility list, big reactors being one of them. You can use fluiducts to pump liquid yellorium into casting basins/tables and use item ducts to push them into whatever inventory you want them to go to (i haven't tested other item/fluid pipes but im sure it should still work). You can also use minetweaker to add your own recipies, but other than that, liquid yellorium basically has no use within the base modpack.

**Comment by xJon** [comment]
This is indeed a compatibility issue. Unfortunately I am not expecting any new updates, so this bug will probably not be addressed. As the previous user mentioned it can be resolved manually.
Sorry for the inconvenience!
