### ISSUE TITLE
Chunk Loaders Don't Work

### ISSUE THREAD

**Issue by LTGamer** [xJon/The-1.7.10-Pack#1903]
On my own hosted server with friends and on the latest version and chunk loaders just don't work. We've tried all the chunk loaders and world anchors in the pack and none of them work. Some of them will keep chunks loaded for a bit but will just stop or cut out after a few mins.
Server has 6gb ramn and is setup corretly
Everything else works fine
They haven't been working on previous versions of the pack either

**Comment by xJon** [comment]
Sorry for the late reply!
Do they work for you on singleplayer?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
