### ISSUE TITLE
Game crashes in the start screen help

### ISSUE THREAD

**Issue by Sticker128** [xJon/The-1.7.10-Pack#1904]
Please help.
I start the 1.7.10 pack normally with the Technic Laucher at Version 0.9.8d. It starts as always.
But if I get to the Mainscreen it crashes I cant klick any button. I need your help the solve this problem.
This is the crash report:
https://paste.ubuntu.com/p/QSxgnpTdkF/

**Comment by xJon** [comment]
Try to reset (delete) the `options.txt` file.

**Comment by Sticker128** [comment]
it worked thanks !!!
