### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by maddiemmr** [xJon/The-1.7.10-Pack#1905]
Whenever I start my game up, it manages to get to the title screen, but every time I click my single player world it will load for at least 5 minutes and then crash.

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide (use it with 1.7.10 instead).

**Comment by maddiemmr** [comment]
This is the server crash log: https://paste.ubuntu.com/p/6yP9kywMzf/
This is the client crash log: https://paste.ubuntu.com/p/j8ZzsGqkct/

**Comment by xJon** [comment]
Try to manually remove the VoxelMenu mod, and try again.

**Comment by maddiemmr** [comment]
So I removed the mod but it still crashed. Ill post the crash reports below:
Client: https://paste.ubuntu.com/p/ctG2ddD37y/
Server: https://paste.ubuntu.com/p/n4wRgV54Zj/

**Comment by xJon** [comment]
Seems to happen due to the addition of MoCreatures.

**Comment by maddiemmr** [comment]
Damn, thanks for your help.
