### ISSUE TITLE
Unable to lauch modpack

### ISSUE THREAD

**Issue by AnnieDoody** [xJon/The-1.7.10-Pack#1907]
I'm not sure if anyone has had a similar issue, but when I try to click play on the mod pack in the launcher, a little icon appears on the toolbar but does not seem to load, and I can't get a window to pop up.  I've tried reinstalling the launcher, the mod pack, and java itself, as well as changing which version of java I'm using and upping the amount of memory allotted (it's now up to 6 gigs).  I'm not terribly technologically gifted- any advice?

**Comment by xJon** [comment]
If using the modpack through the Technic Launcher gives you trouble, you can always use the Twitch App: http://bit.ly/The-1-12-2-Pack-Twitch-Download

**Comment by Bookklover** [comment]
Thanks for the quick response! Unfortunately, I'm trying to use the 1.7.10 pack.  Is there a twitch download for that?

**Comment by xJon** [comment]
Sorry for the late reply!
There's no Twitch version of The 1.7.10 Pack. 
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
