### ISSUE TITLE
Crash that leads back to title screen

### ISSUE THREAD

**Issue by ShadowBlink5** [xJon/The-1.7.10-Pack#1908]
so, a buddy of mine has a problem, everytime he tries to enter on a map, singleplayer or multiplayer it puts him back on the main menu, telling him with the error,a fatal error has occured, this connection is terminated, i found out it has to do something to do with Morph mod, we deleted it, it worked no problem, tried a different version of the mod, same problem again, perhaps is was the iChunUtil, nope
I ain`t planning on just removing that mod, cuz it will fill like ordering a pizza and finding out it doesnt come with a specific topping, it just doesnt feel right
Logs: https://paste.ubuntu.com/p/fj5vdGsQWk/

**Comment by xJon** [comment]
Did you intend to close this issue?
