### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by HCCyberCraft77** [xJon/The-1.7.10-Pack#1909]
I'm playing Galacticraft 4  mod on Minecraft 1.12.2 and the server crashes when i go to Mars.

Logs file

**EDITED: Do not post logs like this. Use a paste-tool**

**Comment by xJon** [comment]
Please post your crash log using a [paste-tool](http://paste.ubuntu.com/).

**Comment by HCCyberCraft77** [comment]
ok

https://paste.ubuntu.com/p/5x2g5z3fkQ/

**Comment by xJon** [comment]
You're not playing The 1.7.10 Pack.
