### ISSUE TITLE
My Server crashes when using Telepad in Galacticraft 4 Minecraft 1.12.2 Forge

### ISSUE THREAD

**Issue by HCCyberCraft77** [xJon/The-1.7.10-Pack#1910]
Here is the Crash report : https://paste.ubuntu.com/p/rkzPjpm3Gk/

Here is the Log Text File : https://paste.ubuntu.com/p/2jxJWYZsjR/

**Comment by xJon** [comment]
You're not playing The 1.12.2 Pack.
