### ISSUE TITLE
Unable to download mods

### ISSUE THREAD

**Issue by Helena1652** [xJon/The-1.7.10-Pack#1911]
![fail](https://user-images.githubusercontent.com/62789365/77818749-b5e52c80-70dd-11ea-8296-deedfd1e28e1.png)
I was having connection issues to the server and decided to reinstall the pack. As soon as I get to witchery-0.24.1.zip  it hangs for a while, then I get an error message to contact creator.

**Comment by xJon** [comment]
Did this get resolved?
