### ISSUE TITLE
My mod pack is not working

### ISSUE THREAD

**Issue by FiTzLab1** [xJon/The-1.7.10-Pack#1913]
https://paste.ubuntu.com/p/f25m37ZB78/
Can some one please help me, when I press play the technic launcher loads then mine craft opens then just crashes.

**Comment by xJon** [comment]
Try allocating 6GB of RAM. How much do you have in your computer?

**Comment by FiTzLab1** [comment]
I have 8gb of ram, how do i allocate more

**Comment by FiTzLab1** [comment]
on the Technic launcher i have 7GB  in the memory slot

**Comment by FiTzLab1** [comment]
so I deleted the mod pack and redownloaded it to see if that would help and it kind of did. and be fore I did this i took the file of my old world out and then after the pack reinstalled I put the folder of my world back in. I was able to launch the game and I hit the single player button and selected my world, the world started to load then it crashed. 

This is the crash report https://paste.ubuntu.com/p/wTQWtBxHwh/

**Comment by xJon** [comment]
You have corrupted questing data - simply reset (delete) the inside of `HardcoreQuesting` within your server's world folder. This will reset your quests progress, but you can always cheat the items you had back in if you want.

**Comment by FiTzLab1** [comment]
when i delete it do i put it back in

**Comment by xJon** [comment]
Simply delete it.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
