### ISSUE TITLE
1.7.10

### ISSUE THREAD

**Issue by Bigwil557** [xJon/The-1.7.10-Pack#1914]
Whenever I try and Join a server (any server) it says: Failed to login:  Invalid session ( Try Restarting your game) and no matter how many times I restart it it keeps happening. The console says com.mojang.authlib.GameProfile@
When I try to join.

**Comment by xJon** [comment]
You need to restart your launcher session, so log out completely.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
