### ISSUE TITLE
The 1.7.10 pack isn’t opening 

### ISSUE THREAD

**Issue by LoexLoe** [xJon/The-1.7.10-Pack#1915]
I will click play it’ll pop up at the bottom in the task bar but there isn’t a screen that pops up at all it’ll load in the background because once it’s been sitting there for like 5 minutes the music will start playing but the screen never pops up. Please help.

**Comment by xJon** [comment]
Is this an issue with other modpacks as well?

**Comment by jbjerri** [comment]
I had this same exact problem with m new computer.  It seems that the most recent version of java (1.8.261) for windows 10 causes problems with some (but not all) versions of minecraft.  I ended up reverting to java 1.8.25 which seemed to fix the problem (It's worth noting that java 1.8.261 was causing problems for all of minecraft 1.7.10 and 1.12.2, not just this modpack).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
