### ISSUE TITLE
'Attempting to extract file the-1710-pack-0.9.8d.zip, but it did not exist'

### ISSUE THREAD

**Issue by Ominous0** [xJon/The-1.7.10-Pack#1917]
Hello,

I recently deleted the modpack due to an error with the modpack not loading properly, and when I attempt to install it I recieve this error.

Is the web server for downloading down, or is it a client side issue?

Thanks for answering in advance.

e: I assume it's on your end, considering that the website looks like it's from 1989. https://the-1710-pack.com/

e 2: Just saw your message on discord. Oops. Wasn't on it. For anyone else who wasn't in the know: there's an issue with the download and it's being fixed.

**Comment by xJon** [comment]
Sorry for the inconvenience, we had issues on our end. We had updates over Discord.
It should be fixed now though!
