### ISSUE TITLE
Mekanism Teleporter + Railcraft Personal Anchor = forced & perma chunkloading

### ISSUE THREAD

**Issue by Nivid-IT** [xJon/The-1.7.10-Pack#1920]
After thorough testing I have concluded that placing down a Mekanism Teleporter inside of the chunkloading range of a Railcraft Personal Anchor will cause the chunk(s) to force load on server start, as well as keep chunks permanently loaded. Different combinations have been tested with a waiting time of more than 5 minutes after logging out as the owner of the personal anchor each time (since Railcraft's anchor class states `private static final int MINUTES_BEFORE_DISABLE = 5;`).

Verification of chunks being loaded without being inside or near them was done using:
- a tick profiler;
- an advanced computer sending HTTP Posts to a server in a loop.

And chunks containing the teleporter and anchor are force-loaded after a restart without player interference, I tested this by whitelisting the server.

After a player places down both, a ticket is made by either of the two mods for the ForgeChunkManager and kept alive by the personal anchor, making it persist through server restarts, as the ticket is never de-registered, at least that is my hypothesis.

This issue has a considerable negative effect on server performance as a lot of player bases are permanently loaded.

**Comment by xJon** [comment]
Thank you for reporting this. It seems that disabling the anchors by default might be beneficial for servers but not for all players, so I suppose the only solution would be to recommend server owners to disable Railcraft anchors on their end.

**Comment by xJon** [comment]
Might be fixed with https://github.com/GTNewHorizons/Hodgepodge/pull/12
