### ISSUE TITLE
Error downloading pack

### ISSUE THREAD

**Issue by Skyroseee** [xJon/The-1.7.10-Pack#1921]
I'm trying to open the pack through technic launcher and it just gives me an error message and says to contact the modpack author.
![Screenshot (2)](https://user-images.githubusercontent.com/68195955/87251429-b231a780-c439-11ea-864d-f8784b1322e3.png)

**Comment by xJon** [comment]
>The launcher says "failed to download x file, please contact modpack author".
Make sure you have no firewall or antivirus software interfering with the modpack or the Technic Launcher. Try adding the Technic Launcher and the Technic installation folder (%AppData%/.technic by default) to the firewall and antivirus exceptions. Alternatively, you can try temporarily disabling your firewall and antivirus instead.

> If that does not work, rebooting your router can help resolve connection issues. If you are on Wifi, try switching to a cabled connection.


From https://discordapp.com/channels/96554564429299712/648461574620708874/649922365119266837.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
