### ISSUE TITLE
World Map Data Disappears After Exiting Server

### ISSUE THREAD

**Issue by croachly** [xJon/The-1.7.10-Pack#1922]
I just started a server with the 1.7.10 v0.9.8d, and it turns out that my world map data disappears when I leave the server. My waypoints still exist, but everything is black on the map. I'm brand new to running a server and using modpacks, so I'm not even sure which file I need to look at. Is there any way I can fix this?

**Comment by xJon** [comment]
You can manually look for the cached files in your modpack installation folder.
`the-1710-pack\mods\VoxelMods\`.

**Comment by croachly** [comment]
So it turns out that when I originally set everything up, the VoxelMods didn't transfer. I've uploaded them to the server now, but the problem still persists. I can find the cached files, but I don't see them being updated as I play.

**Comment by xJon** [comment]
The cache only needs to be stored on the client side, not on the server.
