### ISSUE TITLE
Server problems 

### ISSUE THREAD

**Issue by whiteninja31** [xJon/The-1.7.10-Pack#1925]
when i try to connect to my own server it say mod rejections and after that 3 mods are listed

**Comment by xJon** [comment]
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by whiteninja31** [comment]
[latest.log](https://github.com/xJon/The-1.7.10-Pack/files/5184662/latest.log)
thats the latest log

**Comment by xJon** [comment]
Please use a [paste-tool](http://paste.ubuntu.com/).
Also, why did you close the issue?
