### ISSUE TITLE
"A fatal error has occured, this connection is terminated" While attempting to join a server

### ISSUE THREAD

**Issue by EshayAdlay** [xJon/The-1.7.10-Pack#1926]
So I installed the modpack a day ago, I can play single player no dramas, I was able to play multiplayer for about 5 minutes before disconnecting. 

Came back today to play with friends, and thats all I get "Fatal Error, Connection Terminated". Ive spoken to my friends, and they're saying to reinstall, change settings, etc. 

Ive allocated 8gbs in my 16gb system to technic launcher, so I know its not that. 

From what I've read online, is that Morph mod is shit, and it causes countless issues. I've asked them to disable it. As they were all headhunting eachother and morphing. As well as spamming what ever is in the Flans mod. 

I have a decent system, so I know its not that. The server had upto 8 people on with no issues. All of which playing on a range of different computers. 

Only thing I've done to the pack its self, is disable Voxel Menu, as its ugly and lags. And add optifine for shaders. I was able to run shaders no problem on single player and yesterday on multiplayer. I've since disabled them. But no beuno. 

Idk what to attach, no crash reports as it diddn't crash. But this was in the reports file.

Thanks in advanced, if you can help with this problem
[2020-09-12_14.49.08.zip](https://github.com/xJon/The-1.7.10-Pack/files/5212239/2020-09-12_14.49.08.zip)
-Pack/files/5212238/2020-09-12_14.49.08.zip)

**Comment by EshayAdlay** [comment]
Quickly reply to my self. There is a default server. I can join that no worries. I did have issues at first. But they seem to have resolved them selves. So I assume its the server they're using

**Comment by xJon** [comment]
If you're using Optifine, make sure you use version D6.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
