### ISSUE TITLE
Installing Freezes Up and Crashes Launcher

### ISSUE THREAD

**Issue by jordanpball** [xJon/The-1.7.10-Pack#1927]
Howdy! Big fan of this modpack.

I've been trying to install this on my PC but each time I try, it freezes up at 19% (Downloading Mod: steves-carts-2-2.0.0b18.zip).

I have tried reinstalling the entire launcher, deleting the pack and reinstalling it all, reinstalled Java, and I am out of ideas.

Also, each time this happens, the entire launcher crashes as well, and I need to open up Task Manager to close out.

I don't seem to have any antivirus software nor firewall blocking it.

Please let me know if there's any more info you need.

Thank you!!!

**Comment by xJon** [comment]
Hi! Are you using the original Technic Launcher?

**Comment by jordanpball** [comment]
I am using whatever the latest version is. I just installed the launcher yesterday. Other modpacks' installations seem to work perfectly.

**Comment by xJon** [comment]
Can you download this link?
http://solder.endermedia.com/repository/mods/steves-carts-2/steves-carts-2-2.0.0b18.zip
If you so can place the file under `the-1710-pack/cache` to download it manually.

**Comment by jordanpball** [comment]
It works!!!!!!!!!!! Thank you so much!
