### ISSUE TITLE
Internal Error when joining the server

### ISSUE THREAD

**Issue by TOMTOMBOOM101** [xJon/The-1.7.10-Pack#1929]
Hi, when my girlfriend and I try to join the official 1.7.10 server, we're not able to. The game either rejects us, citing "internal error", or just crashes

I'm aware there's something about ME systems glitching out in chests, but we dont have an ME system. any help or advice is appreciated

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
