### ISSUE TITLE
Can't get any texture packs to replace in game textures

### ISSUE THREAD

**Issue by Imbalance** [xJon/The-1.7.10-Pack#1931]
I've tried a few resource packs, have them installed in the right place for this modpack, activated them, and the only thing that changes are some icons and other misc gui graphics.

I want hi-res textures for the blocks in the game. I've always hated the grainy pixel look of original minecraft.

I've replaced these in the past with optifine, etc, but how do I do it with this mod pack and launcher combo?
Nothing I've tried has replaces the blocks textures.

**Comment by xJon** [comment]
You need to make sure to install a resource pack that supports both vanilla and modded textures. A combo that works is Sphax for vanilla + this patch for The 1.7.10 Pack: https://bdcraft.net/community/viewtopic.php?t=3729

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
