### ISSUE TITLE
Is there a way to add optifine, etc, or other mods manually to this mod pack?

### ISSUE THREAD

**Issue by Imbalance** [xJon/The-1.7.10-Pack#1932]
I'm much more familiar with doing this in Terraria, editing the appropirate files and where to manually install mods, but trying this with the technic launcher and associated files didn't load the mods I added. 
Is there a file inside the 1.7.xxx directory that tells minecraft all of the mods to load? I couldn't find one if there is.

**Comment by xJon** [comment]
You need to put the new mods in the `mods` folder inside the modpack installation folder.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
