### ISSUE TITLE
Tinkers tools not accepting batteries, cells, capacitors, version 0.9.8d

### ISSUE THREAD

**Issue by Miles343** [xJon/The-1.7.10-Pack#1934]
I tried adding power to a tinkers pickaxe and only the leadstone energy cell and the leadstone flux capacitor worked giving it the fluxed modifier, none of the upgraded versions (hardened versions) or energy cubes or ender IO capacitor bank blocks and even the HV capacitor from modular suits that says "for use in tinker table" didn't work.

**Comment by xJon** [comment]
It might be because of this:
![image](https://user-images.githubusercontent.com/8945347/113906561-0d33d780-97dd-11eb-82fb-770b2305ec48.png)
But apart from that, as the mod is no longer in active development for 1.7.10, there's not much we can do.
Thanks for reporting nonetheless!
