### ISSUE TITLE
Cinnabar Ore interaction with Alloy Smelter enderIO, version 0.9.8d

### ISSUE THREAD

**Issue by Miles343** [xJon/The-1.7.10-Pack#1935]
The recipe says that one cinnabar ore makes 2 quicksilver from smelting it in the enderIO alloy smelter but it only makes one. The recipe is displaying incorrectly.

**Comment by xJon** [comment]
Hi! As 1.7.10 is over 5 years old, there's nothing much we can do about these issues. Thank you for reporting nonetheless!
