### ISSUE TITLE
Incorrect thaumcraft aspects on some items I have found, version 0.9.8d

### ISSUE THREAD

**Issue by Miles343** [xJon/The-1.7.10-Pack#1936]
Osmium ore has 64 of power, fire, sense, terra, crystal, greed - doesn't break down in an alchemical furnace but does break down into aspects in a crucible.

Thermal Foundation Nitre has 64 of air, power, fire; 22 of destruction, crystal greed - doesn't break down in an alch furnace but does break down in a crucible.

Paper has 1 mind, 2 water, 2 metal - does break down in an alch furnace and crucible.

**Comment by xJon** [comment]
As I wrote before, due to 1.7.10 being over 5 years old, there's nothing much we can do about these issues, but thank you for reporting nonetheless!
