### ISSUE TITLE
world on Steve's Galaxy modpack wont load and crashes

### ISSUE THREAD

**Issue by scribscrub** [xJon/The-1.7.10-Pack#1937]
i can make a new world and play it but whenever i try to load a world it makes it to the loading screen and crashes.

heres the crash log:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2/2/21 9:47 AM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@74f9b221
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5706749976 bytes (5442 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 4 loaded mod(s)
          - VoxelCam version 1.3.2
          - VoxelMap version 1.5.14
          - VoxelLib version 2.3.1
          - Mouse Tweaks version 2.4.4
	LaunchWrapper: 49 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: myrathi.infinibows.asm.BowTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: pcl.lc.coremod.LCCoreTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: li.cil.oc.common.asm.ClassTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: micdoodle8.mods.miccore.MicdoodleAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: lumien.resourceloader.asm.ClassTransformer
          - Transformer: alexiil.mods.load.coremod.BetterLoadingScreenTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
          - Transformer: com.thevoxelbox.common.TimeUpdateTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: com.thatapplefreak.voxelcam.VoxelCamTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 5 total; -Xms6144m -Xmx6144m -XX:+UseG1GC -XX:MaxGCPauseMillis=4 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 91
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 93 mods loaded, 93 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (modpack.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-9} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	InfiniBows{1.3.0 build 20} [InfiniBows] (minecraft.jar) 
	UCHIJAAAA	LanteaCraft-Core{1.0} [LanteaCraft Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	betterloadingscreen{1.3.2} [Better Loading Screen] ([1.7.10] BetterLoadingScreen-1.3.2.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-9} [Applied Energistics 2] (appliedenergistics2-rv2-stable-9.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3B2} [CoFH Core] (CoFHCore-[1.7.10]3.0.3B2-294.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0B1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0B1-95.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.2B2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.2B2-210.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.1.2.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.1.2.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.1.2.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.2.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.2.jar) 
	UCHIJAAAA	CustomMainMenu{1.5} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.5-client.jar) 
	UCHIJAAAA	lootablebodies{1.3.5} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.3.5-backport.jar) 
	UCHIJAAAA	defaultworldgenerator{0.1-b13} [Default World Generator] (DefaultWorldGenerator-1.7.10-0.1-b13-client.jar) 
	UCHIJAAAA	IC2{2.2.744-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.744-experimental.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.344} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.333.jar) 
	UCHIJAAAA	Mekanism{8.1.5} [Mekanism] (Mekanism-1.7.10-8.1.5.246.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJAAAA	FlatSigns{2.1.0.19} [Flat Signs] (FlatSigns-1.7.10-universal-2.1.0.19.jar) 
	UCHIJAAAA	fossil{1.7.10 Build 7.2.0} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.333.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.0.8.16} [MrTJPCore] (MrTJPCore-1.7.10-1.0.8.16-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.6.2.82} [ProjectRed] (ProjectRed-1.7.10-4.6.2.82-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.6.2.82} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.6.2.82-Integration.jar) 
	UCHIJAAAA	OpenComputers{1.5.12.26} [OpenComputers] (OpenComputers-MC1.7.10-1.5.12.26-universal.jar) 
	UCHIJAAAA	LanteaCraft{1.0.0-70} [LanteaCraft] (LanteaCraft-1.7.10-70.jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	MekanismGenerators{8.1.5} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.5.246.jar) 
	UCHIJAAAA	MekanismTools{8.1.5} [MekanismTools] (MekanismTools-1.7.10-8.1.5.246.jar) 
	UCHIJAAAA	meteors{2.14.3} [Falling Meteors] (meteors-1.7.10-2.14.3.jar) 
	UCHIJAAAA	minechem{5.0.5.399} [Minechem] (Minechem-1.7.10-5.0.5.399.jar) 
	UCHIJAAAA	MineMenu{1.2.0} [MineMenu] (MineMenu-1.7.10-1.2.0.B44-universal-client.jar) 
	UCHIJAAAA	numina{0.4.0.7-QMX} [Numina] (Numina-0.4.0.7-QMX.jar) 
	UCHIJAAAA	powersuits{0.11.0.7-QMX} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.7-QMX.jar) 
	UCHIJAAAA	powersuitaddons{0.11.0.7-QMX} [Modular Powersuit Addons] (ModularPowersuitsAddons-0.11.0.7-QMX.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10-client.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHIJAAAA	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29-client.jar) 
	UCHIJAAAA	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) 
	UCHIJAAAA	openmodularturrets{2.0.1-137} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.0.1-137.jar) 
	UCHIJAAAA	fodc{1.6.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.6.1.jar) 
	UCHIJAAAA	Ping{%MOD_VERSION} [Ping] (Ping-1.7.X-1.0.2.B6-universal.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.6.2.82} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.6.2.82-Mechanical_beta.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.6.2.82} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.6.2.82-World.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.6.2.82} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.6.2.82-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.6.2.82} [ProjectRed-Integration] (ProjectRed-1.7.10-4.6.2.82-Integration.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.6.2.82} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.6.2.82-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.6.2.82} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.6.2.82-Mechanical_beta.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.1B1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1B1-85.jar) 
	UCHIJAAAA	ResourceLoader{1.2} [Resource Loader] (ResourceLoader-1.2-client.jar) 
	UCHIJAAAA	Schematica{1.7.6.121} [Schematica] (Schematica-1.7.10-1.7.6.121-universal.jar) 
	UCHIJAAAA	Shatter{4.0.0} [Shatter] (Shatter-4.0.0-client.jar) 
	UCHIJAAAA	simplyjetpacks{1.5.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.1.jar) 
	UCHIJAAAA	Stackie{1.6.0.35} [Stackie] (Stackie-1.7.10-1.6.0.35-universal.jar) 
	UCHIJAAAA	Sync{4.0.0} [Sync] (Sync-4.0.0.jar) 
	UCHIJAAAA	tabbychat{1.11.2.2} [TabbyChat] (TabbyChat-1.7.10-1.11.2.2-fml-client.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0B2} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0B2-149.jar) 
	UCHIJAAAA	TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4-client.jar) 
	UCHIJAAAA	tradeboothmod{1.7.10.1} [Trade Booth Mod] (tradebooth.1.7.10.1.jar) 
	UCHIJAAAA	WLM{1.4.3} [The Wasteland Mod] (Wasteland mod-1.4.4.jar) 
	UCHIJAAAA	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness-1.9.6.jar) 
	UCHIJAAAA	McMultipart{1.2.0.344} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	UCHIJAAAA	aobd{2.6.3} [Another One Bites The Dust] (AOBD-2.6.3.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.344} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
	AE2 Version: stable rv2-stable-9 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3B2-294
	ThermalFoundation: -[1.7.10]1.2.0B1-95
	ThermalExpansion: -[1.7.10]4.0.2B2-210
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	NetherOres: -[1.7.10]2.3.0-12
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.1B1-85
	ThermalDynamics: -[1.7.10]1.1.0B2-149
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [GCEntityPlayerMP['Scrib123'/140, l='Copy of pe n is', x=665.50, y=64.00, z=1138.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by xJon** [comment]
This repository is for The 1.7.10 Pack, and not for Steve's Galaxy. Unfortunately there's not much we can do.
