### ISSUE TITLE
BugTorch prevents Thermos/Crucible from loading plugins.

### ISSUE THREAD

**Issue by Zilacon** [xJon/The-1.7.10-Pack#1940]
On the recent update BugTorch was included.
When loading the server up around 80% of my plugins did not load at all.
After disabling mods one by one the problem was fixed when BugTorch was disabled.

This should be reproducible on any thermos/crucible server.

**Comment by clienthax** [comment]
bugTorch is screwing with code it shouldn't be touching with a crappy overwrite mixin

Following config will 'fix'

            BugTorchConfig.skipInitialWorldChunkLoad = false;
            BugTorchConfig.fasterGetBlockByIdForAirBlocks = false;

**Comment by xJon** [comment]
These settings are shipped by default with the `0.10.1` server package. When you update your server you should make sure to include new config files.
