### ISSUE TITLE
Game crashing back to Technic launcher

### ISSUE THREAD

**Issue by saucysailor** [xJon/The-1.7.10-Pack#1942]
I have a few issues when it comes to right clicking on a stack of items, For example in industrial craft when I am converting ingots into plates if I right click to convert the entire stack it crashes the game, the same happens on pretty much most recipes. I haven't had an issue with this before but it seems to be since the last update the issue has arisen.

**Comment by xJon** [comment]
Hi, what version of the modpack are you running?
Also, can you please provide a crash log using a [paste-tool](http://paste.ubuntu.com/)?

**Comment by saucysailor** [comment]
I am using the 0.10.2 version, I would post a crash log how ever there is no crash report being generated it simply closes down the game with out any sort of information as to why.

**Comment by saucysailor** [comment]
My apologies about that, here is the correct report.

https://paste.ubuntu.com/p/wHXCN3zGgm/plain/

**Comment by Kuro-sudo** [comment]
Why can't I have 1.7.10 optifine in the pack?

**Comment by xJon** [comment]
> Why can't I have 1.7.10 optifine in the pack?

You need to use version D6 for Fastcraft compatibility.

**Comment by xJon** [comment]
This was generously fixed by @clienthax and will be included in the next update!
