### ISSUE TITLE
game lagging and it's not my fault

### ISSUE THREAD

**Issue by 25BLUEMAN25** [xJon/The-1.7.10-Pack#1944]
my game lag when i hold torch or any light source(dynamic lights) and when smelter (tinkers construct) pours metal ? (i have good computer and in 0.9.8 v all that things work propertly)
Ps. my friends have the same problem

**Comment by xJon** [comment]
Hi, you can disable Dynamic Lights by removing the mod or toggling it off (press `D`).

**Comment by 25BLUEMAN25** [comment]
ty, with dynamic lights it helps but smelter is stil lagging

**Comment by xJon** [comment]
If you need to boost performance I'd recommend you to manually install Optifine D6 for 1.7.10.

**Comment by 25BLUEMAN25** [comment]
thank you very much, that's helps a bit, that's all
