### ISSUE TITLE
Game closed when i try to join my single player world

### ISSUE THREAD

**Issue by Orends** [xJon/The-1.7.10-Pack#1950]
I reinstalled the game several times, but the game is still crashing when i try to load in my world.

**Comment by Orends** [comment]
[latest.log](https://github.com/xJon/The-1.7.10-Pack/files/6764869/latest.log)
[2021-07-05-7.log.gz](https://github.com/xJon/The-1.7.10-Pack/files/6764871/2021-07-05-7.log.gz)
Is this right, i dont know how to use the paste-tool

**Comment by xJon** [comment]
Can you load a world backup?
Also, does it help to enable `removeErroringTileEntities` in `.technic\modpacks\the-1710-pack\config\forge.cfg`?

**Comment by Orends** [comment]
I enabeld it but it does not work. Also all backups are deleted.

**Comment by xJon** [comment]
Do other worlds work fine? Can you try to include the most recent log?

**Comment by Orends** [comment]
Other worlds work fine.
And I put the recent log in the mail
[latest.log](https://github.com/xJon/The-1.7.10-Pack/files/6765398/latest.log)
[2021-07-05-7.log.gz](https://github.com/xJon/The-1.7.10-Pack/files/6765400/2021-07-05-7.log.gz)

**Comment by xJon** [comment]
How did all the backups get deleted?
You can try to remove the OpenMods mod, but it will remove all of that mod's content in your world.

**Comment by Orends** [comment]
Dont know, id tried to load an backup but it failed and then all the backups were disappered.

**Comment by Orends** [comment]
what do you mean with the openmods mod? the openblocks mods or what do you mean?

**Comment by xJon** [comment]
All the backup files should be located in `.technic\modpacks\the-1710-pack\backups\`.
The OpenBlocks mod file name is `.technic\modpacks\the-1710-pack\mods\OpenBlocks-1.7.10-1.6.jar`.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
