### ISSUE TITLE
1.7.10 pack technic

### ISSUE THREAD

**Issue by cammac123** [xJon/The-1.7.10-Pack#1952]
hey! I'm having a problem with the pack, I'm trying to install shaders through optifine and just the option "shaders" isnt popping up in the options. i fixed all the crashing problems that most people seem to be having. If anyone could help that'd be great! 

Also I'm using the optifine d6 since it bypasses the problem with the crashing with some of the mods that're in the 1.7.10 pack. Thanks!

**Comment by xJon** [comment]
Hi, is it working for you when trying to setup Shaders for 1.7.10 Vanilla?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
