### ISSUE TITLE
Game crashing back to Technic Launcher after power outage

### ISSUE THREAD

**Issue by kajmoerk** [xJon/The-1.7.10-Pack#1953]
PC shut down due to a power outage in my apartment. When i tried to load my world again it crashes and returns to the Technic Launcher.

I had no issues/crashes before the power outage.

Crash report is here: [https://paste.ubuntu.com/p/bWZTnwn8z6/](url)
Installed version is: 0.10.2.

I managed to load a backup, but lost quite a lot of work.

Is there any way i can fix the original version and recover my lost work?

Thanks in regards

**Comment by xJon** [comment]
Unfortunately Minecraft gets very easily corrupted when not saved properly, this is a common issue.
You can try to reset (delete) your questing data and see if that helps - you can do that by deleting the `HardcoreQuesting` folder inside your world save folder.

**Comment by kajmoerk** [comment]
Thank you very much, that worked!
