### ISSUE TITLE
keybinds linux

### ISSUE THREAD

**Issue by dot161** [xJon/The-1.7.10-Pack#1954]
Hey there, 
I'm using linux (debian-based). When I try hitting the morphmod key ('ß') it doesn't work. When I'm in keybind-settings and try to assign any bind to 'ß' it just switches to "none". I hope someone can help we with that problem.

detailed information in attachment
![Screenshot at 2021-09-03 12-28-41](https://user-images.githubusercontent.com/90036183/131991193-e93ff8f1-0afd-451c-b3b9-c8c473142548.png)

**Comment by xJon** [comment]
Did you try editing the keybinds through the config file? `\the-1122-pack\config\ichunutil_keybinds.cfg`.

**Comment by dot161** [comment]
Thank you - No I did not. Where can I find the key "defaults"?

**Comment by xJon** [comment]
You can delete the file to have it regenerate with the default values :)

**Comment by dot161** [comment]
in the config file I can't find the keybind to open the selector (which was the one I wanted to change originally). Is it just me or is the keybind missing there?

**Comment by xJon** [comment]
I indeed cannot find it there. Perhaps the keybind for that is within the Controls menu?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
