### ISSUE TITLE
Modpack stops loading at specific point

### ISSUE THREAD

**Issue by Chief-Squanto** [xJon/The-1.7.10-Pack#1956]
Attempted to load the modpack after roughly two years of not playing it, only for it to not load. Watching the Console in the technic launcher revealed that it reached a certain point and then promptly ceased all activity until the loading window was forced closed. I have watched the console readout on another's computer when they started it, and the same error code appears, with a higher volume of messages, but theirs doesn't halt or even slow down the process. Other technic modpacks of similar complexity and ram usage do not have this problem

I have attempted switching versions, reinstalling the pack, reinstalling technic, and allocating more ram with no discernable results.
The last messages before the halt:
https://pastebin.ubuntu.com/p/s25NkcnSwq/

**Comment by xJon** [comment]
Hi, did you attempt resetting `F:\technic\cache`?

**Comment by Chief-Squanto** [comment]
Looked for a file or folder with that name but only found liteconfig. Is it supposed to be at C:\Users\(******)\AppData\Roaming\.technic\modpacks\the-1710-pack?

**Comment by xJon** [comment]
`C:\Users(******)\AppData\Roaming.technic\modpacks\the-1710-pack\mods\1.7.10\` :)

**Comment by Chief-Squanto** [comment]
10/10.
