### ISSUE TITLE
Wand Foci Overlap (Thaumcraft)

### ISSUE THREAD

**Issue by DarkSide1305** [xJon/The-1.7.10-Pack#1957]
There are some Wand Foci (Thaumcraft) Overlaps. If you have 2 of these in your Inventory, one will not show as its replaced (in the Wand Foci Selection menu)
AE Wrench replaces Animation
Excavation replaces Liquification
Blink replaces Animation

**Comment by xJon** [comment]
Unfortunately as this is running a very old version of Thaumcraft I'm not sure there's much we can do about this. Are you sure it's a bug and there's no functionality provided by this?

**Comment by DarkSide1305** [comment]
Well... only being able to see, at max, 24 out of the 27 available doesnt seem like a good function to me. Even just having 2 Foci, I dont see why the AE2 Wrench Foci should override the Animation Foci, none of the Foci that override another have even remotely the same function.

**Comment by xJon** [comment]
Also - did you modify the modpack in any way? (e.g. installed Optifine?)

**Comment by DarkSide1305** [comment]
I do, but I just checked without those - same problem still applies

**Comment by xJon** [comment]
Even in a new world can you reproduce this issue (without the added mods)?

**Comment by xJon** [comment]
With the help of someone over Discord, the bug was reproduceable yet it doesn't seem to have any solution unfortunately (unless you can convince some 1.7.10 developers to help), so there's nothing I can do. Thank you nevertheless for the report!
