### ISSUE TITLE
Pack stops loading once it says "Starting Game"

### ISSUE THREAD

**Issue by TheNetPlex** [xJon/The-1.7.10-Pack#1958]
II have tried reinstalling everything from technic to the pack to java. Nothing has worked. People in the discord seem to think its a file perms issue. It never crashes, it just stops responding and then loads infinitely until I close it. Here is a link to the logs. https://github.com/TheNetPlex/Logs/blob/2752b6a91c7468f5e7428e43d48556612b7cdfeb/technicLog

**Comment by xJon** [comment]
Seems to be the same issue as https://github.com/xJon/The-1.7.10-Pack/issues/1956.
Did you modify the modpack in any way? Also please try the workaround I suggested there!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
