### ISSUE TITLE
The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

### ISSUE THREAD

**Issue by ShokeiGM** [xJon/The-1.7.10-Pack#1961]
My minecraft sever doesnt even start. It shows this error.

**Comment by ShokeiGM** [comment]
> My minecraft sever doesnt even start. It shows this error.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.3B.jar)
  ReachFixPlugin (ReachFix-1.12.2-1.0.1.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  LevelUpCore (levelup2-1.5.8.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  FarseekCoreMod (Farseek-1.12-2.5.1.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.0.2.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 1/12/22 6:48 PM
Description: Ticking entity

java.lang.NoSuchFieldError: currentEntity
	at team.cqr.cqrepoured.entity.pathfinding.PathNavigateGroundCQR$1.func_189553_b(PathNavigateGroundCQR.java:105)
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186330_a(WalkNodeProcessor.java:385)
	at team.cqr.cqrepoured.entity.pathfinding.PathNavigateGroundCQR$1.func_193577_a(PathNavigateGroundCQR.java:66)
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186319_a(WalkNodeProcessor.java:298)
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186331_a(WalkNodeProcessor.java:380)
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186318_b(WalkNodeProcessor.java:71)
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:37)
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30)
	at team.cqr.cqrepoured.entity.pathfinding.PathNavigateGroundCQR.getPathToPosCQR(PathNavigateGroundCQR.java:230)
	at team.cqr.cqrepoured.entity.pathfinding.PathNavigateGroundCQR.func_179680_a(PathNavigateGroundCQR.java:191)
	at net.minecraft.pathfinding.PathNavigateGround.func_75494_a(SourceFile:73)
	at net.minecraft.pathfinding.PathNavigate.func_75497_a(PathNavigate.java:163)
	at team.cqr.cqrepoured.entity.ai.attack.EntityAIAttack.updatePath(EntityAIAttack.java:58)
	at team.cqr.cqrepoured.entity.ai.attack.EntityAIAttack.func_75249_e(EntityAIAttack.java:35)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:807)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2688)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:609)
	at team.cqr.cqrepoured.entity.bases.AbstractEntityCQR.func_70636_d(AbstractEntityCQR.java:834)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2509)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:318)
	at team.cqr.cqrepoured.entity.bases.AbstractEntityCQR.func_70071_h_(AbstractEntityCQR.java:757)
	at net.minecraft.world.World.func_72866_a(World.java:2340)
	at net.minecraft.world.World.func_72870_g(World.java:2294)
	at net.minecraft.world.World.func_72939_s(World.java:2076)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:852)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:988)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at team.cqr.cqrepoured.entity.pathfinding.PathNavigateGroundCQR$1.func_189553_b(PathNavigateGroundCQR.java:105)
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186330_a(WalkNodeProcessor.java:385)
	at team.cqr.cqrepoured.entity.pathfinding.PathNavigateGroundCQR$1.func_193577_a(PathNavigateGroundCQR.java:66)
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186319_a(WalkNodeProcessor.java:298)
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186331_a(WalkNodeProcessor.java:380)
	at net.minecraft.pathfinding.WalkNodeProcessor.func_186318_b(WalkNodeProcessor.java:71)
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:37)
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30)
	at team.cqr.cqrepoured.entity.pathfinding.PathNavigateGroundCQR.getPathToPosCQR(PathNavigateGroundCQR.java:230)
	at team.cqr.cqrepoured.entity.pathfinding.PathNavigateGroundCQR.func_179680_a(PathNavigateGroundCQR.java:191)
	at net.minecraft.pathfinding.PathNavigateGround.func_75494_a(SourceFile:73)
	at net.minecraft.pathfinding.PathNavigate.func_75497_a(PathNavigate.java:163)
	at team.cqr.cqrepoured.entity.ai.attack.EntityAIAttack.updatePath(EntityAIAttack.java:58)
	at team.cqr.cqrepoured.entity.ai.attack.EntityAIAttack.func_75249_e(EntityAIAttack.java:35)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:807)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2688)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:609)
	at team.cqr.cqrepoured.entity.bases.AbstractEntityCQR.func_70636_d(AbstractEntityCQR.java:834)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2509)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:318)
	at team.cqr.cqrepoured.entity.bases.AbstractEntityCQR.func_70071_h_(AbstractEntityCQR.java:757)
	at net.minecraft.world.World.func_72866_a(World.java:2340)
	at net.minecraft.world.World.func_72870_g(World.java:2294)

-- Entity being ticked --
Details:
	Entity Type: cqrepoured:skeleton (team.cqr.cqrepoured.entity.mobs.EntityCQRSkeleton)
	Entity ID: 2157
	Entity Name: Skeleton
	Entity's Exact location: 538.35, 76.00, 709.12
	Entity's Block location: World: (538,76,709), Chunk: (at 10,4,5 in 33,44; contains blocks 528,0,704 to 543,255,719), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2076)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:852)

-- Affected level --
Details:
	Level name: world
	All players: 3 total; [EntityPlayerMP['Xairox437'/288, uuid='85785f40-9510-3f9d-a298-f6cb51c8ce56', l='world', x=63.47, y=75.00, z=113.37, cx=3, cd=7, tl=219726, v=true, d=false](Xairox437 at 63.47460155917755,75.0,113.37030399548146), EntityPlayerMP['JorgelioKun'/840, uuid='02c240d2-4d5c-3660-8122-03ce00493571', l='world', x=357.24, y=71.00, z=652.71, cx=22, cd=40, tl=225742, v=true, d=false](JorgelioKun at 357.23750001192093,71.0,652.7128865938921), EntityPlayerMP['Papirola2'/2075, uuid='ce14ccb4-8094-3464-a491-28ec5e7bd976', l='world', x=529.21, y=74.18, z=702.98, cx=33, cd=43, tl=92008, v=true, d=false](Papirola2 at 529.2136227923722,74.17992979617382,702.9756194891274)]
	Chunk stats: ServerChunkCache: 1289 Drop: 0
	Level seed: 7604347581306022184
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-24,64,248), Chunk: (at 8,4,8 in -2,15; contains blocks -32,0,240 to -17,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 135092 game time, 178314 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 113995 (now: false), thunder time: 98198 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:988)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Magma Version: 1bc8635
	Operating System: Linux (amd64) version 4.15.0-166-generic
	Java Version: 1.8.0_292, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 4959283984 bytes (4729 MB) / 7859601408 bytes (7495 MB) up to 7859601408 bytes (7495 MB)
	JVM Flags: 2 total; -Xmx8000M -Xms8000M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 91 mods loaded, 91 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                                | Signature                                |
	|:------ |:--------------------- |:------------------------ |:----------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                         | None                                     |
	| LCHIJA | mcp                   | 9.42                     | minecraft.jar                                         | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                | magma1.12.2                                           | None                                     |
	| LCHIJA | forge                 | 14.23.5.2855             | magma1.12.2                                           | None                                     |
	| LCHIJA | ivtoolkit             | 1.3.3-1.12               | minecraft.jar                                         | None                                     |
	| LCHIJA | micdoodlecore         |                          | minecraft.jar                                         | None                                     |
	| LCHIJA | reachfix              | 1.0.1                    | minecraft.jar                                         | None                                     |
	| LCHIJA | securitycraft         | v1.9.0.2                 | [1.12.2]+SecurityCraft+v1.9.0.2.jar                   | None                                     |
	| LCHIJA | advancedcombat        | 1.1.2                    | advancedcombat-1.1.2-[1.12].jar                       | None                                     |
	| LCHIJA | animcolle             | 1.0.0b3                  | Animcolle+1.1.0r+Official+Release+Fix1.jar            | None                                     |
	| LCHIJA | jei                   | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                             | None                                     |
	| LCHIJA | appleskin             | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                            | None                                     |
	| LCHIJA | thedragonlib          | 1.12.2-5.3.0             | thedragonlib-1.12.2-5.3.0.jar                         | None                                     |
	| LCHIJA | armorplus             | 1.12.2-11.28.0.69        | armorplus-1.12.2-11.28.0.69.jar                       | None                                     |
	| LCHIJA | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                                | None                                     |
	| LCHIJA | artifacts             | 1.12.2-1.2.3             | Artifacts-1.12.2-1.2.3.jar                            | None                                     |
	| LCHIJA | bloodmoon             | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                          | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bookshelf             | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bookworm              | 1.12.2-2.5.2.1           | bookworm-1.12.2-2.5.2.1.jar                           | None                                     |
	| LCHIJA | buildcraftlib         | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCHIJA | buildcraftcore        | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCHIJA | buildcraftbuilders    | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCHIJA | buildcrafttransport   | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCHIJA | buildcraftsilicon     | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCHIJA | theoneprobe           | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                           | None                                     |
	| LCHIJA | buildcraftcompat      | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCHIJA | buildcraftenergy      | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCHIJA | buildcraftfactory     | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCHIJA | buildcraftrobotics    | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                          | None                                     |
	| LCHIJA | cavern                | 2.3.1                    | Cavern_1.12.2-v2.3.1.jar                              | None                                     |
	| LCHIJA | cqrepoured            | 2.6.3B                   | Chocolate_Quest_Repoured-1.12.2-2.6.3B.jar            | None                                     |
	| LCHIJA | clumps                | 3.1.2                    | Clumps-3.1.2.jar                                      | None                                     |
	| LCHIJA | cosmeticarmorreworked | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar                  | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | props                 | 2.6.3.7                  | Decocraft-2.6.3.7_1.12.2.jar                          | None                                     |
	| LCHIJA | reccomplex            | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                          | None                                     |
	| LCHIJA | dynamictrees          | 1.12.2-0.9.25            | DynamicTrees-1.12.2-0.9.25.jar                        | None                                     |
	| LCHIJA | eleccore              | 1.9.453                  | ElecCore-1.12.2-1.9.453.jar                           | None                                     |
	| LCHIJA | ebwizardry            | 4.3.4                    | ElectroblobsWizardry-4.3.4-MC1.12.2.jar               | None                                     |
	| LCHIJA | elevatorid            | 1.3.14                   | ElevatorMod-1.12.2-1.3.14.jar                         | None                                     |
	| LCHIJA | eplus                 | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | umm3185118519         | release 1.4 - MC 1.12.2  | Extended+ItemsOres+[1.12.2]+(release+1.4).jar         | None                                     |
	| LCHIJA | potioncore            | 1.9_for_1.12.2           | PotionCore-1.9_for_1.12.2.jar                         | None                                     |
	| LCHIJA | extra_spells          | 1.2.0                    | ExtraSpells-1.12.2-1.2.0.jar                          | None                                     |
	| LCHIJA | farseek               | 2.5.1                    | Farseek-1.12-2.5.1.jar                                | None                                     |
	| LCHIJA | fastleafdecay         | v14                      | FastLeafDecay-v14.jar                                 | None                                     |
	| LCHIJA | ftblib                | 5.4.7.2                  | FTBLib-5.4.7.2.jar                                    | None                                     |
	| LCHIJA | itemfilters           | 1.0.4.2                  | ItemFilters-1.0.4.2.jar                               | None                                     |
	| LCHIJA | ftbquests             | 1202.9.0.15              | FTBQuests-1202.9.0.15.jar                             | None                                     |
	| LCHIJA | galacticraftcore      | 4.0.2.280                | GalacticraftCore-1.12.2-4.0.2.280.jar                 | None                                     |
	| LCHIJA | galacticraftplanets   | 4.0.2.280                | Galacticraft-Planets-1.12.2-4.0.2.280.jar             | None                                     |
	| LCHIJA | geckolib3             | 3.0.13                   | geckolib-forge-1.12.2-3.0.13.jar                      | None                                     |
	| LCHIJA | gottschcore           | 1.14.0                   | GottschCore-mc1.12.2-f14.23.5.2854-v1.14.0.jar        | None                                     |
	| LCHIJA | gravestone            | 1.10.3                   | gravestone-1.10.3.jar                                 | None                                     |
	| LCHIJA | hammerx               | ${version}               | hammerx-1.12-1.1.4.jar                                | None                                     |
	| LCHIJA | ichunutil             | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | hats                  | 7.1.1                    | Hats-1.12.2-7.1.1.jar                                 | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
	| LCHIJA | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest             | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                       | None                                     |
	| LCHIJA | ironfurnaces          | 1.3.5                    | ironfurnaces-1.3.5.jar                                | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                           | None                                     |
	| LCHIJA | levelup2              | ${version}               | levelup2-1.5.8.jar                                    | None                                     |
	| LCHIJA | mca                   | 6.1.0                    | MCA-1.12.2-6.1.0-universal.jar                        | None                                     |
	| LCHIJA | mcwbridges            | 1.0.6                    | mcw-bridges-1.0.6b-mc1.12.2.jar                       | None                                     |
	| LCHIJA | mcwdoors              | 1.3                      | mcw-doors-1.0.3-mc1.12.2.jar                          | None                                     |
	| LCHIJA | mcwroofs              | 1.0.2                    | mcw-roofs-1.0.2-mc1.12.2.jar                          | None                                     |
	| LCHIJA | mcwtrpdoors           | 1.0.2                    | mcw-trapdoors-1.0.3-mc1.12.2.jar                      | None                                     |
	| LCHIJA | mcwwindows            | 1.0                      | mcw-windows-1.0.0-mc1.12.2.jar                        | None                                     |
	| LCHIJA | mobends               | 1.2.1                    | MoBends_1.12.2-1.2.1-19.12.21.jar                     | None                                     |
	| LCHIJA | more_mob_drops        | 1.0.0                    | MoreMobDrops1.12.2-1.0.0.jar                          | None                                     |
	| LCHIJA | morpheus              | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                           | None                                     |
	| LCHIJA | multiplelights        | 1.0.2                    | MultipleLights-1.12.x-1.0.2.jar                       | None                                     |
	| LCHIJA | mutantbeasts          | 1.12.2-1.0.2             | MutantBeasts-1.12.2-1.0.2.jar                         | None                                     |
	| LCHIJA | performant            | 1.12.2-1.5               | performant-1.11.jar                                   | None                                     |
	| LCHIJA | randomenchantments    | @VERSION@                | randomenchants-0.1.4.jar                              | None                                     |
	| LCHIJA | realdrops             | 1.2.14                   | RealisticItemDrops-1.2.14.jar                         | None                                     |
	| LCHIJA | silentlib             | 3.0.13                   | SilentLib-1.12.2-3.0.14+168.jar                       | None                                     |
	| LCHIJA | scalinghealth         | 1.3.37                   | ScalingHealth-1.12.2-1.3.42+147.jar                   | None                                     |
	| LCHIJA | spartanshields        | 1.5.5                    | SpartanShields-1.12.2-1.5.5.jar                       | None                                     |
	| LCHIJA | streams               | 0.4.8                    | Streams-1.12-0.4.8.jar                                | None                                     |
	| LCHIJA | teamsmod              | 1.12.2-Rfinal            | teamsmod-1.12.2-Rfinal-fixed.jar                      | None                                     |
	| LCHIJA | treasure2             | 1.18.0                   | Treasure2-mc1.12.2-f14.23.5.2859-v1.18.0.jar          | None                                     |
	| LCHIJA | treasure2_wizardry_lp | 1.0.1                    | Treasure2WizardryLP-mc1.12.2-f14.23.5.2854-v1.0.1.jar | None                                     |
	| LCHIJA | uteamcore             | 2.2.5.147                | u_team_core-1.12.2-2.2.5.147.jar                      | None                                     |
	| LCHIJA | usefulbackpacks       | 1.5.4.85                 | useful_backpacks-1.12.2-1.5.4.85.jar                  | None                                     |
	| LCHIJA | waystones             | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                            | None                                     |
	| LCHIJA | xpholder              | 2.0.4                    | XpHolder-2.0.4-mc1.12.x.jar                           | None                                     |
	| LCHIJA | zawa                  | 1.12.2-2.1.3             | zawa-1.12.2-2.1.3.jar                                 | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCHIJA | zettaimagic           | 1.4.3                    | ZettaiMagic-1.4.3.jar                                 | None                                     |
	| LCHIJA | ancientspellcraft     | 1.12.2-1.2.3             | AncientSpellcraft-1.12.2-1.2.3.jar                    | None                                     |
	| LCHIJA | eleccoreloader        | 1.9.453                  | ElecCore-1.12.2-1.9.453.jar                           | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CQRPlugin (Chocolate_Quest_Repoured-1.12.2-2.6.3B.jar)
  team.cqr.cqrepoured.asm.CQRClassTransformer
ReachFixPlugin (ReachFix-1.12.2-1.0.1.jar)
  meldexun.reachfix.asm.ReachFixClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
LevelUpCore (levelup2-1.5.8.jar)
  
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
FarseekCoreMod (Farseek-1.12-2.5.1.jar)
  farseek.core.FarseekClassTransformer
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.0.2.jar)
  
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 3 / 15; [EntityPlayerMP['Xairox437'/288, uuid='85785f40-9510-3f9d-a298-f6cb51c8ce56', l='world', x=63.47, y=75.00, z=113.37, cx=3, cd=7, tl=219726, v=true, d=false](Xairox437 at 63.47460155917755,75.0,113.37030399548146), EntityPlayerMP['JorgelioKun'/840, uuid='02c240d2-4d5c-3660-8122-03ce00493571', l='world', x=357.24, y=71.00, z=652.71, cx=22, cd=40, tl=225742, v=true, d=false](JorgelioKun at 357.23750001192093,71.0,652.7128865938921), EntityPlayerMP['Papirola2'/2075, uuid='ce14ccb4-8094-3464-a491-28ec5e7bd976', l='world', x=529.21, y=74.18, z=702.98, cx=33, cd=43, tl=92008, v=true, d=false](Papirola2 at 529.2136227923722,74.17992979617382,702.9756194891274)]
	Is Modded: Definitely; Server brand changed to 'Magma'
	Type: Dedicated Server (map_server.txt)

**Comment by Jaari** [comment]
What modpack is this? It's a 1.12.2 modpack (thus doesn't fit on this project), its not the 1.12.2 Pack either, and it doesn't appear to be Hexxit 2 either.
