### ISSUE TITLE
Stuttering every second

### ISSUE THREAD

**Issue by EmilJohan** [xJon/The-1.7.10-Pack#1964]
"About once per second running this modpack, the game stutters for a few frames and then goes back to smooth 60fps. What's causing this, and how do I fix it?"
https://github.com/xJon/The-1.7.10-Pack/issues/1485

I have the same issue, Couldn't find a solution in the previous post, been trying to fix this for a couple of days now.
I've tried the following:
- Updating java
- Updating Graphics drivers
- Reinstalled the modpack
- Opening the modpack in both Technic launcher, and multimc
- Allocating more/less ram

I never reach the cap on ram usage, disk or processor usage while playing, do you have any ideas?

**Comment by EmilJohan** [comment]
I've tried tweaking with the performance settings, but the stuttering still occurs on the shortest render distance, and lowest overall settings. Consistently.

**Comment by EmilJohan** [comment]
Fixed the issue after some research. Seemed to be the combination of dynamic lighting, and the polling rate on my mouse. Seems minecraft prefers a rather low polling rate.

**Comment by xJon** [comment]
Interesting - the issue is usually due to Dynamic Lights being problematic on some machines. Glad you got it working!
