### ISSUE TITLE
Mod rejections [FMLMod:jexclusives(1.1.0)]

### ISSUE THREAD

**Issue by Just-Chakal** [xJon/The-1.7.10-Pack#1966]
https://cdn.discordapp.com/attachments/932214313366720563/973243462809964555/sC4vpcIE.png

**Comment by xJon** [comment]
When are you experiencing this issue?

**Comment by Just-Chakal** [comment]
in my mod pack the version 1.1.1 dosen't work i need 1.1.0 if you can send it to me pls.

**Comment by xJon** [comment]
https://solder.endermedia.com/repository/mods/jons-exclusives/jons-exclusives-1.7.10-1.1.0.zip

**Comment by Just-Chakal** [comment]
Thanks a lot !!!!! Have a nice day !
