### ISSUE TITLE
Mod Addition

### ISSUE THREAD

**Issue by Bongo12345** [xJon/The-1.7.10-Pack#1968]
Hello xJon,
i would like to suggest the addition of the Extra Utilities 2 Mod.
Extra Utilities 1 is already in the Mod Pack but not 2.
Extra Utilities 2 adds Quantum Quarrys, more Generators, Machines, Spikes and much more.
It also improves Extra Utilities 1 Machines/Items (for exsample Transfer Nodes).
Since Extra Utilities 2 adds cool Machines and is technic themed I believe that it would fit perfectly in the 1.7.10 Pack.
I hope for a response.

Love Bongo12345

**Comment by xJon** [comment]
Hi Bongo12345!
Unfortunately Extra Utilities 2 is not available for Minecraft 1.7.10, so we are not able to add it.
