### ISSUE TITLE
Thaumcraft wrecked my game. 

### ISSUE THREAD

**Issue by generalmiscreant** [xJon/The-1.7.10-Pack#1970]
I have just gotten into the pack with one of my buddies. We started a server together along with a few others and I seem to be the only one having problems with the modpack. I dont know if it is my laptop or the modpack. when I open vanilla minecraft it works just fine. Without further ado I will get to the issue: I started to learn thaumcraft and was scanning things around the area with my thaumometer and I tried to scan a villager and my game froze and I was logged out of the server. upon my return my screen and every block on it has been glitched to the point of unplayability and for some stretch of time my scree will just completely fill with the color of the pixel I happen to be looking at. The game has become unplayable for me and me only. my friends on the server never had the same problem. I already tried undownloading and downloading the modpack again, restarting my computer yada yada all the basic tech support stuff you can think of I have tried it. The game is still unplayable. I tried openning my vanilla minecraft server to check if it was a problem with java, but that server works just fine. any suggestions?

my only theory is java recently had an update that I did not intentionally install, but may have automatically installed when I shut my computer down and booted it back up. That is the only thing I can think of I played on the server without issue for weeks before that message for the update went away and I tried playing with thaumcraft.

Everything else on my computer works fine. I have no viruses and my RL craft and Vanilla worlds are all okay. No matter what I do in the 1.7.10 pack its just a screen entirely filled with one color that changes as I look around.

The only thing I have not undownloaded and redownloaded is java. Not too hopeful that it will work though.

**Comment by generalmiscreant** [comment]
my worlds open they are just unplayable tried undownloading and redownloading everything including the launcher. only thing I have not tried yet is undownloading and redownloading java.

**Comment by xJon** [comment]
Hey, sorry about that! Could you please include your [latest game log](https://github.com/xJon/The-1.7.10-Pack#if-you-have-all-that-required-post-an-issue-with)?

**Comment by generalmiscreant** [comment]
@xJon Certainly! but there is a character limit on comments. any chance I can add a link or send it some other way to you directly?

**Comment by generalmiscreant** [comment]
@xJon nevermind the URL you linked just opened. I shared the log file. One more quesion: which version of java would work best with this pack. I have tried updating my drivers and different recommended java versions to fix the issue as well and none have worked

**Comment by generalmiscreant** [comment]
@xJon Sorry last thing. I also have 6gb of ram dedicated to the game when I run it so ram should not be an issue

**Comment by generalmiscreant** [comment]
@xJon The problem gets way way worse when I enter other dimensions (Nether, mining, etc)
the game only functions like 1/10 times i open it only if I am above world not interacting with items in my inventory/hot key, mobs and chests, I may be able to open my inventory once every 50 tries.

**Comment by generalmiscreant** [comment]
@xJon I am so sorry for the multitude of comments I am not trying to spam I am just trying to give you all the info I can in hopes that it will help the troubleshooting

**Comment by generalmiscreant** [comment]
@xJon I have solved the issue mostly by updating drivers and going back to old version of java and reinstalling pack once. There are still persisting problems though. any other dimension but the overworld is ruined. interacting with mobs (mainly killing them) reverts screen back to the seizure inducing mess of flashing color until I hit f3 A. morphing is working in the sense that once I am in the morph I can play normally, but as I scroll through them I am bombarded with the colors (the colors mason, what do they mean? xD). I can now hold items go into my inventory craft and build, but every so often it goes back to flashes and unplayable bullshit. I have been self troubleshooting going through every basic IT bs thing I can think of on the check list and doing it (checking drivers checking for windows updates etc etc. and I have gotten it to the point where it is barely playable
I will share the latest log alongside the other one maybe it will help compare and contrast between the other one to see what the remaining issue is?

**Comment by generalmiscreant** [comment]
this was over the course of 7 days of scrolling through reddits and trying different stuff

**Comment by generalmiscreant** [comment]
@xJon I thought that maybe the game was having issues handling the graphics so I tried turning graphics from fancy to fast and that made the problem WAY worse until I turned it back to fancy

**Comment by xJon** [comment]
Interesting problem, and I'm surprised you don't have similar issues with other 1.7.10 modpacks. You don't need more than 4 GB of RAM allocated in most cases. Also, I still don't see your latest client log link. As for Java, version 8 in 64 bit is the recommended version!

**Comment by generalmiscreant** [comment]
@xJon I opened it as a pull request and copied and pasted the entire log 
is there any good way to send it to you I am unfamiliar with how to use this website. not gonna lie I made an account here because I heard this is the best way to get your help but I do not know how to send log link. I tried copying and pasting and or uploading log into pull requests which I realize now was probably the wrong move

**Comment by generalmiscreant** [comment]
@xJon I went to the link you sent in your first comment on this thread and just went to add file and uploaded it that way. was that wrong?

**Comment by xJon** [comment]
You can also use this service - https://mclo.gs/ to share logs.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info!
