### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by Dirty3Thirty** [xJon/The-1.7.10-Pack#1972]
Ive never had a problem with 1.7.10 until recently. i launch the game just fine an it runs. i get to home screen an login to a solo or multiplayer server an as soon as i load in i get a solid color screen have no clue where to begin. ive updated all drivers hoping it would help. Do you have any adivice
![unknown](https://user-images.githubusercontent.com/110804225/183343050-51ee2144-799b-4836-991e-3e600aac80c3.png)

**Comment by xJon** [comment]
Please include your latest game log using https://mclo.gs/.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info!
