### ISSUE TITLE
Pack hangs on "Starting Game" while loading

### ISSUE THREAD

**Issue by TheNetPlex** [xJon/The-1.7.10-Pack#1973]

**Comment by TheNetPlex** [comment]
So essentially, I have had this issue once before but it was a long time ago. It was super weird, but whenever I load up the pack there is a ton of text going by in the console as usual until the game window turns from black to the hourglass loading screen, saying "starting game" with the bar a little over half full. It will then hang there for hours if left alone, never loading. I will attach a text file with the console info, as since the game never actually crashes, there would be no crash log. However, I will attach the most recent crash log just in case. There is a suspicious bit at the end of the console that I suspect to be the issue, but I could not find a solution online. This seems to be a niche issue. I assume it will be the: 
"[B#757]  [23:32:18] [Client thread/ERROR]: The jar file D:\Technic Launcher\cache\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar has a security seal for path net.java.games.input, but that path is defined and not secure" 
that is the issue. Hopefully someone can give me a hand on this, thank you!

[Console Log.txt](https://github.com/xJon/The-1.7.10-Pack/files/9330947/Console.Log.txt)

[latest.log](https://github.com/xJon/The-1.7.10-Pack/files/9330949/latest.log)

**Comment by xJon** [comment]
Hey, can you start other similar modpacks in the launcher?
It could be an anti virus issue.

**Comment by TheNetPlex** [comment]
Interestingly enough, only certain packs work and dont work. I tried attack of the b-team, which is on a version before 1.7.10, and it worked. I then tried blightfall which is on 1.7.10 and it didnt work, same issue. But when I tried tekkit legends which is also on 1.7.10, it went through perfectly fine. Also interestingly enough, I have my antivirus (trend micro) on my laptop but not on my desktop right now. Ive even tried disabling the windows firewall.

**Comment by xJon** [comment]
Did you try a complete reinstall of the launcher? (assuming you have backups of your saves)

**Comment by TheNetPlex** [comment]
I play on a server so I dont need backups, and yeah I have tried reinstalling multiple times, including deleting the main files and .technic files manually beforehand.

**Comment by xJon** [comment]
In this case I highly recommend you to get support from Technic's Discord, as they have more knowledge in troubleshooting such issues :)
You can join over: https://discord.com/invite/technic

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested!
