### ISSUE TITLE
Nether Quartz Ore not dropping properly

### ISSUE THREAD

**Issue by Apocrophon** [xJon/The-1.7.10-Pack#1974]
![image](https://user-images.githubusercontent.com/24848664/186770499-6e335e98-3627-4c6f-8cc9-02cf0af38485.png)
![image](https://user-images.githubusercontent.com/24848664/186803147-b8fecf5f-d767-4f2f-9326-74c15c09590c.png)
As demonstrated Above, the IC2 Macerator processes Nether Quartz Ore improperly, giving the ore back instead of raw quartz.

Also, NQO drops as the ore block when mined by hand without Silk Touch. I would assume the two bugs are related.

**Comment by xJon** [comment]
Hi, regarding the drop, it is a feature of Nether Ores which I will disable in the next update.
Regarding the macerator recipe, after looking into it I'm unfortunately unable to resolve it - that recipe seems to be added by Atomic Stryker's Advanced Machines mod for some odd reason https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/24.

**Comment by xJon** [comment]
Fixed in `0.10.7` :)
