### ISSUE TITLE
Advanced Enchantment Table not showing all relevant enchantments

### ISSUE THREAD

**Issue by Apocrophon** [xJon/The-1.7.10-Pack#1977]
The AET doesn't show all relevant unlocked enchantments for items(swords, armor, tools, etc.).
![javaw_jTMkHyHa1z](https://user-images.githubusercontent.com/24848664/188054931-d185edd4-520c-4b2c-94bd-6baedc1355a9.png)
![javaw_WcsMz6zDPQ](https://user-images.githubusercontent.com/24848664/188054933-a5a6712b-4e3e-48cf-b6d9-06242b6e8b3d.png)
This example shows Dispersed Strike, Final Strike, and Focused Strike(all sword enchants) not showing when sword is in the table.

Also I tried to add Night Vision to my helmet on the anvil but after it didn't show on the helmet.

**Comment by xJon** [comment]
See https://github.com/xJon/The-1.7.10-Pack/issues/1664#issuecomment-459960327.

**Comment by Apocrophon** [comment]
> See [#1664 (comment)](https://github.com/xJon/The-1.7.10-Pack/issues/1664#issuecomment-459960327).

Yes that issue is the same as this issue, but your diagnosis is misunderstood. I've unlocked all the enchantments already, they aren't showing when i try to enchant the items they're supposed to be enchanted onto(i.e. Focused Strike onto a Sword, or Repair on any item).
The one exception is a vanilla book, which can take any of the enchants no matter what.
