### ISSUE TITLE
Mekanism + Refined Relocation + Buildcraft looping crash

### ISSUE THREAD

**Issue by IronSpaceCore** [xJon/The-1.7.10-Pack#1978]
There's an issue where, if you take a chest, attach a Mekanism logistical Transporter to it, attach a RR buffer to the Transporter, attach a BC Golden Pipe to the other side of the buffer, and attach a chest to the golden pipe, and put something in the first chest, it causes an entity error that crashes the server every time it's rendered.
[lmao.txt](https://github.com/xJon/The-1.7.10-Pack/files/9481422/lmao.txt)

![cognitohazard](https://user-images.githubusercontent.com/100050106/188245277-db06b5ce-6c3d-44ec-8663-4a18f45a17a9.png)

there is no reason anyone should ever make a setup like this, but placing an item in the left chest crashes the client to desktop and closes the server, repeatedly.

I'd also like to add that doing this but in reverse, by using a wooden pipe -> buffer -> transporter setup just spits the item out of the buffer, so it's only this direct linear configuration that creates a rendering error

**Comment by xJon** [comment]
Hmm, could you report it over https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/issues ?

**Comment by xJon** [comment]
Also, what modpack version are you playing this on?

**Comment by xJon** [comment]
Closing for now, will reopen if requested!
