### ISSUE TITLE
Right-click crafting crashes client

### ISSUE THREAD

**Issue by Apocrophon** [xJon/The-1.7.10-Pack#1979]
I've crashed at least 4 times while right clicking to Craft All either from JEI or the crafting table UI.
[crash-2022-09-03_12.41.58-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/9483390/crash-2022-09-03_12.41.58-client.txt)
[crash-2022-09-03_14.00.31-server.txt](https://github.com/xJon/The-1.7.10-Pack/files/9483391/crash-2022-09-03_14.00.31-server.txt)
[crash-2022-09-01_13.22.47-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/9483392/crash-2022-09-01_13.22.47-client.txt)
[crash-2022-09-01_20.53.30-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/9483393/crash-2022-09-01_20.53.30-client.txt)

**Comment by xJon** [comment]
As a workaround, you can remove the Fairy Lights mod.

**Comment by xJon** [comment]
@Apocrophon Can you try to reproduce the issue using this version of Fairy Lights?
[Unzip me.zip](https://github.com/xJon/The-1.7.10-Pack/files/9483698/Unzip.me.zip)

**Comment by xJon** [comment]
Should be resolved with a modpack reinstall in the launcher, had the wrong (unpatched) version of Fairy Lights included to begin with :)
