### ISSUE TITLE
Osmium Compressor takes incorrect amount of osmium

### ISSUE THREAD

**Issue by Apocrophon** [xJon/The-1.7.10-Pack#1980]
When making Refined Obsidian Ingots, the recipe takes 201 Liquid Osmium(1.005 Osmium ingots) so you waste an ingot to complete the craft.

**Comment by xJon** [comment]
I'm not sure whether this is intentional or not. Any chance you can forward this issue to https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/issues ?

**Comment by Apocrophon** [comment]
> I'm not sure whether this is intentional or not. Any chance you can forward this issue to https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/issues ?

done https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/issues/32

**Comment by xJon** [comment]
Fixed in `0.10.7` :)
