### ISSUE TITLE
Clash between Industrial Craft 2 and Mekanism.

### ISSUE THREAD

**Issue by Ratchet5886** [xJon/The-1.7.10-Pack#1982]
When I am trying to create steel via the mekanism process it is instead turning into refined iron from Industrial Craft 2. Until now this wasn't a problem however when attempting to make enriched alloy the only item that is accepted is Mekanism steel. The refined iron does not work; therefore, we cannot progress with mekanism as the enriched alloy is required for progress within the mod.  Enriched alloy used to be made with iron instead but this also does not work in this pack therefore we have no way of creating this essential material. Help would be appreciated.

**Comment by xJon** [comment]
Hi, thanks for the report! This is an issue which will get fixed in the next version of the modpack with the latest Mekanism version. For now, you could manually update the mod if you like.

**Comment by xJon** [comment]
Fixed in `0.10.7` :)
