### ISSUE TITLE
[suggestion] pls update archaic fix to fix some bugs and crash

### ISSUE THREAD

**Issue by quentin452** [xJon/The-1.7.10-Pack#1983]

**Comment by xJon** [comment]
Hey, thanks for the suggestion! Is there any specific bug fix that would be useful in the new version of ArchaicFix?

**Comment by quentin452** [comment]
fix crash with threaded chunk update

**Comment by xJon** [comment]
`enableThreadedChunkUpdates` is disabled by default so it doesn't affect most modpack players! If someone manually enables it I assume they can also manually update ArchaicFix :)

**Comment by xJon** [comment]
Seems like the new ArchaicFix version also resolved a crash with the Beacon GUI.

**Comment by xJon** [comment]
Updated in `0.10.8`, thanks :)
