### ISSUE TITLE
Thermal Expansion Machines Reset

### ISSUE THREAD

**Issue by Cr1spEY** [xJon/The-1.7.10-Pack#1989]
Currently having an issue with Thermal Expansion machines reverting to basic and losing all augments after dimension changes and server restarts. Modpack does not have any extra mods nor does the server. Using the most recent version of the server files and modpack files. 

You're using the recommended/latest version of the modpack, without any major additional mods. Yes
You're using the latest version of Java (7 or 8) and a 64 bit version of it. Yes
You have 4GB of RAM or more installed on your computer. Yes
You're using the original Technic Launcher in its latest version, and not a cracked or modified launcher. Yes
Herobrine has successfully been removed in version 0.5.4. I hope ;)

Problem was not always present. Possibly related to a corrupted save? 

 Love the pack and I have played it on and off for ~5 years maybe longer. Appreciate all the work put into it over these years. Thanks in advance :D

**Comment by xJon** [comment]
Hey! A few players reported this issue, possibly since the introduction of a lot of the recent enhancement mods. Some players mentioned that a clean reinstall resolved this issue, any chance you could try and report back?
Alternatively, if you can find any specific errors in the log that could point out the cause, that could help.

**Comment by Cr1spEY** [comment]
Yes I can try to do a clean reinstall, although im not sure of the proper method. I will look into it and get back to you with more details. I will try to go through the log but I'm not very well versed in these things. Thanks for responding so timely and on a holiday as well. You really are extremely dedicated to these packs you create.

**Comment by Cr1spEY** [comment]
Im pretty stumped on this one. Deleted modpack and all files associated with it in the .technic folder, downloaded fresh server files, and copied in a backup version of my world. The problem still persists. However I started a fresh server to test on and cannot replicate the issue. My only idea (I am a novice at these things) is that I somehow corrupted the world with a bad save and/ or I am not restoring the backups properly. Im going to start a fresh server and try to get back to where I was and see if the issue will reoccur. I dont want to write this off entirely yet though and I will update if I learn something new.

**Comment by Cr1spEY** [comment]
Alright I'm pretty lost on this. Lost all augments and the dynamo blocked reset to natural position. My other Thermal machines stayed normal. All I can think of is that it possibly has something to do with augmenting the machine itself as the non affected machines were not augmented and stayed normal. Heres the latest log https://mclo.gs/Uo8uwgL

Hopefully you can find something. I did load in new chunks and unloaded my base chunks during this period as well. Thanks for your time :)

**Comment by Cr1spEY** [comment]
Those logs seem to be missing alot of stuff. Heres some better logs, I noticed the problem and disconnected pretty much right after. 
https://mclo.gs/sTBzaqr

**Comment by xJon** [comment]
@Cr1spEY This latest log shows you joining the server right after starting it, right? So did the dynamo reset between server restarts or whilst playing?

**Comment by Cr1spEY** [comment]
The dynamos reset  during play, not when i logged on.  Dormant cache chunk size is set to 0. I can try loading the old server and getting a log from that one as the issue has not reoccurred on this one.

**Comment by xJon** [comment]
In the log that you sent, the server starts at around `[16:31:40]` and you join a minute later, when did the issue start?
Regarding `dormantChunkCacheSize`, if it's set to `0` then it's not the cause unfortunately...

**Comment by Cr1spEY** [comment]
I noticed the problem right when the log ended and I logged off. Cant be sure it occured right then though. I can try the old server and see if I can get better logs.

**Comment by Cr1spEY** [comment]
Well I think I'm gonna have to leave it at that. Tested on my old server with dimension changes, teleports, and a server restart with and without a chunk loader at the base. Havent been able to get the issue to reoccur, even on my old world where it was happening frequently. I still feel like it has something to do with chunk loading so I placed  a chunk loader at my base. Thanks for the help, wish I could provide more useful info and logs.

**Comment by xJon** [comment]
Glad it didn't happen again since! Any chance the reinstall did end up helping?
Will close for now but feel free to reopen whenever you want :)

**Comment by xJon** [comment]
@Cr1spEY Can you try to manually add [this mod](https://modrinth.com/mod/tileentity-reset-fix/version/1.0.1-noreq) and see whether the issue is resolved?

**Comment by Cr1spEY** [comment]
oh man, I never saw this. I did a full wipe on my computer a couple months ago and my backup got corrupted so I lost the server anyways. Sorry about that

**Comment by xJon** [comment]
No worries, either way apparently that mod doesn't resolve it. It seems the only current solution is chunk loading.

**Comment by xJon** [comment]
Marking as duplicate due to https://github.com/xJon/The-1.7.10-Pack/issues/1984#issuecomment-1876233556.

**Comment by xJon** [comment]
Should be resolved in `0.10.12` :)
