### ISSUE TITLE
Server is crashing after teleporting

### ISSUE THREAD

**Issue by ilushkabond** [xJon/The-1.7.10-Pack#1991]
Hello.

Server is crashing after walking through portal / teleporting using OP command.

Launch options:
`java -server -Xmx12G -Dfml.queryResult=confirm -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui`

Crashlog:
https://pastebin.com/KTvLnx8i

**Comment by xJon** [comment]
Thank you for the report! Can you reproduce it consistently or was it a one-off time of crash?

**Comment by ilushkabond** [comment]
I can reproduce it consistently.
I have "world" that is corrupted in that manner.
Backup helped to solve situation.

**Comment by xJon** [comment]
Seems so, glad you figured it out!
