### ISSUE TITLE
Mods Suggestion 

### ISSUE THREAD

**Issue by DanAzev** [xJon/The-1.7.10-Pack#1994]
Hi, I started following the project for a while and wanted to ask if it is possible to add 4 mods: Reactor Craft, Rotary Craft, Electric Craft and Dragon API. I normally find it pretty hard to find a good modpack in 1.7.10 that has these mods and they are really interesting for someone who wishes to have a more "realistic" approach so to speak.

None the less, thanks for the attention!!

**Comment by xJon** [comment]
Thank you for the suggestion! I decided I don't want to add new content mods to The 1.7.10 Pack at this stage, so the mods won't be added.
That being said, please feel free to add them locally and enjoy the game :)
