### ISSUE TITLE
Flight Surival issues

### ISSUE THREAD

**Issue by SyFy001** [xJon/The-1.7.10-Pack#1996]
Hello, having issues with flight. This is in survival only, creative still works. This issue happens on my personal server, and in a single player world. It's affecting all players on the server as well.  We've tried morphs, rings, and all sorts of ways.

**Comment by xJon** [comment]
Hi! Using an Angel Ring, I'm unable to reproduce this on singleplayer or server using the latest version of the pack. Which version are you running?

**Comment by SyFy001** [comment]
Using version 0.10.9 due to the 0.10.10 not being available for akliz Servers yet . The only other mod I have added is a one peice mod , but this was happening before this mod was added . I have checked to make sure flight is enabled as well

**Comment by xJon** [comment]
@SyFy001 I'll make sure `0.10.10` will be available on Akliz as soon as possible (hopefully later today)!

**Comment by SyFy001** [comment]
Thank you for your help!

**Comment by xJon** [comment]
@SyFy001 Should be available now :)

**Comment by SyFy001** [comment]
I'm still having issues with flight, but i'll keep looking through my config files to see if i can find out why.
