### ISSUE TITLE
The 1.7.10 pack Crashes after using Optifine

### ISSUE THREAD

**Issue by VarioxCS** [xJon/The-1.7.10-Pack#1998]
The modpack crashes while starting after adding Optifine.

 

Yes I have removed fastcraft.

 
[crash-2023-07-06_13.11.08-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/11967635/crash-2023-07-06_13.11.08-client.txt)

Logs are added.

I wanted to add Optifine because my 3080 only gets about 50 fps in this modpack, which is quite low.
The logs say something about EnderIO does not support Optifine, but I saw other people use this modpack with Optifine, so maybe anyone of you has a solution.

**Comment by LocalPhysicsEnthusiast** [comment]
Please use Optifine D6 and not E7.

**Comment by xJon** [comment]
Note that for further performance, you can add https://github.com/makamys/Neodymium.

**Comment by xJon** [comment]
Closed due to inactivity, will reopen if requested.
