### ISSUE TITLE
The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

### ISSUE THREAD

**Issue by GameMaggot** [xJon/The-1.7.10-Pack#2000]
This error happened in a specific part of the trainrail which the minecart passed in minecraft 1.10.2 with forge, wjat happened?

**Comment by xJon** [comment]
Minecraft 1.10.2? I'm not exactly sure what you mean, and there isn't enough information here to help. There is a small chance your issue is not enabling `eula.txt`.

**Comment by xJon** [comment]
Closed due to inactivity.
