### ISSUE TITLE
Blood Magic - Convocation of the Damned - improper generation.

### ISSUE THREAD

**Issue by Zachary-Vowles** [xJon/The-1.7.10-Pack#2001]
Upon initiating the Blood Magic ritual, Convocation of the Damned, the buildings generate with the "Schematic saver", an untextured block. There are no chests, and no variation in buildings - the invasion does not progress in phases, and does not form the cage-like nether-brick structure. This is due to the config folder (schematic subfolder) of Blood Magic not properly updating/not being configured properly. 

It initially has files with just numbers ( -856220939.json, 1665108200.json, 173428443.json, -965964095.json, 1413342655.json, 2146576730.json). These seem to be placeholders without actual information for further structures beyond the basic house unit.
An example of the file contents (with the exception of -856220939.json, which has detail for the basic house structure that has the untextured "AWWayofTime:blockSchemSaver" block) :

{
  "name": "",
  "doorX": 0,
  "doorZ": 0,
  "doorY": 0,
  "buildingTier": 0,
  "buildingType": 0,
  "blockList": [
    {
      "blockid": "AWWayofTime:blockSchemSaver",
      "metadata": [
        0,
        0,
        0,
        0
      ],
      "positions": [
        {
          "xCoord": 0,
          "yCoord": 0,
          "zCoord": 0
        }
      ]
    }
  ]
}

Upon deleting the Blood Magic config folder, and restarting the game, the structure files are generated properly. There should be the following files (.json files) present in the schematic subfolder of the Blood Magic config folder:
Ampitheter
LavaLight
MedFarm1
MedForge1
MedHouse1
MedMossyForge
MossyCellar1
MossyGourdHouse
MossyTheatre
QuickDemonStructure
SmallHouse1
SmallHouse2
SmallMossyTower1
SmallTower1

![image](https://github.com/xJon/The-1.7.10-Pack/assets/16482819/974f1c86-2d3e-4547-b277-26577057ad79)
Highlighted files have been restored from trash.

**Comment by Zachary-Vowles** [comment]
For context, here is what was generated before deleting the config file.
![image](https://github.com/xJon/The-1.7.10-Pack/assets/16482819/8d13f162-015b-4b99-bd42-5ab8b37c1815)

Here is what was generated afterwards. I had tested the ritual on different dimension, including the nether, overworld, mining world, and deep dark, the results were consistently 'bugged'.
![image](https://github.com/xJon/The-1.7.10-Pack/assets/16482819/876d2562-71df-4874-9730-218859d61856)

**Comment by xJon** [comment]
Thank you very much for the report! Although I'm not quite certain I understand - does resetting the configs resolve the issue?

**Comment by Zachary-Vowles** [comment]
> 

Yup! Just deleting the folder/files and rerunning the game will resolve the issue :)

**Comment by xJon** [comment]
Perfect, so I highly appreciate both the report and the solution. Will make sure it's resolved for everyone in the next modpack update :)

**Comment by Zachary-Vowles** [comment]
Thanks for the quick reply! :)

**Comment by xJon** [comment]
Should be resolved in `0.10.11` :)
