### ISSUE TITLE
Server file download link broken for 1.7.10

### ISSUE THREAD

**Issue by darkseus** [xJon/The-1.7.10-Pack#2002]
https://the-1710-pack.com/repo
The 1.12.2 official link was broken as well, though it was recently routed to the curseforge server file page which still works. 
![image](https://github.com/xJon/The-1.7.10-Pack/assets/141870209/65f5d3c4-99c7-457e-bcb9-18c21de90e36)

**Comment by xJon** [comment]
Thanks for the report. It was down due to migration, and should be working properly now :)
