### ISSUE TITLE
On peut mettre des shaders et si oui comment ?

### ISSUE THREAD

**Issue by liamotech** [xJon/The-1.7.10-Pack#2003]
Je voulais savoir si il y avait la possibilité de mettre des shaders ?

**Comment by xJon** [comment]
Shaders aren't really supported by default due to compatibility issues between Optifine and Fastcraft.
If you want, you can ask around in the modpack's Discord if  some people managed to tweak it and install shaders successfully.

**Comment by liamotech** [comment]
d'accord merci et autre chose pour le problème avec thermal la réinitialisation se passe lors du fonctionnement des fours mais quand la zone n'est plus chargé donc ça se produit au moment ou l'on quitte la zone et que le four fonctionne

**Comment by xJon** [comment]
Yes, unfortunately it's a known bug. You need to make sure the chunks stay chunk loaded.
