### ISSUE TITLE
VillagerMetaFix crash with Last Millenium Villager interaction

### ISSUE THREAD

**Issue by goobyq** [xJon/The-1.7.10-Pack#2004]
[crash-2023-08-29_14.36.04-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/12469696/crash-2023-08-29_14.36.04-client.txt)
[crash-2023-08-29_14.34.26-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/12469697/crash-2023-08-29_14.34.26-client.txt)
(Uploaded: https://mclo.gs/JRvlXTO)
![javaw_cv4Ixb3V8m](https://github.com/xJon/The-1.7.10-Pack/assets/24848664/1c77fcd1-c62a-4283-9a43-cd4da3764f92)

**Comment by xJon** [comment]
Can you try to manually remove the `VillagerMetaFix-0.3.jar` mod and see if it changes anything?

**Comment by Apocrophon** [comment]
removing the .jar works 
![image](https://github.com/xJon/The-1.7.10-Pack/assets/24848664/96d267d7-c436-4a29-acf1-f28de3f09b10)

**Comment by xJon** [comment]
I forwarded this to the mod author, but considering the mod is ~7 years old, it will probably get removed in the next maintenance update. Thanks for the report!

**Comment by xJon** [comment]
Should be resolved in `0.10.12` :)
