### ISSUE TITLE
Armor textures not displayed on player but still functional on NPC

### ISSUE THREAD

**Issue by SolarisGC** [xJon/The-1.7.10-Pack#2005]
![image](https://github.com/xJon/The-1.7.10-Pack/assets/82925878/6023dfb5-d653-4a4a-95b8-f61fad2ee34e)

there is the issue, the title describes all i cannot fix it

![image](https://github.com/xJon/The-1.7.10-Pack/assets/82925878/62b19400-d6e9-46d1-8ebc-292170522dc9)

**Comment by xJon** [comment]
Which armour is it? Can you detail how to reproduce the issue?

**Comment by SolarisGC** [comment]
sure it's all the armors from all the addons installed, you just have to wear it to see many bugs happening 
![image](https://github.com/xJon/The-1.7.10-Pack/assets/82925878/fc9a419f-79aa-4780-bc93-e865daf471af)

**Comment by xJon** [comment]
The 1.7.10 Pack does not ship with all of these Flan's addons. I tried wearing a few of the ones that ship with the pack, and there are no issues there, so I'm unable to reproduce this issue.

**Comment by xJon** [comment]
Closed due to inactivity, will reopen if requested.
