### ISSUE TITLE
1.7.10 Pack is Offline

### ISSUE THREAD

**Issue by Wolfleaf** [xJon/The-1.7.10-Pack#2007]
The 1.7.10 Pack, as well as other packs hosted from the same source (The 1.12.2 Pack, Rexxit, Etc.), are all listed as "Offline" in the Technic Launcher. I have not found any other pack in the Technic Launcher, including both official and unofficial packs, that currently have the same issue.

![image](https://github.com/xJon/The-1.7.10-Pack/assets/28445645/44572ab2-bb54-4ea4-b3ca-aae8f38940cb)

When attempting to install or reinstall the modpack, it gives an error message stating "The modpack The 1.7.10 Pack does not appear to be installed or is corrupt, and is not available for Offline Play."

![image](https://github.com/xJon/The-1.7.10-Pack/assets/28445645/2b50d9c2-2b4f-441b-997e-0e663f5b2826)

When an old version of the modpack is installed, it can be updated, but the updates don't seem to work. Old versions of the modpack that are updated to the newest cannot connect to servers running the newest version of the modpack due to a mod-config mismatch error.

The server downloads have also disappeared.

![image](https://github.com/xJon/The-1.7.10-Pack/assets/28445645/1829aab0-da30-43bc-b929-74dcaceaf4a4)

I have tried a few workarounds, such as disabling the firewall or reinstalling Java, but I have found nothing that works. Is this an issue with the servers hosting the modpack? Is there something else I can do to fix this error? It appears other people are also currently suffering from this issue and were discussing it on the official discord server.

**Comment by xJon** [comment]
Thank you for reporting, it is resolved now :)
