### ISSUE TITLE
Twilight Forest Uncrafting table returns Wither materials for vanilla tools

### ISSUE THREAD

**Issue by metabloxer** [xJon/The-1.7.10-Pack#2009]
Discovered on multiplayer, verified on singleplayer

As simple as the title says. If you put, for example, a plain Iron Axe into the Twilight Forest Uncrafting table, you get Progressive Automation's Wither Iron instead of regular iron. This is likely because Wither materials craft vanilla tools, just with OP enchantments.

**Comment by xJon** [comment]
Thank you for the report, I can reproduce. I think this issue is minor enough that I will leave it as-is, the only other option would be updating the Twilight Forest more into the [GTNH fork](https://github.com/GTNewHorizons/twilightforest), which I will consider in the future.
