### ISSUE TITLE
Replacing Flan's Mod with MCHeli

### ISSUE THREAD

**Issue by DrLivingstones** [xJon/The-1.7.10-Pack#334]
MC Heli adds helicopters, planes, and other things like AA turrets and fuel trucks. With the current Flans mod there are only 3 Jets, 2 Heli's and a few other WW2 planes. Flans mod aircraft are also very hard to use and a bit buggy like landing is very odd and buggy and the aircraft tend to go inside the ground. MC heli adds a variety of other aircraft and is smoother then the Flans mod aircraft.
Enchanced Portals 3 gives you the ability to make custom portals however you want it where ever you want it. This is especially useful if you have multiple bases either far away or in another world which the 1.7.10 modpack has plenty of.

MC Heli: http://mchelicoptermod.weebly.com/about.html
Enchanced Portal 3: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292751-enhancedportals-3

**Comment by FatherTexas** [comment]
Hell yea add this flans is way to plain +1

**Comment by stoutrouge** [comment]
I feel like this would add a lot to the mod. The helicopters in flans are not the best. They are a waste of code.

**Comment by TreePuncher9501** [comment]
Honestly, on one world I made a huge runway for Flan's planes. Within the first takeoff and landing, the center of the runway was destroyed. So the MC-Heli looks good.

Portals... Just use the teleporters from either IC2 or Mekanism.

**Comment by santanana** [comment]
The helicopters are a great idea and would add some more interesting aspects to the mod, as for the portals I believe anything would be better than the current mod for it.

**Comment by TreePuncher9501** [comment]
To be honest, Santanana, I think we have mods for portals that work plenty already. Let me list a few examples:
1: Mechanism Teleporters, use with chunk loaders for anywhere on map teleportation, including multidimensional teleporting.

2: IC2 Teleporters: Same, exept no multi-dimensions and less efficient.

3: (VERY LATE GAME) Celestial Gateways from Thaumic Tinkerer

And for items:
Enderchest
Flux Teleportation Pipes (forget what they are called.)
Endertank (Both kinds)
Tesseracts
Enderpouch

As for adding more portals... Meh. Don't see the real use for this mod when one can use the Mekanism portals.

Heli though, seems good in my books.

**Comment by The-1-7-10-Pack** [comment]
Adding Enchanced Portal 3 - No, we don't need it.
Replacing Flan's Mod with the japanese MCHeli - I'll consider it, I'll leave this suggestion open for now :)

**Comment by LongJohn8877** [comment]
I agree with the mc heli, flans weapons are great but the vehicles feel very buggy trying to land a plane is hard without damaging or destroying your runway.

**Comment by The-1-7-10-Pack** [comment]
Anyway this will require a lot of testing guys, don't expect any kind of this change next update.

**Comment by alex2710xela** [comment]
I dont think we should add it.  The recipes suck and it is way to easy to get them.  MC heli also doesnt add any guns. I think flans is better overall.

**Comment by DrLivingstones** [comment]
Replacing flans mod planes does NOT completely remove the entire pack. Flans mod comes in modules and the guns are a separate module from the planes. I'd much rather have the more stable, and better looking vehicles that MCHeli has. Plus easier recipes can be a good thing

**Comment by CriticalRocket** [comment]
I haven't tried flans mod since minecraft beta haha xd Was about to try one of the aiplanes a few days ago but my world crashed whilst I was building it ><

So I can't say anything about issues, but I like the crafting system of flans mod waaay better. I like the controls better too, being able to look around the whole aircraft whilst still flying forward, stuff like that. 

If there are big issues like runways breaking and such I guess the only good option is to use MCHeli. But @TreePuncher9501 what did you make your runway out of? Maybe you just need to use stronger blocks or take of and land with less speed?..

**Comment by CriticalRocket** [comment]
P.s. I just noticed there's a EE3.cfg in the ./configs folder, whats that doing in there?.. o.O

**Comment by The-1-7-10-Pack** [comment]
@CriticalRocket It's from the old version of the pack :P

**Comment by imsupermario** [comment]
it doesn't matter what materials you use for the runway. I am a long term Flan's mod player,the only thing I don't feel comfortable is the planes. titans ,guns ,etc are good

**Comment by ChiknNRiceGaming** [comment]
Yea! you should switch it, Flan's mod is extremely confusing and frustrating to use

**Comment by Malorn44** [comment]
Flans mod is so fun. Please don't remove it from this mod pack! And also... for the block breaking thing with planes in flans mod... you can disable that. Just type in:
/teams vehiclesBreakBlocks false

**Comment by mandm635** [comment]
I say keep Flans mod guns, but remove the vehicles, as the are glitchy and outdated. Add McHeli to replace them.

**Comment by The-1-7-10-Pack** [comment]
@mandm635 And what about the fact that MCHeli's recipes are not balanced?

**Comment by imsupermario** [comment]
don't care if they are balanced or not ...

**Comment by mtcs** [comment]
Well, sorry for jumping in so late, but in my opinion, vehicles from McHeli are out of context in Minecraft. The design are no "minecrafty" at all, it is suuuper overpowered and terrible for performance. Imagine the chunk loading happening in a plane flight!!! Flans in the other hand have a better design, but I cant testify for how it works because I only tested one of the giant mechs with a terrible bounding box collision... SO, -1 for McHeli

**Comment by mandm635** [comment]
@The-1-7-10-Pack Sorry for replying late, I was on vacation, but McHeli just updated and that seems to have fixed a lot of balance issues (I haven't fully looked through the update though).

**Comment by imsupermario** [comment]
we have been testing MC-heli for a month now (MC Heli MOD 0.10.6) ,its less overpowered than flans mod heli (flansmod heli is immune to alot of attacks) , its true they are easy to craft , but they are easy to destroy.plus you have speed boats and all that stuff, fuel is similar to flans and ammo is similar to flans . Try it with "open modular turret 2 "

**Comment by Just-some-cannibal** [comment]
I believe that mchelicopters should be added. They are easier to control, look much better, and are immune to no attacks. Also the recipes can be changed with a recipe modifier if you think it is too op.

**Comment by Jakorosin** [comment]
I have no opinion on this, as I don't use Flan's vehicles at all. I /do/, however, use the Flan's mod guns and I absolutely love them. So if the final decision is to add MCheli, I would just ask that we not remove Flan's guns, but only the vehicles.

**Comment by RobinEH** [comment]
Can this idea be processed? The vehicles in Flan's are incredibly unstable, at least on servers.

**Comment by happysmash27** [comment]
I personally hate the MCHeli controls. Flan's mod is much better.

**Comment by Curunir** [comment]
Jon still takes suggestions, but has no intention to consider any of them, because he is a dick.
