### ISSUE TITLE
Suggestion: Portal/Gravity Gun

### ISSUE THREAD

**Issue by Jofkos** [xJon/The-1.7.10-Pack#480]
[Portal/Gravity Gun 1.7.10](http://ichun.us/its-my-birthday-today-heres-my-gift-to-you-folks-portalgun-and-gravitygun-for-minecraft-1-7-10/)

**Comment by Neology2k** [comment]
I'd upvote this.....

**Comment by TANGOjPANDA** [comment]
Yeah I like this especially the new balancing mechanics.

**Comment by CriticalRocket** [comment]
I love the portal gun, buts it a tiny bit OP in survival mode haha xd
I won't be using it in my world. Planes and EnderIO travel anchors are already OP enough ;)

**Comment by TANGOjPANDA** [comment]
They balanced it that's why I think its a great addition to the tech side of things. The balancing is that you require enderpearl dust to Create a portal and this is per portal so it can't be spammed.

**Comment by TreePuncher9501** [comment]
I wouldn't like this. The modpack has great ways of transporting already, from Mekanism teleporters to Thaumcraft Celestial Anchors, to Travel Anchors from EnderIO.

**Comment by Neology2k** [comment]
I Kind of agree, but would love a way to move Chests....

**Comment by The-1-7-10-Pack** [comment]
@Neology2k A dolly?

**Comment by The-1-7-10-Pack** [comment]
Currently won't add the mods, thanks anyway for suggesting.

**Comment by xJon** [comment]
Maybe we should look at this again.

**Comment by xJon** [comment]
Added! :+1:
