### ISSUE TITLE
Sugestion - Update Magical Crops to Version 4

### ISSUE THREAD

**Issue by martinegui** [xJon/The-1.7.10-Pack#512]
I know that magical crops 4 is in beta, but like you know the actual version has some problems with some crops.
The new version changes a little bit the way you get new crops and i think this would be more balanced.
Anyway, great modpack! I playing it for months.

**Comment by CriticalRocket** [comment]
Read comment 2: http://www.resonant-rise.com/topic/4551-magical-crops-400/

**Comment by The-1-7-10-Pack** [comment]
Magical Crops v4 is indeed [public[(http://minecraft.curseforge.com/mc-mods/228834-magical-crops/files/2235126) now, and this is an idea.

**Comment by martinegui** [comment]
You should look at http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287451-magical-crops-farm-your-resources-3-2-0-who-stole and the twitter https://twitter.com/MarkDCUK. Its a great way get informed about this mod.

**Comment by CriticalRocket** [comment]
Those links provide 0 info :)
Jon's link however has a changelog, ty!

**Comment by The-1-7-10-Pack** [comment]
@CriticalRocket This is the changelog of release 2, you should also look at the changelog of release 1, which shows what is different from Magical Crops v3 -> v4

**Comment by martinegui** [comment]
New Magic Crops Beta online (V5) : http://minecraft.curseforge.com/mc-mods/232150-magical-crops-core/files/2245371

**Comment by The-1-7-10-Pack** [comment]
Currently we'll wait for a stable version :)

**Comment by xJon** [comment]
Updating to the latest version of Magical Crops (which is sort of stable) will delete all items and blocks from the world + reset all quests regarding it. Not sure if we want to do it.

**Comment by Syford** [comment]
@xJon My self and my few friends that play find Magical Crops v4 much easier to manage than v3. Not only does work well with other mods, it opens up more options in the the game play as well.

**Comment by xJon** [comment]
@Syford Yet updating will reset all of the mod's items and blocks of existing worlds. Would you want that as a player?

**Comment by Syford** [comment]
@xJon After playing years of Minecraft and many different modpacks I have come to accept the fact  that sometimes there will be updates that cause you start over. I, as player, would be ok with this and would want this update.

**Comment by joelou1** [comment]
I do agree that quite a few mods in this modpack is actually out-dated and requires an update, even if it means loosing everything I had. Magical crops is no exception. The new formula with the stones and Minicio => Zivicio allows a better control (To my opinion) on certain crafts. Players has been playing around with the latest version of Magical Crop since a while now, and "Essence Ore" isn't as appealing as it used to be.

But I'll make a more accurate suggestion of mods to update. Then it'll be up to you to make an actually poll to decide with players whether it worths it or not.

**Comment by xJon** [comment]
@joelou1 Good idea. http://www.strawpoll.me/11059760

**Comment by xJon** [comment]
Thank you @joelou1!
